### ISSUE TITLE
Incompatible masters found in varLib._add_gvar()

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#1004]
I've ran into this traceback,
```python
Traceback (most recent call last):
  File "/fontTools/varLib/__init__.py", line 633, in build
    _add_gvar(vf, model, master_fonts)
  File "/fontTools/varLib/__init__.py", line 248, in _add_gvar
    allCoords = [d[0] for d in allData]
TypeError: 'NoneType' object has no attribute '__getitem__'
```
It was caused by U+0020 being named `space` in one master font, and `uni0020` in the other.

@behdad where should a check for this kind of incompatibility be added?

**Comment by behdad** [comment]
> It was caused by U+0020 being named space in one master font, and uni0020 in the other.
> 
> @behdad where should a check for this kind of incompatibility be added?

I can fix the code to allow configs where not all glyph is in all fonts.  I just need a few sample fonts...  I will probably require that all glyphs be available in the base master, which would catch an error like yours as well.

**Comment by behdad** [comment]
Though, it's not clear what to do with GPOS interpolation if masters have different glyph configs...

**Comment by justvanrossum** [comment]
I think all that's needed is a better error msg.

**Comment by behdad** [comment]
> I think all that's needed is a better error msg.

No, long-term I do want to allow masters that do not have all glyphs.  Aka the brace trick:
https://glyphsapp.com/tutorials/additional-masters-for-individual-glyphs-the-brace-trick

**Comment by justvanrossum** [comment]
Makes sense. But Miguel's case is clearly a mistake, where two glyphs with the same code point have different glyph names.
