### ISSUE TITLE
Distinction between hintmask bits and an operator in charstring

### ISSUE THREAD

**Issue by mashabow** [fonttools/fonttools#1006]
While subsetting I got an error raised in `op_or()`, although this font has no `or` operators, of course.

```console
$ pyftsubset font.otf --text=島 --no-hinting
Traceback (most recent call last):
  File "/Users/mnakamura/.pyenv/versions/subset-2.7.13/bin/pyftsubset", line 11, in <module>
    load_entry_point('fonttools', 'console_scripts', 'pyftsubset')()
  File "/Users/mnakamura/.ghq/github.com/fonttools/fonttools/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/mnakamura/.ghq/github.com/fonttools/fonttools/Lib/fontTools/subset/__init__.py", line 2971, in main
    subsetter.subset(font)
  File "/Users/mnakamura/.ghq/github.com/fonttools/fonttools/Lib/fontTools/subset/__init__.py", line 2785, in subset
    self._prune_post_subset(font)
  File "/Users/mnakamura/.ghq/github.com/fonttools/fonttools/Lib/fontTools/subset/__init__.py", line 2768, in _prune_post_subset
    retain = table.prune_post_subset(self.options)
  File "/Users/mnakamura/.ghq/github.com/fonttools/fonttools/Lib/fontTools/subset/__init__.py", line 2208, in prune_post_subset
    decompiler.execute(c)
  File "/Users/mnakamura/.ghq/github.com/fonttools/fonttools/Lib/fontTools/subset/__init__.py", line 2001, in execute
    psCharStrings.T2WidthExtractor.execute(self, charString)
  File "/Users/mnakamura/.ghq/github.com/fonttools/fonttools/Lib/fontTools/misc/psCharStrings.py", line 303, in execute
    rv = handler(index)
  File "/Users/mnakamura/.ghq/github.com/fonttools/fonttools/Lib/fontTools/misc/psCharStrings.py", line 375, in op_or
    raise NotImplementedError
NotImplementedError
```

This glyph has fifteen stems, and contains a sequence `hintmask 0110111101110010` in its charstring. Since the mask bits `0110111101110010` (= `6f72` in hex) can be decoded as a string "or" in ASCII-compatible encodings, the sequence is stored as `[..., 'hintmask', 'or', ...]` in `charString.program`, and eventually it's impossible to distinguish the bits from an `or` operator.

### Workaround

Use Python 3.

**Comment by anthrotype** [comment]
I think I've fixed the issue in https://github.com/fonttools/fonttools/commit/c0d672ba70ba6907759b086d59f110496d79c606
Could you please check it works now?
Also it would be nice if you could provide a minimal font the reproduces the issue so we can add to our regression tests (one glyph would be enough).

**Comment by mashabow** [comment]
@anthrotype Now it works fine. Thank you!

> Also it would be nice if you could provide a minimal font the reproduces the issue so we can add to our regression tests (one glyph would be enough).

Sure, I'll post a test font next week.

**Comment by mashabow** [comment]
Here is a test font, originally hinted with AFDKO's `autohint`.

[bug1006.otf.zip](https://github.com/fonttools/fonttools/files/1171743/bug1006.otf.zip)

To reproduce the issue, run `pyftsubset bug1006.otf --text=島 --no-hinting` on Python 2.7.

**Comment by anthrotype** [comment]
@mashabow Thank you! 😄
