### ISSUE TITLE
[feaLib] Error messages not very useful

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#1024]
I'm trying to build OTFs with fontmake from a Glyphs file, when feaLib fails.

It gives no hint which part of the feature file causes the error, so I have no clue where to start debugging ...

```
Traceback (most recent call last):
  File "/Users/jens/Library/Python/2.7/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontmake/font_project.py", line 378, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontmake/font_project.py", line 434, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontmake/font_project.py", line 473, in run_from_ufos
    ufos, remove_overlaps, **kwargs)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontmake/font_project.py", line 175, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontmake/font_project.py", line 295, in save_otfs
    font = compileOTF(ufo, optimizeCFF=subroutinize, **compiler_options)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/ufo2ft/__init__.py", line 42, in compileOTF
    featureCompiler.compile()
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/ufo2ft/featureCompiler.py", line 39, in compile
    self.setupFile_features()
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/ufo2ft/featureCompiler.py", line 57, in setupFile_features
    features = self._findLayoutFeatures()
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/ufo2ft/featureCompiler.py", line 122, in _findLayoutFeatures
    doc = parser.parse()
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/feaLib/parser.py", line 55, in parse
    statements.append(self.parse_feature_block_())
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/feaLib/parser.py", line 1143, in parse_feature_block_
    self.parse_block_(block, vertical, stylisticset, size_feature)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/feaLib/parser.py", line 1225, in parse_block_
    statements.append(self.parse_substitute_())
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/feaLib/parser.py", line 618, in parse_substitute_
    self.parse_glyph_pattern_(vertical=False)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/feaLib/parser.py", line 321, in parse_glyph_pattern_
    gc = self.parse_glyphclass_(accept_glyphname=True)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/feaLib/parser.py", line 261, in parse_glyphclass_
    glyph = self.expect_glyph_()
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/feaLib/parser.py", line 1276, in expect_glyph_
    self.advance_lexer_()
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/feaLib/parser.py", line 1385, in advance_lexer_
    self.next_token_location_) = next(self.lexer_)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/feaLib/lexer.py", line 197, in next
    return self.__next__()
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/feaLib/lexer.py", line 203, in __next__
    token_type, token, location = next(lexer)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/feaLib/lexer.py", line 49, in next
    return self.__next__()
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/feaLib/lexer.py", line 53, in __next__
    token_type, token, location = self.next_()
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/feaLib/lexer.py", line 159, in next_
    location)
fontTools.feaLib.error.FeatureLibError
```

**Comment by anthrotype** [comment]
hm.. at line 159 of `lexer.py` I see:

```python
raise FeatureLibError("Unexpected character: '%s'" % cur_char, location)
```

https://github.com/fonttools/fonttools/blob/5906b53/Lib/fontTools/feaLib/lexer.py#L158-L159

so it should print the offending character and the location.

**Comment by anthrotype** [comment]
can you debug, or maybe send me the file and I try later?

**Comment by jenskutilek** [comment]
Interesting ... nothing is printed. I'll try to find out what's up.

**Comment by jenskutilek** [comment]
There was a no-break space in the feature code (U+00A0). `makeotf` seems to ignore it. Should we ignore it (treat as whitespace) in feaLib too?

**Comment by anthrotype** [comment]
yes, maybe we could treat nbsp as another whitespace and ignore it, though it would be nice if the Adobe Feature File specification mentioned explicitly what are the allowed whitespace characters. Currently it just says:

```
White space is not significant except for delimiting tokens. You can have multiple line endings, spaces, and tabs between tokens. Macintosh, UNIX and PC line endings are all supported.
```

but why was the exception not printing the error message?

**Comment by jenskutilek** [comment]
nbsp is a non-ASCII char, but exception messages are ASCII in Python 2.7.

Something like this should help:

````python
raise FeatureLibError("Unexpected character: '%s'" % cur_char if ord(cur_char) < 128 else "Unexpected character: 0x%04X" % ord(cur_char),
    location)
````

Other options that come to mind would be either ignore it because it works in Python 3, or solve via `misc/py23.py` for all cases. WDYT?

**Comment by anthrotype** [comment]
oh, if that's the case, then we just need to replace 

```diff
-raise FeatureLibError("Unexpected character: '%s'" % cur_char, location)
+raise FeatureLibError("Unexpected character: %r" % cur_char, location)
```

so we use a correctly escaped ASCII-safe `repr()` for that character.

**Comment by jenskutilek** [comment]
OK, fixed it: f36c7ec

**Comment by anthrotype** [comment]
thanks @jenskutilek!

**Comment by anthrotype** [comment]
maybe we could open a separate issue on the afdko repository on clarifying the exact whitespace characters that the parsers must support.

**Comment by jenskutilek** [comment]
I was thinking just that :)

**Comment by jenskutilek** [comment]
Done: https://github.com/adobe-type-tools/afdko/issues/191
