### ISSUE TITLE
[merge] Cannot merge variable fonts

### ISSUE THREAD

**Issue by brawer** [fonttools/fonttools#1059]
The following command fails:

```
../fonttools/fonttools merge NotoSerif-VF.ttf NotoSerifSinhala-Regular.ttf

Traceback (most recent call last):
  File "../fonttools/fonttools", line 12, in <module>
    sys.exit(main())
  File "/home/sascha/src/fonttools/Lib/fontTools/__main__.py", line 29, in main
    runpy.run_module(mod, run_name='__main__')
  File "/usr/lib/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sascha/src/fonttools/Lib/fontTools/merge.py", line 1079, in <module>
    sys.exit(main())
  File "/home/sascha/src/fonttools/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/home/sascha/src/fonttools/Lib/fontTools/merge.py", line 1072, in main
    font = merger.merge(args)
  File "/home/sascha/src/fonttools/Lib/fontTools/merge.py", line 913, in merge
    table = clazz(tag).merge(self, tables)
  File "/home/sascha/src/fonttools/Lib/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/home/sascha/src/fonttools/Lib/fontTools/merge.py", line 958, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/home/sascha/src/fonttools/Lib/fontTools/merge.py", line 121, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in lst)
  File "/home/sascha/src/fonttools/Lib/fontTools/merge.py", line 105, in mergeObjects
    logic = clazz.mergeMap
AttributeError: type object 'VarStore' has no attribute 'mergeMap'
```

**Comment by behdad** [comment]
Right...

If and when I fix this, then we can merge variable fonts, which means different scripts would not need to have the same master configuration, just the same design range.

**Comment by behdad** [comment]
It should be trivial to merge gvar.  fvar/avar must match. MVAR we should take the first.

HVAR/VVAR/GPOS/GDEF are more work, as VarStore's need to be merged. I'll get to that some time.

**Comment by justvanrossum** [comment]
> fvar/avar must match.

In the ordinary use case, probably yes, but isn't that a higher level decision that merge doesn't need to make? I can totally imagine font A with a ABCD axis being merged with font B that has a EFGH axis, with merge creating a font that has both axes, each working on a subset of the glyphs. Unless there's a technical reason for such a restriction, I wouldn't enforce it.

Or is it only about individual axes? Probably the min/default/max values for an axis must be consistent across input fonts (although I can even imagine workarounds for that, but that would likely be out of scope for merge).

**Comment by behdad** [comment]
> Unless there's a technical reason for such a restriction, I wouldn't enforce it.

You are welcome to write the code for it... It's significantly more complicated to merge if fvar/avar are different.

**Comment by behdad** [comment]
Though, looks like what we need for Noto...

**Comment by marekjez86** [comment]
@behdad: @brawer: I created about 60+ variable Noto fonts that have only weight axis and they vary only from Regular .. Bold... Would it make the problem of merging simpler?

**Comment by behdad** [comment]
> How could we make progress on this?

We need someone to implement VarStore merging.  The VarStore builder/optimizer is the starting point, but someone needs to pick it up and make it happen.  If Cosimo can't, we need to find who can, as well as what kind of priority this has.
