### ISSUE TITLE
Decompile from working TTF. What to do about this error?

### ISSUE THREAD

**Issue by petrvanblokland** [fonttools/fonttools#1065]
Traceback (most recent call last):
  File "findParametricAxes.py", line 35, in <module>
  File "findParametricAxes.py", line 23, in findTTF
  File "/Users/petr/Desktop/git/Pagebot/Lib/pagebot/fonttoolbox/analyzers/glyphanalyzer.py", line 60, in _get_verticals
  File "/Users/petr/Desktop/git/Pagebot/Lib/pagebot/fonttoolbox/analyzers/glyphanalyzer.py", line 76, in findVerticals
  File "/Users/petr/Desktop/git/Pagebot/Lib/pagebot/fonttoolbox/objects/glyph.py", line 335, in _get_pointContexts
  File "/Users/petr/Desktop/git/Pagebot/Lib/pagebot/fonttoolbox/objects/glyph.py", line 350, in _get_contours
  File "/Users/petr/Desktop/git/Pagebot/Lib/pagebot/fonttoolbox/objects/glyph.py", line 121, in _initialize
  File "/Users/petr/Desktop/git/Pagebot/Lib/pagebot/fonttoolbox/objects/glyph.py", line 289, in _get_coordinates
  File "/Users/petr/Desktop/git/Pagebot/Lib/pagebot/fonttoolbox/objects/glyph.py", line 256, in _get_ttGlyph
  File "/Applications/DrawBot.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 424, in __getitem__
  File "/Applications/DrawBot.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/_g_l_y_f.py", line 59, in decompile
TTLibError: not enough 'glyf' table data

**Comment by anthrotype** [comment]
it means the loca table has an offset that's pointing beyond the length of the glyf table so something must be wrong in the font...

**Comment by davelab6** [comment]
What do other validators say (eg Hin-Tak FontVal, ftxvalidator,
FontLab/FontForge "Check Problems", OTMaster)

**Comment by anthrotype** [comment]
broken font
