### ISSUE TITLE
[feaLib] complains about malformed feature file even when it doesn't exist anymore

### ISSUE THREAD

**Issue by madig** [fonttools/fonttools#1100]
(First reported as https://github.com/googlei18n/fontmake/issues/347, but may actually be a bug in feaLib).

1. Get [Cantarell.glyphs.zip](https://github.com/fonttools/fonttools/files/1464798/Cantarell.glyphs.zip)
2. `fontmake -g Cantarell.glyphs -i -o otf`
```
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.parser:Parsing .glyphs file
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/Cantarell-Light.ufo
INFO:glyphsLib.util:Writing master_ufo/Cantarell-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/Cantarell-Bold.ufo
INFO:fontmake.font_project:Interpolating master UFOs from designspace
INFO:mutatorMath:Reading master_ufo/Cantarell.designspace
INFO:mutatorMath:	Generating instance Cantarell-Thin.ufo
INFO:mutatorMath:	Generating instance Cantarell-Light.ufo
INFO:mutatorMath:	Generating instance Cantarell-Regular.ufo
INFO:mutatorMath:	Generating instance Cantarell-Bold.ufo
INFO:mutatorMath:	Generating instance Cantarell-ExtraBold.ufo
INFO:fontmake.font_project:Building OTFs
INFO:fontmake.font_project:Decomposing glyphs for Cantarell-Thin
INFO:fontmake.font_project:Decomposing glyphs for Cantarell-Light
INFO:fontmake.font_project:Decomposing glyphs for Cantarell-Regular
INFO:fontmake.font_project:Decomposing glyphs for Cantarell-Bold
INFO:fontmake.font_project:Decomposing glyphs for Cantarell-ExtraBold
INFO:fontmake.font_project:Removing overlaps for Cantarell-Thin
INFO:fontmake.font_project:Removing overlaps for Cantarell-Light
INFO:fontmake.font_project:Removing overlaps for Cantarell-Regular
INFO:fontmake.font_project:Removing overlaps for Cantarell-Bold
INFO:fontmake.font_project:Removing overlaps for Cantarell-ExtraBold
INFO:fontmake.font_project:Saving OTF for Cantarell-Thin
Traceback (most recent call last):
  File "/Users/nw/Library/Python/3.6/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/Users/nw/Library/Python/3.6/lib/python/site-packages/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/nw/Library/Python/3.6/lib/python/site-packages/fontmake/font_project.py", line 378, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/Users/nw/Library/Python/3.6/lib/python/site-packages/fontmake/font_project.py", line 434, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/Users/nw/Library/Python/3.6/lib/python/site-packages/fontmake/font_project.py", line 473, in run_from_ufos
    ufos, remove_overlaps, **kwargs)
  File "/Users/nw/Library/Python/3.6/lib/python/site-packages/fontmake/font_project.py", line 175, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/Users/nw/Library/Python/3.6/lib/python/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/nw/Library/Python/3.6/lib/python/site-packages/fontmake/font_project.py", line 295, in save_otfs
    font = compileOTF(ufo, optimizeCFF=subroutinize, **compiler_options)
  File "/Users/nw/Library/Python/3.6/lib/python/site-packages/ufo2ft/__init__.py", line 42, in compileOTF
    featureCompiler.compile()
  File "/Users/nw/Library/Python/3.6/lib/python/site-packages/ufo2ft/featureCompiler.py", line 40, in compile
    self.setupFile_featureTables()
  File "/Users/nw/Library/Python/3.6/lib/python/site-packages/ufo2ft/featureCompiler.py", line 145, in setupFile_featureTables
    filename=feapath)
  File "/Users/nw/Library/Python/3.6/lib/python/site-packages/fontTools/feaLib/builder.py", line 25, in addOpenTypeFeaturesFromString
    addOpenTypeFeatures(font, featurefile)
  File "/Users/nw/Library/Python/3.6/lib/python/site-packages/fontTools/feaLib/builder.py", line 16, in addOpenTypeFeatures
    builder.build()
  File "/Users/nw/Library/Python/3.6/lib/python/site-packages/fontTools/feaLib/builder.py", line 78, in build
    self.parseTree = Parser(self.file, self.glyphMap).parse()
  File "/Users/nw/Library/Python/3.6/lib/python/site-packages/fontTools/feaLib/parser.py", line 53, in parse
    statements.append(self.parse_markClass_())
  File "/Users/nw/Library/Python/3.6/lib/python/site-packages/fontTools/feaLib/parser.py", line 504, in parse_markClass_
    self.expect_symbol_(";")
  File "/Users/nw/Library/Python/3.6/lib/python/site-packages/fontTools/feaLib/parser.py", line 1334, in expect_symbol_
    self.cur_token_location_)
fontTools.feaLib.error.FeatureLibError: instance_ufo/Cantarell-Thin.ufo/features.fea:433:1: Expected ';'
```
The offending feature file is actually just 404 lines long, its' GDEF table looks like (abridged):
```
table GDEF {
  # automatic
  GlyphClassDef
    [A ... macroncomb.loclVIET macroncomb.narrow macronbelowcomb.narrow], # Base
    [f_f f_f_i f_f_l fi fl brevecomb_acutecomb.case ... _copyright.C _registered.R], # Liga
    [dieresiscomb dotaccentcomb ... tildecomb.loclVIET hookabovecomb.loclVIET], # Mark
    ;
} GDEF;
```

Saving the file in the ASCII encoding doesn't help. The GDEF table looks the same syntactically in [Montserrat](https://github.com/JulietaUla/Montserrat), yet it compiles fine.

**Comment by madig** [comment]
I deleted all feature files from the generated master and instance UFOs, did `fontmake -u instance_ufo/Cantarell-Thin.ufo -o otf` and I'm still getting this error:
```
fontTools.feaLib.error.FeatureLibError: instance_ufo/Cantarell-Thin.ufo/features.fea:29:1: Expected ';'
```
The file does not exist anymore, what's going on here?

**Comment by anthrotype** [comment]
> The file does not exist anymore, what's going on here?

ufo2ft featureCompiler passes a string containing the UFO features.fea to feaLib, not the actual file (the reported file path that you see in the error message is simply the UFO path + the default "features.fea" file).
Ufo2ft generates kern and mark+mkmk features automatically given the data in kerning.plist groups.plist and the glyphs' anchors. It appends these automatic features to the existing features.fea content, if the file exists.
I guess we could wrap the call to feaLin in a try/except block and if a FeatureLibError is raised, save the content to a temporary file somewhere that the user can inspect. I'll do that.

anyway, the specific issue with cantarell is that it contains some glyphs whose names start with a "#", e.g. "#periodcentered".
When ufo2ft creates names for the mark classes it creates something like:

```
markClass _Qtail <anchor 183 79> @MC_#Qtail;
```

but that character is not legal for a class identifier in a feature file and feaLib chokes.

In the interim you could change the glyph names in your font, but maybe we should normalize those names and prevent ufo2ft feature writers from writing invalid identifiers.

**Comment by madig** [comment]
Something synthesizes a feature file from memory. Intercepting feaLib -> addOpenTypeFeaturesFromString() and looking at `features` yields the following:
```




markClass _Qtail <anchor 183 79> @MC_#Qtail;

markClass _bowl.b <anchor 59 252> @MC_#bowl;
markClass _bowl.d <anchor 412 252> @MC_#bowl;

markClass _part.bottomhook <anchor 463 0> @MC_#hook;

markClass periodcentered.loclCAT <anchor 172 353> @MC_#periodcentered;
markClass periodcentered.loclCAT.case <anchor 171 352> @MC_#periodcentered;

markClass _ytail <anchor 249 0> @MC_#ytail;

markClass cedillacomb <anchor 125 0> @MC_bottom;
markClass dotbelowcomb <anchor 120 0> @MC_bottom;
markClass commaaccentcomb <anchor 129 0> @MC_bottom;
markClass brevebelowcomb <anchor 206 0> @MC_bottom;
markClass macronbelowcomb <anchor 250 0> @MC_bottom;
markClass dieresisbelowcomb <anchor 220 0> @MC_bottom;
markClass macronbelowcomb.narrow <anchor 221 0> @MC_bottom;
markClass verticallinebelowcomb <anchor 110 0> @MC_bottom;
[...]
```
So it's the hashtag-anchors which I use for glyph construction that are being interpreted as comments and thus cut off the syntax behind them. Grr. I don't even want them in my instances!

**Comment by anthrotype** [comment]
and I at least had no idea about that feature.
it's going to be tricky to support something like that in ufo2ft mark feature writer, because the latter knows nothing about such Glyphs.app specific hacks. Probably glyphsLib will have to do something. Maybe provide a custom mark feature class that ufo2ft can use. I'll have to think about it

**Comment by anthrotype** [comment]
closing this since it's not really something fonttools can fix.
we can continue track this at https://github.com/googlei18n/fontmake/issues/347
