### ISSUE TITLE
varLib fails to merge type-2 lookups with different number of PairPos subtables

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1125]
As @punchcutter reported via email, running `fontmake -g src/NotoSerifKannada-MM.glyphs -o variable` throws an error.

It looks like in one of the four masters of Noto Serif Kannada, specifically the Light, the lookup number 48 (which is registered for the kern feature) does not contain a PairPosFormat1 subtable, but only has a single PairPosFormat2 subtable; all the other three masters have two subtables: one PairPosFormat1 (with some kerning exceptions) and one PairPosFormat2 for the class-based kerning.
[NotoSerifKannada-kern.zip](https://github.com/fonttools/fonttools/files/1547398/NotoSerifKannada-kern.zip)

```
INFO:fontTools.varLib:Merging OpenType Layout tables
Traceback (most recent call last):
  File "/Users/clupo/Github/fontmake/venv3/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "/Users/clupo/Github/fontmake/Lib/fontmake/__main__.py", line 186, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/clupo/Github/fontmake/Lib/fontmake/font_project.py", line 369, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/Users/clupo/Github/fontmake/Lib/fontmake/font_project.py", line 438, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/Users/clupo/Github/fontmake/Lib/fontmake/font_project.py", line 497, in run_from_ufos
    self.build_variable_font(designspace_path)
  File "/Users/clupo/Github/fontmake/Lib/fontmake/font_project.py", line 220, in build_variable_font
    font, _, _ = varLib.build(designspace_path, finder)
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/__init__.py", line 720, in build
    _merge_OTL(vf, model, master_fonts, axisTags)
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/__init__.py", line 513, in _merge_OTL
    merger.mergeTables(font, master_fonts, ['GPOS'])
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 107, in mergeTables
    self.mergeThings(font[tag], [m[tag] for m in master_ttfs])
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 94, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 71, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 94, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 71, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 94, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 71, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 96, in mergeThings
    self.mergeLists(out, lst)
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 81, in mergeLists
    self.mergeThings(value, values)
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 92, in mergeThings
    mergerFunc(self, out, lst)
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 621, in merge
    merger.mergeLists(self.SubTable, subtables)
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 81, in mergeLists
    self.mergeThings(value, values)
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 92, in mergeThings
    mergerFunc(self, out, lst)
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 468, in merge
    _PairPosFormat1_merge(self, lst, merger)
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 283, in _PairPosFormat1_merge
    'PairSet', 'PairSetCount'))
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 71, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/clupo/Github/fontmake/venv3/lib/python3.6/site-packages/fontTools/varLib/merger.py", line 98, in mergeThings
    assert all(out == v for v in lst), (out, lst)
AssertionError: ((4, [0, 4, 4, 4]), 'int', '.ValueFormat1', 'PairPos', '[0]', 'Lookup', '[48]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')
```

Below is the first part of the diff between the kern feature of Light vs Bold. You can see that the former does not have any `enum pos` statements, but only class-to-class pairs.

```diff
--- /Users/clupo/Github/noto-source/master_ufo/NotoSerifKannada-Light.kern.fea  2017-12-11 09:59:29.000000000 +0000
+++ /Users/clupo/Github/noto-source/master_ufo/NotoSerifKannada-Bold.kern.fea   2017-12-11 10:04:01.000000000 +0000
@@ -264,4653 +264,4964 @@

 lookup kern_ltr {
     lookupflag IgnoreMarks;
-    pos @public.kern1.KND_a_R @public.kern2.LTN_comma_L -30;
+    enum pos @public.kern1.KND_kha_R ya_kannada.below 40;
+    enum pos @public.kern1.KND_rVocalicMatra_R bracketleft 68;
+    enum pos @public.kern1.KND_rVocalicMatra_R underscore 162;
+    enum pos ya_kannada.below @public.kern2.KND_nnaa_L 126;
+    enum pos ya_kannada.below @public.kern2.KND_o_L 118;
+    enum pos ya_kannada.below @public.kern2.KND_reph_L 112;
+    enum pos ya_kannada.below @public.kern2.KND_rra_L 84;
+    enum pos ya_kannada.below @public.kern2.KND_sa_L 146;
+    enum pos ya_kannada.below @public.kern2.KND_shi_L 122;
+    enum pos ya_kannada.below @public.kern2.KND_si_L 136;
+    enum pos ya_kannada.below @public.kern2.KND_ta_L 78;
+    enum pos ya_kannada.below @public.kern2.KND_tta_L 78;
+    enum pos ya_kannada.below @public.kern2.KND_ya_L 68;
     pos @public.kern1.KND_aaMatra_R @public.kern2.KND_ailength_L 30;
     pos @public.kern1.KND_aaMatra_R @public.kern2.KND_babelow_L 30;
```

Attaching below the ufo2ft-generated kern features as well as the TTF files

[NotoSerifKannada-kern.zip](https://github.com/fonttools/fonttools/files/1547409/NotoSerifKannada-kern.zip)

[NotoSerifKannada-master_ttf_interpolatable.zip](https://github.com/fonttools/fonttools/files/1547407/NotoSerifKannada-master_ttf_interpolatable.zip)

**Comment by behdad** [comment]
That's supposed to work.  Will investigate.

**Comment by anthrotype** [comment]
I confirm this works for NotoSerifKannada variable font

**Comment by behdad** [comment]
Thanks!

**Comment by anthrotype** [comment]
Thank _you_!
