### ISSUE TITLE
add chromacheck color fonts to test suite 

### ISSUE THREAD

**Issue by RoelN** [fonttools/fonttools#1145]
I have a [working sbix testfont](https://github.com/RoelN/ChromaCheck/blob/master/fonts/chromacheck-sbix.woff) that I know ttx was able to handle properly half a year ago. Today I decompiled it with ttx version 3.21.2 (and before updating, 3.19.0) and tried to recompile it without making any changes.

This resulted in the following error:

```
$ ttx chromacheck-sbix.ttx
Compiling "chromacheck-sbix.ttx" to "chromacheck-sbix#1.ttf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'hmtx' table...
Parsing 'cmap' table...
Parsing 'loca' table...
Parsing 'glyf' table...
Parsing 'name' table...
Parsing 'post' table...
Parsing 'sbix' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttx.py", line 389, in main
    process(jobs, options)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttx.py", line 363, in process
    action(input, output, options)
  File "/usr/local/lib/python3.6/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttx.py", line 281, in ttCompile
    ttf.save(output)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/__init__.py", line 221, in save
    self._writeTable(tag, writer, done)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/__init__.py", line 660, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/__init__.py", line 671, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/tables/_s_b_i_x.py", line 81, in compile
    current_strike.compile(ttFont)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/tables/sbixStrike.py", line 86, in compile
    self.glyphDataOffsets += sstruct.pack(sbixGlyphDataOffsetFormat, current_glyph)
TypeError: must be str, not bytes
```

Any idea what's going wrong?

**Comment by anthrotype** [comment]
maybe this time you're using python3, and you hit one of my favourite bugs :)

**Comment by anthrotype** [comment]
@RoelN it would be great if you could contribute one of your test color fonts to help improve fonttools test suite :)

**Comment by anthrotype** [comment]
The license seems to be compatible (MIT). Can I use parts of chromacheck fonts for our internal tests?

**Comment by RoelN** [comment]
@anthrotype But certainly! The ChromaCheck fonts (or, all of it in fact) are free to re-use.

Take heed that I'm updating the fonts at this moment, so I'll be pushing new versions later tonight. For some reason the COLR font doesn't render in Firefox any more, and I'm adding a `glyf` table to the CBDT one to make it spec compliant. So you might want to wait for that before you include them in your test suite.

Curious to find out what your favourite bug is! :D

**Comment by anthrotype** [comment]
The specific issue of compiling the sbix chromachek ttx should be fixed on master.
But I'm confident we will find plenty of similar py2-py3 bugs once we start adding systematic tests.

oh, it was just a trivial one: attempting to concatenate str and bytes, which is rightfully illegal in python3.

**Comment by RoelN** [comment]
@anthrotype Fantastic, it works! Thanks for picking this up so quickly!!

**Comment by anthrotype** [comment]
I changed the title of the issue. Let’s keep it open until I or someone else add the chromacheck fonts to the test suite.

**Comment by behdad** [comment]
> I'm adding a glyf table to the CBDT one to make it spec compliant.

Wait. What? I thought the spec specifically says that CBDT fonts should NOT have a glyf table.

**Comment by RoelN** [comment]
@behdad I thought so too, but apparently it's no longer mentioned as requirement: https://www.microsoft.com/typography/otspec/cbdt.htm (also see https://github.com/googlei18n/noto-emoji/issues/43#issuecomment-324056041 ) It was part of the original proposal though: GOO: Google CBDT/CBLC tables (search for "GOO: Google CBDT/CBLC tables" and click the expand button)

**Comment by RoelN** [comment]
The color fonts in ChromaCheck have been updated and ready for use! Each font has a unicode character in a specific red (e.g. `rgb(50, 0, 0)`) and I check if that exact red is being drawn to the canvas. I hope you can do something with 'em!
