### ISSUE TITLE
TTX assert delta is not None

### ISSUE THREAD

**Issue by thany** [fonttools/fonttools#1165]
I've just installed fonttools using apt, and got TTX version 3.0. I was trying to use it to rename a font, but got stuck at an inexplicable error when converting the font back to ttf.

Here's what I do:
```
ttx verveine.ttf
ttx verveine.ttx
```
That's literally it. I omitted renaming the font, because literally just converting to font to ttx, and immediately back to ttf, produces the error that got me stuck:
```
Compiling "verveine.ttx" to "verveine.ttf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'hmtx' table...
Parsing 'VDMX' table...
Parsing 'hdmx' table...
Parsing 'cmap' table...
Parsing 'fpgm' table...
Parsing 'prep' table...
Parsing 'cvt ' table...
Parsing 'loca' table...
Parsing 'glyf' table...
Parsing 'name' table...
Parsing 'post' table...
Parsing 'gasp' table...
Parsing 'DYNA' table...
Parsing 'GDYN' table...
Parsing 'GPOS' table...
Parsing 'GSUB' table...
Traceback (most recent call last):
  File "/usr/bin/ttx", line 6, in <module>
    ttx.main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttx.py", line 350, in main
    process(jobs, options)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttx.py", line 333, in process
    action(input, output, options)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttx.py", line 249, in ttCompile
    ttf.save(output)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/__init__.py", line 221, in save
    self._writeTable(tag, writer, done)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/__init__.py", line 653, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/__init__.py", line 666, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/otBase.py", line 85, in compile
    self.table.compile(writer, font)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/otBase.py", line 657, in compile
    conv.write(writer, font, table, value)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/otConverters.py", line 349, in write
    value.compile(subWriter, font)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/otBase.py", line 637, in compile
    conv.writeArray(writer, font, table, value)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/otConverters.py", line 124, in writeArray
    self.write(writer, font, tableDict, values[i], i)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/otConverters.py", line 349, in write
    value.compile(subWriter, font)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/otBase.py", line 637, in compile
    conv.writeArray(writer, font, table, value)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/otConverters.py", line 124, in writeArray
    self.write(writer, font, tableDict, values[i], i)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/otConverters.py", line 349, in write
    value.compile(subWriter, font)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/otBase.py", line 617, in compile
    table = self.preWrite(font)
  File "/usr/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/otTables.py", line 185, in preWrite
    assert delta is not None
AssertionError
```
Not sure what I should do with this.

This is the font in question: [verveine.zip](https://github.com/fonttools/fonttools/files/1681254/verveine.zip)

**Comment by anthrotype** [comment]
it works with the latest fonttools. The version you're using is too old, please upgrade to the latest.

**Comment by thany** [comment]
I just did `sudo apt install fonttools` in Ubuntu. I don't know how to update that, other than `sudo apt upgrade`, but it's already at what apt thinks is the latest...

**Comment by anthrotype** [comment]
I don't know who is responsible for maintaining the fonttools apt package. The only method of installation that we directly support is through pip. I certainly would like that the other dowstream packages would be kept up to date but unfortunately I don't have the time to do that. 
Please refer to the Python Packaging User Guide to learn how to ensure you have a working pip installer and how to use that to install third-party modules hosted on the Python Package Index (PyPI).
https://packaging.python.org/tutorials/installing-packages/

**Comment by chrissimpkins** [comment]
It looks like 3.21.2 is currently in testing (as of last week):

https://tracker.debian.org/news/926746

@thany here is the package listing if you want to contact the package maintainer for more information about update status.

https://tracker.debian.org/pkg/fonttools

@thany It might be helpful to include your comments here in the communication with the package maintainer so that they are aware that users on the distro are impacted by the release schedule v/ release schedule here.  If you have the time and ability, pitch in on the effort to help maintain these distro specific redistribution packages (including a prompt to maintainers to update when new versions with desired features are available).  Unfortunately, these updates just take a bit of time to work their way through approval channels when you install through something like apt.  You benefit from the testing that is performed by the teams involved to make sure that compatibility is maintained at the cost of a slower release cycle.  If you want the latest immediately, best to install with pip as Cosimo suggested.
