### ISSUE TITLE
[ttFont] xmlWriter import error with saveXML split tables = True requests

### ISSUE THREAD

**Issue by chrissimpkins** [fonttools/fonttools#1188]
Attempt to dump split OT tables with ttx, executed in Python 3 venv with PyPI release of fontTools:

```
$ ttx -s -d regular-ttx Hack-Regular.ttf
Dumping "Hack-Regular.ttf" to "regular-ttx/Hack-Regular.ttx"...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttx.py", line 389, in main
    process(jobs, options)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttx.py", line 363, in process
    action(input, output, options)
  File "/usr/local/lib/python3.6/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttx.py", line 260, in ttDump
    newlinestr=options.newlinestr)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/ttFont.py", line 221, in saveXML
    self._saveXML(writer, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/ttFont.py", line 264, in _saveXML
    tableWriter = xmlWriter.XMLWriter(tablePath,
NameError: name 'xmlWriter' is not defined
```

PR for fix incoming...

**Comment by chrissimpkins** [comment]
PR #1189
