### ISSUE TITLE
Problem in varLib when fonts do not have GPOS?

### ISSUE THREAD

**Issue by Lorp** [fonttools/fonttools#1194]
I think there‘s a problem in varLib with fonts that do not have a GPOS table, with varLib trying to merge non-existent tables.

fontmake crashes when trying to build a variable TTF from MutatorSans UFOs + designspace:

    $fontmake -o variable -m MutatorSans.designspace
    INFO:fontmake.font_project:Building interpolation-compatible TTFs
    INFO:fontmake.font_project:Converting curves compatibly
    ...
    Traceback (most recent call last):
      File "/Users/lorp/Library/Python/2.7/bin/fontmake", line 9, in <module>
        load_entry_point('fontmake==1.4.0', 'console_scripts', 'fontmake')()
      File "/Users/lorp/Library/Python/2.7/lib/python/site-packages/fontmake/__main__.py", line 191, in main
        project.run_from_designspace(designspace_path, **args)
      File "/Users/lorp/Library/Python/2.7/lib/python/site-packages/fontmake/font_project.py", line 437, in run_from_designspace
        interpolate_layout_from=interpolate_layout_from, **kwargs)
      File "/Users/lorp/Library/Python/2.7/lib/python/site-packages/fontmake/font_project.py", line 496, in run_from_ufos
        self.build_variable_font(designspace_path)
      File "/Users/lorp/Library/Python/2.7/lib/python/site-packages/fontmake/font_project.py", line 220, in build_variable_font
        font, _, _ = varLib.build(designspace_path, finder)
      File "/Users/lorp/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/__init__.py", line 756, in build
        _merge_OTL(vf, model, master_fonts, axisTags)
      File "/Users/lorp/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/__init__.py", line 534, in _merge_OTL
        merger.mergeTables(font, master_fonts, ['GPOS'])
      File "/Users/lorp/Library/Python/2.7/lib/python/site-packages/fontTools/varLib/merger.py", line 107, in mergeTables
        self.mergeThings(font[tag], [m[tag] for m in master_ttfs])
      File "/Users/lorp/Library/Python/2.7/lib/python/site-packages/fontTools/ttLib/ttFont.py", line 372, in __getitem__
        data = self.reader[tag]
      File "/Users/lorp/Library/Python/2.7/lib/python/site-packages/fontTools/ttLib/sfnt.py", line 104, in __getitem__
        entry = self.tables[Tag(tag)]
    KeyError: 'GPOS'

A couple of days ago I made __init__.py line 534 (`merger.mergeTables(font, master_fonts, ['GPOS'])`) conditional (`if 'GPOS' in font:`) and that allowed me to make a var TTFs from MutatorSans. However that no longer works. Any ideas?

**Comment by anthrotype** [comment]
thanks Laurence. We should not raise KeyError if the master ttfs don't have GPOS but skip the _merge_OTL step altogether.
Behdad added a -x argument to `fonttools varLib` console script the other day (haven't published a release yet, will do soon). It allows to exclude tables from the output variable font. You should be able to say `-x GPOS` and it will skip merging that.
I'll fix the KeyError anyway

**Comment by Lorp** [comment]
Thanks for that. Good I can skip tables manually.

**Comment by anthrotype** [comment]
it looks like you need to exclude both `-x GPOS -x GDEF`, as `_merge_OTL` does the two of them

**Comment by anthrotype** [comment]
about the KeyError though... I think the varLib Merger is correct to raise an error if the base master has the table that's being requested to merge ('GPOS' in this case) but any of the other masters don't, which seems the case for mutatorSans.

https://github.com/fonttools/fonttools/blob/efca91e7f12ee0ae00e4efb7dddaafd8e6e22954/Lib/fontTools/varLib/merger.py#L106

Specifically, MutatorSansBoldWide.ufo does not have any kerning.plist, so the generated master ttf MutatorSansBoldWide.ttf does not have a GPOS and varLib fails. All other do have some kerning.plist...

it would be worse if skipped silently I think.

**Comment by anthrotype** [comment]
oh... this was probably intentional.

If you build it with the Robofont batch extension, then there's a `makeMasterKerningCompatible` function that takes care of those missing kerning pairs in the BoldWide master:

https://github.com/typemytype/batchRoboFontExtension/blob/53ce0761445a9994eb08dde712eef79b75a96060/Batch.roboFontExt/lib/variableFontGenerator/__init__.py#L468

whereas if you build with fontmake (which what I did, and probably what you tried to do as well), you don't, and one of the masters ends up without GPOS and varLib raises the KeyError.

Hm.. maybe we should do something similar in fontmake (in the ufo2ft.preProcessor).

**Comment by Lorp** [comment]
Interesting explanation, thanks!

**Comment by behdad** [comment]
In some distant future we like to allow intermediate masters that just provide a few glyph fixups. Those won't have a GPOS or GDEF, and we will ignore those for merging GPOS. For that to work, we require that full masters have GPOS. So, yeah, some process in ufo2ft should fill this in. Ie. generate (empty) kern lookups. The merge logic knows how to merge such lookups. But expecting it to build up completely nonexistent tables is a bit too much to ask.

**Comment by Lorp** [comment]
(pinging @LettError)

**Comment by LettError** [comment]
Inserting glyph fixups involves a couple of new problems, AFAICT? Will gladly discuss at Robothon.

**Comment by belluzj** [comment]
(somehow related) I'm also interested in knowing more about the plan for "glyph fixups", especially how they should be stored in UFOs/designspace, in order to support bracket layers in glyphsLib and in a way that will work by the rest of the toolchain

**Comment by behdad** [comment]
> (somehow related) I'm also interested in knowing more about the plan for "glyph fixups", especially how they should be stored in UFOs/designspace, in order to support bracket layers in glyphsLib and in a way that will work by the rest of the toolchain

Right. Something to discuss on Wednesday afternoon?

**Comment by belluzj** [comment]
That would be nice but I won't be at Robothon. @moyogo might be able to participate in a Wednesday discussion, but I'm not sure about his planning either.

**Comment by LettError** [comment]
I think these brace glyphs are necessary and I've done a small experiment with support glyphs (aren't these called "brace glyphs" rather than "bracket glyphs"?) in separate layers in UFO3. The designspace location for the glyph saved in its lib with some sort of generic key. But I realised that this requires a trawling through all glyphs in all layers to make sure a glyph has all its masters. So it would be necessary to store all information about brace glyphs in the designspace. It would be nice to be able to store those in different layers though. So:

In a designsdocument a brace glyph could be an element in the `sources` element as it is part of the data that define the designspace. It needs to store these things:
* the source font (by path or by name?)
* the glyphname
* the designspace location
* the layername.
* additionally it might be useful to have a flag a location for a **sample and hold** functionality. Rather than take a glyph from a source, _this calculates an instance at that location, with the current masters available, and then insert that instance as a brace glyph._ Note this requires a separate discussion about ordering the masters.

I would prefer to store the brace glyphs in the neutral UFO. By definition these are more or less orphaned shapes - not in the same dimension as any of the master UFOs, but they need to go somewhere.
