### ISSUE TITLE
[feaLib] feaLib may fail to parse name table's entry encoded by x_mac_japanese_ttx

### ISSUE THREAD

**Issue by derwind** [fonttools/fonttools#1196]
It is not a serious problem but I would like to share a bug.
A name table's entry encoded by x_mac_japanese_ttx caused UnicodeDecodeError as below:
```
UnicodeDecodeError: 'x_mac_japanese_ttx' codec can't decode byte 0x8f in position 0: incomplete multibyte sequence
```
by a snippet like:
```python
parser = Parser(sys.argv[1], [])
doc = parser.parse()
for statement in doc.statements:
    if isinstance(statement, fontTools.feaLib.ast.TableBlock):
        if hasattr(statement, "statements"):
            for statement2 in statement.statements:
                print(statement2.string)
```

A sample of such a name table can be got from page 8 of:
https://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/5149.OTFname_Tutorial.pdf
i.e.
```
table name {
  nameid 9 1 1 11 "Masahiko Kozuka \8f\ac\92\cb\8f\b9\95F";
} name;
```

**Comment by derwind** [comment]
I checked `feaLib` and found the implementation of `Parser.unescape_string_` seemed incomplete.
I think a MacJapanese string must be sequentially parsed from the beginning.

An ad-hoc and ugly fix is as follows:
```
diff --git a/Lib/fontTools/feaLib/parser.py b/Lib/fontTools/feaLib/parser.py
index e9a215cb..58210bc2 100644
--- a/Lib/fontTools/feaLib/parser.py
+++ b/Lib/fontTools/feaLib/parser.py
```
```python
@@ -972,6 +972,34 @@ class Parser(object):
     def unescape_string_(self, string, encoding):
         if encoding == "utf_16_be":
             s = re.sub(r"\\[0-9a-fA-F]{4}", self.unescape_unichr_, string)
+        elif encoding == "x_mac_japanese_ttx":
+            s = ""
+            while True:
+                m = re.search(r"\\[0-9a-fA-F]{2}", string)
+                if m:
+                    start = m.start()
+                    s += string[:start]
+                    string = string[start:]
+                    n = int(m.group(0)[1:], 16)
+                    # ftp://ftp.unicode.org/Public/MAPPINGS/VENDORS/APPLE/JAPANESE.TXT
+                    #    c)  Two-byte characters with first/lead/high byte in the range
+                    #        0x81-0x9F or 0xE0-0xFC, and second/trail/low byte in the
+                    #        range 0x40-0x7E or 0x80-0xFC.
+                    if 0x81 <= n <= 0x9f or 0xe0 <= n <= 0xfc:
+                        m = re.search(r"^(\\[0-9a-fA-F]{2})(\\[0-9a-fA-F]{2})", string)
+                        if m:
+                            s += self.unescape_two_bytes_(m, encoding)
+                            string = string[len("\\xx\\xx"):]
+                        else:
+                            m = re.search(r"^(\\[0-9a-fA-F]{2})(\w{1})", string)
+                            s += self.unescape_two_bytes_(m, encoding)
+                            string = string[len("\\xxX"):]
+                    else:
+                        s += self.unescape_byte_(m, encoding)
+                        string = string[len("\\xx"):]
+                else:
+                    s += string
+                    break
         else:
             unescape = lambda m: self.unescape_byte_(m, encoding)
             s = re.sub(r"\\[0-9a-fA-F]{2}", unescape, string)
@@ -991,6 +1019,15 @@ class Parser(object):
         n = match.group(0)[1:]
         return bytechr(int(n, 16)).decode(encoding)
 
+    @staticmethod
+    def unescape_two_bytes_(match, encoding):
+        n1num = int(match.group(1)[1:], 16)
+        if match.group(2)[0] == "\\":
+            n2num = int(match.group(2)[1:], 16)
+        else:
+            n2num = byteord(match.group(2))
+        return (bytechr(n1num) + bytechr(n2num)).decode(encoding)
+
     def parse_table_BASE_(self, table):
         statements = table.statements
         while self.next_token_ != "}" or self.cur_comments_:
```

**Comment by behdad** [comment]
Not sure what this is about, but probably needs work in fontTools.misc.encodings.codecs module.

**Comment by derwind** [comment]
The background is as follows:
When I tried to check whether tables of given OpenType fonts are consistent with their corresponding features.fea, `feaLib.parser.Parser.parse` raised UnicodeDecodeError during parsing the name table in features.fea.
This occurred when using a Japanese font and I investigated the problem and found that strings in name table definitions encoded by MacJapanese (e.g. "\8f\ac") were related.

**Comment by behdad** [comment]
I don't know if fea files are supposed to allow that. @brawer @readroberts @miguelsousa

**Comment by miguelsousa** [comment]
@derwind is right. feaLib fails on some Mac Japanese strings. makeotf has no problem parsing them.
Below is a test case taken from the referenced PDF and the expected result in TTX.

```fea
table name {
	nameid 0 "Copyright \00a9 2001-2010 Adobe Systems Incorporated. All Rights Reserved.";
	nameid 0 1 "Copyright \a9 2001-2010 Adobe Systems Incorporated. All Rights Reserved.";
	nameid 0 1 1 11 "Copyright \fd 2001-2010 Adobe Systems Incorporated. All Rights Reserved.";
	nameid 9 "Masahiko Kozuka \5c0f\585a\660c\5f66";          # Windows (Unicode)
	nameid 9 1 "Masahiko Kozuka";                             # Macintosh (Mac Roman)
	nameid 9 1 1 11 "Masahiko Kozuka \8f\ac\92\cb\8f\b9\95F"; # Macintosh (Japanese)
} name;
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ttFont>

  <name>
    <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
      Copyright © 2001-2010 Adobe Systems Incorporated. All Rights Reserved.
    </namerecord>
    <namerecord nameID="0" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Copyright © 2001-2010 Adobe Systems Incorporated. All Rights Reserved.
    </namerecord>
    <namerecord nameID="0" platformID="1" platEncID="1" langID="0xb" unicode="True">
      Copyright © 2001-2010 Adobe Systems Incorporated. All Rights Reserved.
    </namerecord>
    <namerecord nameID="9" platformID="3" platEncID="1" langID="0x409">
      Masahiko Kozuka 小塚昌彦
    </namerecord>
    <namerecord nameID="9" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Masahiko Kozuka
    </namerecord>
    <namerecord nameID="9" platformID="1" platEncID="1" langID="0xb" unicode="True">
      Masahiko Kozuka 小塚昌彦
    </namerecord>
  </name>

</ttFont>
```
Here's the full traceback when I ran it via `builder_test.py`.

```python
Traceback (most recent call last):
  File "builder_test.py", line 507, in <lambda>
    return lambda self: self.check_feature_file(name)
  File "builder_test.py", line 133, in check_feature_file
    addOpenTypeFeatures(font, self.getpath("%s.fea" % name))
  File "fonttools/Lib/fontTools/feaLib/builder.py", line 22, in addOpenTypeFeatures
    builder.build(tables=tables)
  File "fonttools/Lib/fontTools/feaLib/builder.py", line 107, in build
    self.parseTree = Parser(self.file, self.glyphMap).parse()
  File "fonttools/Lib/fontTools/feaLib/parser.py", line 75, in parse
    statements.append(self.parse_table_())
  File "fonttools/Lib/fontTools/feaLib/parser.py", line 821, in parse_table_
    handler(table)
  File "fonttools/Lib/fontTools/feaLib/parser.py", line 918, in parse_table_name_
    statement = self.parse_nameid_()
  File "fonttools/Lib/fontTools/feaLib/parser.py", line 970, in parse_nameid_
    platformID, platEncID, langID, string = self.parse_name_()
  File "fonttools/Lib/fontTools/feaLib/parser.py", line 955, in parse_name_
    unescaped = self.unescape_string_(string, encoding)
  File "fonttools/Lib/fontTools/feaLib/parser.py", line 979, in unescape_string_
    s = re.sub(r"\\[0-9a-fA-F]{2}", unescape, string)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "fonttools/Lib/fontTools/feaLib/parser.py", line 978, in <lambda>
    unescape = lambda m: self.unescape_byte_(m, encoding)
  File "fonttools/Lib/fontTools/feaLib/parser.py", line 994, in unescape_byte_
    return bytechr(int(n, 16)).decode(encoding)
  File "fonttools/Lib/fontTools/encodings/codecs.py", line 56, in decode
    return codecs.decode(input, self.base_encoding, self.name), len(input)
  File "fonttools/Lib/fontTools/encodings/codecs.py", line 70, in error
    raise e
UnicodeDecodeError: 'x_mac_japanese_ttx' codec can't decode byte 0x8f in position 0: incomplete multibyte sequence
```

**Comment by behdad** [comment]
Yeah, our encodings.codecs module needs more work.
