### ISSUE TITLE
Building variable font fails with latest FontTools

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fonttools#1206]
Building variable font for [Mada](https://github.com/alif-type/mada) fails with FontTools 3.24 but works with 3.23. From [build log](https://travis-ci.org/alif-type/mada/builds/347996762#L560):
```
$ make vf
     MAKE    variable
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontmake/__main__.py", line 191, in main
    project.run_from_designspace(designspace_path, **args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontmake/font_project.py", line 437, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontmake/font_project.py", line 496, in run_from_ufos
    self.build_variable_font(designspace_path)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontmake/font_project.py", line 220, in build_variable_font
    font, _, _ = varLib.build(designspace_path, finder)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 760, in build
    _merge_OTL(vf, model, master_fonts, axisTags)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 558, in _merge_OTL
    font['GPOS'].table.remap_device_varidxes(varidx_map)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontTools/varLib/varStore.py", line 247, in Object_remap_device_varidxes
    _visit(self, ot.Device, mapper)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontTools/varLib/varStore.py", line 219, in _visit
    _visit(that, objType, func)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontTools/varLib/varStore.py", line 219, in _visit
    _visit(that, objType, func)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontTools/varLib/varStore.py", line 213, in _visit
    _visit(that, objType, func)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontTools/varLib/varStore.py", line 219, in _visit
    _visit(that, objType, func)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontTools/varLib/varStore.py", line 213, in _visit
    _visit(that, objType, func)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontTools/varLib/varStore.py", line 219, in _visit
    _visit(that, objType, func)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontTools/varLib/varStore.py", line 213, in _visit
    _visit(that, objType, func)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontTools/varLib/varStore.py", line 219, in _visit
    _visit(that, objType, func)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontTools/varLib/varStore.py", line 213, in _visit
    _visit(that, objType, func)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontTools/varLib/varStore.py", line 219, in _visit
    _visit(that, objType, func)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontTools/varLib/varStore.py", line 223, in _visit
    _visit(that, objType, func)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontTools/varLib/varStore.py", line 208, in _visit
    func(self)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fontTools/varLib/varStore.py", line 241, in _Device_mapVarIdx
    varIdx = mapping[(self.StartSize<<16)+self.EndSize]
KeyError: 131104
make: *** [build/variable_ttf/Mada-VF.ttf] Error 1
```

**Comment by anthrotype** [comment]
Ouch. Can you bisect?

**Comment by khaledhosny** [comment]
I’m bisecting right now, but there are commits that does not even run (like 06678755387b86f7144790c4b5b988f187176365), that is why I always try to have bisectable history :(

**Comment by anthrotype** [comment]
Yeah. Apologies for that specific commit you mentioned above, it was probably me while attempting to fix some merge conflicts.

**Comment by khaledhosny** [comment]
No problem, luckily bisecting managed to give useful results anyway. Seems to have been caused by 54fd71f73c22051c50382fccb32fd292467ae9b8, reverting it locally fixes the build (I might be doing something weird in my VF setup as well. my design space file is a mess).

**Comment by anthrotype** [comment]
Thanks Khaled. I’ll have a look when I get to the office.

**Comment by anthrotype** [comment]
yes, I can also reproduce with this file "Mada-VF.ttf":
https://github.com/alif-type/mada/blob/1dacb4960089e1092b76b78bab7085b945e842d6/Mada-VF.ttf

The font was built with the latest fontmake and using fonttools 3.23 (as 3.24 failed with the mentioned error).

Running the `fonttools varLib.varStore` script (which optimizes the GDEF VarStore) on this Mada-VF.ttf, with the current fonttools 3.24 returns the same error:
```
$ fonttools varLib.varStore Mada-VF.ttf Mada-VF_optimized.ttf
Before:    3705 bytes
Traceback (most recent call last):
  File "/home/clupo/.local/share/virtualenvs/mada-MHb5EeSn/bin/fonttools", line 11, in <module>
    load_entry_point('fonttools', 'console_scripts', 'fonttools')()
  File "/home/clupo/Github/fonttools/Lib/fontTools/__main__.py", line 29, in main
    runpy.run_module(mod, run_name='__main__')
  File "/usr/lib/python3.5/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 515, in <module>
    sys.exit(main())
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 501, in main
    font['GPOS'].table.remap_device_varidxes(varidx_map)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 247, in Object_remap_device_varidxes
    _visit(self, ot.Device, mapper)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 219, in _visit
    _visit(that, objType, func)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 219, in _visit
    _visit(that, objType, func)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 213, in _visit
    _visit(that, objType, func)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 219, in _visit
    _visit(that, objType, func)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 213, in _visit
    _visit(that, objType, func)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 219, in _visit
    _visit(that, objType, func)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 219, in _visit
    _visit(that, objType, func)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 213, in _visit
    _visit(that, objType, func)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 219, in _visit
    _visit(that, objType, func)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 213, in _visit
    _visit(that, objType, func)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 219, in _visit
    _visit(that, objType, func)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 223, in _visit
    _visit(that, objType, func)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 208, in _visit
    func(self)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 241, in _Device_mapVarIdx
    varIdx = mapping[(self.StartSize<<16)+self.EndSize]
KeyError: 14
```

Reverting 54fd71f73c22051c50382fccb32fd292467ae9b8 makes the varStore script to complete -- even though the size seems to increase:
```
Before:    3705 bytes
After:     3719 bytes
```

Incidentally, attempting to subset the same Mada-VF.ttf also returns an other error, which I suspect may be related:

```
$ fonttools subset Mada-VF.ttf A B C
Traceback (most recent call last):
  File "/home/clupo/.local/share/virtualenvs/mada-MHb5EeSn/bin/fonttools", line 11, in <module>
    load_entry_point('fonttools', 'console_scripts', 'fonttools')()
  File "/home/clupo/Github/fonttools/Lib/fontTools/__main__.py", line 29, in main
    runpy.run_module(mod, run_name='__main__')
  File "/usr/lib/python3.5/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/clupo/Github/fonttools/Lib/fontTools/subset/__main__.py", line 7, in <module>
    sys.exit(main())
  File "/home/clupo/Github/fonttools/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/home/clupo/Github/fonttools/Lib/fontTools/subset/__init__.py", line 3281, in main
    subsetter.subset(font)
  File "/home/clupo/Github/fonttools/Lib/fontTools/subset/__init__.py", line 3095, in subset
    self._prune_post_subset(font)
  File "/home/clupo/Github/fonttools/Lib/fontTools/subset/__init__.py", line 3078, in _prune_post_subset
    retain = table.prune_post_subset(font, self.options)
  File "/home/clupo/Github/fonttools/Lib/fontTools/subset/__init__.py", line 1664, in prune_post_subset
    _pruneGDEF(font)
  File "/home/clupo/Github/fonttools/Lib/fontTools/subset/__init__.py", line 1644, in _pruneGDEF
    varidx_map = store.subset_varidxes(usedVarIdxes)
  File "/home/clupo/Github/fonttools/Lib/fontTools/varLib/varStore.py", line 158, in VarStore_subset_varidxes
    newItems.append(items[minor])
IndexError: list index out of range
```

**Comment by anthrotype** [comment]
Interestingly, if I comment out this in `varLib/__init__.py`
```diff
diff --git a/Lib/fontTools/varLib/__init__.py b/Lib/fontTools/varLib/__init__.py
index 2579f6b8..d2aad064 100644
--- a/Lib/fontTools/varLib/__init__.py
+++ b/Lib/fontTools/varLib/__init__.py
@@ -552,10 +552,10 @@ def _merge_OTL(font, model, master_fonts, axisTags):
        GDEF.VarStore = store
 
        # Optimize
-       varidx_map = store.optimize()
-       GDEF.remap_device_varidxes(varidx_map)
-       if 'GPOS' in font:
-               font['GPOS'].table.remap_device_varidxes(varidx_map)
+       # varidx_map = store.optimize()
+       # GDEF.remap_device_varidxes(varidx_map)
+       # if 'GPOS' in font:
+       #       font['GPOS'].table.remap_device_varidxes(varidx_map)
```

and rebuild everything with `make vf`, but this time without optimizing the GDEF VarStore while generating the varfonts, the non-optimized varfont can be creatred, and _then_ I can run the `fonttools varLib.varStore` on it without errors.

```
$ fonttools varLib.varStore Mada-VF.ttf Mada-VF_optimized.ttf
Before:    7246 bytes
After:     3705 bytes
```

:thinking:

**Comment by behdad** [comment]
I'm on it. Looks suspicious.

**Comment by behdad** [comment]
But yeah, I can reproduce with other fonts too. :|

**Comment by behdad** [comment]
Can someone send me the ttf-interpolatable sources and the designspace please? The optimizer is clearly doing something wrong.

**Comment by khaledhosny** [comment]
Here they are: [Mada.zip](https://github.com/fonttools/fonttools/files/1777739/Mada.zip)

**Comment by behdad** [comment]
@khaledhosny Thanks in advance!

**Comment by anthrotype** [comment]
I wonder if we want to make this GDEF optimization optional (like #1208)?
probably not, better to fix the bug.

**Comment by behdad** [comment]
No, why? It's a bug. Should be fixed.

**Comment by khaledhosny** [comment]
Build works now, thanks! But I don’t see the file size reduction reported in https://github.com/fonttools/fonttools/issues/1206#issuecomment-369907915, is this expected?

**Comment by behdad** [comment]
I get 3719 bytes with the optimization.

**Comment by behdad** [comment]
(Optimization is enabled by default; and I don't see any size change if I rerun it.)
