### ISSUE TITLE
Error on parsing GDEF of Bangla Akademi

### ISSUE THREAD

**Issue by ebraminio** [fonttools/fonttools#1235]
Steps to repro:
1. Download it from https://github.com/harfbuzz/harfbuzz/issues/779#issuecomment-366427878
2. `ttx "Bangla Akademi.ttf"`

```
$ ttx "Bangla Akademi.ttf"      
Dumping "Bangla Akademi.ttf" to "Bangla Akademi.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'LTSH' table...
Dumping 'VDMX' table...
Dumping 'hdmx' table...
Dumping 'cmap' table...
Dumping 'fpgm' table...
Dumping 'prep' table...
Dumping 'cvt ' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
ERROR: An exception occurred during the decompilation of the 'GDEF' table
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/__init__.py", line 409, in __getitem__
    return self.tables[tag]
KeyError: 'GDEF'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/__init__.py", line 424, in __getitem__
    table.decompile(data, self)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/tables/otBase.py", line 42, in decompile
    self.table.decompile(reader, font)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/tables/otBase.py", line 618, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/tables/otConverters.py", line 436, in read
    table.decompile(reader, font)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/tables/otBase.py", line 595, in decompile
    self.readFormat(reader)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/tables/otBase.py", line 779, in readFormat
    assert self.Format != 0, (self, reader.pos, len(reader.data))
AssertionError: (<fontTools.ttLib.tables.otTables.ClassDef object at 0x10c816c50>, 4, 136)
Dumping 'GDEF' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
```

It seems harfbuzz is able to pass that as a sanitized font but there is difference between coretext/uniscribe vs harfbuzz rendering so something is wrong I guess.

**Comment by anthrotype** [comment]
running ttx from lastest master (3.25.1.dev0) on the font linked in the issue, I get a slightly different traceback:

```sh
$ ttx "/home/clupo/Downloads/Bangla Akademi.ttf"
Dumping "/home/clupo/Downloads/Bangla Akademi.ttf" to "/home/clupo/Downloads/Bangla Akademi#1.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'LTSH' table...
Dumping 'VDMX' table...
Dumping 'hdmx' table...
Dumping 'cmap' table...
Dumping 'fpgm' table...
Dumping 'prep' table...
Dumping 'cvt ' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
ERROR: An exception occurred during the decompilation of the 'GDEF' table
Traceback (most recent call last):
  File "/home/clupo/Github/fonttools/Lib/fontTools/ttLib/ttFont.py", line 372, in __getitem__
    return self.tables[tag]
KeyError: 'GDEF'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/clupo/Github/fonttools/Lib/fontTools/ttLib/ttFont.py", line 391, in __getitem__
    table.decompile(data, self)
  File "/home/clupo/Github/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 42, in decompile
    self.table.decompile(reader, font)
  File "/home/clupo/Github/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 626, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/home/clupo/Github/fonttools/Lib/fontTools/ttLib/tables/otConverters.py", line 507, in read
    table.decompile(reader, font)
  File "/home/clupo/Github/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 631, in decompile
    self.postRead(table, font)
  File "/home/clupo/Github/fonttools/Lib/fontTools/ttLib/tables/otTables.py", line 833, in postRead
    assert 0, "unknown format: %s" % self.Format
AssertionError: unknown format: 0
Dumping 'GDEF' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
```
