### ISSUE TITLE
Double-byte Unicodes?

### ISSUE THREAD

**Issue by laerm0** [fonttools/fonttools#1295]
Hi –

It looks like TTX can't handle double-byte Unicodes. I dumped a TTF, edited a few Unicodes, and then when going back to TTF, I won this error:

```Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttx.py", line 398, in main
    process(jobs, options)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttx.py", line 372, in process
    action(input, output, options)
  File "/usr/local/lib/python3.6/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttx.py", line 290, in ttCompile
    ttf.save(output)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/ttFont.py", line 172, in save
    writer_reordersTables = self._save(tmp)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/ttFont.py", line 211, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/ttFont.py", line 632, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/ttFont.py", line 650, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 118, in compile
    chunk = table.compile(ttFont)
  File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 829, in compile
    charCodeArray = array.array("H", endCode + [0] + startCode)
OverflowError: unsigned short is greater than maximum```

**Comment by khaledhosny** [comment]
You probably need to change the `cmap` subtable as well, since characters beyond basic multilingual plane can’t be represented by older subtables, see [`cmap`](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap) documentation.

**Comment by anthrotype** [comment]
Correct

**Comment by laerm0** [comment]
The only place to change encoding in this font is in the `cmap`, and I changed both (`0,3,0` and `3,1,0`), and it's the only thing I changed, so I dunno where else you think I could've changed it.

**Comment by anthrotype** [comment]
You need a cmap subtable format that supports characters beyond the BMP, like format 12

**Comment by laerm0** [comment]
Oh, duh. Sorry! Thanks.

**Comment by anthrotype** [comment]
No problem!

**Comment by campbellgraphics** [comment]
Isn't this only supported in the format 12 subtable?

**Comment by davelab6** [comment]
Could there be a more informative error message?
