### ISSUE TITLE
Can't merge Helvetica Neue with Noto Emoji

### ISSUE THREAD

**Issue by SamusAranX** [fonttools/fonttools#1309]
I need to draw text with Imagemagick, but because it doesn't have proper emoji support, I need to create a merged font consisting of Noto's monochrome emoji and Helvetica Neue's everything else. I thought `fonttools merge helvetica.ttf notoemoji.ttf` would do the trick, but alas:

    ~/fonts$ fonttools merge HelveticaNeue-Regular.ttf NotoEmoji-Regular.ttf
    Traceback (most recent call last):
      File "/usr/local/bin/fonttools", line 11, in <module>
        load_entry_point('fonttools==3.29.0', 'console_scripts', 'fonttools')()
      File "/usr/local/Cellar/fonttools/3.29.0/libexec/lib/python2.7/site-packages/fontTools/__main__.py", line 29, in main
        runpy.run_module(mod, run_name='__main__')
      File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 192, in run_module
        fname, loader, pkg_name)
      File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/usr/local/Cellar/fonttools/3.29.0/libexec/lib/python2.7/site-packages/fontTools/merge.py", line 1129, in <module>
        sys.exit(main())
      File "/usr/local/Cellar/fonttools/3.29.0/libexec/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
        return func(*args, **kwds)
      File "/usr/local/Cellar/fonttools/3.29.0/libexec/lib/python2.7/site-packages/fontTools/merge.py", line 1122, in main
        font = merger.merge(args)
      File "/usr/local/Cellar/fonttools/3.29.0/libexec/lib/python2.7/site-packages/fontTools/merge.py", line 962, in merge
        table = clazz(tag).merge(self, tables)
      File "/usr/local/Cellar/fonttools/3.29.0/libexec/lib/python2.7/site-packages/fontTools/merge.py", line 160, in merge
        return m.mergeObjects(self, self.mergeMap, tables)
      File "/usr/local/Cellar/fonttools/3.29.0/libexec/lib/python2.7/site-packages/fontTools/merge.py", line 1008, in mergeObjects
        value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
      File "/usr/local/Cellar/fonttools/3.29.0/libexec/lib/python2.7/site-packages/fontTools/merge.py", line 49, in equal
        assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
    AssertionError: Expected all items to be equal: [1000, 2048]

I just installed fonttools 3.29.0 on my Mac via homebrew. Help would be appreciated.

**Comment by miguelsousa** [comment]
The two fonts have different UPM values, it seems.

**Comment by SamusAranX** [comment]
I changed NotoEmoji's UPM value to 1000 to match Helvetica's, which resulted in another error:
    ~/fonts$  fonttools merge HelveticaNeue-Regular.ttf NotoEmoji-Regular1000.otf
    Traceback (most recent call last):
      File "/usr/local/bin/fonttools", line 11, in <module>
        load_entry_point('fonttools==3.29.0', 'console_scripts', 'fonttools')()
      File "/usr/local/Cellar/fonttools/3.29.0/libexec/lib/python2.7/site-packages/fontTools/__main__.py", line 29, in main
        runpy.run_module(mod, run_name='__main__')
      File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 192, in run_module
        fname, loader, pkg_name)
      File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/usr/local/Cellar/fonttools/3.29.0/libexec/lib/python2.7/site-packages/fontTools/merge.py", line 1129, in <module>
        sys.exit(main())
      File "/usr/local/Cellar/fonttools/3.29.0/libexec/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
        return func(*args, **kwds)
      File "/usr/local/Cellar/fonttools/3.29.0/libexec/lib/python2.7/site-packages/fontTools/merge.py", line 1122, in main
        font = merger.merge(args)
      File "/usr/local/Cellar/fonttools/3.29.0/libexec/lib/python2.7/site-packages/fontTools/merge.py", line 962, in merge
        table = clazz(tag).merge(self, tables)
      File "/usr/local/Cellar/fonttools/3.29.0/libexec/lib/python2.7/site-packages/fontTools/merge.py", line 160, in merge
        return m.mergeObjects(self, self.mergeMap, tables)
      File "/usr/local/Cellar/fonttools/3.29.0/libexec/lib/python2.7/site-packages/fontTools/merge.py", line 1008, in mergeObjects
        value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
      File "/usr/local/Cellar/fonttools/3.29.0/libexec/lib/python2.7/site-packages/fontTools/merge.py", line 49, in equal
        assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
    AssertionError: Expected all items to be equal: ['loca', NotImplemented]

Is there an option that takes care of all of this? All I want is Noto Emoji's glyphs in Helvetica, overwriting Helvetica's glyphs.

**Comment by justvanrossum** [comment]
Now you're trying to merge a ttf with an otf.

**Comment by SamusAranX** [comment]
That's just a side effect of my font editing app only being able to export OTF files.
The original Helvetica Neue and Noto Emoji files are TTFs.

**Comment by justvanrossum** [comment]
Sure, but it's also causing your error.

**Comment by SamusAranX** [comment]
I think we got sidetracked here. I have two files: HelveticaNeue-Regular.ttf, with an UPM of 1000, and NotoEmoji-Regular.ttf, with an UPM of 2048.
(Let's ignore the otf file from earlier, that was something else)

I neither have the tools or skills required to go through either of these fonts and rescale every glyph, so I was hoping fonttools could take care of that for me. Can it?

**Comment by justvanrossum** [comment]
There is no command line tool to scale a font currently, so it can't be done without writing code (and it's not quite trivial, as things like GPOS also need to be scaled).

**Comment by m4rc1e** [comment]
Does the EULA for your version Helvetica Neue grant you permission to make modifications?

Doing a quick search I found, https://www.fonts.com/font/linotype/helvetica/licenses#

> **9. Intellectual and Industrial Property Rights**...You agree not to adapt, modify, alter, translate, convert, or otherwise change the Font Software, or to create Derivative Works from Font Software or any portion thereof

**Comment by SamusAranX** [comment]
> it can't be done without writing code

That's what I feared. Thanks for clearing that up though.

> Does the EULA for your version Helvetica Neue grant you permission to make modifications?

I honestly have no idea. I extracted my ttf from the version of `HelveticaNeue.ttc` that comes with macOS High Sierra. But since I'm neither redistributing the file nor selling it, who could possibly care?

**Comment by behdad** [comment]
The merge script is really designed to merge very similar fonts, not arbitrary ones...

**Comment by NightMachinary** [comment]
@SamusAranX Did you find any solutions?

**Comment by khaledmsm** [comment]
did you find solution ?
