### ISSUE TITLE
otf2ttf  OverflowError: unsigned short is greater than maximum

### ISSUE THREAD

**Issue by plutext** [fonttools/fonttools#1329]
I want to convert the Noto CJK fonts from OTF to TTF (so they work better with Microsoft Word).

Here's what happens with NotoSansCJKtc-Regular.otf

```
$ ./otf2ttf.py NotoSansCJKtc-Regular.otf -o NotoSansCJKtc-Regular.ttf
Traceback (most recent call last):
  File "./otf2ttf.py", line 91, in <module>
    sys.exit(main())
  File "./otf2ttf.py", line 87, in main
    font.save(output)
  File "/home/me/.local/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 173, in save
    writer_reordersTables = self._save(tmp)
  File "/home/me/.local/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 212, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/home/me/.local/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 633, in _writeTable
    tabledata = self.getTableData(tag)
  File "/home/me/.local/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 651, in getTableData
    return self.tables[tag].compile(self)
  File "/home/me/.local/lib/python3.7/site-packages/fontTools/ttLib/tables/_p_o_s_t.py", line 51, in compile
    data = data + self.encode_format_2_0(ttFont)
  File "/home/me/.local/lib/python3.7/site-packages/fontTools/ttLib/tables/_p_o_s_t.py", line 173, in encode_format_2_0
    indices.append(index)
OverflowError: unsigned short is greater than maximum
```

**Comment by miguelsousa** [comment]
Have you tried using `--post-format 3` option?

**Comment by plutext** [comment]
I hadn't, but using that does work, thanks!

```
$ ./otf2ttf.py NotoSansCJKtc-Regular.otf -o NotoSansCJKtc-Regular.ttf --post-format 3
```

**Comment by miguelsousa** [comment]
https://github.com/googlei18n/cu2qu/issues/47#issuecomment-272054508

**Comment by khaledhosny** [comment]
I think the otf2ttf.py should check if the number of glyphs does not fit in `post` table format 2 and automatically switch to format 3, probably with a warning.
