### ISSUE TITLE
[subset/CFF] fails with a hinted empty path

### ISSUE THREAD

**Issue by blueshade7** [fonttools/fonttools#1379]
pyftsubset fails with --no-hinting, --no-desubroutinize (default) on the attached font (mod copy of Source Code Pro Regular) at a glyph calling out a subroutine of a hinted empty path.
[SourceCodePro-mod.otf.zip](https://github.com/fonttools/fonttools/files/2582279/SourceCodePro-mod.otf.zip)

```
% pyftsubset SourceCodePro-mod.otf --output-file=temp.otf --unicodes=20 --no-hinting 
Traceback (most recent call last):
  File "/usr/local/bin/pyftsubset", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3320, in main
    save_font(font, outfile, options)
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 3171, in save_font
    font.save(outfile, reorderTables=options.canonical_order)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 173, in save
    writer_reordersTables = self._save(tmp)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 212, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 629, in _writeTable
    self._writeTable(masterTable, writer, done, tableCache)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 633, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 651, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/C_F_F_.py", line 20, in compile
    self.cff.compile(f, otFont, isCFF2=False)
  File "/usr/local/lib/python2.7/site-packages/fontTools/cffLib/__init__.py", line 141, in compile
    children = topCompiler.getChildren(strings)
  File "/usr/local/lib/python2.7/site-packages/fontTools/cffLib/__init__.py", line 453, in getChildren
    children.extend(topDict.getChildren(strings))
  File "/usr/local/lib/python2.7/site-packages/fontTools/cffLib/__init__.py", line 2144, in getChildren
    items, strings, self, isCFF2=isCFF2)
  File "/usr/local/lib/python2.7/site-packages/fontTools/cffLib/__init__.py", line 370, in __init__
    self.items = self.getItems(items, strings)
  File "/usr/local/lib/python2.7/site-packages/fontTools/cffLib/__init__.py", line 537, in getItems
    cs.compile(self.isCFF2)
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/psCharStrings.py", line 1004, in compile
    self.check_program(program, isCFF2=isCFF2)
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/psCharStrings.py", line 997, in check_program
    assert self.program[-1] in ("endchar", "return", "callsubr", "callgsubr", "seac"), "illegal CharString"
AssertionError: illegal CharString
```
The offending CharString reads (as ttx output):
```
        <CharString name="space">
          -107 callgsubr
        </CharString>
```
```
    <GlobalSubrs>
      <!-- The 'index' attribute is only for humans; it is ignored when parsed. -->
      <CharString index="0">
        1000 10 20 hstem
        endchar
      </CharString>
    </GlobalSubrs>
```

**Comment by behdad** [comment]
Do you have a full font I can test?

**Comment by blueshade7** [comment]
I don't have a license to post the original font with which I found the bug, sorry. Attached is my result of attempt to repro the bug by modifying an open source font.

**Comment by behdad** [comment]
Ah sorry didn't see the attachment. Was on mobile.

**Comment by behdad** [comment]
Fixed.  Thanks.

**Comment by behdad** [comment]
Good to add a test some time.
