### ISSUE TITLE
Issue generating instance

### ISSUE THREAD

**Issue by weiweihuanghuang** [fonttools/fonttools#1380]
I'm running `fonttools varLib.mutator WorkSans-Italic-VF.ttf wght=900` on this [VF-ttf](https://github.com/weiweihuanghuang/Work-Sans/blob/master/fonts/variable/WorkSans-Italic-VF.ttf?raw=true) and get this outpuit:
```
Location: {'wght': 900.0}
Loading variable font
Normalized location: {'wght': 1.0}
Mutating glyf/gvar tables
Mutating MVAR table
Mutating GDEF/GPOS/GSUB tables
Building interpolated tables
Traceback (most recent call last):
  File "/usr/local/bin/fonttools", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/fontTools/__main__.py", line 29, in main
    runpy.run_module(mod, run_name='__main__')
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/mutator.py", line 212, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/mutator.py", line 203, in main
    instantiateVariableFont(varfont, loc, inplace=True)
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/mutator.py", line 122, in instantiateVariableFont
    merger.instantiate()
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/merger.py", line 732, in instantiate
    assert record.FeatureTableSubstitution.Version == 0x00010000
AssertionError

```

**Comment by anthrotype** [comment]
same as https://github.com/fonttools/fonttools/pull/1374

@weiweihuanghuang mind to send a PR?

**Comment by anthrotype** [comment]
oh it's actually the same file and line! so you just need to use the updated fonttools.
I'll cut a new release later today. You can `pip install -e .` from a git-cloned fonttools

**Comment by justvanrossum** [comment]
Yeah, it was fixed by #1375.

**Comment by weiweihuanghuang** [comment]
New bug from installing from [latest commit](https://github.com/fonttools/fonttools/tree/f99afc70d3fd21addcae2f955ccb2a2b99c5cc2e):
[WorkSans-Italic-VF.ttf.zip](https://github.com/fonttools/fonttools/files/2591702/WorkSans-Italic-VF.ttf.zip)

```
fonttools varLib.mutator WorkSans-Italic-VF.ttf wght=900
Location: {'wght': 900.0}
Loading variable font
Normalized location: {'wght': 1.0}
Mutating glyf/gvar tables
Mutating MVAR table
Mutating GDEF/GPOS/GSUB tables
Building interpolated tables
Pruning name table
Removing variable tables
Saving instance font WorkSans-Italic-VF-instance.ttf
Traceback (most recent call last):
  File "/usr/local/bin/fonttools", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/fontTools/__main__.py", line 29, in main
    runpy.run_module(mod, run_name='__main__')
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/mutator.py", line 212, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/mutator.py", line 206, in main
    varfont.save(outfile)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 173, in save
    writer_reordersTables = self._save(tmp)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 212, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 633, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 651, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 70, in compile
    self.table.compile(writer, font)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 709, in compile
    conv.write(writer, font, table, value)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 520, in write
    value.compile(subWriter, font)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 680, in compile
    conv.write(writer, font, table, value, i)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 520, in write
    value.compile(subWriter, font)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 680, in compile
    conv.write(writer, font, table, value, i)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 520, in write
    value.compile(subWriter, font)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 709, in compile
    conv.write(writer, font, table, value)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 520, in write
    value.compile(subWriter, font)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 680, in compile
    conv.write(writer, font, table, value, i)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 394, in write
    value.compile(writer, font)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 709, in compile
    conv.write(writer, font, table, value)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 520, in write
    value.compile(subWriter, font)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 709, in compile
    conv.write(writer, font, table, value)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 218, in write
    writer.writeShort(value)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 425, in writeShort
    assert -32768 <= value < 32768, value
AssertionError: (None, 'XCoordinate', 'Anchor', 'MarkRecord[0]', 'MarkArray', 'MarkBasePos[0]', 'Lookup[2]', 'LookupList')
```
from this

**Comment by behdad** [comment]
I'm fixing it.
