### ISSUE TITLE
AssertionError merging woff

### ISSUE THREAD

**Issue by dimaqq** [fonttools/fonttools#1408]
Test data: https://github.com/dimaqq/kanji-sudoku/tree/gh-pages/fnt (it's my repo, a 3rd party Kanji stroke order font split into subsets)

`pyftmerge stroke0.woff` OK

`pyftmerge stroke0.woff stroke1.woff` fails with:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 1122, in main
    font = merger.merge(args)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 962, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 653, in merge
    DefaultTable.merge(self, m, tables)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 160, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 1008, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 122, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in lst)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 122, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in lst)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 516, in mergeScriptRecords
    rec.Script = mergeScripts(d[tag])
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 501, in mergeScripts
    self.DefaultLangSys = mergeLangSyses([s.DefaultLangSys for s in lst if s.DefaultLangSys])
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 468, in mergeLangSyses
    assert lst
AssertionError
```

**Comment by anthrotype** [comment]
I know, that AssertionError is quite obscure, and overall the merge.py module is poorly documented.

In this case the problem is not about the files being woff. What's triggering the assertion error is the fact that in your fonts' GSUB table, there are script tables without DefaultLangSys table.
They look like this:

```xml
  <GSUB>
    <Version value="0x00010000"/>
    <ScriptList>
      <!-- ScriptCount=7 -->
      <ScriptRecord index="0">
        <ScriptTag value="DFLT"/>
        <Script>
          <!-- LangSysCount=0 -->
        </Script>
      </ScriptRecord>
      <ScriptRecord index="1">
        <ScriptTag value="arab"/>
        <Script>
          <!-- LangSysCount=0 -->
        </Script>
      </ScriptRecord>
```

Note, this doesn't mean that the fonts are invalid, the spec does allow DefaultLangSys offset to be NULL.
I think the merger should take this possibility into account.

@behdad would it be enough to check whether `[s.DefaultLangSys for s in lst if s.DefaultLangSys]` turns out to be an empty list and in that case set `self.DefaultLangSys` to None?

**Comment by behdad** [comment]
I don't know why I did it that way.  But yeah, if all are None, just set to None.
