### ISSUE TITLE
pyftmerge: getting OverflowError

### ISSUE THREAD

**Issue by dadasutasudadas** [fonttools/fonttools#1412]
When I tried to merge fonts covering the range of U + 100000 to U + 10EA5F and fonts covering U + 10EA60 to U + 10FFF5, I got the following error.

Traceback (most recent call last):
  File "c:\python2715\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python2715\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python2715\Scripts\pyftmerge.exe\__main__.py", line 9, in <module>
  File "c:\python2715\lib\site-packages\fontTools\misc\loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "c:\python2715\lib\site-packages\fontTools\merge.py", line 1125, in main
    font.save(outfile)
  File "c:\python2715\lib\site-packages\fontTools\ttLib\ttFont.py", line 173, in save
    writer_reordersTables = self._save(tmp)
  File "c:\python2715\lib\site-packages\fontTools\ttLib\ttFont.py", line 212, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "c:\python2715\lib\site-packages\fontTools\ttLib\ttFont.py", line 633, in _writeTable
    tabledata = self.getTableData(tag)
  File "c:\python2715\lib\site-packages\fontTools\ttLib\ttFont.py", line 651, in getTableData
    return self.tables[tag].compile(self)
  File "c:\python2715\lib\site-packages\fontTools\ttLib\tables\_p_o_s_t.py", line 51, in compile
    data = data + self.encode_format_2_0(ttFont)
  File "c:\python2715\lib\site-packages\fontTools\ttLib\tables\_p_o_s_t.py", line 173, in encode_format_2_0
    indices.append(index)
OverflowError: unsigned short is greater than maximum

**Comment by anthrotype** [comment]
you're trying to pack too many glyphs into a single opentype font. you can't fit more than 65535 glyphs.

**Comment by dadasutasudadas** [comment]
Fonts that support the range U+100000 to U+10EA5F have 60003 glyphs(include 3 other glyphs). The font that supports U + 10EA 60 to U + 10 FFF 5 has 5527 (include 1 other glyph)glyphs. Since the total number of glyphs expected after merging is 65530, I think that there are five margins.

**Comment by anthrotype** [comment]
right ok, then your fonts probably aren't including glyph names from the "standard macintosh set" so all glyph names in post table format 2.0 end up in the extra names, but post format 2.0 only has room between 258 and 65535 for these:

> If the name index is between 0 and 257, treat the name index as a glyph index in the Macintosh standard order. If the name index is between 258 and 65535, then subtract 258 and use that to index into the list of Pascal strings at the end of the table. 

https://docs.microsoft.com/en-us/typography/opentype/spec/post

I'd recommend you switch to post table format 3.0, which basically means dropping all the glyph names.

**Comment by anthrotype** [comment]
try something like this
```python
from fontTools.ttLib import TTFont
font = TTFont("myfont.ttf")
font["post"].formatType = 3.0
font.save("myfont2.ttf")
````

**Comment by dadasutasudadas** [comment]
Thank you! It went well!
