### ISSUE TITLE
[subset] support subsetting glyphs from CFF2 fonts

### ISSUE THREAD

**Issue by anthrotype** [fonttools/fonttools#1448]
Right now, if one passes an OpenType font containing CFF2 table, the subsetter chokes like this

```
$ fonttools subset /home/clupo/Downloads/SourceSerifVariable-Roman.otf A B C
Traceback (most recent call last):
  File "/home/clupo/.pyenv/versions/fontmake-py37/bin/fonttools", line 11, in <module>
    load_entry_point('fonttools', 'console_scripts', 'fonttools')()
  File "/home/clupo/Github/fonttools/Lib/fontTools/__main__.py", line 29, in main
    runpy.run_module(mod, run_name='__main__')
  File "/home/clupo/.pyenv/versions/3.7.0/lib/python3.7/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/home/clupo/.pyenv/versions/3.7.0/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/clupo/Github/fonttools/Lib/fontTools/subset/__main__.py", line 7, in <module>
    sys.exit(main())
  File "/home/clupo/Github/fonttools/Lib/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/home/clupo/Github/fonttools/Lib/fontTools/subset/__init__.py", line 2824, in main
    subsetter.subset(font)
  File "/home/clupo/Github/fonttools/Lib/fontTools/subset/__init__.py", line 2625, in subset
    self._prune_pre_subset(font)
  File "/home/clupo/Github/fonttools/Lib/fontTools/subset/__init__.py", line 2433, in _prune_pre_subset
    retain = table.prune_pre_subset(font, self.options)
  File "/home/clupo/Github/fonttools/Lib/fontTools/subset/cff.py", line 80, in prune_pre_subset
    private = font.FDArray[fdSelectIndex].Private
  File "/home/clupo/Github/fonttools/Lib/fontTools/cffLib/__init__.py", line 585, in __getitem__
    item = self.items[index]
TypeError: list indices must be integers or slices, not NoneType
```

**Comment by anthrotype** [comment]
after commit https://github.com/anthrotype/fonttools/commit/9b296463bde96e6032dedd4c886580cae8ee171e, I can run the subsetter on CFF2 font like SourceSerifVariable without error. We probably need more tests before we can say that CFF2 is properly supported by the subsetter.

**Comment by anthrotype** [comment]
Hm.. It seems like I can't even dump a CFF2 table with ttx.

```
$ ttx ~/Downloads/SourceSerifVariable-Roman.otf 
Dumping "/home/clupo/Downloads/SourceSerifVariable-Roman.otf" to "/home/clupo/Downloads/SourceSerifVariable-Roman.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'BASE' table...
Dumping 'CFF2' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/home/clupo/Github/fonttools/Lib/fontTools/ttx.py", line 398, in main
    process(jobs, options)
  File "/home/clupo/Github/fonttools/Lib/fontTools/ttx.py", line 372, in process
    action(input, output, options)
  File "/home/clupo/Github/fonttools/Lib/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/home/clupo/Github/fonttools/Lib/fontTools/ttx.py", line 269, in ttDump
    newlinestr=options.newlinestr)
  File "/home/clupo/Github/fonttools/Lib/fontTools/ttLib/ttFont.py", line 228, in saveXML
    self._saveXML(writer, **kwargs)
  File "/home/clupo/Github/fonttools/Lib/fontTools/ttLib/ttFont.py", line 283, in _saveXML
    self._tableToXML(tableWriter, tag, splitGlyphs=splitGlyphs)
  File "/home/clupo/Github/fonttools/Lib/fontTools/ttLib/ttFont.py", line 314, in _tableToXML
    table.toXML(writer, self)
  File "/home/clupo/Github/fonttools/Lib/fontTools/ttLib/tables/C_F_F_.py", line 42, in toXML
    self.cff.toXML(writer)
  File "/home/clupo/Github/fonttools/Lib/fontTools/cffLib/__init__.py", line 156, in toXML
    font.toXML(xmlWriter)
  File "/home/clupo/Github/fonttools/Lib/fontTools/cffLib/__init__.py", line 2330, in toXML
    BaseDict.toXML(self, xmlWriter)
  File "/home/clupo/Github/fonttools/Lib/fontTools/cffLib/__init__.py", line 2272, in toXML
    conv.xmlWrite(xmlWriter, name, value)
  File "/home/clupo/Github/fonttools/Lib/fontTools/cffLib/__init__.py", line 1175, in xmlWrite
    value.toXML(xmlWriter)
  File "/home/clupo/Github/fonttools/Lib/fontTools/cffLib/__init__.py", line 722, in toXML
    self[i].toXML(xmlWriter)
  File "/home/clupo/Github/fonttools/Lib/fontTools/cffLib/__init__.py", line 2272, in toXML
    conv.xmlWrite(xmlWriter, name, value)
  File "/home/clupo/Github/fonttools/Lib/fontTools/cffLib/__init__.py", line 1175, in xmlWrite
    value.toXML(xmlWriter)
  File "/home/clupo/Github/fonttools/Lib/fontTools/cffLib/__init__.py", line 2272, in toXML
    conv.xmlWrite(xmlWriter, name, value)
  File "/home/clupo/Github/fonttools/Lib/fontTools/cffLib/__init__.py", line 1175, in xmlWrite
    value.toXML(xmlWriter)
  File "/home/clupo/Github/fonttools/Lib/fontTools/cffLib/__init__.py", line 652, in toXML
    subr.toXML(xmlWriter)
  File "/home/clupo/Github/fonttools/Lib/fontTools/misc/psCharStrings.py", line 1091, in toXML
    if self.isCFF2:
AttributeError: 'T2CharString' object has no attribute 'isCFF2'
```
