### ISSUE TITLE
[CFF2] Unhandled exception

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#1474]
[cff2_vf.otf.zip](https://github.com/fonttools/fonttools/files/2809647/cff2_vf.otf.zip)

```
$ ttx -t CFF2 cff2_vf.otf 
Dumping "cff2_vf.otf" to "cff2_vf.ttx"...
Dumping 'CFF2' table...
ERROR: Error in charstring 3
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "fontTools/ttx.py", line 398, in main
    process(jobs, options)
  File "fontTools/ttx.py", line 372, in process
    action(input, output, options)
  File "fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "fontTools/ttx.py", line 269, in ttDump
    newlinestr=options.newlinestr)
  File "fontTools/ttLib/ttFont.py", line 228, in saveXML
    self._saveXML(writer, **kwargs)
  File "fontTools/ttLib/ttFont.py", line 283, in _saveXML
    self._tableToXML(tableWriter, tag, splitGlyphs=splitGlyphs)
  File "fontTools/ttLib/ttFont.py", line 314, in _tableToXML
    table.toXML(writer, self)
  File "fontTools/ttLib/tables/C_F_F_.py", line 42, in toXML
    self.cff.toXML(writer)
  File "fontTools/cffLib/__init__.py", line 156, in toXML
    font.toXML(xmlWriter)
  File "fontTools/cffLib/__init__.py", line 2322, in toXML
    self.decompileAllCharStrings()
  File "fontTools/cffLib/__init__.py", line 2336, in decompileAllCharStrings
    charString.decompile()
  File "fontTools/misc/psCharStrings.py", line 966, in decompile
    decompiler.execute(self)
  File "fontTools/misc/psCharStrings.py", line 292, in execute
    token, isOperator, index = charString.getToken(index)
  File "fontTools/misc/psCharStrings.py", line 1040, in getToken
    token, index = handler(self, b0, self.bytecode, index)
  File "fontTools/misc/psCharStrings.py", line 37, in read_smallInt2
    b1 = byteord(data[index])
IndexError: string index out of range
```

**Comment by justvanrossum** [comment]
See #1451 and #1456. Could it be that that font was compiled with a version of fonttools before those bugs were fixed? The font is currupt in exactly the way that bug fixed in #1456 could have.

**Comment by readroberts** [comment]
I think this is something new: I get the same stack dump with that head of the fonttools master branch, which has the aforementioned fixes. Will look at this.

**Comment by readroberts** [comment]
Now that I have fixed the font ( which is a test font in the afdko), I argue against protecting  psCharstrings against this error. The test font had some garbage data added to the  end of the charstring because of bugs in July 2018 in merging charstring hint data. However, in general, you get this problem only when you have a malformed charstring, with some data truncated from the end of the charstring, and it would be bad to silently truncate the charstring at the start of the bad data. I think  that "ERROR: Error in charstring X' is more appropriate. This should also be a very rare error.

**Comment by miguelsousa** [comment]
Bad charstring. Closing.
