### ISSUE TITLE
[CFF2] 'T2CharString' object has no attribute 'isCFF2'

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#1479]
[font_cff2.otf.zip](https://github.com/fonttools/fonttools/files/2814236/font_cff2.otf.zip)

```
$ ttx -t CFF2 font_cff2.otf 
Dumping "font_cff2.otf" to "font_cff2.ttx"...
Dumping 'CFF2' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "fontTools/ttx.py", line 398, in main
    process(jobs, options)
  File "fontTools/ttx.py", line 372, in process
    action(input, output, options)
  File "fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "fontTools/ttx.py", line 269, in ttDump
    newlinestr=options.newlinestr)
  File "fontTools/ttLib/ttFont.py", line 228, in saveXML
    self._saveXML(writer, **kwargs)
  File "fontTools/ttLib/ttFont.py", line 283, in _saveXML
    self._tableToXML(tableWriter, tag, splitGlyphs=splitGlyphs)
  File "fontTools/ttLib/ttFont.py", line 314, in _tableToXML
    table.toXML(writer, self)
  File "fontTools/ttLib/tables/C_F_F_.py", line 42, in toXML
    self.cff.toXML(writer)
  File "fontTools/cffLib/__init__.py", line 156, in toXML
    font.toXML(xmlWriter)
  File "fontTools/cffLib/__init__.py", line 2330, in toXML
    BaseDict.toXML(self, xmlWriter)
  File "fontTools/cffLib/__init__.py", line 2272, in toXML
    conv.xmlWrite(xmlWriter, name, value)
  File "fontTools/cffLib/__init__.py", line 1175, in xmlWrite
    value.toXML(xmlWriter)
  File "fontTools/cffLib/__init__.py", line 722, in toXML
    self[i].toXML(xmlWriter)
  File "fontTools/cffLib/__init__.py", line 2272, in toXML
    conv.xmlWrite(xmlWriter, name, value)
  File "fontTools/cffLib/__init__.py", line 1175, in xmlWrite
    value.toXML(xmlWriter)
  File "fontTools/cffLib/__init__.py", line 2272, in toXML
    conv.xmlWrite(xmlWriter, name, value)
  File "fontTools/cffLib/__init__.py", line 1175, in xmlWrite
    value.toXML(xmlWriter)
  File "fontTools/cffLib/__init__.py", line 652, in toXML
    subr.toXML(xmlWriter)
  File "fontTools/misc/psCharStrings.py", line 1091, in toXML
    if self.isCFF2:
AttributeError: 'T2CharString' object has no attribute 'isCFF2'
```

**Comment by justvanrossum** [comment]
Can't reproduce, I think you're looking at #1451, which has been fixed.

**Comment by justvanrossum** [comment]
Line 1091 in `fontTools/misc/psCharStrings.py` looks different now.

**Comment by readroberts** [comment]
@justvanrossum  Just, the current afdko requires fonttools 3.35, so it doesn't have this fix yet.
