### ISSUE TITLE
[ufoLib] UnicodeDecodeError in py27

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#1494]
```python
# coding: utf-8
from fontTools.ufoLib import UFOReader
UFOReader('zá意.txt', validate=False)
```
```
Traceback (most recent call last):
  File "ft.py", line 5, in <module>
    UFOReader('zá意.txt', validate=False)
  File "fontTools/ufoLib/__init__.py", line 209, in __init__
    structure = _sniffFileStructure(path)
  File "fontTools/ufoLib/__init__.py", line 1602, in _sniffFileStructure
    "The specified UFO does not have a known structure: '%s'" % ufo_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 2: ordinal not in range(128)
```

**Comment by justvanrossum** [comment]
@miguelsousa we're considering to close this as "won't fix". Feel free to make a better PR than mine, though.

**Comment by miguelsousa** [comment]
That's fine. I agree, too much overhead for little gain since py27 is on its way out.
Thanks for the effort.
