### ISSUE TITLE
KeyError when executing ttx with F_F_T_M_ table

### ISSUE THREAD

**Issue by vitalyvolkov** [fonttools/fonttools#150]
Here is traceback

```
FAILED: /home/hash/Documents/Dave/collection/ofl/rozhaone
'value'
Traceback (most recent call last):
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/bin/fontbakery.py", line 4, in <module>
    __import__('pkg_resources').run_script('FontBakery-cli==0.1', 'fontbakery.py')
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/pkg_resources.py", line 1438, in run_script
    execfile(script_filename, namespace, namespace)
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontBakery_cli-0.1-py2.7.egg/EGG-INFO/scripts/fontbakery.py", line 103, in <module>
    run_bakery(p)
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontBakery_cli-0.1-py2.7.egg/EGG-INFO/scripts/fontbakery.py", line 88, in run_bakery
    b.run()
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontBakery_cli-0.1-py2.7.egg/bakery_cli/bakery.py", line 169, in run
    return self.normal_run(self.pipes)
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontBakery_cli-0.1-py2.7.egg/bakery_cli/bakery.py", line 191, in normal_run
    p.execute(self.config)
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontBakery_cli-0.1-py2.7.egg/bakery_cli/pipe/build.py", line 86, in execute
    self.execute_ttx(ttxfiles)
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontBakery_cli-0.1-py2.7.egg/bakery_cli/pipe/build.py", line 117, in execute_ttx
    ttx.main(paths)
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontTools/fontTools/ttx.py", line 310, in main
    process(jobs, options)
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontTools/fontTools/ttx.py", line 295, in process
    action(input, output, options)
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontTools/fontTools/ttx.py", line 216, in ttCompile
    ttf.importXML(input, quiet=options.quiet)
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontTools/fontTools/ttLib/__init__.py", line 337, in importXML
    reader.read()
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontTools/fontTools/misc/xmlReader.py", line 30, in read
    self._parseFile(file)
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontTools/fontTools/misc/xmlReader.py", line 49, in _parseFile
    parser.Parse(chunk, 0)
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontTools/fontTools/misc/xmlReader.py", line 68, in _startElementHandler
    subReader.read()
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontTools/fontTools/misc/xmlReader.py", line 30, in read
    self._parseFile(file)
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontTools/fontTools/misc/xmlReader.py", line 49, in _parseFile
    parser.Parse(chunk, 0)
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontTools/fontTools/misc/xmlReader.py", line 115, in _endElementHandler
    self.currentTable.fromXML(name, attrs, content, self.ttFont)
  File "/home/hash/Documents/Dave/fontbakery-webui/venv/lib/python2.7/site-packages/FontTools/fontTools/ttLib/tables/F_F_T_M_.py", line 41, in fromXML
    value = attrs["value"]
KeyError: 'value'
```

**Comment by silicontrip** [comment]
Is this missing raw="True" tag a bug in the font or a bug in the software?
If it's a bug in the font have you considered writing a TTX validator, that validates the TTX structure.

**Comment by behdad** [comment]
The raw="True" wasn't being written out in original TTX;  I fixed that a while ago.  Before, TTX format was not suitable for archival purposes.  It is my aim to make it so, and I think it's in much better shape now.
