### ISSUE TITLE
[subset/var] subsetting VVAR table fails if VOrgMap non-empty

### ISSUE THREAD

**Issue by blueshade7** [fonttools/fonttools#1516]
Line 1856 - 1857 in `fonttools/Lib/fontTools/subset/__init__.py` reads:
```
	if table.VOrgMap:

		table.RsbMap.mapping = {k:varidx_map[v] for k,v in table.RsbMap.mapping.items()}
```
It should be:
```
	if table.VOrgMap:
		table.VOrgMap.mapping = {k:varidx_map[v] for k,v in table.VOrgMap.mapping.items()}
```
Otherwise subsetting VVAR table with non-empty VOrgMap fails as:
```
Traceback (most recent call last):
  File "/usr/local/bin/pyftsubset", line 11, in <module>
    load_entry_point('fonttools==3.37.4.dev0', 'console_scripts', 'pyftsubset')()
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.37.4.dev0-py2.7.egg/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.37.4.dev0-py2.7.egg/fontTools/subset/__init__.py", line 2827, in main
    subsetter.subset(font)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.37.4.dev0-py2.7.egg/fontTools/subset/__init__.py", line 2630, in subset
    self._subset_glyphs(font)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.37.4.dev0-py2.7.egg/fontTools/subset/__init__.py", line 2576, in _subset_glyphs
    retain = table.subset_glyphs(self)
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.37.4.dev0-py2.7.egg/fontTools/subset/__init__.py", line 1857, in subset_glyphs
    table.RsbMap.mapping = {k:varidx_map[v] for k,v in table.RsbMap.mapping.items()}
  File "/usr/local/lib/python2.7/site-packages/fonttools-3.37.4.dev0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 546, in __getattr__
    raise AttributeError(attr)
```

**Comment by blueshade7** [comment]
[AdobeVFPrototype.abc_vvar.otf.zip](https://github.com/fonttools/fonttools/files/2895949/AdobeVFPrototype.abc_vvar.otf.zip)
Test case: mod-copy of AdobeVFPrototype.otf with VVAR table added.

**Comment by blueshade7** [comment]
[AdobeVFPrototype.abc_vvar2.otf.zip](https://github.com/fonttools/fonttools/files/2896042/AdobeVFPrototype.abc_vvar2.otf.zip)
BsbMap had the same problem. Another test case font with BsbMap.
