### ISSUE TITLE
ttx file contain Chinese character cannot compile to ttf

### ISSUE THREAD

**Issue by asnahu** [fonttools/fonttools#1530]
![image](https://user-images.githubusercontent.com/19888895/53811494-80cae100-3f94-11e9-8b30-085a13d11be1.png)

the value above `fzpingxianlantingsong_GBK` should be changed to:

```
方正屏显兰亭宋_GBK
```

but it will generate an error, as bellow:

> ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttx.py", line 401, in main
    process(jobs, options)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttx.py", line 375, in process
    action(input, output, options)
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttx.py", line 286, in ttCompile
    ttf.importXML(input)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 336, in importXML
    reader.read()
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/xmlReader.py", line 49, in read
    self._parseFile(self.file)
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/xmlReader.py", line 74, in _parseFile
    parser.Parse(chunk, 0)
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/xmlReader.py", line 156, in _endElementHandler
    self.currentTable.fromXML(name, attrs, content, self.ttFont)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/_n_a_m_e.py", line 94, in fromXML
    name.fromXML(name, attrs, content, ttFont)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/tables/_n_a_m_e.py", line 436, in fromXML
    self.string = s.encode(encoding)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/mac_roman.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-6: character maps to <undefined>

**Comment by justvanrossum** [comment]
`platformID="1"` is Mac, `platEncID="0"` is Roman, and you can't encode Chinese characters with that encoding. It seems encoding support for Mac is weak in fonttools, and while in theory it should be possible to encode Chinese for the Mac platform, I don't immediately see how to do that. If however you'd use the Windows platformID (3) and Windows unicode platEncId (1) and the appropriate langID (see https://docs.microsoft.com/en-us/typography/opentype/spec/name#platform-specific-encoding-and-language-ids-windows-platform-platform-id-3) it should work.

**Comment by khaledhosny** [comment]
Something like:
```xml
    <namerecord nameID="4" platformID="1" platEncID="2" langID="0x13" unicode="True">
      方正屏显兰亭宋_GBK                                                        
    </namerecord>
```

Should work, but it doesn’t since this legacy mac encoding does not support every modern Unicode character. Nothing for FontTools to fix here, either use a different string or a different `platEncID`.
