### ISSUE TITLE
'NoneType' object has no attribute 'nominalWidthX'

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#1558]
FontTools v3.39.0

This is a snippet straight from [fontBuilder](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/fontBuilder.py) to which I added the line with `print`.
My intent is to replace the hardcoded  **lsb** a few lines below.

```python
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.t2CharStringPen import T2CharStringPen

def drawTestGlyph(pen):
    pen.moveTo((100, 100))
    pen.lineTo((100, 1000))
    pen.curveTo((200, 900), (400, 900), (500, 1000))
    pen.lineTo((500, 100))
    pen.closePath()

fb = FontBuilder(1024, isTTF=False)
fb.setupGlyphOrder([".notdef", ".null", "A", "a"])
fb.setupCharacterMap({65: "A", 97: "a"})

advanceWidths = {".notdef": 600, "A": 600, "a": 600, ".null": 600}

familyName = "HelloTestFont"
styleName = "TotallyNormal"
nameStrings = dict(familyName=dict(en="HelloTestFont", nl="HalloTestFont"),
                   styleName=dict(en="TotallyNormal", nl="TotaalNormaal"))
nameStrings['psName'] = familyName + "-" + styleName

pen = T2CharStringPen(600, None)
drawTestGlyph(pen)
charString = pen.getCharString()
print(charString.calcBounds(None))
charStrings = {".notdef": charString, "A": charString, "a": charString, ".null": charString}
fb.setupCFF(nameStrings['psName'], {"FullName": nameStrings['psName']}, charStrings, {})

metrics = {}
for gn, advanceWidth in advanceWidths.items():
    metrics[gn] = (advanceWidth, 100)  # XXX lsb from glyph
fb.setupHorizontalMetrics(metrics)

fb.setupHorizontalHeader(ascent=824, descent=200)
fb.setupNameTable(nameStrings)
fb.setupOS2()
fb.setupPost()

fb.save("test.otf")
```

Running this yields the following traceback:
```
Traceback (most recent call last):
  File "fb_otf.py", line 26, in <module>
    print(charString.calcBounds(None))
  File "fonttools/Lib/fontTools/misc/psCharStrings.py", line 977, in calcBounds
    self.draw(boundsPen)
  File "fonttools/Lib/fontTools/misc/psCharStrings.py", line 970, in draw
    self.private.nominalWidthX, self.private.defaultWidthX,
AttributeError: 'NoneType' object has no attribute 'nominalWidthX'
```

How do I get past this ever pesky missing nominalWidthX & defaultWidthX attributes problem?

**Comment by justvanrossum** [comment]
Move the `print()` to after `fb.setupCFF()` and it works.

**Comment by miguelsousa** [comment]
Indeed. Thanks!
