### ISSUE TITLE
[subset] TT VF fails to subset

### ISSUE THREAD

**Issue by blueshade7** [fonttools/fonttools#1576]
A humongous TrueType variable font (15 axes) DecovarAlpha-VF.ttf (https://github.com/TypeNetwork/Decovar/blob/master/fonts/DecovarAlpha-VF.ttf) fails to subset.
```
% pyftsubset DecovarAlpha-VF.ttf --text=A
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/pyftsubset", line 11, in <module>
    load_entry_point('fonttools==3.40.1.dev0', 'console_scripts', 'pyftsubset')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 2834, in main
    subsetter.subset(font)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 2635, in subset
    self._prune_pre_subset(font)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 2443, in _prune_pre_subset
    retain = table.prune_pre_subset(font, self.options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontTools/subset/__init__.py", line 2201, in prune_pre_subset
    nameIDs.update([axis_rec.AxisNameID for axis_rec in stat.table.DesignAxisRecord.Axis])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_abcoll.py", line 605, in __iter__
    v = self[i]
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 102, in __getitem__
    item = self.conv.read(self.reader, self.font, {})
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 390, in read
    table.decompile(reader, font)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 631, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 264, in read
    return reader.readTag()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontTools/ttLib/tables/otBase.py", line 198, in readTag
    assert len(value) == 4, value
AssertionError: ('', 'AxisTag')
```

**Comment by behdad** [comment]
Works for me.
