### ISSUE TITLE
Pyftmerge crash on large GSUB Tables

### ISSUE THREAD

**Issue by ClintGoss** [fonttools/fonttools#1607]
A crash in pyftmerge ... I think it is an overstuffed GSUB table that is causing this crash in pyftmerge ... yes?

```
Traceback (most recent call last):
  File "C:\App\Python37\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 271, in getData
    items[i] = packUShort(item.pos - pos)
  File "C:\App\Python37\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 526, in packUShort
    return struct.pack(">H", value)
struct.error: 'H' format requires 0 <= number <= 65535

...

  File "C:\App\Python37\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 276, in getData
    raise OTLOffsetOverflowError(overflowErrorRecord)
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: ('GSUB', 'LookupIndex:', 1240, 'SubTableIndex:', None, 'ItemName:'
, None, 'ItemIndex:', None)
```

A combined GSUB table of between 99K and 124K bytes seems to cause this (I have a working example at 98K and it fails at 124K).

Any guidance / suggestions / ideas would be appreciated!

A reproducer package has been sent to Behdad at his request ...

**Comment by ClintGoss** [comment]
The original report I submitted was done against FontTools 3.38.0. I have just tried the same script against 3.41.0 and get (essentially) the same results.

The fonts are mostly Noto fonts and most have been scaled from 1000 UperEm to 2048 by my code on top of perl FontUtils (the "KM2K" in the file name). All fonts have then been subset by pyftsubset to a single script (but mulitple blocks) - the "_SS..." in the file name.

The GSUB tables of the merged files are rather large (NotoSerifTibetan and Myanmar, in particular) ... but that's all the likely useful info I have.

Running on Win7x64 produces this STDOUT/STDERR:

```
D:\Dev\MergeCrash>pyftmerge NotoSansRejang-Regular_2019_OFL_KM2K_SSRjng.ttf NotoSansSamaritan-Regular_2019_OFL_K
M2K_SSSamr.ttf NotoSansSaurashtra-Regular_2019_OFL_KM2K_SSSaur.ttf NotoSansSharada-Regular_2019_OFL_KM2K_SSShrd.ttf Noto
SansSoraSompeng-Regular_2019_OFL_KM2K_SSSora.ttf NotoSansSundanese-Regular_2019_OFL_KM2K_SSSund.ttf NotoSansSyriac-Regul
ar_2019_OFL_KM2K_SSSyrc.ttf NotoSansTagbanwa-Regular_2019_OFL_KM2K_SSTagb.ttf NotoSansTaiTham-Regular_2019_OFL_SSLana.tt
f NotoSansTakri-Regular_2019_OFL_KM2K_SSTakr.ttf NotoSansTirhuta-Regular_2019_OFL_KM2K_SSTirh.ttf NotoSansVai-Regular_20
19_OFL_KM2K_SSVaii.ttf NotoSansWarangCiti-Regular_2019_OFL_KM2K_SSWara.ttf NotoSansYi-Regular_2019_OFL_KM2K_SSYiii.ttf N
otoSerifSinhala-Regular_2019_OFL_KM2K_SSSinh.ttf NotoSerifTamil-Regular_2019_OFL_KM2K_SSTaml.ttf NotoSerifTelugu-Regular
_2019_OFL_SSTelu.ttf NotoSerifThai-Regular_2019_OFL_KM2K_SSThai.ttf NotoSerifTibetan-Regular_2019_OFL_KM2K_SSTibt.ttf Ta
iHeritagePro-Regular_SIL_2018_OFL_SSTavt.ttf
Traceback (most recent call last):
  File "c:\app\python37\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 271, in getData
    items[i] = packUShort(item.pos - pos)
  File "c:\app\python37\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 526, in packUShort
    return struct.pack(">H", value)
struct.error: 'H' format requires 0 <= number <= 65535

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\app\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\app\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\App\Python37\Scripts\pyftmerge.exe\__main__.py", line 9, in <module>
  File "c:\app\python37\lib\site-packages\fontTools\misc\loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "c:\app\python37\lib\site-packages\fontTools\merge.py", line 1129, in main
    font.save(outfile)
  File "c:\app\python37\lib\site-packages\fontTools\ttLib\ttFont.py", line 173, in save
    writer_reordersTables = self._save(tmp)
  File "c:\app\python37\lib\site-packages\fontTools\ttLib\ttFont.py", line 212, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "c:\app\python37\lib\site-packages\fontTools\ttLib\ttFont.py", line 633, in _writeTable
    tabledata = self.getTableData(tag)
  File "c:\app\python37\lib\site-packages\fontTools\ttLib\ttFont.py", line 651, in getTableData
    return self.tables[tag].compile(self)
  File "c:\app\python37\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 71, in compile
    return writer.getAllData()
  File "c:\app\python37\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 401, in getAllData
    tableData = table.getData()
  File "c:\app\python37\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 276, in getData
    raise OTLOffsetOverflowError(overflowErrorRecord)
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: ('GSUB', 'LookupIndex:', 284, 'SubTableIndex:', None, 'ItemName:',
 None, 'ItemIndex:', None)
```

**Comment by ClintGoss** [comment]
Would it be helpful if I posted the reproducer package here?

**Comment by miguelsousa** [comment]
I could be wrong but this error

      struct.error: 'H' format requires 0 <= number <= 65535

makes me think that the resulting font would have more glyphs than what the format allows.

**Comment by behdad** [comment]
I debugged this some.  Gets stuck trying to fix overflow in one of the  lookups, keeps retrying on the same lookup.  Maybe it is number of glyphs getting too large, donno.  Needs more debugging.

**Comment by ClintGoss** [comment]
Glyph count should be within (official) limits, but the combined GSUB is large (I think NotoSerifTibetan-Regular is the worst offender). I've got 20+ years of perl history, but no Python experience, so I'm stumbling around here ... not sure what to do. Been trying to track down the handling of GSUB LookupType 7 / Extension Substitution subtables, but I'm mostly stumbling ...

Any suggestions as to where I should look / what I can do would be appreciated. As a last resort, I can carve the project into multiple smaller fonts, but that would be a bit sad ...

**Comment by ClintGoss** [comment]
This pyftmerge crash is still an issue for me. I have carved multi-script fonts into separate "variants" to accommodate scripts that carry large GPOS tables. However (and I cannot see how this is done), is there use of / implementation of **GPOS lookup type 9 (Extension Positioning)**?
