### ISSUE TITLE
Varlib cannot find designspace from Glyphs source

### ISSUE THREAD

**Issue by aaronbell** [fonttools/fonttools#1623]
Hi. I recently updated my FontTools install from 3.33 to 3.42 and am now encountering a bug that I did not see previously:

`Traceback (most recent call last):
  File "build.py", line 172, in <module>
    main(sys.argv)
  File "build.py", line 153, in main
    proj.run_from_glyphs(GLYPHS_SOURCE, **args)
  File "/Users/aaronbell/Documents/LocalProjects/virtualenv/test/lib/python2.7/site-packages/fontmake/font_project.py", line 378, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/Users/aaronbell/Documents/LocalProjects/virtualenv/test/lib/python2.7/site-packages/fontmake/font_project.py", line 434, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/Users/aaronbell/Documents/LocalProjects/virtualenv/test/lib/python2.7/site-packages/fontmake/font_project.py", line 493, in run_from_ufos
    self.build_variable_font(designspace_path)
  File "/Users/aaronbell/Documents/LocalProjects/virtualenv/test/lib/python2.7/site-packages/fontmake/font_project.py", line 216, in build_variable_font
    master_locations, _ = self._designspace_locations(designspace_path)
  File "/Users/aaronbell/Documents/LocalProjects/virtualenv/test/lib/python2.7/site-packages/fontmake/font_project.py", line 549, in _designspace_locations
    ds = varLib.designspace.load(designspace_path)
AttributeError: 'module' object has no attribute 'designspace'`

For this specific project, I am building a variable font in Glyphs, exporting a GX version, then finally building the full variable font through FontTools. Has there been a change between 3.33 and 3.42 related to how the designspace is captured, or is there something else I am missing?

Thank you!

**Comment by aaronbell** [comment]
Looks like I needed to update my fontmake! Closing.
