### ISSUE TITLE
"Base master not found." error with OTF sparse masters

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#1634]
Getting a "Base master not found." error when running the command below on the attached file. The error does not happen with the TTF example (also included in the attachment).

    fonttools varLib SourceCodeVariable-Roman_OTF.designspace

```
Traceback (most recent call last):
  File "fonttools", line 11, in <module>
    sys.exit(main())
  File "fontTools/__main__.py", line 29, in main
    runpy.run_module(mod, run_name='__main__')
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "fontTools/varLib/__main__.py", line 7, in <module>
    sys.exit(main())
  File "fontTools/varLib/__init__.py", line 1075, in main
    optimize=options.optimize
  File "fontTools/varLib/__init__.py", line 916, in build
    _merge_OTL(vf, model, master_fonts, axisTags)
  File "fontTools/varLib/__init__.py", line 688, in _merge_OTL
    merger.mergeTables(font, master_fonts, ['GSUB', 'GDEF', 'GPOS'])
  File "fontTools/varLib/merger.py", line 108, in mergeTables
    for m in master_ttfs])
  File "fontTools/varLib/merger.py", line 950, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "fontTools/varLib/merger.py", line 94, in mergeThings
    self.mergeObjects(out, lst)
  File "fontTools/varLib/merger.py", line 73, in mergeObjects
    mergerFunc(self, value, values)
  File "fontTools/varLib/merger.py", line 950, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "fontTools/varLib/merger.py", line 94, in mergeThings
    self.mergeObjects(out, lst)
  File "fontTools/varLib/merger.py", line 73, in mergeObjects
    mergerFunc(self, value, values)
  File "fontTools/varLib/merger.py", line 950, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "fontTools/varLib/merger.py", line 94, in mergeThings
    self.mergeObjects(out, lst)
  File "fontTools/varLib/merger.py", line 73, in mergeObjects
    mergerFunc(self, value, values)
  File "fontTools/varLib/merger.py", line 950, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "fontTools/varLib/merger.py", line 96, in mergeThings
    self.mergeLists(out, lst)
  File "fontTools/varLib/merger.py", line 82, in mergeLists
    self.mergeThings(value, values)
  File "fontTools/varLib/merger.py", line 950, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "fontTools/varLib/merger.py", line 92, in mergeThings
    mergerFunc(self, out, lst)
  File "fontTools/varLib/merger.py", line 755, in merge
    merger.mergeLists(self.SubTable, subtables)
  File "fontTools/varLib/merger.py", line 82, in mergeLists
    self.mergeThings(value, values)
  File "fontTools/varLib/merger.py", line 950, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "fontTools/varLib/merger.py", line 92, in mergeThings
    mergerFunc(self, out, lst)
  File "fontTools/varLib/merger.py", line 623, in merge
    _MarkBasePosFormat1_merge(self, lst, merger)
  File "fontTools/varLib/merger.py", line 611, in _MarkBasePosFormat1_merge
    merger.mergeThings(anchor, allAnchors)
  File "fontTools/varLib/merger.py", line 947, in mergeThings
    model, lst = masterModel.getSubModel(lst)
  File "fontTools/varLib/models.py", line 219, in getSubModel
    subModel = VariationModel(subList(key, self.origLocations), self.axisOrder)
  File "fontTools/varLib/models.py", line 203, in __init__
    keyFunc = self.getMasterLocationsSortKeyFunc(locations, axisOrder=self.axisOrder)
  File "fontTools/varLib/models.py", line 225, in getMasterLocationsSortKeyFunc
    assert {} in locations, "Base master not found."
AssertionError: ('Base master not found.', 'MarkBasePos', '[0]', 'Lookup', '[6]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')
```
[SourceCode_sparse.zip](https://github.com/fonttools/fonttools/files/3267236/SourceCode_sparse.zip)

**Comment by readroberts** [comment]
@miguelsousa The immediate problem is that the model for dealing with sparse fonts requires that that default font have a value for every value for every value in a region fonts. That isn't the case here. For the MarkToBaseFor and MarkToBasePos lookups, the default instance (ExtraLight) has NULL anchors in some BaseRecords, while the Black instance does not.

The reason that the TTF sources can be merged into a VF is that , and the OTF sources cannot, is that the GPOS tables differ. In the TTF sources, there are no NULL anchors. The BaseRecord lists are the same for the TTF and OTF sources, but the latter have many empty anchors.

The merger.py logic can pre-process the source fonts lookups, and fill in the default font values in some cases, but I don't think we should be doing that here. There has been repeated discussion about how using NULL anchors on GPOS formats 4 and 6 should be discouraged. See https://github.com/adobe-type-tools/afdko/issues/87.

**Comment by miguelsousa** [comment]
@readroberts the OTFs and the TTFs are built from the same source files. The former were compiled with makeotf while the latter were made with fontmake. Are you saying that makeotf needs to be changed?

**Comment by readroberts** [comment]
I will next look into why the OTF and TTF are so different. Given the same feature files, the differences should not happen.

**Comment by readroberts** [comment]
@miguelsousa Does look like makeotf has a problem. I am pretty sure that the OTF output is wrong, not just a functional equivalent. This will take at least a couple hours to look into, some of simply to relearn how these structures work. I will post a bug in the afdko. Any case, definitely not a fonttools bug.

**Comment by miguelsousa** [comment]
@readroberts thanks

**Comment by miguelsousa** [comment]
[makeot issue](https://github.com/adobe-type-tools/afdko/issues/811)
