### ISSUE TITLE
More errors in merging OTF sparse masters

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#1651]
Test case attached.

    fonttools varLib SourceCodeVariable-Roman.designspace

```
Merging OpenType Layout tables
Traceback (most recent call last):
  File "fontTools/varLib/cff.py", line 205, in merge_PrivateDicts
    values = [pd.rawDict[key] for pd in pds]
  File "fontTools/varLib/cff.py", line 205, in <listcomp>
    values = [pd.rawDict[key] for pd in pds]
KeyError: 'FamilyBlues'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fonttools", line 10, in <module>
    sys.exit(main())
  File "fontTools/__main__.py", line 29, in main
    runpy.run_module(mod, run_name='__main__')
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "fontTools/varLib/__main__.py", line 7, in <module>
    sys.exit(main())
  File "fontTools/varLib/__init__.py", line 1075, in main
    optimize=options.optimize
  File "fontTools/varLib/__init__.py", line 924, in build
    _add_CFF2(vf, model, master_fonts)
  File "fontTools/varLib/__init__.py", line 767, in _add_CFF2
    merge_region_fonts(varFont, model, ordered_fonts_list, glyphOrder)
  File "fontTools/varLib/cff.py", line 312, in merge_region_fonts
    merge_PrivateDicts(top_dicts, cvData.vsindex_dict, model, fd_map)
  File "fontTools/varLib/cff.py", line 209, in merge_PrivateDicts
    b"Warning: {key} in default font Private dict is "
AttributeError: 'bytes' object has no attribute 'format'
```

[SourceCode_sparse2.zip](https://github.com/fonttools/fonttools/files/3308015/SourceCode_sparse2.zip)

**Comment by miguelsousa** [comment]
@readroberts the source file of the master OTF without `FamilyBlues` [has those values set](https://github.com/adobe-fonts/source-code-pro/blob/master/Roman/Masters/master_1/SourceCode_Regular.ufo/fontinfo.plist#L34-L48); when the font is built the values are rightly left out because they match the `BlueValues`.
So there's no simple workaround to this issue, and I expect other projects to run into the same problem.
