### ISSUE TITLE
fealib/otlib fails on building a VF from a source that has 2 font master and 1 glyph master

### ISSUE THREAD

**Issue by twardoch** [fonttools/fonttools#1663]
when running fontmake with `fontmake -g 13-Aileron-2fm-1gm.glyphs -o variable` or `fontmake -m 13-fontmake-ufo/Aileron.designspace -o variable`, I get a fail, see below. 

Files: [190712-aileron-vffail.zip](https://github.com/fonttools/fonttools/files/3387839/190712-aileron-vffail.zip)

```
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "13-Aileron-2fm-1gm.glyphs" file into <GSFont>
INFO:fontmake.font_project:Building variable font variable_ttf/Aileron-VF.ttf
INFO:ufo2ft:Pre-processing glyphs
INFO:cu2qu.ufo:New spline lengths: 2: 9, 3: 5
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Aileron-Light
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Aileron-Light-{500}
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Aileron-Bold
INFO:ufo2ft:Building OpenType tables for Aileron-Light
Traceback (most recent call last):
  File "/Users/adam/Library/Python/3.7/bin/fontmake", line 10, in <module>
    sys.exit(main())
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontmake/__main__.py", line 391, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontmake/font_project.py", line 764, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontmake/font_project.py", line 914, in run_from_designspace
    **kwargs
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontmake/font_project.py", line 969, in _run_from_designspace_interpolatable
    designspace, output_path=output_path, output_dir=output_dir, **kwargs
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontmake/font_project.py", line 411, in build_variable_font
    inplace=True,
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/ufo2ft/__init__.py", line 542, in compileVariableTTF
    inplace=inplace,
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/ufo2ft/__init__.py", line 388, in compileInterpolatableTTFsFromDS
    for source, ttf in zip(result.sources, ttfs):
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/ufo2ft/__init__.py", line 299, in compileInterpolatableTTFs
    featureCompilerClass=featureCompilerClass,
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/ufo2ft/__init__.py", line 500, in compileFeatures
    return featureCompiler.compile()
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/ufo2ft/featureCompiler.py", line 126, in compile
    self.buildTables()
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/ufo2ft/featureCompiler.py", line 244, in buildTables
    addOpenTypeFeaturesFromString(self.ttFont, self.features, filename=path)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/feaLib/builder.py", line 32, in addOpenTypeFeaturesFromString
    addOpenTypeFeatures(font, featurefile, tables=tables)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/feaLib/builder.py", line 23, in addOpenTypeFeatures
    builder.build(tables=tables)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/feaLib/builder.py", line 133, in build
    table = self.makeTable(tag)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/feaLib/builder.py", line 544, in makeTable
    table.LookupList.Lookup = self.buildLookups_(tag)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/feaLib/builder.py", line 534, in buildLookups_
    return [l.build() for l in lookups]
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/feaLib/builder.py", line 534, in <listcomp>
    return [l.build() for l in lookups]
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/feaLib/builder.py", line 1278, in build
    self.setLookAheadCoverage_(suffix, st)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/feaLib/builder.py", line 1165, in setLookAheadCoverage_
    coverage = otl.buildCoverage(s, self.glyphMap)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/otlLib/builder.py", line 12, in buildCoverage
    self.glyphs = sorted(glyphs, key=glyphMap.__getitem__)
KeyError: 'l'
```

**Comment by twardoch** [comment]
Oh, I see that this is because the feature definitions have glyphs that the font does not include. Closing.
