### ISSUE TITLE
Error on merging font: UPM of a font as both font UPM are different

### ISSUE THREAD

**Issue by ashakoshti1988** [fonttools/fonttools#1665]
**pyftmerge noto-fonts/unhinted/NotoSans-Regular.ttf noto-fonts/unhinted/SourceHanSansKR-Regular.ttf**
WARNING: Dropped cmap subtable from font [1]:	format 14, platformID  0, platEncID  5
WARNING: Dropped cmap subtable from font [1]:	format  6, platformID  1, platEncID  0
WARNING: Dropped cmap subtable from font [1]:	format  6, platformID  1, platEncID  3
Traceback (most recent call last):
  File "/usr/local/bin/pyftmerge", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 1157, in main
    font = merger.merge(args)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 997, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 160, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 1043, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 49, in equal
    assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
AssertionError: Expected all items to be equal: [1000, 2048]

How to make both fonts UPM same?

**Comment by anthrotype** [comment]
fonttools currently doesn't have a ready-made tool to scale a font's UPEM, though it can certainly be used to build such a tool (and probably somebody may have done that already).
To accomplish that, one would have to change head.unitsPerEm to the new desired value while also scaling all the numeric values that are expressed in Font Units throughout all the various font tables by a factor of `new_upem / old_upem`.
It would certainly be nice to have.

**Comment by JeremieHornus** [comment]
I have made such a tool, it does scale all values to a user-defined UPM, including kerning, etc. Where can I propose such a thing ? Should it go to the Snippets directory ?

**Comment by ashakoshti1988** [comment]
yes you can give Pull request pointing to snippets directory and also the links of libs you have used in that.please submit it as soon so i can use it and it can help me too.. :)

**Comment by JeremieHornus** [comment]
No libs used except FontTools itself ;)
you can find it here: 
https://github.com/fonttools/fonttools/blob/scale-font/Snippets/scale-font.py

**Comment by ashakoshti1988** [comment]
thanks a lot, JeremieHornus .. after scaling to fonts i am getting problem of glyph format,
pyftmerge NotoKufiArabic-Regular.ttf NotoSansCJKsc-Regular.ttf 
WARNING: Dropped cmap subtable from font [1]:	format  6, platformID  1, platEncID  0
WARNING: Dropped cmap subtable from font [1]:	format  6, platformID  1, platEncID 25
Traceback (most recent call last):
  File "/usr/local/bin/pyftmerge", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 1157, in main
    font = merger.merge(args)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 997, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 160, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 1043, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/usr/local/lib/python2.7/site-packages/fontTools/merge.py", line 49, in equal
    assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
AssertionError: Expected all items to be equal: [NotImplemented, 'vhea']

do you know anything regarding this?

**Comment by JeremieHornus** [comment]
this is a different issue: that is because there is a 'vhea' table in one font only (missing in the other font) and there is no merge strategy for this.

**Comment by JeremieHornus** [comment]
also please note that NotoSansCJK is packed: it uses all the glyphs slots available for a TTF: 65535 glyphs, so there is no room for adding more glyphs to it. You may need to subset it before…
