### ISSUE TITLE
ufoLib.glifLib [TypeError: Expected a path string or fs object, found tuple]

### ISSUE THREAD

**Issue by typoman** [fonttools/fonttools#1666]
I was saving a normalized ufo using `fontParts.fontshell.font` RFont, where I got the following error:

```Traceback (most recent call last):
  File "user/Desktop/test2.py", line 21, in <module>
    f.save()
  File "user/Github/fontParts/Lib/fontParts/base/font.py", line 203, in save
    formatVersion=formatVersion)
  File "user/Github/fontParts/Lib/fontParts/fontshell/font.py", line 49, in _save
    self.naked().save(path=path, formatVersion=formatVersion)
  File "/usr/local/lib/python3.7/site-packages/defcon/objects/font.py", line 862, in save
    self.layers.save(writer, saveAs=saveAs, progressBar=progressBar)
  File "/usr/local/lib/python3.7/site-packages/defcon/objects/layerSet.py", line 321, in save
    glyphSet = writer.getGlyphSet(layerName=None, defaultLayer=True, validateRead=self.ufoLibReadValidate, validateWrite=self.ufoLibWriteValidate)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ufoLib/__init__.py", line 1383, in getGlyphSet
    return self._getGlyphSetFormatVersion1(validateRead, validateWrite, glyphNameToFileNameFunc=glyphNameToFileNameFunc)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ufoLib/__init__.py", line 1400, in _getGlyphSetFormatVersion1
    validateWrite=validateWrite,
  File "/usr/local/lib/python3.7/site-packages/fontTools/ufoLib/glifLib.py", line 148, in __init__
    % type(path).__name__
TypeError: Expected a path string or fs object, found tuple
```

**Comment by justvanrossum** [comment]
It seems your source UFO is in format 1, and in that code path there's a bug. #1667 should fix this.

**Comment by typoman** [comment]
Thank You just for such a fast response! Exactly! I just saved the UFO in RF3 and it got fixed!
