### ISSUE TITLE
[subset] KeyError in GSUB table with batang.ttc

### ISSUE THREAD

**Issue by john45676** [fonttools/fonttools#1724]
The font is Microsoft Windows embeded font.

C:\Windows\Fonts\Batang

My command code is:
pyftsubset batang.ttc --text-file=XXX.txt --output-file=batang_subset.ttf --drop-tables= --font-number=1

fonttools version is 4.0.1

Here is the message:
`Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\fontTools\ttLib\ttFont.py", lin2, in __getitem__
    return self.tables[tag]
KeyError: 'GSUB'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\user\AppData\Local\Programs\Python\Python36-32\Scripts\pyftsubset.exe\__main__.py", line 9, in <le>
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\fontTools\misc\loggingTools.py"ne 374, in wrapper
    return func(*args, **kwds)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\fontTools\subset\__init__.py",  2883, in main
    subsetter.subset(font)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\fontTools\subset\__init__.py",  2684, in subset
    self._prune_pre_subset(font)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\fontTools\subset\__init__.py",  2476, in _prune_pre_subset
    table = font[tag]
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\fontTools\ttLib\ttFont.py", lin1, in __getitem__
    table.decompile(data, self)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\fontTools\ttLib\tables\otBase.pline 41, in decompile
    self.table.decompile(reader, font)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\fontTools\ttLib\tables\otBase.pline 631, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\fontTools\ttLib\tables\otConver.py", line 330, in read
    assert (value >> 16) == 1, "Unsupported version 0x%08x" % value
AssertionError: ('Unsupported version 0x00001000', 'Version')`

Thanks.

**Comment by behdad** [comment]
Looks like the GSUB table has a wrong version number. Instead of correct `0x00010000`, it has `0x00001000`. Typically we don't do anything with such bad fonts.
