### ISSUE TITLE
ImportError: cannot import name redirect_stderr

### ISSUE THREAD

**Issue by vbarbarosh** [fonttools/fonttools#1730]
Hello,

From some time `pyftsubset` stopped working on my vps. Even the following command throws an error:

    pyftsubset --help
    Traceback (most recent call last):
      File "/usr/local/bin/pyftsubset", line 7, in <module>
        from fontTools.subset import main
      File "/usr/local/lib/python2.7/dist-packages/fontTools/__init__.py", line 1, in <module>
        from fontTools.misc.py23 import *
      File "/usr/local/lib/python2.7/dist-packages/fontTools/misc/__init__.py", line 3, in <module>
        from fontTools.misc.py23 import *
      File "/usr/local/lib/python2.7/dist-packages/fontTools/misc/py23.py", line 6, in <module>
        from contextlib import redirect_stderr, redirect_stdout
    ImportError: cannot import name redirect_stderr

How can I fix this?

**Comment by justvanrossum** [comment]
The version of fonttools you're using no longer supports Python 2.7. Either upgrade to Python 3.6 or higher, or downgrade fonttools to version 3.44.0.
