### ISSUE TITLE
Unneccessary (?) & failing GSUB merging in  _merge_OTL(vf, model, master_fonts, axisTags) 

### ISSUE THREAD

**Issue by twardoch** [fonttools/fonttools#1734]
Here’s a test font: [lato-mini.zip](https://github.com/fonttools/fonttools/files/3664902/lato-mini.zip)

The .designspace has 2 axes (wght and ASCN = ascender). There are 2 full master fonts (-Hairline and -Black), with 6 glyphs each (`a`, `b`, `f`, `i`, `fi`, plus .notdef), and one **sparse master** with only 3 glyphs (`.notdef`, `b`, `f`). That sparse master is the extreme master in the ASCN axis and has a `/f/b` kerning pair. 

The full masters have the `liga` feature for the `f i > fi` substitutions. The sparse master does not have such feature. The master fonts are provided as UFO (for fontmake) but also as TTFs (because I built them using another tool). 

When I build the TTF VF with fontmake, it works. But building directly with varLib via included `buildvfttf.py` that uses the .designspace and the TTFs directly

```python
import os, os.path, sys
import logging
from fontTools import varLib, designspaceLib
logging.basicConfig(level=logging.INFO)
def build_variable_font(designspace_path):
    basedir = os.path.dirname(designspace_path)
    outfile = os.path.splitext(designspace_path)[0] + '-VF.ttf'
    ds = designspaceLib.DesignSpaceDocument()
    ds.read(designspace_path)
    ufo_paths = [os.path.join(basedir, m.filename) for m in ds.sources]
    ufodir = os.path.dirname(ufo_paths[0])
    ttfdir = os.path.join(basedir, 'master_ttf_interpolatable_flvi')
    finder = lambda s: s.replace(ufodir, ttfdir).replace('.ufo', '.ttf')
    font, model, master_ttfs = varLib.build(designspace_path, finder)
    font.save(outfile)
designspace_path = sys.argv[1]
build_variable_font(designspace_path)
```

fails with the report below. 

It seems that varLib tries to merge both GSUB and GPOS. Merging GPOS is reasonable. But merging GSUB is potentially futile with a sparse master workflow. 

When I remove the GSUB table from both -Bold and -Tall, and only leave it in -Hairline (which is the main master), then it also works. 

But I’m wondering if we think merging GSUB for variable purposes es ever a good idea, or if _merge_OTL shouldn’t be just merging GPOS but only use GSUB from the "main" master?

A.

```
INFO:fontTools.varLib:Axes:
[{'default': 100.0,
  'hidden': False,
  'labelNames': {'en': 'Weight'},
  'map': [(100.0, 0.0),
          (200.0, 100.0),
          (300.0, 250.0),
          (400.0, 540.0),
          (500.0, 600.0),
          (600.0, 666.0),
          (700.0, 780.0),
          (800.0, 880.0),
          (900.0, 1000.0)],
  'maximum': 900.0,
  'minimum': 100.0,
  'name': 'weight',
  'tag': 'wght'},
 {'default': 720.0,
  'hidden': False,
  'labelNames': {'en': 'Ascender'},
  'map': [],
  'maximum': 820.0,
  'minimum': 720.0,
  'name': 'ascender',
  'tag': 'ASCN'}]
INFO:fontTools.varLib:Internal master locations:
[{'ascender': 720.0, 'weight': 1000.0},
 {'ascender': 720.0, 'weight': 0.0},
 {'ascender': 820.0, 'weight': 0.0}]
INFO:fontTools.varLib:Internal axis supports:
{'ascender': [720.0, 720.0, 820.0], 'weight': [0.0, 0.0, 1000.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'ascender': 0.0, 'weight': 1.0},
 {'ascender': 0.0, 'weight': 0.0},
 {'ascender': 1.0, 'weight': 0.0}]
INFO:fontTools.varLib:Index of base master: 1
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading master fonts
INFO:fontTools.varLib:Generating fvar
INFO:fontTools.varLib:Generating avar
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating MVAR
INFO:fontTools.varLib:	cpht: OS/2.sCapHeight	[1457, 1400, 1400]
INFO:fontTools.varLib:	xhgt: OS/2.sxHeight	[1037, 980, 980]
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
Traceback (most recent call last):
  File "./buildflvivf.command", line 21, in <module>
    build_variable_font(designspace_path)
  File "./buildflvivf.command", line 18, in build_variable_font
    font, model, master_ttfs = varLib.build(designspace_path, finder)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/__init__.py", line 862, in build
    _merge_OTL(vf, model, master_fonts, axisTags)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/__init__.py", line 589, in _merge_OTL
    merger.mergeTables(font, master_fonts, ['GSUB', 'GDEF', 'GPOS'])
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/merger.py", line 109, in mergeTables
    for m in master_ttfs])
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/merger.py", line 74, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/merger.py", line 74, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/merger.py", line 74, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/merger.py", line 999, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/merger.py", line 99, in mergeThings
    assert allEqualTo(out, lst), (out, lst)
AssertionError: ((2, [2, 2, 0]), 'int', '.FeatureCount', 'FeatureList', '.FeatureList', 'GSUB', '.table', 'table_G_S_U_B_')

```

**Comment by behdad** [comment]
It's okay if some of the fonts don't have a GSUB.  But if they *do* have, they should be mergeable.  Currently, that simply means they should be identical...  One day we might make it generate feature variations automagically.
