### ISSUE TITLE
INFO:fontTools.varLib:Generating GSUB FeatureVariations ... KeyError: ('gmacron', 'SingleSubst[0]', 'Lookup[31]', 'LookupList')

### ISSUE THREAD

**Issue by twardoch** [fonttools/fonttools#1748]
I cannot figure this one out. Trying to build a VF. I have a bunch of TTFs and a designspace that includes some rules. If I don’t use any rules, the VF builds fine. If I use only some rules (e.g. for `a` or `aacute`), it builds fine. But when I include rules for glyphs like `gmacron`, I get very weird reports. 

1. Unpack [rvrn-fail-191017-VF.zip](https://github.com/fonttools/fonttools/files/3741100/rvrn-fail-191017-VF.zip)

2. Run 

```bash
./buildflvivf.command rvrn-fail-191017-rules.designspace 2> output.txt
```

3. Observe: 

```
INFO:fontTools.varLib:Axes:
[{'default': 10.0,
  'hidden': False,
  'labelNames': {'en': u'Weight'},
  'map': [(10.0, 4.0), (300.0, 300.0)],
  'maximum': 300.0,
  'minimum': 10.0,
  'name': 'weight',
  'tag': 'wght'},
 {'default': 100.0,
  'hidden': False,
  'labelNames': {'en': u'Width'},
  'map': [],
  'maximum': 100.0,
  'minimum': 0.0,
  'name': 'width',
  'tag': 'wdth'},
 {'default': 8.0,
  'hidden': False,
  'labelNames': {'en': u'Optical Size'},
  'map': [],
  'maximum': 144.0,
  'minimum': 8.0,
  'name': 'optical size',
  'tag': 'opsz'},
 {'default': 0.0,
  'hidden': False,
  'labelNames': {'en': u'Slant'},
  'map': [],
  'maximum': 8.0,
  'minimum': 0.0,
  'name': 'slant',
  'tag': 'slnt'}]
INFO:fontTools.varLib:Internal master locations:
[{'optical size': 144.0, 'slant': 0.0, 'weight': 150.0, 'width': 0.0},
 {'optical size': 144.0, 'slant': 8.0, 'weight': 150.0, 'width': 0.0},
 {'optical size': 8.0, 'slant': 0.0, 'weight': 150.0, 'width': 0.0},
 {'optical size': 8.0, 'slant': 8.0, 'weight': 150.0, 'width': 0.0},
 {'optical size': 144.0, 'slant': 0.0, 'weight': 150.0, 'width': 100.0},
 {'optical size': 144.0, 'slant': 8.0, 'weight': 150.0, 'width': 100.0},
 {'optical size': 8.0, 'slant': 0.0, 'weight': 150.0, 'width': 100.0},
 {'optical size': 8.0, 'slant': 8.0, 'weight': 150.0, 'width': 100.0},
 {'optical size': 144.0, 'slant': 0.0, 'weight': 300.0, 'width': 0.0},
 {'optical size': 144.0, 'slant': 8.0, 'weight': 300.0, 'width': 0.0},
 {'optical size': 8.0, 'slant': 8.0, 'weight': 300.0, 'width': 0.0},
 {'optical size': 8.0, 'slant': 0.0, 'weight': 300.0, 'width': 0.0},
 {'optical size': 144.0, 'slant': 0.0, 'weight': 300.0, 'width': 100.0},
 {'optical size': 144.0, 'slant': 8.0, 'weight': 300.0, 'width': 100.0},
 {'optical size': 8.0, 'slant': 8.0, 'weight': 300.0, 'width': 100.0},
 {'optical size': 8.0, 'slant': 0.0, 'weight': 300.0, 'width': 100.0},
 {'optical size': 144.0, 'slant': 0.0, 'weight': 4.0, 'width': 0.0},
 {'optical size': 144.0, 'slant': 8.0, 'weight': 4.0, 'width': 0.0},
 {'optical size': 8.0, 'slant': 8.0, 'weight': 4.0, 'width': 0.0},
 {'optical size': 8.0, 'slant': 0.0, 'weight': 4.0, 'width': 0.0},
 {'optical size': 144.0, 'slant': 0.0, 'weight': 4.0, 'width': 100.0},
 {'optical size': 144.0, 'slant': 8.0, 'weight': 4.0, 'width': 100.0},
 {'optical size': 8.0, 'slant': 8.0, 'weight': 4.0, 'width': 100.0},
 {'optical size': 8.0, 'slant': 0.0, 'weight': 4.0, 'width': 100.0}]
INFO:fontTools.varLib:Internal axis supports:
{'optical size': [8.0, 8.0, 144.0],
 'slant': [0.0, 0.0, 8.0],
 'weight': [4.0, 4.0, 300.0],
 'width': [0.0, 100.0, 100.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'optical size': 1.0,
  'slant': 0.0,
  'weight': 0.49324324324324326,
  'width': -1.0},
 {'optical size': 1.0,
  'slant': 1.0,
  'weight': 0.49324324324324326,
  'width': -1.0},
 {'optical size': 0.0,
  'slant': 0.0,
  'weight': 0.49324324324324326,
  'width': -1.0},
 {'optical size': 0.0,
  'slant': 1.0,
  'weight': 0.49324324324324326,
  'width': -1.0},
 {'optical size': 1.0,
  'slant': 0.0,
  'weight': 0.49324324324324326,
  'width': 0.0},
 {'optical size': 1.0,
  'slant': 1.0,
  'weight': 0.49324324324324326,
  'width': 0.0},
 {'optical size': 0.0,
  'slant': 0.0,
  'weight': 0.49324324324324326,
  'width': 0.0},
 {'optical size': 0.0,
  'slant': 1.0,
  'weight': 0.49324324324324326,
  'width': 0.0},
 {'optical size': 1.0, 'slant': 0.0, 'weight': 1.0, 'width': -1.0},
 {'optical size': 1.0, 'slant': 1.0, 'weight': 1.0, 'width': -1.0},
 {'optical size': 0.0, 'slant': 1.0, 'weight': 1.0, 'width': -1.0},
 {'optical size': 0.0, 'slant': 0.0, 'weight': 1.0, 'width': -1.0},
 {'optical size': 1.0, 'slant': 0.0, 'weight': 1.0, 'width': 0.0},
 {'optical size': 1.0, 'slant': 1.0, 'weight': 1.0, 'width': 0.0},
 {'optical size': 0.0, 'slant': 1.0, 'weight': 1.0, 'width': 0.0},
 {'optical size': 0.0, 'slant': 0.0, 'weight': 1.0, 'width': 0.0},
 {'optical size': 1.0, 'slant': 0.0, 'weight': 0.0, 'width': -1.0},
 {'optical size': 1.0, 'slant': 1.0, 'weight': 0.0, 'width': -1.0},
 {'optical size': 0.0, 'slant': 1.0, 'weight': 0.0, 'width': -1.0},
 {'optical size': 0.0, 'slant': 0.0, 'weight': 0.0, 'width': -1.0},
 {'optical size': 1.0, 'slant': 0.0, 'weight': 0.0, 'width': 0.0},
 {'optical size': 1.0, 'slant': 1.0, 'weight': 0.0, 'width': 0.0},
 {'optical size': 0.0, 'slant': 1.0, 'weight': 0.0, 'width': 0.0},
 {'optical size': 0.0, 'slant': 0.0, 'weight': 0.0, 'width': 0.0}]
INFO:fontTools.varLib:Index of base master: 23
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading master fonts
INFO:fontTools.varLib:Generating fvar
INFO:fontTools.varLib:Generating avar
INFO:fontTools.varLib:No need for avar
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating MVAR
INFO:fontTools.varLib:	hcof: hhea.caretOffset	[0, 0, 0, 0, 0, 0, 0, 0, 0, -38, -38, 0, 0, -38, -38, 0, 0, -38, -38, 0, 0, -38, -38, 0]
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
INFO:fontTools.varLib:Generating gvar
INFO:fontTools.varLib:Merging TT hinting
INFO:fontTools.varLib:Generating GSUB FeatureVariations
INFO:fontTools.varLib:Setting OS/2.usWidthClass = 10
Traceback (most recent call last):
  File "./buildflvivf.command", line 26, in <module>
    build_variable_font(designspace_path)
  File "./buildflvivf.command", line 20, in build_variable_font
    font.save(outfile)
  File "fontTools/ttLib/ttFont.py", line 173, in save
    writer_reordersTables = self._save(tmp)
  File "fontTools/ttLib/ttFont.py", line 212, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "fontTools/ttLib/ttFont.py", line 633, in _writeTable
    tabledata = self.getTableData(tag)
  File "fontTools/ttLib/ttFont.py", line 651, in getTableData
    return self.tables[tag].compile(self)
  File "fontTools/ttLib/tables/otBase.py", line 70, in compile
    self.table.compile(writer, font)
  File "fontTools/ttLib/tables/otBase.py", line 710, in compile
    conv.write(writer, font, table, value)
  File "fontTools/ttLib/tables/otConverters.py", line 520, in write
    value.compile(subWriter, font)
  File "fontTools/ttLib/tables/otBase.py", line 681, in compile
    conv.write(writer, font, table, value, i)
  File "fontTools/ttLib/tables/otConverters.py", line 520, in write
    value.compile(subWriter, font)
  File "fontTools/ttLib/tables/otBase.py", line 681, in compile
    conv.write(writer, font, table, value, i)
  File "fontTools/ttLib/tables/otConverters.py", line 520, in write
    value.compile(subWriter, font)
  File "fontTools/ttLib/tables/otBase.py", line 650, in compile
    table = self.preWrite(font)
  File "fontTools/ttLib/tables/otTables.py", line 723, in preWrite
    gidItems = [(getGlyphID(a), getGlyphID(b)) for a,b in items]
  File "fontTools/ttLib/ttFont.py", line 602, in getGlyphID
    glyphID = d[glyphName]
KeyError: ('gmacron', 'SingleSubst[0]', 'Lookup[31]', 'LookupList')

```

**Comment by justvanrossum** [comment]
I see a rule `<sub name="gcommaaccent" with="gcommaaccent.ss01"/>` but in the fonts only `gcommaaccent.ss01` exists, and not `gcommaaccent`. Since `uni0123` does exist I think something like "production names" was applied too early.

**Comment by anthrotype** [comment]
yes, like Just said. The glyph names in the `<rules>` have to match the glyph names in the master interpolatable TTFs that are used as sources for varLib. In fontmake we do the renaming after we built the VF so that the designspace can contain human-readable glyph names in the rules.
If you rename the glyphs before building the VF, then you have to provide uniXXXX glyph names for the rules.

**Comment by twardoch** [comment]
oh yes of course, stupid me
