### ISSUE TITLE
fontTools fails on python3.6 due to lack of ast.literal_eval function

### ISSUE THREAD

**Issue by sophiawisdom** [fonttools/fonttools#1783]
In `texttools.py`, there is a reference to ast.literal_eval, which doesn't exist in python3.6. In the readme for the project, it mentions support for python3.6 or later. My guess is that ast.literal_eval is required and that the readme should be updated to python3.7 or later.

**Comment by justvanrossum** [comment]
Hm:
```python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> ast.literal_eval
<function literal_eval at 0x10655d400>
>>> import fontTools.misc.textTools
>>> 
```

**Comment by justvanrossum** [comment]
Very odd, which Python 3.6.x are you using?

**Comment by justvanrossum** [comment]
Ah, this is a possible scenario: perhaps you have another module installed called `ast` that shadows the builtin one. That can lead to the error you describe:
```
$ touch ast.py
$ python3.6
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fontTools.misc.textTools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/just/code/git/fontTools/Lib/fontTools/misc/textTools.py", line 10, in <module>
    safeEval = ast.literal_eval
AttributeError: module 'ast' has no attribute 'literal_eval'
>>> 
```

**Comment by sophiawisdom** [comment]
Oh that's true I was wrong sorry yeah I have something else called ast.py sorry for this thanks for the help!
