### ISSUE TITLE
varLib: UnboundLocalError: local variable 'model' referenced before assignment

### ISSUE THREAD

**Issue by twardoch** [fonttools/fonttools#1787]
When exporting a DesignSpace + 1 OTF into a VF OTF, I get a `UnboundLocalError: local variable 'model' referenced before assignment` error. It’s not a good use scenario, but still, a corresponding TTF-based VF exports. 

### Files

[fsType02.~VF.zip](https://github.com/fonttools/fonttools/files/3976986/fsType02.VF.zip)

### Error log

```
INFO:fontTools.varLib:Axes:
[{'default': 400.0,
  'hidden': False,
  'labelNames': {'en': 'Weight'},
  'map': [(1.0, 1.0), (400.0, 400.0), (1000.0, 1000.0)],
  'maximum': 1000.0,
  'minimum': 1.0,
  'name': 'weight',
  'tag': 'wght'}]
INFO:fontTools.varLib:Internal master locations:
[{'weight': 400.0}]
INFO:fontTools.varLib:Internal axis supports:
{'weight': [1.0, 400.0, 1000.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'weight': 0.0}]
INFO:fontTools.varLib:Index of base master: 0
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading master fonts
INFO:fontTools.varLib:Generating fvar
INFO:fontTools.varLib:Generating avar
INFO:fontTools.varLib:No need for avar
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating MVAR
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
Traceback (most recent call last):
  File "/Users/adam/bin/buildflvivf.command", line 30, in <module>
    build_variable_font(designspace_path)
  File "/Users/adam/bin/buildflvivf.command", line 23, in build_variable_font
    font, model, master_ttfs = varLib.build(designspace_path, finder)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/__init__.py", line 888, in build
    _add_CFF2(vf, model, master_fonts)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/__init__.py", line 691, in _add_CFF2
    merge_region_fonts(varFont, model, ordered_fonts_list, glyphOrder)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/cff.py", line 320, in merge_region_fonts
    cvData = merge_charstrings(glyphOrder, num_masters, top_dicts, model)
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/fontTools/varLib/cff.py", line 409, in merge_charstrings
    _add_new_vsindex(model, key, masterSupports, vsindex_dict,
UnboundLocalError: local variable 'model' referenced before assignment
```

### My code

```python
#!/usr/bin/env python3
#-*- coding: utf-8 -*-

from __future__ import unicode_literals, print_function
import os, os.path, sys
import logging
from fontTools import varLib, designspaceLib
logging.basicConfig(level=logging.INFO)
def build_variable_font(designspace_path):
    basedir = os.path.dirname(designspace_path)
    ds = designspaceLib.DesignSpaceDocument()
    ds.read(designspace_path)
    #print(help(ds))
    ufo_paths = [os.path.join(basedir, m.filename) for m in ds.sources]
    ufodir = os.path.dirname(ufo_paths[0])
    vfdir = os.path.join(basedir, 'master_ttf_interpolatable')
    vfext = 'ttf'
    if not os.path.exists(vfdir):
        vfdir = os.path.join(basedir, 'master_otf_interpolatable')
        vfext = 'otf'
    vfpath = os.path.splitext(designspace_path)[0] + '-VF.' + vfext
    finder = lambda s: s.replace(ufodir, vfdir).replace('.ufo', '.' + vfext)
    font, model, master_ttfs = varLib.build(designspace_path, finder)
    font.save(vfpath)

if len(sys.argv) > 1:
    designspace_path = sys.argv[1]
else: 
    designspace_path = raw_input("Please enter the path to the .designspace file or drag-drop it from Finder and press Enter:").lstrip().rstrip().replace("\\ ", " ").replace("\\~", "~")
build_variable_font(designspace_path)
```

**Comment by behdad** [comment]
This should fix it I believe:
```
diff --git a/Lib/fontTools/varLib/cff.py b/Lib/fontTools/varLib/cff.py
index 4e2672b3..0a6ba220 100644
--- a/Lib/fontTools/varLib/cff.py
+++ b/Lib/fontTools/varLib/cff.py
@@ -413,7 +413,7 @@ def merge_charstrings(glyphOrder, num_masters, top_dicts, masterModel):
        # in the PrivatDict, so we will build the default data for vsindex = 0.
        if not vsindex_dict:
                key = (True,) * num_masters
-               _add_new_vsindex(model, key, masterSupports, vsindex_dict,
+               _add_new_vsindex(masterModel, key, masterSupports, vsindex_dict,
                        vsindex_by_key, varDataList)
        cvData = CVarData(varDataList=varDataList, masterSupports=masterSupports,
                                                vsindex_dict=vsindex_dict)
```

**Comment by anthrotype** [comment]
ouch -- thanks for reminding me of this, how come have I missed this for so long
