### ISSUE TITLE
Patching a STAT table - otBase.py - KeyError: 'AxisIndex'

### ISSUE THREAD

**Issue by kosbarts** [fonttools/fonttools#1803]
I am working on a [variable font](https://github.com/kosbarts/Commissioner) with 2 unregistered axes. 
My build is trying to patch the name and STAT tables but I get the following message:

`Parsing 'STAT' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/Users/Kostas/Documents/github-repos/Google/Commissioner/venv/lib/python3.6/site-packages/fontTools/ttx.py", line 400, in main
    process(jobs, options)
  File "/Users/Kostas/Documents/github-repos/Google/Commissioner/venv/lib/python3.6/site-packages/fontTools/ttx.py", line 374, in process
    action(input, output, options)
  File "/Users/Kostas/Documents/github-repos/Google/Commissioner/venv/lib/python3.6/site-packages/fontTools/misc/loggingTools.py", line 367, in wrapper
    return func(*args, **kwds)
  File "/Users/Kostas/Documents/github-repos/Google/Commissioner/venv/lib/python3.6/site-packages/fontTools/ttx.py", line 285, in ttCompile
    ttf.importXML(input)
  File "/Users/Kostas/Documents/github-repos/Google/Commissioner/venv/lib/python3.6/site-packages/fontTools/ttLib/ttFont.py", line 335, in importXML
    reader.read()
  File "/Users/Kostas/Documents/github-repos/Google/Commissioner/venv/lib/python3.6/site-packages/fontTools/misc/xmlReader.py", line 48, in read
    self._parseFile(self.file)
  File "/Users/Kostas/Documents/github-repos/Google/Commissioner/venv/lib/python3.6/site-packages/fontTools/misc/xmlReader.py", line 73, in _parseFile
    parser.Parse(chunk, 0)
  File "/Users/sysadmin/build/v3.6.6/Modules/pyexpat.c", line 468, in EndElement
  File "/Users/Kostas/Documents/github-repos/Google/Commissioner/venv/lib/python3.6/site-packages/fontTools/misc/xmlReader.py", line 155, in _endElementHandler
    self.currentTable.fromXML(name, attrs, content, self.ttFont)
  File "/Users/Kostas/Documents/github-repos/Google/Commissioner/venv/lib/python3.6/site-packages/fontTools/ttLib/tables/otBase.py", line 105, in fromXML
    self.table.fromXML(name, attrs, content, font)
  File "/Users/Kostas/Documents/github-repos/Google/Commissioner/venv/lib/python3.6/site-packages/fontTools/ttLib/tables/otBase.py", line 767, in fromXML
    value = conv.xmlRead(attrs, content, font)
  File "/Users/Kostas/Documents/github-repos/Google/Commissioner/venv/lib/python3.6/site-packages/fontTools/ttLib/tables/otConverters.py", line 448, in xmlRead
    table.fromXML(name, attrs, content, font)
  File "/Users/Kostas/Documents/github-repos/Google/Commissioner/venv/lib/python3.6/site-packages/fontTools/ttLib/tables/otBase.py", line 767, in fromXML
    value = conv.xmlRead(attrs, content, font)
  File "/Users/Kostas/Documents/github-repos/Google/Commissioner/venv/lib/python3.6/site-packages/fontTools/ttLib/tables/otConverters.py", line 448, in xmlRead
    table.fromXML(name, attrs, content, font)
  File "/Users/Kostas/Documents/github-repos/Google/Commissioner/venv/lib/python3.6/site-packages/fontTools/ttLib/tables/otBase.py", line 764, in fromXML
    conv = self.getConverterByName(name)
  File "/Users/Kostas/Documents/github-repos/Google/Commissioner/venv/lib/python3.6/site-packages/fontTools/ttLib/tables/otBase.py", line 804, in getConverterByName
    return self.convertersByName[self.Format][name]
KeyError: 'AxisIndex'`

What is the problem?

Also, I am using Axis value table, format 4 and from what I read in https://github.com/daltonmaag/statmake : 
"ATTENTION: Using format 4 axis values bumps the STAT table version from 1.1 to 1.2. At the time of this writing (February 2019), version 1.2 is not supported by Windows."
What is the case with that?

**Comment by justvanrossum** [comment]
AxisValue format 4 does not have an AxisIndex attribute, so your ttx at https://github.com/kosbarts/Commissioner/blob/master/sources/vf-patch.ttx can't be valid.

(I know nothing about STAT, so someone else will have to chime in how to fix this.)

**Comment by kosbarts** [comment]
Sorry, the previous version was indeed incorrect. I had a problem figuring out the correct way to write the array of axis. I updated it and it currently works fine.
