### ISSUE TITLE
pip install -r requirements.txt - FAIL - Windows 10 - "PyPy"' don't match your environment etc.

### ISSUE THREAD

**Issue by peterennis** [fonttools/fonttools#1807]
@chrissimpkins 

`"PyPy"' don't match your environment` etc.

Is this expecting to build on Linux?
WSL needed?

Seems like a lot of things are missing.

```
(venv) C:\ae\adaept.com\ae-pyfont\fonttools>pip install -r requirements.txt
Ignoring brotlipy: markers 'platform_python_implementation == "PyPy"' don't match your environment
Ignoring unicodedata2: markers 'python_version < "3.8" and platform_python_implementation != "PyPy"' don't match your environment
Ignoring munkres: markers 'platform_python_implementation == "PyPy"' don't match your environment
Collecting brotli==1.0.7
  Downloading Brotli-1.0.7-cp38-cp38-win32.whl (339 kB)
     |████████████████████████████████| 339 kB 595 kB/s
Collecting scipy==1.3.1
  Downloading scipy-1.3.1.tar.gz (23.6 MB)
     |████████████████████████████████| 23.6 MB 223 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\ae\adaept.com\ae-pyfont\fonttools\venv\scripts\python.exe' 'c:\ae\adaept.com\ae-pyfont\fonttools\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\peter\AppData\Local\Temp\tmpcw3b6p7j'
         cwd: C:\Users\peter\AppData\Local\Temp\pip-install-c2ncgsib\scipy
    Complete output (168 lines):
    lapack_opt_info:
    lapack_mkl_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_rt not found in ['c:\\ae\\adaept.com\\ae-pyfont\\fonttools\\venv\\lib', 'C:\\']
      NOT AVAILABLE

    openblas_lapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries openblas not found in ['c:\\ae\\adaept.com\\ae-pyfont\\fonttools\\venv\\lib', 'C:\\']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
      NOT AVAILABLE

    openblas_clapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries openblas,lapack not found in ['c:\\ae\\adaept.com\\ae-pyfont\\fonttools\\venv\\lib', 'C:\\']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in c:\ae\adaept.com\ae-pyfont\fonttools\venv\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\ae\adaept.com\ae-pyfont\fonttools\venv\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in c:\ae\adaept.com\ae-pyfont\fonttools\venv\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\ae\adaept.com\ae-pyfont\fonttools\venv\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in c:\ae\adaept.com\ae-pyfont\fonttools\venv\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\ae\adaept.com\ae-pyfont\fonttools\venv\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in c:\ae\adaept.com\ae-pyfont\fonttools\venv\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\ae\adaept.com\ae-pyfont\fonttools\venv\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack not found in ['c:\\ae\\adaept.com\\ae-pyfont\\fonttools\\venv\\lib', 'C:\\']
      NOT AVAILABLE

    lapack_src_info:
      NOT AVAILABLE

      NOT AVAILABLE

    setup.py:386: UserWarning: Unrecognized setuptools command ('dist_info --egg-base C:\Users\peter\AppData\Local\Temp\pip-modern-metadata-hl__okjz'), proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
    Running from scipy source directory.
    C:\Users\peter\AppData\Local\Temp\pip-build-env-nr41tjk6\overlay\Lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    C:\Users\peter\AppData\Local\Temp\pip-build-env-nr41tjk6\overlay\Lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    C:\Users\peter\AppData\Local\Temp\pip-build-env-nr41tjk6\overlay\Lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
    Traceback (most recent call last):
      File "c:\ae\adaept.com\ae-pyfont\fonttools\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 257, in <module>
        main()
      File "c:\ae\adaept.com\ae-pyfont\fonttools\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "c:\ae\adaept.com\ae-pyfont\fonttools\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\peter\AppData\Local\Temp\pip-build-env-nr41tjk6\overlay\Lib\site-packages\setuptools\build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\peter\AppData\Local\Temp\pip-build-env-nr41tjk6\overlay\Lib\site-packages\setuptools\build_meta.py", line 242, in run_setup
        super(_BuildMetaLegacyBackend,
      File "C:\Users\peter\AppData\Local\Temp\pip-build-env-nr41tjk6\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 505, in <module>
        setup_package()
      File "setup.py", line 501, in setup_package
        setup(**metadata)
      File "C:\Users\peter\AppData\Local\Temp\pip-build-env-nr41tjk6\overlay\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "setup.py", line 403, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\ae\adaept.com\ae-pyfont\fonttools\venv\scripts\python.exe' 'c:\ae\adaept.com\ae-pyfont\fonttools\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\peter\AppData\Local\Temp\tmpcw3b6p7j' Check the logs for full command output.

(venv) C:\ae\adaept.com\ae-pyfont\fonttools>
```

**Comment by chrissimpkins** [comment]
I believe that the recommended approaches are the following if you want to git clone and install from local sources in a venv:

```
$ pip install ".[ufo,lxml,woff,unicode]"
```

or if you intend to edit the sources:

```
$ pip install -e ".[ufo,lxml,woff,unicode]"
```

I don't have any insights into platform-specific build issues, but it may be worth giving one of those two commands a try and see if you run into problems.

**Comment by peterennis** [comment]
```
C:\ae\adaept.com\ae-pyfont>.\Scripts\activate.bat

(ae-pyfont) C:\ae\adaept.com\ae-pyfont>cd fonttools

(ae-pyfont) C:\ae\adaept.com\ae-pyfont\fonttools>pip install ".[ufo,lxml,woff,unicode]"
Processing c:\ae\adaept.com\ae-pyfont\fonttools
Collecting lxml<5,>=4.0
  Downloading lxml-4.4.2-cp38-cp38-win32.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 1.1 MB/s
Collecting fs<3,>=2.2.0
  Using cached fs-2.4.11-py2.py3-none-any.whl (127 kB)
Collecting zopfli>=0.1.4
  Downloading zopfli-0.1.7-cp38-cp38-win32.whl (33 kB)
Collecting brotli>=1.0.1
  Using cached Brotli-1.0.7-cp38-cp38-win32.whl (339 kB)
Requirement already satisfied: setuptools in c:\ae\adaept.com\ae-pyfont\lib\site-packages (from fs<3,>=2.2.0->fonttools==4.2.5.dev0) (41.2.0)
Collecting appdirs~=1.4.3
  Using cached appdirs-1.4.3-py2.py3-none-any.whl (12 kB)
Collecting pytz
  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)
Collecting six~=1.10
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: lxml, appdirs, pytz, six, fs, zopfli, brotli, fonttools
  Attempting uninstall: fonttools
    Found existing installation: fonttools 4.2.4
    Uninstalling fonttools-4.2.4:
      Successfully uninstalled fonttools-4.2.4
    Running setup.py install for fonttools ... done
Successfully installed appdirs-1.4.3 brotli-1.0.7 fonttools-4.2.5.dev0 fs-2.4.11 lxml-4.4.2 pytz-2019.3 six-1.14.0 zopfli-0.1.7

(ae-pyfont) C:\ae\adaept.com\ae-pyfont\fonttools>
```

That looks better. Thanks 👍
