### ISSUE TITLE
Pyftsubset fails on Variable font generated from designspace with <rules>

### ISSUE THREAD

**Issue by kontur** [fonttools/fonttools#1893]
I've been running into this issue with `pyftsubset` in fontTools 4.8.1 when trying to subset a Variable font compiled with a designspace that has `<rules>`:

```
Traceback (most recent call last):
  File "/Users/johannes/.pyenv/versions/3.7.6/bin/pyftsubset", line 8, in <module>
    sys.exit(main())
  File "/Users/johannes/.pyenv/versions/3.7.6/lib/python3.7/site-packages/fontTools/misc/loggingTools.py", line 367, in wrapper
    return func(*args, **kwds)
  File "/Users/johannes/.pyenv/versions/3.7.6/lib/python3.7/site-packages/fontTools/subset/__init__.py", line 2891, in main
    subsetter.subset(font)
  File "/Users/johannes/.pyenv/versions/3.7.6/lib/python3.7/site-packages/fontTools/subset/__init__.py", line 2692, in subset
    self._prune_pre_subset(font)
  File "/Users/johannes/.pyenv/versions/3.7.6/lib/python3.7/site-packages/fontTools/subset/__init__.py", line 2486, in _prune_pre_subset
    retain = table.prune_pre_subset(font, self.options)
  File "/Users/johannes/.pyenv/versions/3.7.6/lib/python3.7/site-packages/fontTools/subset/__init__.py", line 1558, in prune_pre_subset
    self.prune_lookups(remap=False)
  File "/Users/johannes/.pyenv/versions/3.7.6/lib/python3.7/site-packages/fontTools/subset/__init__.py", line 1502, in prune_lookups
    lookup_indices = self.table.LookupList.closure_lookups(lookup_indices)
  File "/Users/johannes/.pyenv/versions/3.7.6/lib/python3.7/site-packages/fontTools/subset/__init__.py", line 1247, in closure_lookups
    for i in recurse if i < self.LookupCount), [])
  File "/Users/johannes/.pyenv/versions/3.7.6/lib/python3.7/site-packages/fontTools/subset/__init__.py", line 1247, in <genexpr>
    for i in recurse if i < self.LookupCount), [])
AttributeError: 'NoneType' object has no attribute 'collect_lookups'
```

The same Variable font seems to run through `pyftsubset` just fine when the designspace to generate it does not include any `<rules>` elements.

```
<?xml version='1.0' encoding='UTF-8'?>
<designspace format="4.1">
  <axes>
    <axis tag="wght" name="Weight" minimum="300" maximum="700" default="300">
      <map input="300" output="50"/>
      <map input="400" output="360"/>
      <map input="600" output="650"/>
      <map input="700" output="920"/>
    </axis>
    <axis tag="NEGA" name="Negative" minimum="-1" maximum="0" default="0"/>
  </axes>

<!-- having these <rules> break the pyftsubset (not the generated VF ;) ) -->
  <rules>
    <rule name="icon-alternates-escalator">
      <conditionset>
        <condition minimum="650" maximum="700" name="Weight" />
        <sub name="ico.escalator" with="ico.escalator.bold" />
      </conditionset>
    </rule>
    <rule name="icon-alternates-disabled">
      <conditionset>
        <condition minimum="450" maximum="700" name="Weight" />
        <sub name="ico.disabled" with="ico.disabled.bold" />
      </conditionset>
    </rule>
  </rules>

  <sources>
...
```

It seems any `pyftsubset` parameters fail with some general problem when recompiling the subset font, e.g. `$ pyftsubset --glyphs=* breaks-Signika-VF.ttf` fails.

The failing VF: https://www.dropbox.com/s/h62m6xoa3av1i73/breaks-Signika-VF.ttf?dl=0
Compiled with this designspace with `<rules>`: https://www.dropbox.com/s/061sec67ukefvor/breaks-Signika.designspace?dl=0

The same VF compiled without the `<rules>`: https://www.dropbox.com/s/19o5tmc14po66wz/works-Signika-VF.ttf?dl=0
From this designspace: https://www.dropbox.com/s/j60faqim6boy8lu/works-Signika.designspace?dl=0

Pretty lost there in the error backtrace — any idea what is causing this or how to debug further? :/

**Comment by justvanrossum** [comment]
Sounds similar to what #1878 fixed.

**Comment by anthrotype** [comment]
I don't think it's related to #1878.

The font "breaks-Signika-VF.ttf" contains an empty lookup (lookup 45 at the end of LookupList):

```
    </LookupList>
      <!-- ... -->
      <Lookup index="45" empty="1"/>
    </LookupList>
```

The culprit seems to be in `featureVars.buildSubstitutionLookups` which doesn't seem to be handling the possibility that the value returned from `otlLib.buildLookup` can be `None` (when all subtables are `None`).

https://github.com/fonttools/fonttools/blob/84df2c4cd16e8c486bfa6dabc8a4fb31fe8a6d82/Lib/fontTools/varLib/featureVars.py#L396-L397

https://github.com/fonttools/fonttools/blob/84df2c4cd16e8c486bfa6dabc8a4fb31fe8a6d82/Lib/fontTools/otlLib/builder.py#L25-L27

I think the fix should be to skip adding such empty Lookups.
I don't think LookupList can contain NULL offsets to Lookup tables.

I haven't investigated why that particular designspace file produces an empty substitution subtables.

/cc @justvanrossum

**Comment by justvanrossum** [comment]
Hm, I can't dive into this too deeply right now, but:

- Indeed, why would there be an empty lookup in the first place: the rules seem super simple, but both got compiled to this empty lookup
- I notice that the rule coordinates are (likely) using userspace coordinates, but they should be designspace (I would expect the maximum value to be 920, not 700). Still, this does not explain the problem
- While the source font is probably not correct, it does seem to be a valid font, and perhaps the subsetter should not choke on that. Still, it may not be worth to fix that, as I agree that an empty lookup should not be emitted

**Comment by anthrotype** [comment]
ots also rejects the font as invalid

```
python -m ots /Users/clupo/Downloads/breaks-Signika-VF.ttf
ERROR: Layout: Bad lookup offset 0 for lookup 45
ERROR: GSUB: Failed to parse lookup list table
ERROR: GSUB: Failed to parse table
Failed to sanitize file!
```

**Comment by justvanrossum** [comment]
Looking at featureVars.py I don't immediately see how it would ever create an empty lookup. @kontur, would it be possible to share the UFO sources? Possibly privately?

(Oooohhhh opentype-sanitizer on PyPI, how'd I miss that! Awesome!)

**Comment by kontur** [comment]
I'm using fontmake on [this glyphs source](https://www.dropbox.com/s/tqon07fcu5omdqv/Signika-MM-prepped_designspace-Build.glyphs?dl=0) to extract these [UFOs and designspace](﻿https://www.dropbox.com/sh/ovtj8dswi37zdi8/AADvKU80G96gaPKXyxDWgvkPa?dl=0) and add [these rules](﻿https://www.dropbox.com/s/0dcdjwy5hdj25fr/designspace-rules.xml?dl=0) to the generated designspace, to compile from [this modified designspace](https://www.dropbox.com/s/hc9g2b931ahxkgz/Signika.designspace?dl=0) with rules.

Not adding the <rules> and the designspace compiles into a variable font fine. Also using fontmake to variablefont (instead of the ufo/ds in-between) the subsetting works on the generated font. It is when the subsetter encounters the font that has had the rules added that it fails.

Indeed the rules’ maximum should be the design space values eventually and are left over like this from testing, but since min and max are within the axis range that should not matter ;)

**Comment by arrowtype** [comment]
For what it's worth, I haven't had any similar issues with submitting Recursive, though it has a ton of rules. Probably, something else must be an issue in the font, and that must be a blocker.

Just as a stab in the dark, I see that one of the rules subs `name="ico.disabled" with="ico.disabled.bold"`. This maaay clash with the custom Parameter in some of the instances:

```xml
<lib>
        <dict>
          <key>com.schriftgestaltung.customParameters</key>
          <array>
            <array>
              <string>Rename Glyphs</string>
              <array>
                <string>ico.disabled=ico.disabled.bold</string>
              </array>
            </array>
          </array>
        </dict>
      </lib>
```

...or may not. But, have you tried building the designspace without those `lib`s?

**Comment by kontur** [comment]
Thanks for the input @arrowtype Tried without those "glyphs" left overs in the designspace and same result.

@anthrotype / @justvanrossum Should this issue be escalated to another project, and if so which? If the generated font without the `<rules>` in the designspace also causes OTS to output a fail to begin with, the problem might be anywhere else on the _glyphs > fontmake to UFO/DS > fontmake DS_ to Variable chain. I also checked, _glyphs > fontmake to Variable_ produces font that **does not** fail OTS. I'm unclear as to what is the difference in fontmake internally when going straight from glyphs to variable font, as opposed to outputting master ufos and a designspace and then compiling the variable font.

**Comment by justvanrossum** [comment]
I haven't yet had time to reproduce, so I have still no idea where this problem is being caused. I'll try to look at it soon.

**Comment by kontur** [comment]
I did more testing today and it seems really _whatever_ `<rules>` added to this designspace will result in a font with an empty lookup.

E.g.:

```
  <rules>
    <rule name="test">
      <conditionset>
        <condition minimum="50" maximum="920" name="Weight" />
        <sub name="A" with="B" />
      </conditionset>
    </rule>
  </rules>
```

Will add this empty Lookup:

```
      <Lookup index="45" empty="1"/>
```

As well as add a correct FeatureVariations entry referencing that lookup. So the question is: Why does adding rules to _this font/designspace_ always result in an empty lookup, no matter what is in the `<rules>`?

Same result for adding e.g. these rules:

```
  <rules>
    <rule name="test">
      <conditionset>
        <condition minimum="-1" maximum="0" name="Negative" />
        <sub name="A" with="B" />
      </conditionset>
    </rule>
  </rules>
```

I have tried to replicate this with a minimal font with only two characters and the same flow and rules, but that compiles just fine.

**Comment by kontur** [comment]
Also removing all other features from the source glyphs/UFO yields the same result with a single empty lookup.

**Comment by justvanrossum** [comment]
Hi,

The problem is that your `<rules>` element is not correct: the `<sub>` elements are _siblings_ of `<conditionset>`, not children. Everything goes well for this fixed version of the rules:

```xml
  <rules>
    <rule name="icon-alternates-escalator">
      <conditionset>
        <condition minimum="650" maximum="700" name="Weight" />
      </conditionset>
      <sub name="ico.escalator" with="ico.escalator.bold" />
    </rule>
    <rule name="icon-alternates-disabled">
      <conditionset>
        <condition minimum="450" maximum="700" name="Weight" />
      </conditionset>
      <sub name="ico.disabled" with="ico.disabled.bold" />
    </rule>
  </rules>
```

Things to fix in fonttools:
- featureVars should either warn or fail if there's nothing to substitute.
- featureVars should _not_ emit an empty lookup if there's nothing to substitute. I've been looking at the code briefly: to skip an empty lookup is not trivial, given how lookup indices are everywhere. It'll definitely be easier to fail than to warn + skip.
- perhaps DesignSpaceDocument should complain about unknown elements, for example `<sub>` as a child of `<conditionset>` is now silently ignored.

**Comment by kontur** [comment]
Well, that is me feeling stupid now 🤦 There should be a term for how the most obscure problems tend to be caused by the most trivial errors.

I suppose the last of your bullet points would be the most trivial to implement and might hopefully save someone else (and you) the time and trouble of such having to deep-dive due to a silly mistake. Feel free to close, unless you want to keep open for reference/reminder.

**Comment by anthrotype** [comment]
maybe we should have an XML schema for designspace document
