### ISSUE TITLE
[subset] AttributeError: 'ContextHelper' object has no attribute 'Coverage'

### ISSUE THREAD

**Issue by jm4R** [fonttools/fonttools#1955]
```
font = ttLib.TTFont(...)
# ...
subsetter = subset.Subsetter()
subsetter.populate(unicodes=target_charset)
subsetter.subset(font)
```

for such code I receive:
```
Traceback (most recent call last):
  File "/some/path/noto_based_on.py", line 291, in <module>
    main()
  File "/some/path/noto_based_on.py", line 277, in main
    subsetter.subset(font)
  File "/home/some_user/.local/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 2699, in subset
    self._closure_glyphs(font)
  File "/home/some_user/.local/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 2553, in _closure_glyphs
    font['GSUB'].closure_glyphs(self)
  File "/home/some_user/.local/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 1440, in closure_glyphs
    self.table.LookupList.Lookup[i].closure_glyphs(s)
  File "/home/some_user/.local/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 1183, in closure_glyphs
    st.closure_glyphs(s, cur_glyphs)
  File "/home/some_user/.local/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 912, in closure_glyphs
    indices = c.Coverage(self).intersect(cur_glyphs)
AttributeError: 'ContextHelper' object has no attribute 'Coverage'
```

**Comment by anthrotype** [comment]
Can you provide a test font? 
I don't immediately see where the issue originates

**Comment by jm4R** [comment]
The `font` is the result of:
```
merger = merge.Merger()
font = merger.merge(some_files)
```

**Comment by anthrotype** [comment]
Hm. I suspect some conflicts between subset and merge modules both dynamically setting methods on the same classes. I'll take a look soon

**Comment by jm4R** [comment]
Thanks! Can you guess a quick workaround?

**Comment by anthrotype** [comment]
You may try splitting the merging and subsetting steps into two different scripts, running one first, saving the result then running the other.

**Comment by behdad** [comment]
> Hm. I suspect some conflicts between subset and merge modules both dynamically setting methods on the same classes. I'll take a look soon

I don't see how that would happen.

**Comment by behdad** [comment]
Oops I do!

**Comment by behdad** [comment]
Fixing.

**Comment by behdad** [comment]
[Couldn't run tests.  Sorry about anything I broke in advance.]

**Comment by anthrotype** [comment]
thanks!
