### ISSUE TITLE
[name] addMultilingualName fails with one-character names

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#1997]
This bug seems to have been introduced between 4.10 and 4.11. @justvanrossum I think you changed something there?

```python
from fontTools.ttLib.tables._n_a_m_e import table__n_a_m_e

t = table__n_a_m_e()

t.addMultilingualName({"en": "A"})
t.addMultilingualName({"en": "B"})
```

Traceback:
```
Traceback (most recent call last):
  File "./test.py", line 8, in <module>
    t.addMultilingualName({"en": "B"})
  File "/Users/kuti/Quellen/fonttools-github/Lib/fontTools/ttLib/tables/_n_a_m_e.py", line 273, in addMultilingualName
    names, windows=windows, mac=mac, minNameID=minNameID)
  File "/Users/kuti/Quellen/fonttools-github/Lib/fontTools/ttLib/tables/_n_a_m_e.py", line 229, in findMultilingualName
    key = (name.toUnicode(), name.platformID,
  File "/Users/kuti/Quellen/fonttools-github/Lib/fontTools/ttLib/tables/_n_a_m_e.py", line 456, in toUnicode
    string = b'\0' + string
TypeError: can't concat str to bytes
```

**Comment by justvanrossum** [comment]
Confirmed. Yes, that indeed seems to be a regression introduced with my changes. Looking into it.

**Comment by justvanrossum** [comment]
Actually, it's not 100% a regression, the following fails in 4.10.0 as well:
```python
from fontTools.ttLib import newTable
t = newTable("name")
nameID = t.addMultilingualName({"en": "A"})
rec = t.getName(nameID, 3, 1)
print(rec.toUnicode())
```

**Comment by jenskutilek** [comment]
Ah yes, I see, it just happened that the new method (findMultiLingualName) triggers the bug.

**Comment by justvanrossum** [comment]
But the "real bug" is in `toUnicode()`.

**Comment by justvanrossum** [comment]
Thanks for reporting! This is a pretty old bug, probably about as old as Python 3 support in fonttools.
