### ISSUE TITLE
pyftsubset throwing AttributeError

### ISSUE THREAD

**Issue by AndrewLeedham** [fonttools/fonttools#2023]
I am using this package as a dependency of https://github.com/filamentgroup/glyphhanger. However, the error occurs when running the command directly as well.

```
Traceback (most recent call last):
  File "/usr/local/bin/pyftsubset", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/fontTools/misc/loggingTools.py", line 373, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/fontTools/subset/__init__.py", line 2901, in main
    subsetter.subset(font)
  File "/usr/local/lib/python3.8/site-packages/fontTools/subset/__init__.py", line 2704, in subset
    self._prune_post_subset(font)
  File "/usr/local/lib/python3.8/site-packages/fontTools/subset/__init__.py", line 2687, in _prune_post_subset
    retain = table.prune_post_subset(font, self.options)
  File "/usr/local/lib/python3.8/site-packages/fontTools/subset/__init__.py", line 1638, in prune_post_subset
    if not (table.FeatureList and table.FeatureVariations.FeatureVariationRecord):
AttributeError: 'NoneType' object has no attribute 'FeatureVariationRecord'
```

The command in question is:
```bash
pyftsubset "./fonts/WorkSans-Regular.ttf" --output-file="fonts/WorkSans-Regular-subset.ttf" --unicodes=U+20,U+27,U+2D,U+41,U+44-46,U+49,U+4C,U+4F,U+53,U+57,U+61-69,U+6B-70,U+72-77 --layout-features='*'
```
The specific font file can be downloaded from https://fonts.google.com/specimen/Work+Sans.

My environment:
- OS: macOS Catalina 10.15.5
- Python version: 3.8.4
- fonttools version: 4.13.0

**Comment by mcguffin** [comment]
Same for me.
Changing `Lib/fontTools/subset/__init__.py:1638`
https://github.com/fonttools/fonttools/blob/26ac716a8d85c832cba2694dda994c03aafe3386/Lib/fontTools/subset/__init__.py#L1638

to 
```python
		if not (table.FeatureList and hasattr(table.FeatureVariations, 'FeatureVariationRecord'):
```
fixed it for me.

**Comment by AndrewLeedham** [comment]
Thanks @mcguffin that fixed it for me as well. Will leave this open until the change is merged 👍

**Comment by anthrotype** [comment]
Thanks for the report, I just fixed it on master, we'll cut a new release soon.
