### ISSUE TITLE
pyftsubset: WARNING: Unknown Coverage format: 0

### ISSUE THREAD

**Issue by vbarbarosh** [fonttools/fonttools#2071]
I got the following errors trying to use pyftsubset:

[font.woff.zip](https://github.com/fonttools/fonttools/files/5293789/font.woff.zip)

```
$ ls font.woff.zip

$ unzip font.woff.zip

$ docker run --rm -v $PWD:/app -i ubuntu:20.04 << 'EOF'
    apt update
    DEBIAN_FRONTEND=noninteractive apt install -y fonttools
    cd /app
    pyftsubset font.woff --text=abc123 --flavor=woff --with-zopfli
EOF

WARNING: FFTM NOT subset; don't know how to subset; dropped
WARNING: Unknown Coverage format: 0
Traceback (most recent call last):
  File "/usr/bin/pyftsubset", line 11, in <module>
    load_entry_point('fonttools==4.5.0', 'console_scripts', 'pyftsubset')()
  File "/usr/lib/python3/dist-packages/fontTools/misc/loggingTools.py", line 367, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 2891, in main
    subsetter.subset(font)
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 2694, in subset
    self._subset_glyphs(font)
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 2631, in _subset_glyphs
    retain = table.subset_glyphs(self)
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 1445, in subset_glyphs
    lookup_indices = self.table.LookupList.subset_glyphs(s)
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 1215, in subset_glyphs
    return [i for i,l in enumerate(self.Lookup) if l and l.subset_glyphs(s)]
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 1215, in <listcomp>
    return [i for i,l in enumerate(self.Lookup) if l and l.subset_glyphs(s)]
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 1187, in subset_glyphs
    self.SubTable = [st for st in self.SubTable if st and st.subset_glyphs(s)]
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 1187, in <listcomp>
    self.SubTable = [st for st in self.SubTable if st and st.subset_glyphs(s)]
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 1138, in subset_glyphs
    return self.ExtSubTable.subset_glyphs(s)
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 564, in subset_glyphs
    p.PairValueRecord = [r for r in p.PairValueRecord if r.SecondGlyph in s.glyphs]
  File "/usr/lib/python3/dist-packages/fontTools/ttLib/tables/otBase.py", line 545, in __getattr__
    self.decompile(reader, font)
  File "/usr/lib/python3/dist-packages/fontTools/ttLib/tables/otBase.py", line 629, in decompile
    table[conv.name] = conv.readArray(reader, font, table, countValue)
  File "/usr/lib/python3/dist-packages/fontTools/ttLib/tables/otConverters.py", line 149, in readArray
    l.append(self.read(reader, font, tableDict))
  File "/usr/lib/python3/dist-packages/fontTools/ttLib/tables/otConverters.py", line 404, in read
    table.decompile(reader, font)
  File "/usr/lib/python3/dist-packages/fontTools/ttLib/tables/otBase.py", line 633, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/usr/lib/python3/dist-packages/fontTools/ttLib/tables/otConverters.py", line 594, in read
    return reader[self.which].readValueRecord(reader, font)
  File "/usr/lib/python3/dist-packages/fontTools/ttLib/tables/otBase.py", line 883, in readValueRecord
    value.decompile(subReader, font)
  File "/usr/lib/python3/dist-packages/fontTools/ttLib/tables/otBase.py", line 633, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/usr/lib/python3/dist-packages/fontTools/ttLib/tables/otConverters.py", line 227, in read
    return reader.readUShort()
  File "/usr/lib/python3/dist-packages/fontTools/ttLib/tables/otBase.py", line 140, in readUShort
    value, = struct.unpack(">H", self.data[pos:newpos])
struct.error: ('unpack requires a buffer of 2 bytes', 'StartSize', 'Value1', 'PairValueRecord')
```

**Comment by behdad** [comment]
Font seems corrupt.
