### ISSUE TITLE
`name` table decoding error

### ISSUE THREAD

**Issue by NightFurySL2001** [fonttools/fonttools#2132]
While using the following code:
```
for record in font['name'].names:
    if record.nameID == 1:
        print(record)
```
It gave an error for some of the Chinese fonts I have:
```
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\fontTools\encodings\codecs.py", line 54, in decode
    assert errors == 'strict'
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\Desktop\coding\fontname\main.py", line 75, in <module>
    print(record)
  File "C:\Python39\lib\site-packages\fontTools\ttLib\tables\_n_a_m_e.py", line 414, in __str__
    return self.toStr(errors='backslashreplace')
  File "C:\Python39\lib\site-packages\fontTools\ttLib\tables\_n_a_m_e.py", line 460, in toUnicode
    string = tounicode(string, encoding=encoding, errors=errors)
  File "C:\Python39\lib\site-packages\fontTools\misc\py23.py", line 82, in tounicode
    return s.decode(encoding, errors)
AssertionError: decoding with 'x_mac_simp_chinese_ttx' codec failed (AssertionError: )
```
It seems to be stuck on this section (based on `ttx`):
```
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x804">
      汉仪彩云体简
    </namerecord>
```

**Comment by justvanrossum** [comment]
Try `print(record.toUnicode())` as a workaround.

**Comment by NightFurySL2001** [comment]
@justvanrossum  Ok that worked out, thanks. Should i close this issue?

**Comment by justvanrossum** [comment]
No, let's keep it open, because `print(record)` should work, it just doesn't with this specific encoding (and possibly a few others).

**Comment by justvanrossum** [comment]
Thanks for reporting!

**Comment by NightFurySL2001** [comment]
Ok, thanks, hope to see it sloved soon.

**Comment by anthrotype** [comment]
I can't reproduce, @NightFurySL2001 could you please upload or send me a font that exhibits this issue?
I'm surprised this happens. Calling print() on a NameRecord should be equivalent to calling its `__str__` magic method and then printing the result; the `__str__` method in turn calls `record.toStr` which is an alias to record.toUnicode` method (from the py2 days when str == bytes). Basically, it is the same as doing `print(record.toUnicode(errors="backslashreplace"))`.

**Comment by justvanrossum** [comment]
This is the assert:
https://github.com/fonttools/fonttools/blob/70958dca86008aaa52086618876755968f3e82be/Lib/fontTools/encodings/codecs.py#L53-L55
The custom encodings do not support `"backslashreplace"`.

I had a reporducing snippet, but I lost it. Will try to recreate.

**Comment by justvanrossum** [comment]
```python
from fontTools.ttLib.tables._n_a_m_e import NameRecord

nr = NameRecord()
nr.nameID = 0
nr.platformID = 1
nr.platEncID = 25
nr.langID = 0x804
nr.string = "汉仪彩云体简".encode("x_mac_simp_chinese_ttx")

print(nr)
```

```
Traceback (most recent call last):
  File "/Users/just/code/git/fonttools_just/Lib/fontTools/encodings/codecs.py", line 54, in decode
    assert errors == 'strict'
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<untitled>", line 10, in <module>
  File "/Users/just/code/git/fonttools_just/Lib/fontTools/ttLib/tables/_n_a_m_e.py", line 414, in __str__
    return self.toStr(errors='backslashreplace')
  File "/Users/just/code/git/fonttools_just/Lib/fontTools/ttLib/tables/_n_a_m_e.py", line 460, in toUnicode
    string = tounicode(string, encoding=encoding, errors=errors)
  File "/Users/just/code/git/fonttools_just/Lib/fontTools/misc/py23.py", line 82, in tounicode
    return s.decode(encoding, errors)
AssertionError: decoding with 'x_mac_simp_chinese_ttx' codec failed (AssertionError: )

```
