### ISSUE TITLE
pyftsubset "crash" while subset-ing a font

### ISSUE THREAD

**Issue by thanhminhmr** [fonttools/fonttools#2151]
I use Windows 10 x64, just install Python3.9, the most recent PIP and fonttools today.
The font file **StayPuft.ttf** can be downloaded [here](https://www.1001fonts.com/staypuft-font.html).
This is the command I use and the output when it "crash".
```
$ pyftsubset "StayPuft.ttf" --unicodes="U+0030-0039,U+0041-005A,U+0061-007A"
Traceback (most recent call last):
  File "c:\users\meo\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\meo\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Meo\AppData\Local\Programs\Python\Python39\Scripts\pyftsubset.exe\__main__.py", line 7, in <module>
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\misc\loggingTools.py", line 373, in wrapper
    return func(*args, **kwds)
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\subset\__init__.py", line 2921, in main
    subsetter.subset(font)
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\subset\__init__.py", line 2723, in subset
    self._subset_glyphs(font)
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\subset\__init__.py", line 2660, in _subset_glyphs
    retain = table.subset_glyphs(self)
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\subset\__init__.py", line 1454, in subset_glyphs
    lookup_indices = self.table.LookupList.subset_glyphs(s)
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\subset\__init__.py", line 1218, in subset_glyphs
    return [i for i,l in enumerate(self.Lookup) if l and l.subset_glyphs(s)]
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\subset\__init__.py", line 1218, in <listcomp>
    return [i for i,l in enumerate(self.Lookup) if l and l.subset_glyphs(s)]
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\subset\__init__.py", line 1190, in subset_glyphs
    self.SubTable = [st for st in self.SubTable if st and st.subset_glyphs(s)]
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\subset\__init__.py", line 1190, in <listcomp>
    self.SubTable = [st for st in self.SubTable if st and st.subset_glyphs(s)]
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\subset\__init__.py", line 564, in subset_glyphs
    p.PairValueRecord = [r for r in p.PairValueRecord if r.SecondGlyph in s.glyphs]
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\subset\__init__.py", line 564, in <listcomp>
    p.PairValueRecord = [r for r in p.PairValueRecord if r.SecondGlyph in s.glyphs]
  File "c:\users\meo\appdata\local\programs\python\python39\lib\_collections_abc.py", line 899, in __iter__
    v = self[i]
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\ttLib\tables\otConverters.py", line 109, in __getitem__
    item = self.conv.read(self.reader, self.font, {})
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\ttLib\tables\otConverters.py", line 434, in read
    table.decompile(reader, font)
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 640, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\ttLib\tables\otConverters.py", line 633, in read
    return reader[self.which].readValueRecord(reader, font)
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 911, in readValueRecord
    value = reader.readShort()
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 162, in readShort
    return self.readValue("h", staticSize=2)
  File "c:\users\meo\appdata\local\programs\python\python39\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 140, in readValue
    value, = struct.unpack(f">{typecode}", self.data[pos:newpos])
struct.error: ('unpack requires a buffer of 2 bytes', 'Value1')
```

**Comment by justvanrossum** [comment]
A TTX dump of the same font gives the same error. Looks like the GPOS table is invalid/corrupt.

**Comment by thanhminhmr** [comment]
Since the font came with the sfd file, I try to generate the ttf file using the most recent version of FontForge, and now it work perfectly. If the problem is the corrupted font file, maybe print out a nice error message is better for the user than crashing out.

**Comment by behdad** [comment]
There's so many places that we would need to change to report corrupt font files that it's currently not feasible. Thanks.
