### ISSUE TITLE
ttx can't handle `AwamiNastaliq-Regular.ttf`

### ISSUE THREAD

**Issue by lemzwerg** [fonttools/fonttools#2195]
[fonttools 4.20.0 installed with pip]
[Awami Nastaliq Regular 2.100]

Calling
```
ttx AwamiNastaliq-Regular.ttf
```
causes the following
```
/usr/lib/python3.6/site-packages/fontTools/ttLib/tables/grUtils.py:24: UserWarning: Table is compressed with an unsupported compression scheme
  warnings.warn("Table is compressed with an unsupported compression scheme")
Dumping 'Glat' table...
Dumping 'Gloc' table...
ERROR: An exception occurred during the decompilation of the 'Silf' table
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/fontTools/ttLib/ttFont.py", line 372, in __getitem__
    return self.tables[tag]
KeyError: 'Silf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/fontTools/ttLib/ttFont.py", line 391, in __getitem__
    table.decompile(data, self)
  File "/usr/lib/python3.6/site-packages/fontTools/ttLib/tables/S__i_l_f.py", line 331, in decompile
    silfoffsets = struct.unpack_from(('>%dL' % self.numSilf), data[base:])
struct.error: unpack_from requires a buffer of at least 180224 bytes
```
Is this expected?  The font is available [here](https://software.sil.org/awami/download/).

**Comment by anthrotype** [comment]
Thanks for the report. I'm actually not sure, maybe @mhosken who contributed the code may shed some light?

**Comment by khaledhosny** [comment]
Awami Nastaliq lz4-compresses its `Silf` table, but also pads the compressed table with zero bytes. This requires using `LZ4_decompress_safe_partial()` to decompress the table, but the `lz4` module uses a different API that does not handle this case. See also https://github.com/lz4/lz4/issues/783.

**Comment by khaledhosny** [comment]
Or may be it is a different issue, don’t take my word for it. The error might be different from what I was seeing.
