### ISSUE TITLE
Output message for GPOS error 

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fonttools#2224]
Thanks @simoncozens for tackling the output message issue :) I just tried your last commit and run into this new output message.

Using fontmake through builder on a font which was presenting this issue last week, now output error message is:

```
Traceback (most recent call last):
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontmake/font_project.py", line 938, in run_from_designspace
    **kwargs,
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontmake/font_project.py", line 1014, in _run_from_designspace_interpolatable
    designspace, output_path=output_path, output_dir=output_dir, **kwargs
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontmake/font_project.py", line 333, in build_variable_font
    inplace=True,
  File "/Users/rosalie/env/lib/python3.7/site-packages/ufo2ft/__init__.py", line 616, in compileVariableTTF
    ttfDesignSpace, exclude=excludeVariationTables, optimize=optimizeGvar
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/__init__.py", line 926, in build
    _merge_OTL(vf, model, master_fonts, axisTags)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/__init__.py", line 619, in _merge_OTL
    merger.mergeTables(font, master_fonts, ['GSUB', 'GDEF', 'GPOS'])
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 127, in mergeTables
    for m in master_ttfs])
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 1073, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 112, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 84, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 1073, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 112, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 84, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 1073, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 112, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 84, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 1073, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 120, in mergeThings
    "got": lst},))
fontTools.varLib.errors.VarLibMergeError: <exception str() failed>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rosalie/env/bin/gftools-builder.py", line 83, in <module>
    builder.build()
  File "/Users/rosalie/env/lib/python3.7/site-packages/gftools/builder/__init__.py", line 145, in build
    self.build_variable()
  File "/Users/rosalie/env/lib/python3.7/site-packages/gftools/builder/__init__.py", line 246, in build_variable
    output_files = self.run_fontmake(source, args)
  File "/Users/rosalie/env/lib/python3.7/site-packages/gftools/builder/__init__.py", line 265, in run_fontmake
    FontProject().run_from_glyphs(source, **args)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontmake/font_project.py", line 691, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontmake/font_project.py", line 949, in run_from_designspace
    ) from e
fontmake.errors.FontmakeError: <exception str() failed>
```

If I run only fontmake:

```
Traceback (most recent call last):
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontmake/font_project.py", line 938, in run_from_designspace
    **kwargs,
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontmake/font_project.py", line 1014, in _run_from_designspace_interpolatable
    designspace, output_path=output_path, output_dir=output_dir, **kwargs
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontmake/font_project.py", line 333, in build_variable_font
    inplace=True,
  File "/Users/rosalie/env/lib/python3.7/site-packages/ufo2ft/__init__.py", line 616, in compileVariableTTF
    ttfDesignSpace, exclude=excludeVariationTables, optimize=optimizeGvar
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/__init__.py", line 926, in build
    _merge_OTL(vf, model, master_fonts, axisTags)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/__init__.py", line 619, in _merge_OTL
    merger.mergeTables(font, master_fonts, ['GSUB', 'GDEF', 'GPOS'])
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 127, in mergeTables
    for m in master_ttfs])
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 1073, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 112, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 84, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 1073, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 112, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 84, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 1073, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 112, in mergeThings
    self.mergeObjects(out, lst)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 84, in mergeObjects
    mergerFunc(self, value, values)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 1073, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/merger.py", line 120, in mergeThings
    "got": lst},))
fontTools.varLib.errors.VarLibMergeError: <exception str() failed>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontmake/__main__.py", line 445, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontmake/font_project.py", line 691, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontmake/font_project.py", line 949, in run_from_designspace
    ) from e
fontmake.errors.FontmakeError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 372, in __getitem__
    return self.tables[tag]
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rosalie/env/bin/fontmake", line 8, in <module>
    sys.exit(main())
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontmake/__main__.py", line 486, in main
    sys.exit(f"fontmake: Error: {str(e)}")
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontmake/errors.py", line 33, in __str__
    cause = str(self.__cause__) if self.__cause__ is not None else None
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/errors.py", line 39, in __str__
    for ttf in self.merger.ttfs
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/varLib/errors.py", line 39, in <listcomp>
    for ttf in self.merger.ttfs
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 381, in __getitem__
    data = self.reader[tag]
  File "/Users/rosalie/env/lib/python3.7/site-packages/fontTools/ttLib/sfnt.py", line 105, in __getitem__
    entry = self.tables[Tag(tag)]
KeyError: 'name'
```

Same if I reinstall fontmake and https://github.com/fonttools/fonttools in a new venv

**Comment by simoncozens** [comment]
Thanks, I anticipated this *might* happen. I’ll need the font so will contact you separately to resolve.
