### ISSUE TITLE
fonttools crashes on MFEKglif-produced .glif files because they contain `<lib />`

### ISSUE THREAD

**Issue by ctrlcctrlv** [fonttools/fonttools#2234]
To be clear, I'm the principal author and maintainer of MFEK/glif.

But I don't view this as a bug in my software.

```
Traceback (most recent call last):
  File "/home/fred/Workspace/MFEKglif/./glif2svg.py", line 50, in <module>
    glifLib.readGlyphFromString(f.read(), glyph, ptsp)
  File "/home/fred/.local/lib/python3.9/site-packages/fonttools-4.19.2.dev0-py3.9.egg/fontTools/ufoLib/glifLib.py", line 650, in readGlyphFromString
    _readGlyphFromTree(
  File "/home/fred/.local/lib/python3.9/site-packages/fonttools-4.19.2.dev0-py3.9.egg/fontTools/ufoLib/glifLib.py", line 1031, in _readGlyphFromTree
    readGlyphFromTree(
  File "/home/fred/.local/lib/python3.9/site-packages/fonttools-4.19.2.dev0-py3.9.egg/fontTools/ufoLib/glifLib.py", line 1159, in _readGlyphFromTreeFormat2
    _readLib(glyphObject, element, validate)
  File "/home/fred/.local/lib/python3.9/site-packages/fonttools-4.19.2.dev0-py3.9.egg/fontTools/ufoLib/glifLib.py", line 1202, in _readLib
    assert len(lib) == 1
AssertionError
```

Glyph:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<glyph format="2" name="space">
  <advance width="1282" />
  <unicode hex="20" />
  <anchor x="631" name="Anchor-0" y="1048" />
  <lib />
</glyph>
```

The empty `<lib/>` should be OK. This also means fontmake can't understand MFEKglif-produced glyphs. I think fonttools should be more tolerant of empty `<lib/`>'s.

**Comment by anthrotype** [comment]
I'm not sure why that assertion that lib element is not empty and has some children is there in the first place, it seems to be like that since forever, see git blame
https://github.com/fonttools/fonttools/commit/a2895df22f5d9a4d4b15c20b8009cce14d258b8b#diff-f8c8b522f847849ae3baa115ec6618fb0abec0c8bbfd5488fa33d16538b61a31R931

Does the UFO spec say something about it?
I'd be ok with relaxing that.

**Comment by anthrotype** [comment]
FWIW the ufoNormalizer seem to accept such empty lib elements in GLIF -- it just drops them

https://github.com/unified-font-object/ufoNormalizer/blob/783ec1479ed35f26a9992cb18927f1902207b0af/src/ufonormalizer/__init__.py#L817-L818

**Comment by ctrlcctrlv** [comment]
[Spec](https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#lib) says:

```
lib must have one child element that is structure as a dictionary formatted as an XML Property List.
```

But that doesn't sound right or XML-conformant to me?

**Comment by anthrotype** [comment]
I see that. So the spec wants you to have an inner `<dict/>` element inside your empty lib. It expects one, I'm afraid. So you either remove the whole parent lib element if its dict element is empty or you keep it but leave the first-only dict (empty) child in, along with the parent lib. You can raise the issue at the UFO spec repository if you like.

**Comment by anthrotype** [comment]
> XML-conformant to me?

it's not about XML conformancy here, but UFO's, which can define whatever XML elements should be required or not.

**Comment by anthrotype** [comment]
as I said, i'd be fine with relaxing this, a hard crash is no better than a silent skip, as there's no much one can do with such an empty lib. But it'd be also advisable to relax the wording of the spec itself. Can you work on some PRs to both ufo-spec and fonttools?

**Comment by ctrlcctrlv** [comment]
Yup, can do. And XML conformance should matter because `<?xml version="1.0" encoding="UTF-8"?>`.

**Comment by anthrotype** [comment]
UFO is built on top of XML but it is free to say "this element is required", "this other element needs to have exactly one child of this kind" etc. So it is _not_ about XML conformance.

**Comment by ctrlcctrlv** [comment]
:man_shrugging: OK.

**Comment by anthrotype** [comment]
Sorry but -- why can't you simply modify your tool to not emit that empty `<lib/>`?

**Comment by ctrlcctrlv** [comment]
I think I shouldn't have to. Obviously I can. Actually, I'm going to be writing my own XML with an <MFEK> root in a comment after the lib, because a lot of tools freak out if they see an element they don't recognize, but don't care about comments.

**Comment by anthrotype** [comment]
it's definitely simpler to fix one tool than change the spec (which could potentially require to change _all_ other implementations). Unless there's a good reason for the change.

**Comment by ctrlcctrlv** [comment]
It's more correct IMO to allow it though. Besides, binaries of this tool are floating around out there. The normalizer understands it, so this must've come up before? Maybe that's a reach. Anyway, I think my spec change is right, so...

**Comment by benkiel** [comment]
The normalizer removes it as a cleanup, so I'm not sure I'd go so far as to say it means that it's per the spec. Currently I'm tending toward @anthrotype's opinion that it's much easier to change one tool than the spec and then need to test/change a variety of things.

**Comment by benkiel** [comment]
Also: changing the spec to fit a tool that didn't conform to the spec isn't a great precedence to set, even if the author of the tool didn't think that the spec was right/made sense (as an example: the cascading effects of allowing a hyphen in glyph names which still comes up).

**Comment by ctrlcctrlv** [comment]
If one of my users had opened this, would your opinion be different? Out of curiosity alone.

By the way, just wrote this fontTools-related thing, not sure who to tell: https://github.com/ctrlcctrlv/glif2svg

**Comment by benkiel** [comment]
No, if a user had opened it I would say "talk to the author the the tool, fontTools is throwing this error because the UFO doesn't follow the spec".

Still thinking about this, also want others to weigh in over on the UFO issue, sorry for bifurcating the discussion in two places.

**Comment by ctrlcctrlv** [comment]
Well, conversion of MFEK .glif files are already known by me to require normalization (I call it reconciliation). See:

https://github.com/MFEK/docs/blob/master/doc/Layers.md

I don't plan on using the <lib/> at all longterm, my stuff will go in my <MFEK> comment, and I'll just copy whatever <lib> is there, so really this is just my opinion on the spec.

**Comment by benkiel** [comment]
If I understand what you're saying; instead of having a `MFEK` key in the `lib` dict, you're just going to use a comment? That both defeats the purpose of having the `lib` and that no other tool will be able to read/understand `MFEK` data in a UFO. Is there a reason you don't want to use the `lib`?

**Comment by ctrlcctrlv** [comment]
Well no other tool _should_ be able to understand my private MFEK dict without going to the trouble of knowing I exist. So, that's fine with me. It's possible I'll stick some things I think are important for other tools to keep around in `<lib/>`. And also I might implement some of the other `<lib/>` pseudo-standards, like the way Runebender stores Hyperbeziers. Or some of the color-related ones.

And the reason I'm going with the comment is because fontTools doesn't like elements under the root it doesn't recognize, crashes if `<MFEK>` is present under `<glyph>`. I don't like that `<lib>` is a plist, I want to store XML. Guess I could do it as a string keyed like `org.MFEK.dict`, but my partner on this project also preferred the comment in our discussion to that, it's not as ugly.

**Comment by benkiel** [comment]
@ctrlcctrlv to be clear: no tool is expected to understand a `MFEK` key in the lib, but it is required to preserve that key and not mess with the data. Putting things into comments won't guarantee that when the UFO is opened by another tool the data you had put into comments will be preserved. Nothing would/could do anything with the `MFEK` key unless it knew about the `MFEK` and could read your data based on your documentation of it.

Of course your tool can do whatever it wants, but I really, really, really recommend not hacking the UFO format with no-specified things. If the format isn't working for your tool, I'd suggest that you make your own tool specific format and have a UFO export for interchange with other tools (fontmake, font tools, other editors, command line things, etc). 

People will see a UFO file and rightly assume that it functions well without normalization, open it in something other than MFEK and get unexpected results. In other words, please don't make a tool that makes nonstandard UFOs, it's bad for everyone.
