### ISSUE TITLE
subset AssertionError

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fonttools#2257]
I’m getting this assertion while building `AmiriQuranColored.otf`:

```
$ make AmiriQuranColored.otf
Traceback (most recent call last):
  File "/amiri/build.py", line 556, in <module>
    makeQuran(args)
  File "/amiri/build.py", line 411, in makeQuran
    subsetter.subset(otf)
  File "/amiri/venv/lib/python3.9/site-packages/fontTools/subset/__init__.py", line 2861, in subset
    self._prune_post_subset(font)
  File "/amiri/venv/lib/python3.9/site-packages/fontTools/subset/__init__.py", line 2844, in _prune_post_subset
    retain = table.prune_post_subset(font, self.options)
  File "/amiri/venv/lib/python3.9/site-packages/fontTools/subset/__init__.py", line 2094, in prune_post_subset
    assert len(palette) == len(retained_palette_indices)
AssertionError
make: *** [Makefile:32: AmiriQuranColored.otf] Error 1
```

It seems to have been introduced in 056aba8e4afbaccc363f665c79394fbd56b4c380. My `retained_palette_indices` has one extra index, 65535, used for parts of the glyphs that take text color. I’m not sure what is the point of the assertion, but 65535 is legit color index.

**Comment by behdad** [comment]
Just remove `0xFFFF` from `retained_palette_indices` right before that assertion.
