### ISSUE TITLE
feaLib should not fail in getAlternateGlyphs for empty lookups

### ISSUE THREAD

**Issue by kontur** [fonttools/fonttools#2276]
Hey,

following case: I have two feature files, `uprights.fea` and `italics.fea` being compiled. Both files include a `shared.fea` which contains a lot of shared feature code. However, there is a small difference in uprights and italics. 

To get around it, my `uprights.fea` has this:

```
lookup ONLY_UPRIGHTS {
  sub GlyphOnlyExistsInUprights by GlyphOnlyExistsInUprights.alt;
} ONLY_UPRIGHTS;
```

and in `italics.fea` has this:

```
lookup ONLY_UPRIGHTS {
  # pass
} ONLY_UPRIGHTS;
```

and `shared.fea` uses the lookup.

This will fail with a (partial) stacktrace of:
```
  File "/Users/johannes/.pyenv/versions/3.7.6/envs/mrhandy/lib/python3.7/site-packages/ufo2ft/featureWriters/markFeatureWriter.py", line 859, in _getIndicGlyphs
    gsub = self.compileGSUB()
  File "/Users/johannes/.pyenv/versions/3.7.6/envs/mrhandy/lib/python3.7/site-packages/ufo2ft/featureWriters/baseFeatureWriter.py", line 307, in compileGSUB
    gsub = compileGSUB(self.context.feaFile, glyphOrder)
  File "/Users/johannes/.pyenv/versions/3.7.6/envs/mrhandy/lib/python3.7/site-packages/ufo2ft/util.py", line 227, in compileGSUB
    addOpenTypeFeatures(font, featureFile, tables={"GSUB"})
  File "/Users/johannes/.pyenv/versions/3.7.6/envs/mrhandy/lib/python3.7/site-packages/fontTools/feaLib/builder.py", line 60, in addOpenTypeFeatures
    builder.build(tables=tables, debug=debug)
  File "/Users/johannes/.pyenv/versions/3.7.6/envs/mrhandy/lib/python3.7/site-packages/fontTools/feaLib/builder.py", line 184, in build
    self.build_feature_aalt_()
  File "/Users/johannes/.pyenv/versions/3.7.6/envs/mrhandy/lib/python3.7/site-packages/fontTools/feaLib/builder.py", line 286, in build_feature_aalt_
    for glyph, alts in lookup.getAlternateGlyphs().items():
AttributeError: 'NoneType' object has no attribute 'getAlternateGlyphs'
```

I can work around this by using this nonsensical substitution in `italics.fea`:

```
lookup ONLY_UPRIGHTS {
  sub space by space;
} ONLY_UPRIGHTS;
```

It seems functionally there should be no reason to not allow empty lookups, however `feaLib.builder.getAlternateGlyphs` chokes on such an occasion.

This happens at least in fontTools `4.21.1` and `4.22.0`.

**Comment by anthrotype** [comment]
can I see a minimal working block of FEA, not just an extract, but one that compiles and reproduces the error?

I'm not even sure that we do support compiling empty lookup blocks, if I try with the following, I get yet another `AttributeError`

```
lookup EMPTY {
    # pass
} EMPTY;
feature ss01 {
    lookup EMPTY;
} ss01;
```

```
Traceback (most recent call last):
  File "/Users/clupo/Github/fonttools/.venv/bin/fonttools", line 33, in <module>
    sys.exit(load_entry_point('fonttools', 'console_scripts', 'fonttools')())
  File "/Users/clupo/Github/fonttools/Lib/fontTools/__main__.py", line 30, in main
    runpy.run_module(mod, run_name='__main__')
  File "/Users/clupo/Github/brew/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 213, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/Users/clupo/Github/brew/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/feaLib/__main__.py", line 77, in <module>
    sys.exit(main())
  File "/Users/clupo/Github/fonttools/Lib/fontTools/feaLib/__main__.py", line 66, in main
    addOpenTypeFeatures(
  File "/Users/clupo/Github/fonttools/Lib/fontTools/feaLib/builder.py", line 60, in addOpenTypeFeatures
    builder.build(tables=tables, debug=debug)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/feaLib/builder.py", line 200, in build
    table = self.makeTable(tag)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/feaLib/builder.py", line 849, in makeTable
    [l.lookup_index for l in lookups if l.lookup_index is not None]
  File "/Users/clupo/Github/fonttools/Lib/fontTools/feaLib/builder.py", line 849, in <listcomp>
    [l.lookup_index for l in lookups if l.lookup_index is not None]
AttributeError: 'NoneType' object has no attribute 'lookup_index'
```

**Comment by kontur** [comment]
Thanks @anthrotype for the quick action on this!
