### ISSUE TITLE
Error in getOverflowRecordItem

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#2290]
This looks similar to #537 - caused by a massive kern table.

```
  File "/usr/local/lib/python3.8/site-packages/fontTools/ttLib/tables/otBase.py", line 401, in getAllData
    tableData = table.getData()
  File "/usr/local/lib/python3.8/site-packages/fontTools/ttLib/tables/otBase.py", line 270, in getData
    overflowErrorRecord = self.getOverflowErrorRecord(item)
  File "/usr/local/lib/python3.8/site-packages/fontTools/ttLib/tables/otBase.py", line 490, in getOverflowErrorRecord
    while p1 and p1.name not in ['ExtSubTable', 'SubTable']:
AttributeError: 'OTTableWriter' object has no attribute 'name'
```

**Comment by anthrotype** [comment]
hm, that code hasn't changed in a while.
can you upload a file that repro this?

**Comment by behdad** [comment]
Can you debug and print out the type of `p1` at that point?

**Comment by simoncozens** [comment]
It's an `OTTableWriter`, it said that... i.e. this is overflowing at the very top level.

**Comment by simoncozens** [comment]
Here's the overflow object:

```Python console
In [1]: self.name
Out[1]: 'ChainPosClassSet'

In [2]: self.__dict__
Out[2]:
{'items': (b'\x0fA',
  <fontTools.ttLib.tables.otBase.OTTableWriter at 0x116d9a640>,
  <fontTools.ttLib.tables.otBase.OTTableWriter at 0x116d9a670>,
  <fontTools.ttLib.tables.otBase.OTTableWriter at 0x116d9a850>,
  <fontTools.ttLib.tables.otBase.OTTableWriter at 0x116d9aac0>,
...
  ...),
 'pos': 1356,
 'localState': {'LookupType': <fontTools.ttLib.tables.otBase.CountReference at 0x116c66820>},
 'tableTag': None,
 'offsetSize': 2,
 'parent': <fontTools.ttLib.tables.otBase.OTTableWriter at 0x116c66790>,
 'name': 'ChainPosClassSet',
 'repeatIndex': 2}
```

**Comment by behdad** [comment]
I suggest this:
```
diff --git a/Lib/fontTools/ttLib/tables/otBase.py b/Lib/fontTools/ttLib/tables/otBase.py
index 06d5cde5..ae712d8a 100644
--- a/Lib/fontTools/ttLib/tables/otBase.py
+++ b/Lib/fontTools/ttLib/tables/otBase.py
@@ -222,6 +222,8 @@ class OTTableWriter(object):
 
        """Helper class to gather and assemble data for OpenType tables."""
 
+       name = '<none>'
+
        def __init__(self, localState=None, tableTag=None, offsetSize=2):
                self.items = []
                self.pos = None
```

**Comment by simoncozens** [comment]
That gets further, and now I am seeing:

```
Traceback (most recent call last):
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 283, in getData
    items[i] = packUShort(item.pos - pos)
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 566, in packUShort
    return struct.pack(">H", value)
struct.error: 'H' format requires 0 <= number <= 65535

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/Current/bin//fonttools", line 8, in <module>
    sys.exit(main())
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/__main__.py", line 30, in main
    runpy.run_module(mod, run_name='__main__')
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 210, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/feaLib/__main__.py", line 77, in <module>
    sys.exit(main())
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/feaLib/__main__.py", line 66, in main
    addOpenTypeFeatures(
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/feaLib/builder.py", line 65, in addOpenTypeFeatures
    builder.build(tables=tables, debug=debug)
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/feaLib/builder.py", line 214, in build
    table = self.makeTable(tag)
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/feaLib/builder.py", line 860, in makeTable
    table.LookupList.Lookup = self.buildLookups_(tag)
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/feaLib/builder.py", line 847, in buildLookups_
    otLookups = [l.build() for l in lookups]
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/feaLib/builder.py", line 847, in <listcomp>
    otLookups = [l.build() for l in lookups]
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/otlLib/builder.py", line 390, in build
    winner = min(candidates, key=self.getCompiledSize_)
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/otlLib/builder.py", line 353, in getCompiledSize_
    size += len(w.getAllData())
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 417, in getAllData
    tableData = table.getData()
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 288, in getData
    raise OTLOffsetOverflowError(overflowErrorRecord)
fontTools.ttLib.tables.otBase.OTLOffsetOverflowError: (None, 'LookupIndex:', None, 'SubTableIndex:', None, 'ItemName:', '<none>.ChainPosClassSet.ChainPosClassRule', 'ItemIndex:', 2486)
```

This is not a problem for me - it is a pathological font and I've worked around it by sharding the kern table into different subtables based on first glyph. I don't really expect it to be able to compile.

**Comment by behdad** [comment]
Send us the repro just to keep around when working on that code. Thanks.
