### ISSUE TITLE
Subsetting fails: 'NoneType' object has no attribute 'getEffectiveFormat'

### ISSUE THREAD

**Issue by nathan-williams** [fonttools/fonttools#2312]
The following command fails: `fonttools subset fonts/ofl/NotoSansSiddham-Regular.ttf "*"`. Forgive me if I'm using the tool incorrectly. 

Stack trace:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/fonttools", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/__main__.py", line 30, in main
    runpy.run_module(mod, run_name='__main__')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/subset/__main__.py", line 6, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 3094, in main
    subsetter.subset(font)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 2897, in subset
    self._prune_post_subset(font)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 2880, in _prune_post_subset
    retain = table.prune_post_subset(font, self.options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 1665, in prune_post_subset
    table.LookupList.prune_post_subset(font, options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 1264, in prune_post_subset
    if l.prune_post_subset(font, options): ret = True
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 1238, in prune_post_subset
    if st.prune_post_subset(font, options): ret = True
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/subset/__init__.py", line 562, in prune_post_subset
    self.ValueFormat = self.Value.getEffectiveFormat()
AttributeError: 'NoneType' object has no attribute 'getEffectiveFormat'
```

**Comment by rsheeter** [comment]
Summon @anthrotype  :D

**Comment by anthrotype** [comment]
no, you're not using it incorrectly! You found a bug! Thanks!
