### ISSUE TITLE
Instancer failing to remove overlaps

### ISSUE THREAD

**Issue by nathan-williams** [fonttools/fonttools#2363]
(fonttools v4.25.0)

The following instancing command fails: `fonttools varLib.instancer ./NotoSansEthiopic\[wdth\,wght\].ttf wdth=87.5 wght=800 --remove-overlaps`.

The font I was attempting to instance: [NotoSansEthiopic[wdth,wght].ttf.zip](https://github.com/fonttools/fonttools/files/6812558/NotoSansEthiopic.wdth.wght.ttf.zip).

Here's the stack trace:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/ttLib/removeOverlaps.py", line 110, in _simplify
    path = pathops.simplify(path, clockwise=path.clockwise)
  File "src/python/pathops/_pathops.pyx", line 1476, in pathops._pathops.simplify
  File "src/python/pathops/_pathops.pyx", line 1487, in pathops._pathops.simplify
pathops._pathops.PathOpsError: operation did not succeed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/fonttools", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/__main__.py", line 30, in main
    runpy.run_module(mod, run_name='__main__')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/varLib/instancer/__main__.py", line 5, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/varLib/instancer/__init__.py", line 1415, in main
    updateFontNames=options.update_name_table,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/varLib/instancer/__init__.py", line 1251, in instantiateVariableFont
    removeOverlaps(varfont)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/ttLib/removeOverlaps.py", line 210, in removeOverlaps
    glyphName, glyphSet, glyfTable, hmtxTable, removeHinting
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/ttLib/removeOverlaps.py", line 143, in removeTTGlyphOverlaps
    path2 = _simplify(path, glyphName)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fontTools/ttLib/removeOverlaps.py", line 121, in _simplify
    ) from e
fontTools.ttLib.removeOverlaps.RemoveOverlapsError: Failed to remove overlaps from glyph 'cchee.eth'
```

**Comment by moyogo** [comment]
This is related to https://github.com/google/fonts/issues/3365

**Comment by anthrotype** [comment]
Yes like Denis said, this one is the same Skia Pathops bug which we tried to workaround in https://github.com/fonttools/fonttools/pull/2288.
Unfortunately the upstream Skia bug (https://bugs.chromium.org/p/skia/issues/detail?id=11958) has not received any updates since May.. :-/

**Comment by yisibl** [comment]
@anthrotype Upstream is updated, can we update to the latest version to try? https://bugs.chromium.org/p/skia/issues/detail?id=11958#c16

**Comment by anthrotype** [comment]
Yes, I saw. It's good there some progress on that upstream Skia bug.
I did try yesterday to rebuild skia master branch and use that in skia-pathops but it still fails e.g. when I try to instantiate NotoSansEthiopic:

```
$ fonttools varLib.instancer ../fonts/ofl/notosansethiopic/NotoSansEthiopic\[wdth\,wght\].ttf wdth=87.5 wght=800 --remove-overlaps
[... omitted for brevity ...]
  File "/Users/clupo/Github/skia-pathops/.venv/lib/python3.10/site-packages/fontTools/ttLib/removeOverlaps.py", line 120, in _simplify
    raise RemoveOverlapsError(
fontTools.ttLib.removeOverlaps.RemoveOverlapsError: Failed to remove overlaps from glyph 'cchee.eth'
```

I also got a bad "Bus error: 10" error (as bad as a segfault) while running skia-pathops test suite with the updated libskia, so I think I'll wait a bit before upgrading.

**Comment by behdad** [comment]
Needs retesting?
