### ISSUE TITLE
FontTools 4.25.2 breaks some HarfBuzz tests

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fonttools#2378]
The attaching font is created by hb-subset, the latest FontTools can’t decompile it:
[NotoColrEmojiGlyf-Regular.subset.default.1f35e.ttf-subset.zip](https://github.com/fonttools/fonttools/files/6880637/NotoColrEmojiGlyf-Regular.subset.default.1f35e.ttf-subset.zip)
```
$ ttx NotoColrEmojiGlyf-Regular.subset.default.1f35e.ttf-subset.ttf
Dumping "NotoColrEmojiGlyf-Regular.subset.default.1f35e.ttf-subset.ttf" to "NotoColrEmojiGlyf-Regular.subset.default.1f35e.ttf-subset.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
ERROR: An exception occurred during the decompilation of the 'COLR' table
Traceback (most recent call last):
  File "/lib/python3.9/site-packages/fontTools/ttLib/ttFont.py", line 395, in _readTable
    table.decompile(data, self)
  File "/lib/python3.9/site-packages/fontTools/ttLib/tables/C_O_L_R_.py", line 64, in decompile
    table.decompile(reader, ttFont)
  File "/lib/python3.9/site-packages/fontTools/ttLib/tables/otTables.py", line 1229, in decompile
    return BaseTable.decompile(self, reader, font)
  File "/lib/python3.9/site-packages/fontTools/ttLib/tables/otBase.py", line 673, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/lib/python3.9/site-packages/fontTools/ttLib/tables/otConverters.py", line 633, in read
    table.decompile(reader, font)
  File "/lib/python3.9/site-packages/fontTools/ttLib/tables/otBase.py", line 673, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/lib/python3.9/site-packages/fontTools/ttLib/tables/otConverters.py", line 633, in read
    table.decompile(reader, font)
  File "/lib/python3.9/site-packages/fontTools/ttLib/tables/otBase.py", line 673, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/lib/python3.9/site-packages/fontTools/ttLib/tables/otConverters.py", line 290, in read
    return reader.readUShort()
  File "/lib/python3.9/site-packages/fontTools/ttLib/tables/otBase.py", line 176, in readUShort
    return self.readValue("H", staticSize=2)
  File "/lib/python3.9/site-packages/fontTools/ttLib/tables/otBase.py", line 144, in readValue
    value, = struct.unpack(f">{typecode}", self.data[pos:newpos])
struct.error: ('unpack requires a buffer of 2 bytes', 'RegionAxisCount', 'VarRegionList', 'VarStore')
Dumping 'COLR' table...
Dumping 'CPAL' table...
Dumping 'GSUB' table...
```

**Comment by khaledhosny** [comment]
Bisected to 40897a1508cdaf040f940fda0ed784d30d8bcfaf, cc @anthrotype.

**Comment by khaledhosny** [comment]
I don’t actually know which is correct here, HarfBuzz or FontTools, cc @garretrieger since he added the failing `colrv1.notoemoji.tests` to Harfbuzz.

**Comment by anthrotype** [comment]
It is expected since fonttools has been updated to the latest draft COLRv1 spec, whereas harfbuzz hasn't yet

**Comment by khaledhosny** [comment]
OK, so I guess I should bin fonttools version until this is fixed in HarfBuzz.
