### ISSUE TITLE
ImportError: No module named brotli

### ISSUE THREAD

**Issue by knynkwl** [fonttools/fonttools#2406]
I started getting this error recently. 

```sh
Package    Version
---------- -------
Brotli     1.0.9
pip        21.2.4
setuptools 56.0.0
wheel      0.36.2
```

```sh
ERROR: The WOFF2 encoder requires the Brotli Python extension, available at: https://github.com/google/brotli
Traceback (most recent call last):
  File "/usr/local/bin/pyftsubset", line 33, in <module>
    sys.exit(load_entry_point('fonttools==4.25.1', 'console_scripts', 'pyftsubset')())
  File "/usr/local/Cellar/fonttools/4.25.1/libexec/lib/python3.9/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/Cellar/fonttools/4.25.1/libexec/lib/python3.9/site-packages/fontTools/subset/__init__.py", line 3106, in main
    save_font(font, outfile, options)
  File "/usr/local/Cellar/fonttools/4.25.1/libexec/lib/python3.9/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/Cellar/fonttools/4.25.1/libexec/lib/python3.9/site-packages/fontTools/subset/__init__.py", line 2952, in save_font
    font.save(outfile, reorderTables=options.canonical_order)
  File "/usr/local/Cellar/fonttools/4.25.1/libexec/lib/python3.9/site-packages/fontTools/ttLib/ttFont.py", line 172, in save
    writer_reordersTables = self._save(tmp)
  File "/usr/local/Cellar/fonttools/4.25.1/libexec/lib/python3.9/site-packages/fontTools/ttLib/ttFont.py", line 208, in _save
    writer = SFNTWriter(file, numTables, self.sfntVersion, self.flavor, self.flavorData)
  File "/usr/local/Cellar/fonttools/4.25.1/libexec/lib/python3.9/site-packages/fontTools/ttLib/woff2.py", line 175, in __init__
    raise ImportError("No module named brotli")
ImportError: No module named brotli
```

**Comment by knynkwl** [comment]
`fonttool` was using the brew installed version, had to uninstall that and it started working
