### ISSUE TITLE
old ttProgram.py used to check and fix PUSHs mnemonics

### ISSUE THREAD

**Issue by sansplomb** [fonttools/fonttools#248]
The old version of fontTools used to check and fix PUSHs mnemonics so that it did not matter what kind of PUSHW, PUSHB, NPUSHW, or NPUSHB was called.

This current version of fontTools implies a generic 'PUSH' instruction must be used to have the automatic selection of Word-or-Byte One-or-Many while the original fontTools was making that automatic selection anyway.

For backward compatibility reasons I suggest to add the automatic correction of the PUSH instructions

**Comment by behdad** [comment]
What's your exact usecase?

**Comment by sansplomb** [comment]
In RoboFont with the old fontTools I had a case where I did push 11 elements to the stack with a simple PUSHW[ ] and it did not raise any errors (I assume it was corrected to NPUSHW[ ]).

Now with the latest fontTools, I got AssertionError: 11

Traceback (most recent call last):
  File "lib/fontObjects/doodleFontCompiler/ttfCompiler.pyc", line 510, in compile
  File "ufo2fdk/makeotfParts.pyc", line 64, in compile
  File "ufo2fdk/makeotfParts.pyc", line 79, in setupFile_outlineSource
  File "lib/fontObjects/doodleFontCompiler/ttfCompiler.pyc", line 257, in compile
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 214, in save
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 626, in _writeTable
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 626, in _writeTable
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 629, in _writeTable
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 642, in getTableData
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/_g_l_y_f.py", line 70, in compile
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/_g_l_y_f.py", line 325, in compile
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/_g_l_y_f.py", line 556, in compileCoordinates
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/ttProgram.py", line 220, in getBytecode
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/ttProgram.py", line 370, in _assemble
AssertionError: 11

But in fact this was more a problem with my code so I fixed it with a function that gives me the right PUSH for each case:
def autoPush(args):
	nArgs = len(args)
	# Check and Fix mnemonic 
	if max(args) > 255 or min(args) < 0:
		mnemonic = "PUSHW[ ]"
	else:
		mnemonic = "PUSHB[ ]"
	if 8 < nArgs < 256:
		mnemonic = "N" + mnemonic
	elif nArgs >= 256:
		raise tt_instructions_error, "More than 255 push arguments (%s)" % nArgs

	return (' '.join([mnemonic]+[str(a) for a in args]))

**Comment by behdad** [comment]
Ah, somehow I never saw your last comment :(.  Anyway, there's more discussion on this here:
https://github.com/behdad/fonttools/issues/92
