### ISSUE TITLE
Crash in `PointToSegmentPen._flushContour` when going over a glyph's components, but not the original glyph?

### ISSUE THREAD

**Issue by ctrlcctrlv** [fonttools/fonttools#2497]
Dealing with a strange crash in ufo2ft. I've patched my local fontTools to get around it.

# Backtrace
```
ERROR:root:In 'build/FRBAmericanCursive-Regular.ufo': Compiling UFO failed: Illegal line segment point count: 2
Traceback (most recent call last):
  File "/home/fred/.local/lib/python3.10/site-packages/fontmake/font_project.py", line 391, in _iter_compile
    yield compile_func(ufo, debugFeatureFile=debugFeatureFile, **options)
  File "/home/fred/.local/lib/python3.10/site-packages/ufo2ft/__init__.py", line 168, in compileOTF
    glyphSet = call_preprocessor(ufo, **kwargs)
  File "/home/fred/.local/lib/python3.10/site-packages/ufo2ft/__init__.py", line 61, in call_preprocessor
    return preProcessor.process()
  File "/home/fred/.local/lib/python3.10/site-packages/ufo2ft/preProcessor.py", line 62, in process
    func(ufo, glyphSet)
  File "/home/fred/.local/lib/python3.10/site-packages/ufo2ft/filters/base.py", line 196, in __call__
    if include(glyph) and filter_(glyph):
  File "/home/fred/.local/lib/python3.10/site-packages/ufo2ft/filters/decomposeComponents.py", line 11, in filter
    ufo2ft.util.deepCopyContours(self.context.glyphSet, glyph, glyph, Transform())
  File "/home/fred/.local/lib/python3.10/site-packages/ufo2ft/util.py", line 173, in deepCopyContours
    deepCopyContours(
  File "/home/fred/.local/lib/python3.10/site-packages/ufo2ft/util.py", line 194, in deepCopyContours
    contour.draw(pen)
  File "/home/fred/.local/lib/python3.10/site-packages/ufoLib2/objects/contour.py", line 157, in draw
    self.drawPoints(pointPen)
  File "/home/fred/.local/lib/python3.10/site-packages/ufoLib2/objects/contour.py", line 182, in drawPoints
    pointPen.endPath()
  File "/home/fred/.local/lib/python3.10/site-packages/fontTools/pens/pointPen.py", line 155, in endPath
    self._flushContour(segments)
  File "/home/fred/.local/lib/python3.10/site-packages/fontTools/pens/pointPen.py", line 211, in _flushContour
    raise PenError(f"Illegal line segment point count: {len(points)}")
fontTools.pens.basePen.PenError: Illegal line segment point count: 2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fred/.local/lib/python3.10/site-packages/fontmake/__main__.py", line 584, in main
    project.run_from_ufos(
  File "/home/fred/.local/lib/python3.10/site-packages/fontmake/font_project.py", line 1103, in run_from_ufos
    self.build_otfs(ufos, cff_version=cff_version, **kwargs)
  File "/home/fred/.local/lib/python3.10/site-packages/fontmake/font_project.py", line 231, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/home/fred/.local/lib/python3.10/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/home/fred/.local/lib/python3.10/site-packages/fontmake/font_project.py", line 529, in save_otfs
    for font, ufo in zip(fonts, ufos):
  File "/home/fred/.local/lib/python3.10/site-packages/fontmake/font_project.py", line 393, in _iter_compile
    raise FontmakeError("Compiling UFO failed", ufo.path) from e
fontmake.errors.FontmakeError: In 'build/FRBAmericanCursive-Regular.ufo': Compiling UFO failed: Illegal line segment point count: 2
100% 1:0=0s Regular 35 400                                                                                                                       
make[1]: *** [mk/monoline.mk:4: monoline] Error 1
make[1]: Leaving directory '/home/fred/Workspace/NotoHandAmericanCursive'
make: *** [mk/monoline.mk:16: debug-font] Error 2
```

# Diff
```diff python
diff --git a/tmp/pointPen.py b/home/fred/.local/lib/python3.10/site-packages/fontTools/pens/pointPen.py
index 4c3148b..95e71a3 100644
--- a/tmp/pointPen.py
+++ b/home/fred/.local/lib/python3.10/site-packages/fontTools/pens/pointPen.py
@@ -208,7 +208,7 @@ class PointToSegmentPen(BasePointToSegmentPen):
                        points = [pt for pt, _, _ , _ in points]
                        if segmentType == "line":
                                if len(points) != 1:
-                                       raise PenError(f"Illegal line segment point count: {len(points)}")
+                                       continue
                                pt = points[0]
                                # For closed contours, a 'lineTo' is always implied from the last oncurve
                                # point to the starting point, thus we can omit it when the last and
```

On this glyph:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="onehalf" format="2">
  <advance width="513"/>
  <unicode hex="BD"/>
  <outline>
    <component base="one.numr" xScale="1" xyScale="0" yxScale="0" yScale="1" xOffset="0" yOffset="0"/>
    <component base="fraction" xScale="1" xyScale="0" yxScale="0" yScale="1" xOffset="188" yOffset="0"/>
    <component base="two.dnom" xScale="1" xyScale="0" yxScale="0" yScale="1" xOffset="238" yOffset="0"/>
  </outline>
</glyph>
```

But not its components!

# glif files (components)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="one.numr" format="2">
  <advance width="280"/>
  <unicode hex="B9"/>
  <outline>
    <contour>
      <point x="354.2691" y="567.1396" type="curve"/>
      <point x="354.2691" y="567.1396"/>
      <point x="211.16008" y="262.43958" type="line"/>
      <point x="210.53891" y="249.06003" type="curve"/>
      <point x="212.17918" y="244.51442"/>
      <point x="215.18637" y="241.21445"/>
      <point x="219.56044" y="239.16008" type="curve"/>
      <point x="223.9345" y="237.10568"/>
      <point x="228.39432" y="236.89862"/>
      <point x="232.93993" y="238.5389" type="curve"/>
      <point x="237.48553" y="240.17917"/>
      <point x="240.78552" y="243.18636"/>
      <point x="242.83992" y="247.56044" type="curve"/>
      <point x="242.83992" y="247.56044"/>
      <point x="385.9489" y="552.26044" type="line"/>
      <point x="386.57004" y="565.6399" type="curve"/>
      <point x="384.92978" y="570.1855"/>
      <point x="381.92264" y="573.48553"/>
      <point x="377.54858" y="575.5399" type="curve"/>
      <point x="373.1745" y="577.5943"/>
      <point x="368.71466" y="577.80133"/>
      <point x="364.16907" y="576.1611" type="curve"/>
      <point x="359.62344" y="574.5208"/>
      <point x="356.32346" y="571.5137"/>
    </contour>
  </outline>
</glyph>
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="fraction" format="2">
  <advance width="0"/>
  <unicode hex="2044"/>
  <outline>
    <contour>
      <point x="444.4048" y="443.80908" type="curve"/>
      <point x="444.4048" y="443.80908"/>
      <point x="-203.66722" y="-56.143932" type="line"/>
      <point x="-210.33412" y="-67.76069" type="curve"/>
      <point x="-210.95248" y="-72.55345"/>
      <point x="-209.7858" y="-76.86296"/>
      <point x="-206.83406" y="-80.68922" type="curve"/>
      <point x="-203.88231" y="-84.51546"/>
      <point x="-200.01004" y="-86.73776"/>
      <point x="-195.21727" y="-87.35613" type="curve"/>
      <point x="-190.42451" y="-87.9745"/>
      <point x="-186.11502" y="-86.80781"/>
      <point x="-182.28877" y="-83.856064" type="curve"/>
      <point x="-182.28877" y="-83.856064"/>
      <point x="465.7832" y="416.09692" type="line"/>
      <point x="472.4501" y="427.71368" type="curve"/>
      <point x="473.06848" y="432.5064"/>
      <point x="471.9018" y="436.81592"/>
      <point x="468.95007" y="440.6422" type="curve"/>
      <point x="465.99832" y="444.4684"/>
      <point x="462.12604" y="446.69073"/>
      <point x="457.33328" y="447.30914" type="curve"/>
      <point x="452.54053" y="447.92746"/>
      <point x="448.23102" y="446.76077"/>
    </contour>
  </outline>
</glyph>
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="two.dnom" format="2">
  <advance width="280"/>
  <unicode hex="2082"/>
  <outline>
    <contour>
      <point x="77.696686" y="80.37418" type="curve"/>
      <point x="77.696686" y="80.37418"/>
      <point x="57.896683" y="24.27459" type="line"/>
      <point x="58.611633" y="10.899765" type="curve"/>
      <point x="60.696632" y="6.540203"/>
      <point x="64.017624" y="3.5562425"/>
      <point x="68.574615" y="1.9478817" type="curve"/>
      <point x="73.1316" y="0.3395207"/>
      <point x="77.589874" y="0.5778377"/>
      <point x="81.94944" y="2.6628327" type="curve"/>
      <point x="86.309" y="4.7478275"/>
      <point x="89.29296" y="8.068819"/>
      <point x="90.90132" y="12.625809" type="curve"/>
      <point x="90.90132" y="12.625809"/>
      <point x="110.701324" y="68.72541" type="line"/>
      <point x="109.98637" y="82.10023" type="curve"/>
      <point x="107.90137" y="86.45979"/>
      <point x="104.580376" y="89.443756"/>
      <point x="100.02339" y="91.05212" type="curve"/>
      <point x="95.4664" y="92.66047"/>
      <point x="91.008125" y="92.42215"/>
      <point x="86.64856" y="90.33716" type="curve"/>
      <point x="82.289" y="88.25216"/>
      <point x="79.305046" y="84.93117"/>
    </contour>
    <contour>
      <point x="89.472855" y="9.560369" type="curve"/>
      <point x="90.1614" y="10.727887"/>
      <point x="91.26735" y="12.337994"/>
      <point x="92.79069" y="14.390688" type="curve"/>
      <point x="95.98033" y="18.688707"/>
      <point x="99.43871" y="22.617878"/>
      <point x="103.16584" y="26.1782" type="curve"/>
      <point x="108.15321" y="30.942366"/>
      <point x="113.216415" y="34.634724"/>
      <point x="118.35545" y="37.255272" type="curve"/>
      <point x="124.1857" y="40.22829"/>
      <point x="129.96954" y="41.7148"/>
      <point x="135.707" y="41.7148" type="curve"/>
      <point x="139.04698" y="41.7148"/>
      <point x="142.84436" y="41.038464"/>
      <point x="147.09912" y="39.68579" type="curve"/>
      <point x="152.00795" y="38.12518"/>
      <point x="156.42224" y="35.962646"/>
      <point x="160.34203" y="33.198196" type="curve"/>
      <point x="168.95668" y="27.122654"/>
      <point x="173.264" y="19.34956"/>
      <point x="173.264" y="9.87891" type="curve"/>
      <point x="173.264" y="0.19128895"/>
      <point x="169.8839" y="-10.818275"/>
      <point x="163.12366" y="-23.149784" type="curve"/>
      <point x="156.33662" y="-35.53019"/>
      <point x="145.94098" y="-49.55236"/>
      <point x="131.93675" y="-65.21631" type="curve"/>
      <point x="119.68873" y="-78.91592"/>
      <point x="103.541016" y="-95.07708"/>
      <point x="83.493614" y="-113.699814" type="curve"/>
      <point x="75.27174" y="-121.337395"/>
      <point x="65.608345" y="-130.12462"/>
      <point x="54.503414" y="-140.06148" type="curve"/>
      <point x="47.773624" y="-146.0834"/>
      <point x="37.35092" y="-155.33786"/>
      <point x="23.235302" y="-167.82484" type="curve"/>
      <point x="6.929533" y="-182.2493"/>
      <point x="-5.411129" y="-193.21507"/>
      <point x="-13.786686" y="-200.7222" type="curve"/>
      <point x="-27.87342" y="-213.34834"/>
      <point x="-40.585506" y="-224.93765"/>
      <point x="-51.92295" y="-235.49016" type="curve"/>
      <point x="-55.4603" y="-238.7826"/>
      <point x="-57.315567" y="-242.84349"/>
      <point x="-57.488747" y="-247.67288" type="curve"/>
      <point x="-57.661922" y="-252.50226"/>
      <point x="-56.102295" y="-256.68564"/>
      <point x="-52.80986" y="-260.223" type="curve"/>
      <point x="-50.644825" y="-262.54907"/>
      <point x="-48.0395" y="-264.1655"/>
      <point x="-44.993896" y="-265.07233" type="curve"/>
      <point x="-41.948296" y="-265.97916"/>
      <point x="-38.883102" y="-266.0511"/>
      <point x="-35.798313" y="-265.28812" type="curve"/>
      <point x="-34.695976" y="-265.01547"/>
      <point x="-32.375374" y="-264.3371"/>
      <point x="-28.83651" y="-263.25302" type="curve"/>
      <point x="-22.210117" y="-261.2231"/>
      <point x="-16.533146" y="-259.5616"/>
      <point x="-11.805588" y="-258.26852" type="curve"/>
      <point x="-3.417058" y="-255.97409"/>
      <point x="4.8496895" y="-253.98097"/>
      <point x="12.994656" y="-252.28918" type="curve"/>
      <point x="35.815475" y="-247.54907"/>
      <point x="57.455254" y="-245.17903"/>
      <point x="77.91399" y="-245.17905" type="curve"/>
      <point x="111.11778" y="-245.179"/>
      <point x="139.92584" y="-251.41414"/>
      <point x="164.33817" y="-263.88446" type="curve"/>
      <point x="168.64168" y="-266.0828"/>
      <point x="173.0922" y="-266.43765"/>
      <point x="177.68971" y="-264.94904" type="curve"/>
      <point x="182.2872" y="-263.46042"/>
      <point x="185.68512" y="-260.56436"/>
      <point x="187.88345" y="-256.26086" type="curve"/>
      <point x="190.08177" y="-251.95732"/>
      <point x="190.43663" y="-247.5068"/>
      <point x="188.94804" y="-242.9093" type="curve"/>
      <point x="187.45943" y="-238.31178"/>
      <point x="184.56337" y="-234.91388"/>
      <point x="180.25986" y="-232.71556" type="curve"/>
      <point x="150.84761" y="-217.69118"/>
      <point x="116.73232" y="-210.179"/>
      <point x="77.914" y="-210.17905" type="curve"/>
      <point x="55.057625" y="-210.17903"/>
      <point x="31.0452" y="-212.7929"/>
      <point x="5.876721" y="-218.02063" type="curve"/>
      <point x="-2.978949" y="-219.86003"/>
      <point x="-11.951061" y="-222.02269"/>
      <point x="-21.039616" y="-224.5086" type="curve"/>
      <point x="-26.107958" y="-225.89491"/>
      <point x="-32.12411" y="-227.65472"/>
      <point x="-39.08808" y="-229.78804" type="curve"/>
      <point x="-42.015385" y="-230.68478"/>
      <point x="-43.71992" y="-231.19273"/>
      <point x="-44.201687" y="-231.31189" type="curve"/>
      <point x="-44.201687" y="-231.31189"/>
      <point x="-40" y="-248.3" type="line"/>
      <point x="-28.076988" y="-261.10986" type="line"/>
      <point x="9.573948" y="-226.78522" type="curve"/>
      <point x="17.89291" y="-219.32881"/>
      <point x="30.176758" y="-208.41362"/>
      <point x="46.425495" y="-194.03963" type="curve"/>
      <point x="60.590614" y="-181.50885"/>
      <point x="71.062904" y="-172.21028"/>
      <point x="77.84236" y="-166.1439" type="curve"/>
      <point x="89.10976" y="-156.06166"/>
      <point x="98.93378" y="-147.128"/>
      <point x="107.314415" y="-139.34294" type="curve"/>
      <point x="128.15477" y="-119.98361"/>
      <point x="145.0597" y="-103.05066"/>
      <point x="158.02919" y="-88.54407" type="curve"/>
      <point x="173.81445" y="-70.888"/>
      <point x="185.74287" y="-54.69821"/>
      <point x="193.81442" y="-39.974697" type="curve"/>
      <point x="203.44748" y="-22.402802"/>
      <point x="208.264" y="-5.784934"/>
      <point x="208.264" y="9.87891" type="curve"/>
      <point x="208.264" y="21.190863"/>
      <point x="205.49364" y="31.569279"/>
      <point x="199.9529" y="41.01416" type="curve"/>
      <point x="195.23196" y="49.06159"/>
      <point x="188.75232" y="55.990368"/>
      <point x="180.51399" y="61.800507" type="curve"/>
      <point x="173.64961" y="66.64166"/>
      <point x="166.04605" y="70.3884"/>
      <point x="157.70331" y="73.04072" type="curve"/>
      <point x="149.99889" y="75.490105"/>
      <point x="142.6668" y="76.7148"/>
      <point x="135.707" y="76.7148" type="curve"/>
      <point x="124.36374" y="76.7148"/>
      <point x="113.27999" y="73.954994"/>
      <point x="102.455765" y="68.435394" type="curve"/>
      <point x="94.27123" y="64.261856"/>
      <point x="86.44929" y="58.612324"/>
      <point x="78.98992" y="51.4868" type="curve"/>
      <point x="73.826485" y="46.554455"/>
      <point x="69.05808" y="41.141735"/>
      <point x="64.684715" y="35.24865" type="curve"/>
      <point x="62.42657" y="32.20581"/>
      <point x="60.64005" y="29.569605"/>
      <point x="59.325153" y="27.34003" type="curve"/>
      <point x="56.870293" y="23.177502"/>
      <point x="56.246613" y="18.756638"/>
      <point x="57.45412" y="14.077436" type="curve"/>
      <point x="58.661625" y="9.398237"/>
      <point x="61.34664" y="5.831208"/>
      <point x="65.50917" y="3.3763494" type="curve"/>
      <point x="69.6717" y="0.92149043"/>
      <point x="74.09256" y="0.29781342"/>
      <point x="78.77175" y="1.5053182" type="curve"/>
      <point x="83.45096" y="2.7128232"/>
      <point x="87.018" y="5.3978395"/>
    </contour>
  </outline>
</glyph>
```

**Comment by justvanrossum** [comment]
For exaple here:
```xml
      <point x="354.2691" y="567.1396"/>
      <point x="211.16008" y="262.43958" type="line"/>
```
an off-curve is followed by a "line", which is not legal UFO.

See https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#outline:
"""
line | Draw a straight line from the previous point to this point. The previous point must be a move, a line, a curve or a qcurve. It must not be an offcurve.
"""

**Comment by ctrlcctrlv** [comment]
Oh. It's my bug then, sorry.

**Comment by ctrlcctrlv** [comment]
Fixed on my end in https://github.com/MFEK/glifparser.rlib/commit/46a75406d5fc5e89e68f2be0a94b097f4ca89f45 and https://github.com/MFEK/glifparser.rlib/commit/d9aa702df074094f1509f071e15e11cc696a4ca3. [Embarrassing myself here—missing an incredibly obvious UFO glif issue—was just the push I needed](https://twitter.com/fr_brennan/status/1480448555240374272) to write 700 lines of code over 24 hours, solving a longstanding todo list item to bring glifparser up to basic Rust development standards. :-)
