### ISSUE TITLE
VF: Base master not found

### ISSUE THREAD

**Issue by yanone** [fonttools/fonttools#2510]
I've run into this error, but I'm not sure where it originates from. A VF won't build because of `Base master not found`, traceback below.

The build in question is here: https://github.com/yanone/Arima-Font/blob/master/sources/builder.yaml using `gftools builder sources/builder.yaml`

The Glyphs 3 source has a VF Origin set to Thin, and a Thin instance exists, and it reflects in the auto-generated `.designspace` file as the `wght` axis’ `default` value:
```xml
  <axes>
    <axis tag="wght" name="Weight" minimum="100" maximum="700" default="100">
      <map input="100" output="30"/>
      <map input="200" output="45"/>
      <map input="300" output="65"/>
      <map input="400" output="90"/>
      <map input="500" output="103"/>
      <map input="600" output="135"/>
      <map input="700" output="160"/>
    </axis>
  </axes>
```

 So as far as I'm concerned, the data is complete (but I'm not the biggest VF expert).

I've had the `locations` printed after [this line](https://github.com/fonttools/fonttools/blob/036003e8500f5f0d887593f1b622f3687547212e/Lib/fontTools/varLib/models.py#L222), which yields once `[{}, {'wght': 1.0}]` and once `[{'wght': 1.0}]` which then triggers the error because of a missing `{}`. This is as far as I could analyze it, but now I need to ask for help. What is going on here?

Thank you.

The full traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fontmake/font_project.py", line 980, in run_from_designspace
    self._run_from_designspace_interpolatable(
  File "/usr/local/lib/python3.9/site-packages/fontmake/font_project.py", line 1063, in _run_from_designspace_interpolatable
    self.build_variable_font(
  File "/usr/local/lib/python3.9/site-packages/fontmake/font_project.py", line 338, in build_variable_font
    font = ufo2ft.compileVariableTTF(
  File "/usr/local/lib/python3.9/site-packages/ufo2ft/__init__.py", line 554, in compileVariableTTF
    varfont = varLib.build(
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/__init__.py", line 926, in build
    _merge_OTL(vf, model, master_fonts, axisTags)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/__init__.py", line 619, in _merge_OTL
    merger.mergeTables(font, master_fonts, ['GSUB', 'GDEF', 'GPOS'])
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 139, in mergeTables
    self.mergeThings(font[tag], [m[tag] if tag in m else None
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 1044, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 127, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 102, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 1044, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 127, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 102, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 1044, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 127, in mergeThings
    self.mergeObjects(out, lst)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 102, in mergeObjects
    mergerFunc(self, value, values)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 1044, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 129, in mergeThings
    self.mergeLists(out, lst)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 112, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 1044, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 125, in mergeThings
    mergerFunc(self, out, lst)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 833, in merge
    merger.mergeLists(self.SubTable, subtables)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 112, in mergeLists
    self.mergeThings(value, values)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 1044, in mergeThings
    super(VariationMerger, self).mergeThings(out, lst)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 125, in mergeThings
    mergerFunc(self, out, lst)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 653, in merge
    _MarkBasePosFormat1_merge(self, lst, merger)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 635, in _MarkBasePosFormat1_merge
    merger.mergeThings(anchor, allAnchors)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 1041, in mergeThings
    model, lst = masterModel.getSubModel(lst)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/models.py", line 239, in getSubModel
    subModel = VariationModel(subList(key, self.origLocations), self.axisOrder)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/models.py", line 223, in __init__
    keyFunc = self.getMasterLocationsSortKeyFunc(locations, axisOrder=self.axisOrder)
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/models.py", line 246, in getMasterLocationsSortKeyFunc
    raise VariationModelError("Base master not found.")
fontTools.varLib.errors.VariationModelError: Base master not found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yanone/Code/py/git/gftools/bin/gftools-builder.py", line 83, in <module>
    builder.build()
  File "/Users/yanone/Code/py/git/gftools/Lib/gftools/builder/__init__.py", line 183, in build
    self.build_variable()
  File "/Users/yanone/Code/py/git/gftools/Lib/gftools/builder/__init__.py", line 283, in build_variable
    output_files = self.run_fontmake(source, args)
  File "/Users/yanone/Code/py/git/gftools/Lib/gftools/builder/__init__.py", line 320, in run_fontmake
    FontProject().run_from_glyphs(source, **args)
  File "/usr/local/lib/python3.9/site-packages/fontmake/font_project.py", line 718, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fontmake/font_project.py", line 994, in run_from_designspace
    raise FontmakeError(
fontmake.errors.FontmakeError: In 'Arima.glyphs' -> 'master_ufo/Arima.designspace': Generating fonts from Designspace failed: Base master not found.
```

**Comment by yanone** [comment]
Yes, the Thin instance is at wght 30

**Comment by anthrotype** [comment]
and by "source", I mean a "master" -- designspace calles them "sources"

**Comment by yanone** [comment]
Sorry, and Thin master as well, yes

**Comment by anthrotype** [comment]
that's weird. Can you upload the designspace file that fontmake (glypshLib) generates from your .glyphs file?

**Comment by yanone** [comment]
```xml
<?xml version='1.0' encoding='UTF-8'?>
<designspace format="4.1">
  <axes>
    <axis tag="wght" name="Weight" minimum="100" maximum="700" default="100">
      <map input="100" output="30"/>
      <map input="200" output="45"/>
      <map input="300" output="65"/>
      <map input="400" output="90"/>
      <map input="500" output="103"/>
      <map input="600" output="135"/>
      <map input="700" output="160"/>
    </axis>
  </axes>
  <sources>
    <source filename="Arima-Thin.ufo" name="Arima Thin" familyname="Arima" stylename="Thin">
      <lib copy="1"/>
      <groups copy="1"/>
      <features copy="1"/>
      <info copy="1"/>
      <location>
        <dimension name="Weight" xvalue="30"/>
      </location>
    </source>
    <source filename="Arima-Bold.ufo" name="Arima Bold" familyname="Arima" stylename="Bold">
      <location>
        <dimension name="Weight" xvalue="160"/>
      </location>
    </source>
  </sources>
  <instances>
    <instance name="Arima Thin" familyname="Arima" stylename="Thin" filename="../instance_ufo/Arima-Thin.ufo" stylemapfamilyname="Arima Thin" stylemapstylename="regular">
      <location>
        <dimension name="Weight" xvalue="30"/>
      </location>
      <kerning/>
      <info/>
    </instance>
    <instance name="Arima ExtraLight" familyname="Arima" stylename="ExtraLight" filename="../instance_ufo/Arima-ExtraLight.ufo" stylemapfamilyname="Arima ExtraLight" stylemapstylename="regular">
      <location>
        <dimension name="Weight" xvalue="45"/>
      </location>
      <kerning/>
      <info/>
    </instance>
    <instance name="Arima Light" familyname="Arima" stylename="Light" filename="../instance_ufo/Arima-Light.ufo" stylemapfamilyname="Arima Light" stylemapstylename="regular">
      <location>
        <dimension name="Weight" xvalue="65"/>
      </location>
      <kerning/>
      <info/>
    </instance>
    <instance name="Arima Regular" familyname="Arima" stylename="Regular" filename="../instance_ufo/Arima-Regular.ufo" stylemapfamilyname="Arima" stylemapstylename="regular">
      <location>
        <dimension name="Weight" xvalue="90"/>
      </location>
      <kerning/>
      <info/>
    </instance>
    <instance name="Arima Medium" familyname="Arima" stylename="Medium" filename="../instance_ufo/Arima-Medium.ufo" stylemapfamilyname="Arima Medium" stylemapstylename="regular">
      <location>
        <dimension name="Weight" xvalue="103"/>
      </location>
      <kerning/>
      <info/>
    </instance>
    <instance name="Arima SemiBold" familyname="Arima" stylename="SemiBold" filename="../instance_ufo/Arima-SemiBold.ufo" stylemapfamilyname="Arima SemiBold" stylemapstylename="regular">
      <location>
        <dimension name="Weight" xvalue="135"/>
      </location>
      <kerning/>
      <info/>
    </instance>
    <instance name="Arima Bold" familyname="Arima" stylename="Bold" filename="../instance_ufo/Arima-Bold.ufo" stylemapfamilyname="Arima" stylemapstylename="bold">
      <location>
        <dimension name="Weight" xvalue="160"/>
      </location>
      <kerning/>
      <info/>
    </instance>
  </instances>
  <lib>
    <dict>
      <key>GSDimensionPlugin.Dimensions</key>
      <dict>
        <key>60CFBDE8-BC08-4808-BF41-F011F3E03A54</key>
        <dict>
          <key>nd</key>
          <integer>26</integer>
        </dict>
        <key>EBFFFCD3-BAE4-48A5-9442-B72A90AD34A8</key>
        <dict>
          <key>nV</key>
          <integer>146</integer>
          <key>nd</key>
          <integer>48</integer>
          <key>oV</key>
          <integer>150</integer>
        </dict>
      </dict>
      <key>public.skipExportGlyphs</key>
      <array>
        <string>doublesign-malayalam</string>
        <string>va-malyalam.belowalt</string>
      </array>
    </dict>
  </lib>
</designspace>
```

**Comment by anthrotype** [comment]
If i look at the traceback, I see it fails when merging `MarkBasePosFormat1`. Maybe your masters contain different anchors? They should all match those of the base master.

**Comment by yanone** [comment]
Oh. That's not impossible. I need time to analyze this and will report back.

**Comment by yanone** [comment]
Anchors are compatible (relying on Glyphs’ own incompatibility reporting here). Anything else I could check for?

**Comment by yanone** [comment]
I just tried, to no avail.

Please note that I said that I checked the compatibility in Glyphs.app, which reports any anchor incompatibilities. I confirmed both tools by manipulating a glyph’s anchors, and now both Glyphs.app reports it as well as fontmake: `fontmake: Error: In 'sources/Arima.glyphs' -> 'master_ufo/Arima.designspace': Compatibility check failed`

Anyways, in the fontmake help, it says: `--check-compatibility
                        Check if the source files are interpolatable. It is disabled by default, but enabled when building variable fonts or
                        what the 'Enforce Compatibility Check' custom parameter is set on a Glyphs file` so it should be enabled by default.
                        
I'm starting to feel confident about ruling out an anchor incompatibility.

**Comment by anthrotype** [comment]
right, it's enabled by default.

Maybe it could be GDEF classes (whether a glyph should be treated as base or mark) that differ across masters, leading ufo2ft markFeatureWriter to generate GPOS tables that are incompatible and can't be merged in a VF. Those are usually generated by glyphsLib automatically based on the glyph names and the GlyphData.xml database, but category/subCategory can be overridden at a single glyph level -- I'm speculating some masters do that while other don't?

**Comment by yanone** [comment]
You can't edit such things in just one master in Glyphs.app. Any definition change will reflect across all UFO masters. I confirmed by diffing the two auto-generated `features.fea` files for GDEF inconsistencies, and only found caret positions to differ between masters, which is expected.

So that's also a no unfortunately.

**Comment by yanone** [comment]
Simon suggested I try with DEBUG verbosity, so I wanted to post the results here. These are the last couple of lines just before the error happens:

```
INFO:ufo2ft:Building variable TTF font
INFO:fontTools.varLib:Axes:
[{'default': 100.0,
  'hidden': False,
  'labelNames': {'en': 'Weight'},
  'map': [(100.0, 30.0),
          (200.0, 45.0),
          (300.0, 65.0),
          (400.0, 90.0),
          (500.0, 103.0),
          (600.0, 135.0),
          (700.0, 160.0)],
  'maximum': 700.0,
  'minimum': 100.0,
  'name': 'Weight',
  'tag': 'wght'}]
INFO:fontTools.varLib:Internal master locations:
[{'Weight': 30.0}, {'Weight': 160.0}]
INFO:fontTools.varLib:Internal axis supports:
{'Weight': [30.0, 30.0, 160.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'Weight': 0.0}, {'Weight': 1.0}]
INFO:fontTools.varLib:Index of base master: 0
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading master fonts
INFO:fontTools.varLib:Generating fvar
INFO:fontTools.varLib:Generating avar
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating MVAR
INFO:fontTools.varLib:  cpht: OS/2.sCapHeight   [688, 698]
INFO:fontTools.varLib:  xhgt: OS/2.sxHeight     [500, 520]
INFO:fontTools.varLib:  stro: OS/2.yStrikeoutPosition   [300, 312]
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
```

What stands out for me is `INFO:fontTools.varLib:Index of base master: 0`, which contradicts the error message that no base master was found. But then again, Cosimo suggested other compatibility issues, so I don't know...

Simon said he would take a look tomorrow.

**Comment by simoncozens** [comment]
I just saw this:

```
  File "/usr/local/lib/python3.9/site-packages/fontTools/varLib/merger.py", line 635, in _MarkBasePosFormat1_merge
    merger.mergeThings(anchor, allAnchors)
```

There's an anchor missing.

**Comment by anthrotype** [comment]
> There's an anchor missing.

that was my guess too, but how come the fontmake compatibility checker doesn't catch it early on?

**Comment by yanone** [comment]
Okay, so I found a bunch of inactive layers (unused drafts) with anchor inconsistencies. Glyphs doesn't report them as incompatible because they aren't used to interpolate the glyphs. Anyway, I added the missing anchors hoping that that would fix the problem, but it didn't. Now I can't find any more glyphs with missing anchors at all.

This is the Glyphs script I used to find them. Please review its logic and find a mistake in it for my sanity’s sake ;)

```python
anchors = {}
for glyph in font.glyphs:
	for layer in glyph.layers:
		anchorNames = [a.name for a in layer.anchors]
		# Add first set to dict
		if not glyph.name in anchors:
			anchors[glyph.name] = anchorNames
		# Compare new set with dict
		else:
			if set(anchors[glyph.name]) != set(anchorNames):
				print(glyph.name)
print("done")
```

Now it prints nothing where it previously found glyphs with inconsistent anchors.

**Comment by yanone** [comment]
And by the way, I just ran the same script on the font object in `glyphsLib`, so I can rule out a file parsing error.

**Comment by simoncozens** [comment]
It's ufo2ft being "clever".

There's a part of ufo2ft's MarkFeatureWriter which *guesses* whether an anchor belongs to an abvm or a blwm feature. But it doesn't think about variable fonts when it does this guessing. It does it on a master-by-master basis. What's happening here is that although the anchors are source compatible, there's an anchor which, by means of this guessing process, is ending up in the abvm feature of one master and the blwm of another.

The partial solution is to improve the guessing algorithm. The correct solution, as I will rant at length to anyone who will listen, is to give up on the whole build-multiple-fonts-and-merge-them approach and build fonts variable-first.

**Comment by simoncozens** [comment]
Just raise the imatra anchor of ssa-tamil by 10 units in the thin. Then the font will compile without error. ;-)

**Comment by yanone** [comment]
Are you kidding me? How did you even find that?

Okay, that worked, many thanks. Shall I open an issue over at ufo2ft or is this on you guy'ses radar already? Fixing the toolchain here is beyond me, honestly. I need to leave this one to the adults.

**Comment by anthrotype** [comment]
I think we mutuated that logic from Glyphs.app FWIW

```
        # anchors with unknown names whose Y coordinate is greater or equal to
        # the line that cuts the UPEM square in half will be treated as "above
        # base" marks, those that fall below the threshold as "below base".
```

https://github.com/googlefonts/ufo2ft/blob/32fa83c379402c8ac97f34a47f2d13edf11f87ab/Lib/ufo2ft/featureWriters/markFeatureWriter.py#L739-L743

is anchor named "imatra" _always_ meant to be considered abvm or blwm? If we know that in advance, we can add it to the hard-coded known lists of abvm/blwm anchor names, here:
https://github.com/googlefonts/ufo2ft/blob/32fa83c379402c8ac97f34a47f2d13edf11f87ab/Lib/ufo2ft/featureWriters/markFeatureWriter.py#L281-L285

**Comment by simoncozens** [comment]
imatras are always above, yeah.

But in a way the distinction between abvm and blwm is arbitrary, for the font engineer's organisational convenience when writing manual feature code. They're just mark positioning features and both will always be applied at the same time. If the whole point is to generate automated feature code so the engineer doesn't need to think about it, just shove *every* mark-to-base into one or the other. Then this kind of stupidity goes away.

**Comment by anthrotype** [comment]
The original rationale was to match Glyphs.app, but i'd be ok to put all unknown anchors to abvm. Can you send a PR?

**Comment by yanone** [comment]
Simon merged his fix, so I'm closing this issue. Thanks everyone
