### ISSUE TITLE
Some fonts' NameRecord can't be decoded correctly, and also can't be subsetted correctly

### ISSUE THREAD

**Issue by DYY-Studio** [fonttools/fonttools#2524]
I found some old fonts' name tables' record can't be decode correctly, maybe this also lead to the error that they can't be subsetted correctly
These fonts' subsetted fonts can't be recognized by Windows 10. And when I dumped their ttx, I found Glyph table is lost, only **".notdef"** remaining.

I try my best to understand what textcoding they use. I mark them below the fonts' name.

**This is the list of error decoding and error subsetting fonts:**
### "微软简XX" Family
Such as
1. 微软简标宋
2. 微软简粗黑
3. 微软简仿宋

Code

    >>> t = ttLib.TTFont(r'C:\Users\yyfll\AppData\Local\Microsoft\Windows\Fonts\微软简标宋.TTF')
    >>> t['name'].names[9].toStr()
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "C:\Users\yyfll\AppData\Local\Programs\Python\Python39\lib\site-packages\fontTools\ttLib\tables\_n_a_m_e.py", line 458, in toUnicode
        string = tostr(string, encoding=encoding, errors=errors)
    File "C:\Users\yyfll\AppData\Local\Programs\Python\Python39\lib\site-packages\fontTools\misc\textTools.py", line 124, in tostr
        return s.decode(encoding, errors)
    UnicodeDecodeError: 'gb2312' codec can't decode byte 0xce in position 1: illegal multibyte sequence

They are GB-2312/GBK Textcoding, but with '\x00' ASCII char between two bytes

    t['name'].names[9].toBytes()
    b'\x00\xce\x00\xa2\x00\xc8\x00\xed\x00\xbc\x00\xf2\x00\xb1\x00\xea\x00\xcb\x00\xce'
    '微软简标宋'.encode('gbk')
    b'\xce\xa2\xc8\xed\xbc\xf2\xb1\xea\xcb\xce'

**SUBSET ERROR**

### "微软繁XX" Family
Such as
1. 微软繁宋体
2. 微软繁细圆
3. 微软繁粗圆

Like the first one, GB-2312/GBK Textcoding, but also have '\x00' between two bytes.

**SUBSET ERROR**

***not only Simplified Chinese fonts, but also Tranditional Chinese fonts and some Japanese fonts***

### 麗流隷書
UTF-16-BE Encoding, but maybe didn't note that it was Unicode

    t = ttLib.TTFont(r'C:\Users\yyfll\AppData\Local\Microsoft\Windows\Fonts\麗流隷書.TTF')
    >>> t['name'].names[9].toStr()
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "C:\Users\yyfll\AppData\Local\Programs\Python\Python39\lib\site-packages\fontTools\ttLib\tables\_n_a_m_e.py", line 458, in toUnicode
        string = tostr(string, encoding=encoding, errors=errors)
    File "C:\Users\yyfll\AppData\Local\Programs\Python\Python39\lib\site-packages\fontTools\misc\textTools.py", line 124, in tostr
        return s.decode(encoding, errors)
    UnicodeDecodeError: 'shift_jis' codec can't decode byte 0xf8 in position 7: illegal multibyte sequence
    >>> t['name'].names[9].toBytes().decode('utf-16-be')
    '麗流隷書'

**SUBSET ERROR**

### DFLiKaiShu-Md / 華康儷楷書 / DFPLiKaiShu-Md / 華康儷楷書(P)
`\x00`
### 華康海報體W12 / 華康海報體W12(P)
`\x00`
### 文鼎中特廣告體
A strange font, only PlatformID=3; LanguageID=1028 name table. BIG5 Textcoding.
Windows 10 20H1 also can't read the name table, but it is also like the first one, with a `\x00` between 2 bytes

    >>> t['name'].names[4].toBytes()
    b'\x00\xa4\x00\xe5\x00\xb9\x00\xa9\x00\xa4\x00\xa4\x00\xaf\x00S\x00\xbc\x00s\x00\xa7\x00i\x00\xc5\x00\xe9'
    >>> '文鼎中特廣告體'.encode('big5')
    b'\xa4\xe5\xb9\xa9\xa4\xa4\xafS\xbcs\xa7i\xc5\xe9'
### Maybe more.

They are really old fonts. My python technique is too poor to fix these problem by myself.

**Comment by JeremieBergeron** [comment]
Here is an actual that can't be decoded: https://mega.nz/file/S9ERDRpQ#bcPhS06kv-D5jt64aTNDbZVd6gZr6ZfJDYT91yYsoWk

**Comment by moi15moi** [comment]
Here is an example with an actual font: https://mega.nz/file/S9ERDRpQ#bcPhS06kv-D5jt64aTNDbZVd6gZr6ZfJDYT91yYsoWk

If I try to get the encoding of the fontName, I get "mac_roman" when I should get "shift-jis"

If I print the names of the font, I have this:
`[<NameRecord NameID=0; PlatformID=1; LanguageID=11>, <NameRecord NameID=1; PlatformID=1; LanguageID=11>, <NameRecord NameID=2; PlatformID=1; LanguageID=11>, <NameRecord NameID=3; PlatformID=1; LanguageID=11>, <NameRecord NameID=4; PlatformID=1; LanguageID=11>, <NameRecord NameID=5; PlatformID=1; LanguageID=11>, <NameRecord NameID=6; PlatformID=1; LanguageID=11>, <NameRecord NameID=0; PlatformID=3; LanguageID=1041>, <NameRecord NameID=1; PlatformID=3; LanguageID=1041>, <NameRecord NameID=2; PlatformID=3; LanguageID=1041>, <NameRecord NameID=3; PlatformID=3; LanguageID=1041>, <NameRecord NameID=4; PlatformID=3; LanguageID=1041>, <NameRecord NameID=5; PlatformID=3; LanguageID=1041>, <NameRecord NameID=6; PlatformID=3; LanguageID=1041>]`

I think the PlatformID=1 return "mac_roman" but the PlatformID=3 would return "shift-jis".
https://docs.microsoft.com/en-us/typography/opentype/spec/name#platform-encoding-and-language-ids
