### ISSUE TITLE
An exception occurred during the decompilation of the 'OS/2' table

### ISSUE THREAD

**Issue by moi15moi** [fonttools/fonttools#2583]
When I try to get some attributes of the OS/2 table with [Mona.ttf](https://mega.nz/file/q581CajS#smGeGWQdTpTMUFguHxGG1dTD4AD_EOgqVBkMZnu2vQE), I got this error

```
An exception occurred during the decompilation of the 'OS/2' table
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\fonttools-4.29.1-py3.8.egg\fontTools\ttLib\ttFont.py", line 409, in _readTable
    table.decompile(data, self)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\fonttools-4.29.1-py3.8.egg\fontTools\ttLib\tables\O_S_2f_2.py", line 113, in decompile
    dummy, data = sstruct.unpack2(OS2_format_2_addition, data, self)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\fonttools-4.29.1-py3.8.egg\fontTools\misc\sstruct.py", line 103, in unpack2
    return unpack(fmt, data[:length], obj), data[length:]
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\fonttools-4.29.1-py3.8.egg\fontTools\misc\sstruct.py", line 86, in unpack
    elements = struct.unpack(formatstring, data)
struct.error: unpack requires a buffer of 18 bytes
```

Here is an sample code:
```
    font = ttLib.TTFont("Mona.ttf", fontNumber=0, ignoreDecompileErrors=True)

    isItalic = font["OS/2"].fsSelection & 0b1 > 0
    weight = font['OS/2'].usWeightClass
```

**Comment by justvanrossum** [comment]
According to ots, that font is broken in more than one way:
```
$ python -m ots /Users/just/Downloads/Mona.ttf 
WARNING: OS/2: Bad version number, setting it to 1: 2
ERROR: hmtx: Failed to read side bearing 7225
ERROR: hmtx: Failed to parse table
Failed to sanitize file!
```

**Comment by justvanrossum** [comment]
According to ttx, that font is broken in several ways, too:
```
$ ttx /Users/just/Downloads/Mona.ttf 
Dumping "/Users/just/Downloads/Mona.ttf" to "/Users/just/Downloads/Mona.ttx"...
Dumping 'GlyphOrder' table...
WARNING: 'created' timestamp seems very low; regarding as unix timestamp
WARNING: 'modified' timestamp seems very low; regarding as unix timestamp
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
ERROR: An exception occurred during the decompilation of the 'OS/2' table
Traceback (most recent call last):
  File "/Users/just/code/git/fontra/venv/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 417, in _readTable
    table.decompile(data, self)
  File "/Users/just/code/git/fontra/venv/lib/python3.10/site-packages/fontTools/ttLib/tables/O_S_2f_2.py", line 113, in decompile
    dummy, data = sstruct.unpack2(OS2_format_2_addition, data, self)
  File "/Users/just/code/git/fontra/venv/lib/python3.10/site-packages/fontTools/misc/sstruct.py", line 103, in unpack2
    return unpack(fmt, data[:length], obj), data[length:]
  File "/Users/just/code/git/fontra/venv/lib/python3.10/site-packages/fontTools/misc/sstruct.py", line 86, in unpack
    elements = struct.unpack(formatstring, data)
struct.error: unpack requires a buffer of 18 bytes
Dumping 'OS/2' table...
ERROR: An exception occurred during the decompilation of the 'hmtx' table
Traceback (most recent call last):
  File "/Users/just/code/git/fontra/venv/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 417, in _readTable
    table.decompile(data, self)
  File "/Users/just/code/git/fontra/venv/lib/python3.10/site-packages/fontTools/ttLib/tables/_h_m_t_x.py", line 51, in decompile
    glyphName = glyphOrder[i]
IndexError: list index out of range
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'fpgm' table...
Dumping 'cvt ' table...
WARNING: corrupt 'loca' table, or wrong numGlyphs in 'maxp': 7225 7226
Dumping 'loca' table...
WARNING: 6967 glyphs have no name
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'gasp' table...
ERROR: An exception occurred during the decompilation of the 'EBLC' table
Traceback (most recent call last):
  File "/Users/just/code/git/fontra/venv/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 417, in _readTable
    table.decompile(data, self)
  File "/Users/just/code/git/fontra/venv/lib/python3.10/site-packages/fontTools/ttLib/tables/E_B_L_C_.py", line 116, in decompile
    indexSubTable.decompile() # https://github.com/fonttools/fonttools/issues/317
  File "/Users/just/code/git/fontra/venv/lib/python3.10/site-packages/fontTools/ttLib/tables/E_B_L_C_.py", line 438, in decompile
    offsetArray = [struct.unpack(dataFormat, self.data[slice(*loc)])[0] for loc in indexingLocations]
  File "/Users/just/code/git/fontra/venv/lib/python3.10/site-packages/fontTools/ttLib/tables/E_B_L_C_.py", line 438, in <listcomp>
    offsetArray = [struct.unpack(dataFormat, self.data[slice(*loc)])[0] for loc in indexingLocations]
struct.error: unpack requires a buffer of 4 bytes
ERROR: An exception occurred during the decompilation of the 'EBDT' table
Traceback (most recent call last):
  File "/Users/just/code/git/fontra/venv/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 417, in _readTable
    table.decompile(data, self)
  File "/Users/just/code/git/fontra/venv/lib/python3.10/site-packages/fontTools/ttLib/tables/E_B_D_T_.py", line 52, in decompile
    for curStrike in locator.strikes:
AttributeError: 'DefaultTable' object has no attribute 'strikes'
Dumping 'EBDT' table...
Dumping 'EBLC' table...
```

**Comment by moi15moi** [comment]
Yes, the font is broken.

It would be nice if I write something like that to not have the log print like I show in my first message:
```
try:
    font = ttLib.TTFont("Mona.ttf", fontNumber=0, ignoreDecompileErrors=True)
    isItalic = font["OS/2"].fsSelection & 0b1 > 0
    weight = font['OS/2'].usWeightClass
except:
    # Do XYZ
```

**Comment by justvanrossum** [comment]
I'm afraid I don't understand what you are asking for.

**Comment by moi15moi** [comment]
**What I want**
Don't print the exception when it is surrounded by an try except.

**Example** where it would only print: _Warning: The file "XXX.YYY" does not have an OS/2 table. Default style will be applied to the font_)
```
try:
    font = ttLib.TTFont("Mona.ttf", fontNumber=0, ignoreDecompileErrors=True)
    isItalic = font["OS/2"].fsSelection & 0b1 > 0
    weight = font['OS/2'].usWeightClass
except:
        print(f"Warning: The file \"{fontPath}\" does not have an OS/2 table. Default style will be applied to the font.")
```

**Comment by justvanrossum** [comment]
Something like this, perhaps?

```python
from fontTools.ttLib import TTFont


fontPath = "Mona.ttf"

font = TTFont(fontPath, fontNumber=0)
try:
    os2 = font["OS/2"]
except Exception as e:
    print(repr(e))
    print(f"Warning: The file \"{fontPath}\" does not have an OS/2 table. Default style will be applied to the font.")
else:
    isItalic = os2.fsSelection & 0b1 > 0
    weight = os2.usWeightClass
```

**Comment by moi15moi** [comment]
The exception is only print when I try to access to attributes of `font["OS/2"]`

So, there is no exception when you write: `os2 = font["OS/2"]

Even something like this will still print the exception
```
    try:
        os2 = font["OS/2"]
        os2.fsSelection & 0b1 > 0
    except:
        isItalic = False
        weight = 400
        print(Fore.LIGHTRED_EX + f"Warning: The file \"{fontPath}\" does not have an OS/2 table. This can lead to minor errors." + Fore.WHITE)
    else:
        isItalic = os2.fsSelection & 0b1 > 0
        weight = os2.usWeightClass
```

**Comment by moi15moi** [comment]
Oh, I just understand.

I had this before: _font = ttLib.TTFont("Mona.ttf", fontNumber=0, ignoreDecompileErrors=True)_

If I remove the ignoreDecompileErrors, it work. I have no idea why because I thought it will ignore it when it was true, but it seems to do something else.

```python
    font = TTFont(fontPath, fontNumber=0)
    try:
        isItalic = font["OS/2"].fsSelection & 0b1 > 0

        weight = font['OS/2'].usWeightClass
    except:
        print(Fore.LIGHTRED_EX + f"Warning: The file \"{fontPath}\" does not have an OS/2 table. This can lead to minor errors." + Fore.WHITE)
```
