### ISSUE TITLE
'prune_post_subset' does not work for when 'self.Value' is an list of None's

### ISSUE THREAD

**Issue by Ristellise** [fonttools/fonttools#2602]
Hi! As mentioned in the title, when a `self.Value` is a list of `None`'s, the check for `if self.Value is None` returns `false`.

```py
@_add_method(otTables.SinglePos)
def prune_post_subset(self, font, options):
	if self.Value is None: # <-------------- Here.
		assert self.ValueFormat == 0
		return True

	# Shrink ValueFormat
	if self.Format == 1:
		if not options.hinting:
			self.Value.prune_hints()
		self.ValueFormat = self.Value.getEffectiveFormat()
	elif self.Format == 2:
		if not options.hinting:
			for v in self.Value:
				v.prune_hints()
		print(self.Value)
		self.ValueFormat = reduce(int.__or__, [v.getEffectiveFormat() for v in self.Value], 0)

	# Downgrade to Format 1 if all ValueRecords are the same
	if self.Format == 2 and all(v == self.Value[0] for v in self.Value):
		self.Format = 1
		self.Value = self.Value[0] if self.ValueFormat != 0 else None
		del self.ValueCount

	return True
```

The solution would be to replace the line with:
```py
	if self.Value is None or all(v is None for v in self.Value):
```
however, I'm not too sure what other parts will be affected.

The following catbox link is a font that exhibits this issue. I haven't extracted the ttx out of it yet.  
https://files.catbox.moe/audwuu.otf

to generate the ttx file, I used the following command:
```
pyftsubset audwuu.otf --output-file=encode --unicodes=0000-00FF,0370-04FF,2000-206F,20A0-20CF,2122-2122,3000-303F,203D-2044,2018-201F
```

**Comment by anthrotype** [comment]
SinglePos `Value` attribute can be either a single `ValueRecord` object (format 1) or a list of `ValueRecord`s (format 2), or `None` if ValueFormat == 0. I don't think it can ever be a list of `None` values..

**Comment by anthrotype** [comment]
hm, I think I managed to reproduce with the font above and command you provided. I'll take a look, thanks

```
$ fonttools subset --output-file=/tmp/audwuu.subset.otf --unicodes="0000-00FF,0370-04FF,2000-206F,20A0-20CF,2122-2122,3000-303F,203D-2044,2018-201F" /Users/clupo/Downloads/audwuu.otf
Traceback (most recent call last):
  File "/Users/clupo/Github/fonttools/.venv/bin/fonttools", line 33, in <module>
    sys.exit(load_entry_point('fonttools', 'console_scripts', 'fonttools')())
  File "/Users/clupo/Github/fonttools/Lib/fontTools/__main__.py", line 30, in main
    runpy.run_module(mod, run_name='__main__')
  File "/Users/clupo/.pyenv/versions/3.10.2/lib/python3.10/runpy.py", line 212, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/Users/clupo/.pyenv/versions/3.10.2/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/subset/__main__.py", line 6, in <module>
    sys.exit(main())
  File "/Users/clupo/Github/fonttools/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/subset/__init__.py", line 3205, in main
    subsetter.subset(font)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/subset/__init__.py", line 3009, in subset
    self._prune_post_subset(font)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/subset/__init__.py", line 2992, in _prune_post_subset
    retain = table.prune_post_subset(font, self.options)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/subset/__init__.py", line 1746, in prune_post_subset
    table.LookupList.prune_post_subset(font, options)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/subset/__init__.py", line 1339, in prune_post_subset
    if l.prune_post_subset(font, options): ret = True
  File "/Users/clupo/Github/fonttools/Lib/fontTools/subset/__init__.py", line 1313, in prune_post_subset
    if st.prune_post_subset(font, options): ret = True
  File "/Users/clupo/Github/fonttools/Lib/fontTools/subset/__init__.py", line 642, in prune_post_subset
    self.ValueFormat = reduce(int.__or__, [v.getEffectiveFormat() for v in self.Value], 0)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/subset/__init__.py", line 642, in <listcomp>
    self.ValueFormat = reduce(int.__or__, [v.getEffectiveFormat() for v in self.Value], 0)
AttributeError: 'NoneType' object has no attribute 'getEffectiveFormat'
```

**Comment by anthrotype** [comment]
Fixed by #2603

**Comment by Ristellise** [comment]
Fast! Thanks for the fixes.

**Comment by anthrotype** [comment]
out of curiousity, do you happen to know how the font was generated (e.g. which font editor or font compiler)? It's the firt time I see a SinglePosFormat2 with ValueFormat=0, usually the format 2 is to  apply different positioning values to a bunch of glyphs (as opposed to format1 that applies the same positioning to all of them, in this case no positioning).
