### ISSUE TITLE
[ttLib.DSIG] Error when DSIG XML dump is split at XML parse buffer size

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#2614]
When compiling the attached TTX file to TTF, it crashes like this:

```
$ ttx -f roundtrip.ttx
Compiling "roundtrip.ttx" to "roundtrip.ttf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'hmtx' table...
Parsing 'cmap' table...
Parsing 'loca' table...
Parsing 'glyf' table...
Parsing 'name' table...
Parsing 'post' table...
Parsing 'DMMY' table...
Parsing 'DSIG' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/Users/just/code/git/fonttools_just/Lib/fontTools/ttx.py", line 405, in main
    process(jobs, options)
  File "/Users/just/code/git/fonttools_just/Lib/fontTools/ttx.py", line 387, in process
    action(input, output, options)
  File "/Users/just/code/git/fonttools_just/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/just/code/git/fonttools_just/Lib/fontTools/ttx.py", line 298, in ttCompile
    ttf.importXML(input)
  File "/Users/just/code/git/fonttools_just/Lib/fontTools/ttLib/ttFont.py", line 348, in importXML
    reader.read()
  File "/Users/just/code/git/fonttools_just/Lib/fontTools/misc/xmlReader.py", line 47, in read
    self._parseFile(self.file)
  File "/Users/just/code/git/fonttools_just/Lib/fontTools/misc/xmlReader.py", line 72, in _parseFile
    parser.Parse(chunk, 0)
  File "/Users/sysadmin/build/v3.7.6/Modules/pyexpat.c", line 471, in EndElement
  File "/Users/just/code/git/fonttools_just/Lib/fontTools/misc/xmlReader.py", line 155, in _endElementHandler
    self.currentTable.fromXML(name, attrs, content, self.ttFont)
  File "/Users/just/code/git/fonttools_just/Lib/fontTools/ttLib/tables/D_S_I_G_.py", line 96, in fromXML
    sigrec.fromXML(name, attrs, content, ttFont)
  File "/Users/just/code/git/fonttools_just/Lib/fontTools/ttLib/tables/D_S_I_G_.py", line 129, in fromXML
    self.pkcs7 = base64.b64decode(tobytes(strjoin(filter(pem_spam, content))))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

The reason is that the `SignatureRecord.fromXML` methods gets a fragmented XML `content` list, which causes the "pem_spam" not be be filtered correctly, which in turn causes non-base64 data to be fed to the base64 decoder.

https://github.com/fonttools/fonttools/blob/42e4d66184be1acda05bed1896da6d61c084835e/Lib/fontTools/ttLib/tables/D_S_I_G_.py#L125-L129

This happened in a real font that I can't share, but I managed to construct one that reproduces it. The DMMY table has just the right size to cause the `-----BEGIN PKCS7-----` string to be split in two in the `content` list, causing the filter failure mentioned above.

[roundtrip.ttx.zip](https://github.com/fonttools/fonttools/files/8643451/roundtrip.ttx.zip)

**Comment by justvanrossum** [comment]
Fixing this in the DSIG implementation is trivial, but I wonder whether it should be fixed in xmlReader instead, say around here:

https://github.com/fonttools/fonttools/blob/42e4d66184be1acda05bed1896da6d61c084835e/Lib/fontTools/misc/xmlReader.py#L153-L156

**Comment by anthrotype** [comment]
> The reason is that the SignatureRecord.fromXML methods gets a fragmented XML content list

but why does `content` list of strings get split like that? is it the way we use expat to parse the file in chunks that we get unlucky in this case?

Yes, probably it'd be better to fix it in the xmlReader, by joining all the strings in an element's `content` that are not separated by a newline

**Comment by jmsole** [comment]
Hi @anthrotype,

I just hit this issue while running fontbakery in a set of fonts. During check `com.google.fonts/check/ttx_roundtrip`, fontbakery completely stoped working.

Looking into why this happened, I narrowed it down to a file that fails when going from `.ttx` to `.otf`, with the same error Just mentioned in the OP. When I remove the `DSIG` table from the dump and then finish the roundtrip, it all works fine.

So I guess this can definitely happen randomly in the wild. I am wondering if it can also happen when other tables are at the end of the file, not just with `DSIG`?

Cheers!

**Comment by anthrotype** [comment]
cc @justvanrossum

**Comment by anthrotype** [comment]
cool, will make a PR after lunch

**Comment by jmsole** [comment]
@anthrotype I tried your patch locally and that indeed fixes the issue, so now fontbakery completes all the checks. Thanks for looking into this!
