### ISSUE TITLE
AttributeError when uharfbuzz can be imported but version <= 0.23

### ISSUE THREAD

**Issue by koeberlin** [fonttools/fonttools#2671]
Hi,
I tried to run a script that always worked fine for me, but now it throws an error:

```
condSubst = [
    ([{"SS01": (0.01, 1.0)}], {"a": "a.ss01"}),
]
addFeatureVariations(font, condSubst)
```

results in 

```
Traceback (most recent call last):
  File "/Users/koeberlin/Library/Python/3.7/lib/python/site-packages/fontTools/ttLib/tables/otBase.py", line 111, in compile
    return writer.getAllDataUsingHarfbuzz()
  File "/Users/koeberlin/Library/Python/3.7/lib/python/site-packages/fontTools/ttLib/tables/otBase.py", line 555, in getAllDataUsingHarfbuzz
    return hb.repack(data, obj_list)
AttributeError: module 'uharfbuzz' has no attribute 'repack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/koeberlin/Jobs/_eigene Fonts/Pangea Custom/Lonely Planet/otvar/Pangea_makeFeatureVariations 2.py", line 20, in <module>
    f.save(newFontPath)
  File "/Users/koeberlin/Library/Python/3.7/lib/python/site-packages/fontTools/ttLib/ttFont.py", line 184, in save
    writer_reordersTables = self._save(tmp)
  File "/Users/koeberlin/Library/Python/3.7/lib/python/site-packages/fontTools/ttLib/ttFont.py", line 224, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/Users/koeberlin/Library/Python/3.7/lib/python/site-packages/fontTools/ttLib/ttFont.py", line 647, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/koeberlin/Library/Python/3.7/lib/python/site-packages/fontTools/ttLib/ttFont.py", line 669, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/koeberlin/Library/Python/3.7/lib/python/site-packages/fontTools/ttLib/tables/otBase.py", line 112, in compile
    except (ValueError, MemoryError, hb.RepackerError) as e:
AttributeError: module 'uharfbuzz' has no attribute 'RepackerError'
```

I have fontTools 4.33.3 installed.

Thank you!
Christoph

**Comment by justvanrossum** [comment]
You may need to upgrade your uharfbuzz install.

**Comment by koeberlin** [comment]
It was as easy as this. Thank you, Just! 🙏

**Comment by anthrotype** [comment]
maybe we could do better than that and try to catch the AttributeError or check `uharfbuzz.__version__` is greater than 0.23 that exports that symbol, and fall back to the pure-python serializer if not. 

when one installs using the extra fonttools[repacker] (or fonttools[all]), uharfbuzz >= 0.23 is automatically requested

https://github.com/fonttools/fonttools/blob/97958a95e1636a45d718a49d0ebd72d7382b45c0/setup.py#L129

whereas in @koeberlin's case, I suppose he simply found fonttools and uharfbuzz installed independently from one another in the same environment, but uharfbuzz didn't match fonttools minimum required version hence the uncaught exception.
