### ISSUE TITLE
basePen error when pasting from Illustrator

### ISSUE THREAD

**Issue by ryanbugden** [fonttools/fonttools#2726]
Hi there!

Some shapes do not successfully paste from Illustrator to RoboFont (i.e. the shape is not pasted / doesn't show up), and the error that's thrown is below.

TIA!

fontTools `Version: 4.32.0`
RoboFont `Version 4.3b (build 2206031749)`

```
Traceback (most recent call last):
  File "lib/eventTools/editingTool.pyc", line 1457, in paste
  File "lib/fontObjects/doodleSelection.pyc", line 2183, in paste
  File "lib/tools/pdfPastboardTools.pyc", line 143, in PDFDataToPen
  File "lib/tools/pdfPastboardTools.pyc", line 126, in __init__
  File "lib/tools/pdfPastboardTools.pyc", line 109, in drawToPen
  File "lib/tools/pdfPastboardTools.pyc", line 55, in replay
  File "/Applications/RoboFont-4_3b.app/Contents/Resources/lib/python3.7/fontTools/pens/recordingPen.py", line 66, in replay
  File "/Applications/RoboFont-4_3b.app/Contents/Resources/lib/python3.7/fontTools/pens/recordingPen.py", line 23, in replayRecording
  File "/Applications/RoboFont-4_3b.app/Contents/Resources/lib/python3.7/fontTools/pens/pointPen.py", line 302, in closePath
fontTools.pens.basePen.PenError: Contour missing required initial moveTo
```

**Comment by justvanrossum** [comment]
Likely a RF problem I'm afraid.

**Comment by ryanbugden** [comment]
Ok, maybe some data is being manipulated in its `pdfPastboardTools`.

**Comment by ryanbugden** [comment]
Thanks @typemytype !
