### ISSUE TITLE
trying to merge 2 fonts (emoji and text) but get error

### ISSUE THREAD

**Issue by khaledmsm** [fonttools/fonttools#2751]
code 

`from fontTools import ttLib, merge

font_list = {
    "C:\\Users\\kmm\\Desktop\\fonts\\NotoColorEmoji.ttf",
    "C:\\Users\\kmm\\Desktop\\fonts\\Almarai-Bold.ttf",

}

def make_font(font_list, output_to):
    merger = merge.Merger()
    font = merger.merge(font_list)
    metrics = read_line_metrics(ttLib.TTFont(font_list[0]))
    set_line_metrics(font, metrics)
    font.save(output_to)
    font.close()

make_font(font_list,'meged.ttf')`

the error output 

`Dropped cmap subtable from font '1':	format 14, platformID  0, platEncID  5
Traceback (most recent call last):
  File "C:\Users\kmm\PycharmProjects\sawerha_bot\tessst.py", line 17, in <module>
    make_font(font_list,'meged.ttf')
  File "C:\Users\kmm\PycharmProjects\sawerha_bot\tessst.py", line 11, in make_font
    font = merger.merge(font_list)
  File "C:\Users\kmm\AppData\Roaming\Python\Python310\site-packages\fontTools\merge\__init__.py", line 114, in merge
    table = clazz(tag).merge(self, tables)
  File "C:\Users\kmm\AppData\Roaming\Python\Python310\site-packages\fontTools\merge\base.py", line 72, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "C:\Users\kmm\AppData\Roaming\Python\Python310\site-packages\fontTools\merge\__init__.py", line 146, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "C:\Users\kmm\AppData\Roaming\Python\Python310\site-packages\fontTools\merge\util.py", line 21, in equal
    assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
AssertionError: Expected all items to be equal: [1000, 2048]`

**Comment by anthrotype** [comment]
the two fonts probably have different UPEM (units per EM), the merger tool expects all fonts to match. Maybe once @behdad finishes to implement his tool to scale UPEM you can try scaling that Almarai font so it matches NotoColorEmoji's UPEM (See https://github.com/fonttools/fonttools/pull/2718) and try again to merge.

**Comment by behdad** [comment]
The scaleUpem module is merged now. However, the merger does not support color tables.

**Comment by khaledmsm** [comment]
How can i use ? 
> The scaleUpem module is merged now. However, the merger does not support color tables.

**Comment by behdad** [comment]
> How can i use ?

With fonttools main branch you can do:
```
$ ./fonttools ttLib.scaleUpem NotoColorEmoji.ttf 2048
```

But what I said after that is that our merge tool does NOT handle color fonts whatsoever. So even if you change the UPEM, you won't be able to merge these fonts.

**Comment by khaledmsm** [comment]
So if I found a 2 color fonts with same Upem i can merge them ?

> > How can i use ?
> 
> 
> 
> With fonttools main branch you can do:
> 
> ```
> 
> $ ./fonttools ttLib.scaleUpem NotoColorEmoji.ttf 2048
> 
> ```
> 
> 
> 
> But what I said after that is that our merge tool does NOT handle color fonts whatsoever. So even if you change the UPEM, you won't be able to merge these fonts.

**Comment by behdad** [comment]
Let me repeat:

Our merge tool does NOT handle color fonts whatsoever.
