### ISSUE TITLE
cant merge two fonts 

### ISSUE THREAD

**Issue by khaledmsm** [fonttools/fonttools#2754]
this my code 
`
**from fontTools import ttLib, merge

font_list = {
    "C:\\Users\\kmm\\Desktop\\fonts\\NotoColorEmoji.ttf",
    "C:\\Users\\kmm\\Desktop\\fonts\\NotoColorEmoji_WindowsCompatible.ttf",

}

def make_font(font_list, output_to):
    merger = merge.Merger()
    font = merger.merge(font_list)
    metrics = read_line_metrics(ttLib.TTFont(font_list[0]))
    set_line_metrics(font, metrics)
    font.save(output_to)
    font.close()

make_font(font_list,'meged.ttf')`**

and this error message 

`
Dropped cmap subtable from font '0':	format 14, platformID  0, platEncID  5
Dropped cmap subtable from font '1':	format 14, platformID  0, platEncID  5
Traceback (most recent call last):
  File "C:\Users\kmm\PycharmProjects\sawerha_bot\tessst.py", line 17, in <module>
    make_font(font_list,'meged.ttf')
  File "C:\Users\kmm\PycharmProjects\sawerha_bot\tessst.py", line 11, in make_font
    font = merger.merge(font_list)
  File "C:\Users\kmm\AppData\Roaming\Python\Python310\site-packages\fontTools\merge\__init__.py", line 114, in merge
    table = clazz(tag).merge(self, tables)
  File "C:\Users\kmm\AppData\Roaming\Python\Python310\site-packages\fontTools\merge\tables.py", line 214, in merge
    for g in table.glyphs.values():
AttributeError: 'NotImplementedType' object has no attribute 'glyphs'`

**Comment by behdad** [comment]
The merge tool is very primitive, specially around color fonts.
