### ISSUE TITLE
Release 4.37.2 breaks our ci

### ISSUE THREAD

**Issue by m4rc1e** [fonttools/fonttools#2819]
New fonttools release has broken our google/fonts CI:

https://github.com/google/fonts/actions/runs/3066331513/jobs/4951379192#step:6:421

```PYTHON
INFO:gftools.qa:Running Diffenator
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/bin/gftools-qa.py", line 263, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/bin/gftools-qa.py", line 240, in main
    qa.googlefonts_upgrade()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/gftools/qa.py", line 216, in googlefonts_upgrade
    self.diffenator()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/gftools/qa.py", line 109, in diffenator
    font_before = DFont(self.instances_before[style]['filename'])
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/diffenator/font.py", line 100, in __init__
    self.recalc_glyphset()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/diffenator/font.py", line 144, in recalc_glyphset
    inputs = InputGenerator(self).all_inputs()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/diffenator/hbinput.py", line 41, in __init__
    elif hasattr(glyph._glyph, 'xMax'):
AttributeError: '_TTGlyphGlyf' object has no attribute '_glyph'
``` 

Im guessing https://github.com/fonttools/fonttools/commit/b818e1494ff2bfb7f0cd71d827ba97578c919303 may be the culprit.

**Comment by simoncozens** [comment]
This change also broke babelfont and beziers.py. Yes, I know it's a scary underscore class, but it was the only sensible way to get at the font's glyphs.

**Comment by anthrotype** [comment]
hm, but the symbols where prefixed with an underscore which in Python land means they are presumed to be private so you kind of did that at your own risk?

**Comment by anthrotype** [comment]
we can provide a public method if clients need that. Want to send a PR?

**Comment by simoncozens** [comment]
I wonder if we even need it. `font.getGlyphSet()[glyphname]` returns an object with a `draw` method, and that's probably all that it takes. I'm not sure if that does the right thing with components, but presumably it does.

**Comment by anthrotype** [comment]
yeah, that's the intended public interface. If one wants to access the raw glyphs underneath, then one can go and get them directly from the tables. The TTGlyphSet is supposed to be a higher level API.
