### ISSUE TITLE
[ttLib] scale-upem fails in many ways

### ISSUE THREAD

**Issue by punchcutter** [fonttools/fonttools#2840]
Trying to use ttLib.scaleUpem and not getting anything so far

Running on Source Serif VF from https://github.com/adobe-fonts/source-serif/blob/release/VAR/SourceSerif4Variable-Roman.ttf

```
fonttools ttLib.scaleUpem SourceSerif4Variable-Roman.ttf 4096 --output-file=scaledRoman.ttf

too much 'hmtx' table data
Writing scaledRoman.ttf
Traceback (most recent call last):
  File "/venv/test/bin/fonttools", line 8, in <module>
    sys.exit(main())
  File "/venv/test/lib/python3.10/site-packages/fontTools/__main__.py", line 30, in main
    runpy.run_module(mod, run_name='__main__')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/scaleUpem.py", line 336, in <module>
    sys.exit(main())
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/scaleUpem.py", line 330, in main
    font.save(output_file)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 185, in save
    writer_reordersTables = self._save(tmp)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 225, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 658, in _writeTable
    tabledata = self.getTableData(tag)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 680, in getTableData
    return self.tables[tag].compile(self)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/tables/otBase.py", line 135, in compile
    self.table.compile(writer, font)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/tables/otBase.py", line 1006, in compile
    conv.write(writer, font, table, value)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/tables/otConverters.py", line 660, in write
    value.compile(subWriter, font)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/tables/otBase.py", line 970, in compile
    conv.writeArray(writer, font, table, value)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/tables/otConverters.py", line 201, in writeArray
    self.write(writer, font, tableDict, value, i)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/tables/otConverters.py", line 660, in write
    value.compile(subWriter, font)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/tables/otBase.py", line 970, in compile
    conv.writeArray(writer, font, table, value)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/tables/otConverters.py", line 201, in writeArray
    self.write(writer, font, tableDict, value, i)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/tables/otConverters.py", line 1715, in write
    writeSmallArray(values[n1:regionCount])
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/tables/otBase.py", line 674, in writeInt8Array
    self.writeArray('b', values)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/tables/otBase.py", line 666, in writeArray
    a = array.array(typecode, values)
OverflowError: ('signed char is less than minimum', 0, 'Item[]', 0, 'VarData[]', 'VarStore')
```
The OTF has the same except for the too much hmtx line.

Running on a totally different static OTF 

```
Traceback (most recent call last):
  File "/venv/test/bin/fonttools", line 8, in <module>
    sys.exit(main())
  File "/venv/test/lib/python3.10/site-packages/fontTools/__main__.py", line 30, in main
    runpy.run_module(mod, run_name='__main__')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/scaleUpem.py", line 336, in <module>
    sys.exit(main())
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/scaleUpem.py", line 327, in main
    scale_upem(font, new_upem)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/scaleUpem.py", line 291, in scale_upem
    visitor.visit(font)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/ttVisitor.py", line 16, in visit
    super().visit(obj, *args, **kwargs)
  File "/venv/test/lib/python3.10/site-packages/fontTools/misc/visitor.py", line 133, in visit
    ret = visitorFunc(self, obj, *args, **kwargs)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/ttVisitor.py", line 30, in visit
    visitor.visit(font[tag], *args, **kwargs)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/ttVisitor.py", line 16, in visit
    super().visit(obj, *args, **kwargs)
  File "/venv/test/lib/python3.10/site-packages/fontTools/misc/visitor.py", line 137, in visit
    self.visitObject(obj, *args, **kwargs)
  File "/venv/test/lib/python3.10/site-packages/fontTools/misc/visitor.py", line 91, in visitObject
    ret = visitorFunc(self, obj, key, value, *args, **kwargs)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/scaleUpem.py", line 179, in visit
    _cff_scale(visitor, args)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/scaleUpem.py", line 152, in _cff_scale
    args[i] = visitor.scale(arg)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/scaleUpem.py", line 24, in scale
    return otRound(v * self.scaleFactor)
TypeError: can't multiply sequence by non-int of type 'float'
```

It seems to work on some fonts, but not most of what I'm trying.

**Comment by punchcutter** [comment]
Got another different traceback on a different variable font...

```
Traceback (most recent call last):
  File "/venv/test/bin/fonttools", line 8, in <module>
    sys.exit(main())
  File "/venv/test/lib/python3.10/site-packages/fontTools/__main__.py", line 30, in main
    runpy.run_module(mod, run_name='__main__')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/scaleUpem.py", line 337, in <module>
    sys.exit(main())
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/scaleUpem.py", line 331, in main
    font.save(output_file)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 185, in save
    writer_reordersTables = self._save(tmp)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 225, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 658, in _writeTable
    tabledata = self.getTableData(tag)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 680, in getTableData
    return self.tables[tag].compile(self)
  File "/venv/test/lib/python3.10/site-packages/fontTools/ttLib/tables/_h_e_a_d.py", line 72, in compile
    bounds = charString.calcBounds(charStrings)
  File "/venv/test/lib/python3.10/site-packages/fontTools/misc/psCharStrings.py", line 1012, in calcBounds
    self.draw(boundsPen)
  File "/venv/test/lib/python3.10/site-packages/fontTools/misc/psCharStrings.py", line 1007, in draw
    extractor.execute(self)
  File "/venv/test/lib/python3.10/site-packages/fontTools/misc/psCharStrings.py", line 528, in execute
    super().execute(charString)
  File "/venv/test/lib/python3.10/site-packages/fontTools/misc/psCharStrings.py", line 302, in execute
    rv = handler(index)
  File "/venv/test/lib/python3.10/site-packages/fontTools/misc/psCharStrings.py", line 437, in op_vsindex
    self.numRegions = self.private.getNumRegions(vi)
  File "/venv/test/lib/python3.10/site-packages/fontTools/cffLib/__init__.py", line 2802, in getNumRegions
    numRegions = self.vstore.getNumRegions(vi)
  File "/venv/test/lib/python3.10/site-packages/fontTools/cffLib/__init__.py", line 1042, in getNumRegions
    varData = self.otVarStore.VarData[vsIndex]
IndexError: list index out of range
```

**Comment by punchcutter** [comment]
For the static OTF with traceback `TypeError: can't multiply sequence by non-int of type 'float'` it's coming from CFF hinting where we have hintmasks like this with b'\xd8' which `scale` is trying to use as an int. If I make it ignore that then it doesn't fail. 

```
[('', [184]), ('hstemhm', [-102, 32, 686, 38, -29, 29]), ('', [135, 81, 377, 81]), ('hintmask', []), ('', [b'\xd8']), ('rmoveto', [135, 86]), ('vhcurveto', [-66, -1, -28, -2, -28]), 
```

**Comment by behdad** [comment]
I fixed the first issue. I need reproduction fonts for each individual issue. Please file separate issues preferably.

**Comment by behdad** [comment]
I fixed hintmask handling as well.

**Comment by behdad** [comment]
> File "/venv/test/lib/python3.10/site-packages/fontTools/cffLib/__init__.py", line 1042, in getNumRegions
>     varData = self.otVarStore.VarData[vsIndex]
> IndexError: list index out of range

This suggests a bad font. Though I have to see the font to know for sure.

**Comment by anthrotype** [comment]
Thanks Behdad
