### ISSUE TITLE
[designspaceLib] "Recursive" linkedUserValue valid?

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#2852]
I noticed that Adobe seems to link upright and italic VFs "recursively", i.e. on the Italic axis, the upright has linkedUserValue="1", and the italic has linkedUserValue="0". As seen in [Source Code Variable](https://github.com/adobe-fonts/source-code-pro/tree/release/VAR):

![Bildschirmfoto 2022-10-18 um 11 37 04](https://user-images.githubusercontent.com/3185950/196414877-a0791fe2-8689-4c25-b7ff-ef939748c879.png)

Such configuration can not be built with designspaceLib, it throws a RecursionError.

Should it be possible to build such fonts? Or is that kind of linking disallowed? The `ital` axis spec doesn't say anything about linkedUserValue.

Reproducer: [linkeduservalue.zip](https://github.com/fonttools/fonttools/files/9809677/linkeduservalue.zip)

```
Traceback (most recent call last):
  File "/Users/kuti/Code/variable-fonts/Test/test.py", line 12, in <module>
    names = getStatNames(ds, loc)
  File "/Users/kuti/Quellen/fonttools-github/Lib/fontTools/designspaceLib/statNames.py", line 126, in getStatNames
    regularStatNames = getStatNames(doc, regularUserLocation)
  File "/Users/kuti/Quellen/fonttools-github/Lib/fontTools/designspaceLib/statNames.py", line 126, in getStatNames
    regularStatNames = getStatNames(doc, regularUserLocation)
  File "/Users/kuti/Quellen/fonttools-github/Lib/fontTools/designspaceLib/statNames.py", line 126, in getStatNames
    regularStatNames = getStatNames(doc, regularUserLocation)
  [Previous line repeated 987 more times]
  File "/Users/kuti/Quellen/fonttools-github/Lib/fontTools/designspaceLib/statNames.py", line 66, in getStatNames
    defaultSource: Optional[SourceDescriptor] = doc.findDefault()
  File "/Users/kuti/Quellen/fonttools-github/Lib/fontTools/designspaceLib/__init__.py", line 2768, in findDefault
    print(sourceDescriptor)
  File "/Users/kuti/Quellen/fonttools-github/Lib/fontTools/designspaceLib/__init__.py", line 116, in __repr__
    attrs = indent('\n'.join(attrs), '    ')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/textwrap.py", line 488, in indent
    return ''.join(prefixed_lines())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/textwrap.py", line 487, in prefixed_lines
    yield (prefix + line if predicate(line) else line)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/textwrap.py", line 483, in predicate
    return line.strip()
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by justvanrossum** [comment]
Also noted in https://github.com/fonttools/fonttools/discussions/2790.

I think it should be possible to build such fonts.

**Comment by belluzj** [comment]
Ah right, sorry I forgot about that issue. I'll push a PR

**Comment by jenskutilek** [comment]
Thanks! I think the problem is here:

https://github.com/fonttools/fonttools/blob/bc03f0932208c71ecb1bca40a348fdf0170f5abe/Lib/fontTools/designspaceLib/statNames.py#L200-L225

The comparison `urpright_label.linkedUserValue == userLocation[axis.name]` is true for both locations on the italic axis.

**Comment by belluzj** [comment]
@jenskutilek @LettError There's a PR here if you wish to test it for your use-cases: https://github.com/fonttools/fonttools/pull/2853

**Comment by jenskutilek** [comment]
@belluzj I can confirm it works for my font. Thank you very much for the quick fix!

**Comment by anthrotype** [comment]
I wonder, why does Adobe want to have these recursively linked values between Regular <-> Bold?

If I read the spec correctly,  it says at https://learn.microsoft.com/en-us/typography/opentype/spec/stat#axis-value-table-format-3

> A mapping is defined from a “non-bold” value to its “bold” counterpart.

And there is not indication that this works viceversa.. Sure we can relax this and allow the fonts to build but what purpose does this recursive linking serve?

**Comment by anthrotype** [comment]
oh I just was @punchcutter explained this as a workaround for some Indesign bug.. https://github.com/fonttools/fonttools/discussions/2790#discussioncomment-3507714

**Comment by jenskutilek** [comment]
Unless I'm missing something, in the current InDesign using axis value format 2 (ranges) or 1 (no ranges) for weight, and italic backlinked to roman or not, doesn't make a difference.

Switching to Italic via keyboard shortcut only works for predefined weight instances.

Switching to bold via shortcut goes from Regular to Bold to Thin ...

**Comment by punchcutter** [comment]
There are some open bugs about the keyboard shortcuts and how they work (or don't work). I've also filed Apple bugs about how linking works (it doesn't) in more complex variable fonts. 

About @anthrotype's comment:

I don't even remember if this actually mattered to the bug mentioned. I think it's fine to only have the link in Italic which really makes the most sense.
