### ISSUE TITLE
[ttLib] removeOverlaps pathops fails with glyphSet argument

### ISSUE THREAD

**Issue by punchcutter** [fonttools/fonttools#2905]
I'm trying to make instances from a variable TTF and it works fine without `--remove-overlaps`, but with it

```
  File "/fontTools/ttLib/removeOverlaps.py", line 33, in skPathFromGlyph
    pathPen = path.getPen(glyphSet=glyphSet)
  File "src/python/pathops/_pathops.pyx", line 153, in pathops._pathops.Path.getPen
TypeError: getPen() got an unexpected keyword argument 'glyphSet'

```
Looks like there are no tests in removeOverlaps_test.py for getPen with `glyphSet`

**Comment by anthrotype** [comment]
that's weird.. pathops.Path::getPen method definitely has a `glyphSet` parameter

https://github.com/fonttools/skia-pathops/blob/3b05bc343af6c63a5932f84bbb1e28175c7dc66f/src/python/pathops/_pathops.pyx#L159

what version of pathops are you using?

**Comment by anthrotype** [comment]
looks like it was added a couple years ago with https://github.com/fonttools/skia-pathops/pull/32

i'm sure upgrading pathops should fix this

**Comment by punchcutter** [comment]
Ah, probably this venv is just old. I need to trash a few of these and make new venvs.

**Comment by richso** [comment]
HI @punchcutter  and @anthrotype,

I just tried this command but I got an error:

fonttools varLib.instancer --remove-overlaps --update-name-table -o SourceHanSansHC-Regular.ttf SourceHanSansHC-VF.ttf wght=400


Restricting axes: {'wght': (400, 400, 400)}
Loading variable font
Normalized limits: {'wght': (0.390015, 0.390015, 0.390015)}
Updating name table
Instantiating glyf/gvar tables
Dropping HVAR table
Instantiating GDEF and GPOS tables
Instantiating FeatureVariations of GPOS table
Dropping avar table
Instantiating STAT table
Dropping fvar table
Pruning name table
Traceback (most recent call last):
  File "/Users/brotherseven/fonts/tmp/afdko_env/bin/fonttools", line 8, in <module>
    sys.exit(main())
  File "/Users/brotherseven/fonts/tmp/afdko_env/lib/python3.8/site-packages/fontTools/__main__.py", line 30, in main
    runpy.run_module(mod, run_name='__main__')
  File "/Users/brotherseven/opt/anaconda3/lib/python3.8/runpy.py", line 210, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/Users/brotherseven/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/brotherseven/fonts/tmp/afdko_env/lib/python3.8/site-packages/fontTools/varLib/instancer/__main__.py", line 5, in <module>
    sys.exit(main())
  File "/Users/brotherseven/fonts/tmp/afdko_env/lib/python3.8/site-packages/fontTools/varLib/instancer/__init__.py", line 1534, in main
    instantiateVariableFont(
  File "/Users/brotherseven/fonts/tmp/afdko_env/lib/python3.8/site-packages/fontTools/varLib/instancer/__init__.py", line 1317, in instantiateVariableFont
    from fontTools.ttLib.removeOverlaps import removeOverlaps
  File "/Users/brotherseven/fonts/tmp/afdko_env/lib/python3.8/site-packages/fontTools/ttLib/removeOverlaps.py", line 16, in <module>
    import pathops
ModuleNotFoundError: No module named 'pathops'


My Environment:
- MacOS Monterey 12.6
- Python 3.8
- Freshly installed AFDKO (ref: https://github.com/adobe-type-tools/afdko/)
- checked the AFDKO bundled "fonttools" version is v4.38.0
- SourceHanSansHC-VF.ttf freshly downloaded from https://github.com/adobe-fonts/source-han-sans/tree/release (Language-specific Variable Fonts -> TTF -> Variable Traditional Chinese — Hong Kong)

Am I missing something?

**Comment by punchcutter** [comment]
Sorry, I forgot to mention you also need to install pathops. pip install skia-pathops
