### ISSUE TITLE
Problem when merging NotoSansSaurashtra-Regular.ttf with any other font. 

### ISSUE THREAD

**Issue by Veerjee** [fonttools/fonttools#2920]
```
PS C:\ssc> pyftmerge .\NotoSansSaurashtra-Regular.ttf .\NotoSansBatak-Regular.ttf
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ ... \AppData\Local\Programs\Python\Python311\Scripts\pyftmerge.exe\__main__.py", line 7, in <module>
  File "C:\ ... \AppData\Local\Programs\Python\Python311\Lib\site-packages\fontTools\misc\loggingTools.py", line 372, in wrapper return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\ ... \AppData\Local\Programs\Python\Python311\Lib\site-packages\fontTools\merge\__init__.py", line 199, in main font = merger.merge(fontfiles)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ ... \AppData\Local\Programs\Python\Python311\Lib\site-packages\fontTools\merge\__init__.py", line 114, in merge table = clazz(tag).merge(self, tables)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ ... \AppData\Local\Programs\Python\Python311\Lib\site-packages\fontTools\merge\base.py", line 72, in merge return m.mergeObjects(self, self.mergeMap, tables)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ ... \AppData\Local\Programs\Python\Python311\Lib\site-packages\fontTools\merge\__init__.py", line 146, in mergeObjects value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ ... \AppData\Local\Programs\Python\Python311\Lib\site-packages\fontTools\merge\util.py", line 21, in equal assert all(item == first for item in t), "Expected all items to be equal: %s" % lst AssertionError: Expected all items to be equal: ['vmtx', NotImplemented]
```

**Comment by Veerjee** [comment]
Similar results, when merging NotoSerif Dogra-Regular.ttf is merged with any other font.

**Comment by behdad** [comment]
Try `--drop-tables+=vmtx,vhea`

**Comment by Veerjee** [comment]
Works. Thank you, Behdad! 
I noticed the following warning. Do I need to take any action?

WARNING: Have non-identical duplicates to resolve for 'Noto Sans Linear A Regular' but no GSUB. Are duplicates intended?: {'NULL': 'NULL.13', 'CR': 'CR.14', 'space': 'space.16', 'uni00A0': 'uni00A0.15'}
WARNING: Have non-identical duplicates to resolve for 'Noto Sans Linear B Regular' but no GSUB. Are duplicates intended?: {'NULL': 'NULL.14', 'CR': 'CR.15', 'space': 'space.17', 'uni00A0': 'uni00A0.16'}
WARNING: Have non-identical duplicates to resolve for 'Noto Sans Mayan Numerals Regular' but no GSUB. Are duplicates intended?: {'NULL': 'NULL.19', 'CR': 'CR.20', 'space': 'space.22', 'uni00A0': 'uni00A0.21'}
WARNING: Have non-identical duplicates to resolve for 'Noto Sans Nabataean Regular' but no GSUB. Are duplicates intended?: {'NULL': 'NULL.26', 'CR': 'CR.27', 'space': 'space.30', 'uni00A0': 'uni00A0.29'}
WARNING: Have non-identical duplicates to resolve for 'Noto Sans Old North Arabian Regular' but no GSUB. Are duplicates intended?: {'NULL': 'NULL.28', 'CR': 'CR.29', 'space': 'space.32', 'uni00A0': 'uni00A0.31'}
WARNING: Have non-identical duplicates to resolve for 'Noto Serif Nyiakeng Puachue Hmong Regular' but no GSUB. Are duplicates intended?: {'NULL': 'NULL.46', 'CR': 'uni000D.1', 'space': 'space.50', 'uni00A0': 'uni00A0.48'}

**Comment by behdad** [comment]
> I noticed the following warning. Do I need to take any action?

Those glyphs are safe to have duplicates. You're good.

**Comment by Veerjee** [comment]
Thank you, appreciate your super quick responses.
