### ISSUE TITLE
there is a error when running

### ISSUE THREAD

**Issue by seadog-www** [fonttools/fonttools#2979]
input command:
`pyftsubset SourceHanSans-VF.otf --text-file=reserve.txt --output-file=target.otf`

SourceHanSans-VF.otf : https://github.com/adobe-fonts/source-han-sans/blob/release/Variable/OTF/SourceHanSans-VF.otf

[reserve.txt](https://github.com/fonttools/fonttools/files/10571437/reserve.txt)

ERROR:
Traceback (most recent call last):
  File "/usr/bin/pyftsubset", line 11, in <module>
    load_entry_point('fonttools==3.21.2', 'console_scripts', 'pyftsubset')()
  File "/usr/lib/python3/dist-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 3119, in main
    subsetter.subset(font)
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 2930, in subset
    self._prune_pre_subset(font)
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 2759, in _prune_pre_subset
    retain = table.prune_pre_subset(font, self.options)
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 1977, in prune_pre_subset
    dfltWdX = private.defaultWidthX
  File "/usr/lib/python3/dist-packages/fontTools/cffLib/__init__.py", line 2242, in __getattr__
    raise AttributeError(name)
AttributeError: defaultWidthX

**Comment by behdad** [comment]
I cannot reproduce this. Please try with latest version of fonttools.

**Comment by seadog-www** [comment]
> I cannot reproduce this. Please try with latest version of fonttools.

Thank you for your replying. The problem has been solved when you update the installation and require Python 3.8.

**Comment by justvanrossum** [comment]
fonttools 4.38.0 still supports 3.7, though.
