### ISSUE TITLE
MATH table

### ISSUE THREAD

**Issue by LiquidDragonFire** [fonttools/fonttools#3028]
ttx is unable to read more than 71 stretchy delimiters from a .ttx file. It will read an .otf with more than 71 delimiters, but barfs when round tripping. I typically export the .ttx file from an .otf file, replace the MATH table with one using glyph names, and then create a new .otf file (and then import the compiled MATH table into FontLab which does not support glyph names at this time). It does not matter which delimiter has index='71", or the order. It simply fails when it sees index="71". I have appended the error trace at the end. If you would like a failing source file, I will be happy to provide one. I am using python 3.8.3 and ttx version 4.33.3.

Thank you.

R:\ctan\logix\source\xxx>ttx logix.ttx
Compiling "logix.ttx" to "logix#3.otf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'name' table...
Parsing 'cmap' table...
Parsing 'post' table...
Parsing 'CFF ' table...
Parsing 'GDEF' table...
Parsing 'GPOS' table...
Parsing 'GSUB' table...
Parsing 'MATH' table...
Parsing 'hmtx' table...
Parsing 'DSIG' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "c:\bin\python\lib\site-packages\fontTools\ttx.py", line 405, in main
    process(jobs, options)
  File "c:\bin\python\lib\site-packages\fontTools\ttx.py", line 387, in process
    action(input, output, options)
  File "c:\bin\python\lib\site-packages\fontTools\misc\loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "c:\bin\python\lib\site-packages\fontTools\ttx.py", line 305, in ttCompile
    ttf.save(output)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\ttFont.py", line 184, in save
    writer_reordersTables = self._save(tmp)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\ttFont.py", line 224, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\ttFont.py", line 647, in _writeTable
    tabledata = self.getTableData(tag)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\ttFont.py", line 669, in getTableData
    return self.tables[tag].compile(self)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 103, in compile
    self.table.compile(writer, font)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 940, in compile
    conv.write(writer, font, table, value)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\tables\otConverters.py", line 631, in write
    value.compile(subWriter, font)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 904, in compile
    conv.writeArray(writer, font, table, value)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\tables\otConverters.py", line 197, in writeArray
    self.write(writer, font, tableDict, value, i)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\tables\otConverters.py", line 631, in write
    value.compile(subWriter, font)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 940, in compile
    conv.write(writer, font, table, value)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\tables\otConverters.py", line 631, in write
    value.compile(subWriter, font)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 904, in compile
    conv.writeArray(writer, font, table, value)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\tables\otConverters.py", line 197, in writeArray
    self.write(writer, font, tableDict, value, i)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\tables\otConverters.py", line 510, in write
    value.compile(writer, font)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 940, in compile
    conv.write(writer, font, table, value)
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\tables\otConverters.py", line 356, in write
    writer.writeValue(self.typecode, font.getGlyphID(value))
  File "c:\bin\python\lib\site-packages\fontTools\ttLib\tables\otBase.py", line 601, in writeValue
    self.items.append(struct.pack(f">{typecode}", value))
struct.error: ('required argument is not an integer', 'str', 0, 'PartRecords[]', 'GlyphAssembly', 71, 'VertGlyphConstruction[]', 'MathVariants')

**Comment by LiquidDragonFire** [comment]
Clarification: The indices are in order. It doesn't matter which delimiter is 71. The order of the delimiters doesn't matter. The first 71 are processed ok, and it fails on 72 (index 71).

**Comment by behdad** [comment]
Please attach or points us to a sample font file that fails.

**Comment by LiquidDragonFire** [comment]
Here you go. Note that I had to rename this from logix.ttx to logix.txt to allow the upload to work.

[logix.txt](https://github.com/fonttools/fonttools/files/10936388/logix.txt)

**Comment by behdad** [comment]
It's because your record 71 references a nonexistent glyph "ClsDblFloorBtm". Sure our error message sucks, but that's the reason. No superstitous 71 or other magic number.

**Comment by behdad** [comment]
Error message will be improved by https://github.com/fonttools/fonttools/issues/3030
