### ISSUE TITLE
Color font "Format is not hashable"

### ISSUE THREAD

**Issue by RosaWagner** [fonttools/fonttools#3039]
I don't know what it means:
Generating fonts from Designspace failed: <class 'fontTools.ttLib.tables.otTables.Paint'> Format is not hashable: ['colon.color0', '0']

Font can be found here: https://github.com/RosaWagner/Borel/blob/main/sources/BorelGuides.glyphs

Tell me if this issue should be opened in fontmake instead.

This is the traceback:
```
Traceback (most recent call last):
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 1127, in run_from_designspace
    self._run_from_designspace_interpolatable(
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 1223, in _run_from_designspace_interpolatable
    self.build_variable_fonts(
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 420, in build_variable_fonts
    fonts = ufo2ft.compileVariableTTFs(
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/ufo2ft/__init__.py", line 602, in compileVariableTTFs
    vfNameToBaseUfo = _compileNeededSources(
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/ufo2ft/__init__.py", line 793, in _compileNeededSources
    ttfDesignSpace = compileInterpolatableFunc(
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/ufo2ft/__init__.py", line 390, in compileInterpolatableTTFsFromDS
    for source, ttf in zip(result.sources, ttfs):
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/ufo2ft/__init__.py", line 312, in compileInterpolatableTTFs
    ttf = call_outline_compiler(
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/ufo2ft/__init__.py", line 80, in call_outline_compiler
    return outlineCompiler.compile()
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/ufo2ft/outlineCompiler.py", line 163, in compile
    self.setupTable_COLR()
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/ufo2ft/outlineCompiler.py", line 982, in setupTable_COLR
    self.otf["COLR"] = buildCOLR(
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/fontTools/colorLib/builder.py", line 237, in buildCOLR
    colr.LayerList, colr.BaseGlyphList = buildColrV1(
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/fontTools/colorLib/builder.py", line 644, in buildColrV1
    baseGlyphs.append(buildBaseGlyphPaintRecord(baseGlyph, layerBuilder, paint))
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/fontTools/colorLib/builder.py", line 615, in buildBaseGlyphPaintRecord
    self.Paint = layerBuilder.buildPaint(paint)
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/fontTools/colorLib/builder.py", line 599, in buildPaint
    return self.tableBuilder.build(ot.Paint, paint)
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/fontTools/colorLib/table_builder.py", line 130, in build
    fmt, source = _split_format(cls, source)
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/fontTools/colorLib/table_builder.py", line 67, in _split_format
    assert isinstance(
AssertionError: <class 'fontTools.ttLib.tables.otTables.Paint'> Format is not hashable: ['colon.color0', '0']
```

**Comment by anthrotype** [comment]
that's weird, thanks for reporting. It might be a glyphsLib bug, I'll investigate now

**Comment by anthrotype** [comment]
that's really weird, it seems like the colorPalette layer attribute in .glyphs sources sometimes is written out as an unquoted _integer_, sometimes as a quoted _string_... doesn't make any sense /cc @khaledhosny 

```
attr = {
colorPalette = 1;
};
```

```
attr = {
colorPalette = "1";
};
```

Anwyay, the fix should go in glyphsLib, where it extracts these colorPalette attributes, it should convert them to int(). I'll work on a PR.

**Comment by anthrotype** [comment]
@RosaWagner can you please try using glyphsLib from github repo's main branch, I just fixed the bug. We shall make a release soon, hopefully this week

**Comment by RosaWagner** [comment]
It's working :) thanks
