### ISSUE TITLE
Uncaught exception when loading font

### ISSUE THREAD

**Issue by DavidKorczynski** [fonttools/fonttools#3041]
The following program raises an uncaught exception:

```python
import io
import sys
import atheris

from fontTools import ttLib
from fontTools.ttLib import TTFont
import xml         

def TestOneInput(data):
  randfile = "/tmp/random2.ttx"
  with open(randfile, "wb") as f:
    f.write(data)
  try:
    otf = TTFont(randfile)
  except ttLib.TTLibError:
    pass
  except AssertionError:
    pass
  except ImportError:
    pass
  
data = (b"\x4f\x54\x54\x4f\x00\x4b\x46\x32\x74\x63\x70\x46")                    
TestOneInput(data)
```

Where the `atheris` module refers to https://pypi.org/project/atheris/

The program is a derivative of the fuzzer here https://github.com/google/oss-fuzz/blob/master/projects/fonttools/fuzz_ttfont.py

The following program is a shortened version of above, without fuzzing-related logic:

```python
from fontTools import ttLib
from fontTools.ttLib import TTFont

randfile = "/tmp/random2.ttx"
with open(randfile, "wb") as f:
  f.write(b"\x4f\x54\x54\x4f\x00\x4b\x46\x32\x74\x63\x70\x46")
try:
  otf = TTFont(randfile)
except ttLib.TTLibError:
  pass
except AssertionError:
  pass
except ImportError:
  pass
```

This produces the stack trace:
```
# python3 ./reproducer.py 
Traceback (most recent call last):
  File "./reproducer.py", line 24, in <module>
    otf = TTFont(randfile)
  File "/usr/local/lib/python3.8/site-packages/fontTools/ttLib/ttFont.py", line 164, in __init__
    self.reader = SFNTReader(file, checkChecksums, fontNumber=fontNumber)
  File "/usr/local/lib/python3.8/site-packages/fontTools/ttLib/sfnt.py", line 89, in __init__
    entry.fromFile(self.file)
  File "/usr/local/lib/python3.8/site-packages/fontTools/ttLib/sfnt.py", line 490, in fromFile
    sstruct.unpack(self.format, file.read(self.formatSize), self)
  File "/usr/local/lib/python3.8/site-packages/fontTools/misc/sstruct.py", line 88, in unpack
    elements = struct.unpack(formatstring, data)
struct.error: unpack requires a buffer of 16 bytes
```

This was found by way of OSS-Fuzz and the set up here: https://github.com/google/oss-fuzz/tree/master/projects/fonttools If you find this issue helpful then it would be great to have maintainer emails in the [project.yaml](https://github.com/google/oss-fuzz/blob/master/projects/fonttools/project.yaml) to receive notifications of bug reports, which contain all details similar to what I posted above -- namely they contain the stacktrace, crashing input and identification of the fuzzer.

**Comment by DavidKorczynski** [comment]
> IIUC you are throwing a seemingly random string of bytes to fonttools and expecting it to do what exactly?

Your understanding is correct -- my lightly-held assumption was `ttlLib.TTLibError` would be thrown in the event of an error -- this may be a wrong assumption as it's not mentioned explicitly here https://fonttools.readthedocs.io/en/latest/ttLib/ttFont.html#ttfont-read-write-opentype-and-truetype-fonts ?

> And why should `AssertionError` or `ImportError` be handled with a pass in that code, and not, say, struct.error as in this particular case?

Largely, this was to have the fuzzer run for longer and explore more code. I figured `AssertionError`s were less interesting from a code analysis perspective and `ImportError` the same.

Does `TTFont` give any promises in terms of what exceptions can be thrown in the event of arbitrary input to `TTFont` or can any exception be thrown in the event of a arbitrary input?

**Comment by anthrotype** [comment]
thank you for this. TBH I wasn't even aware that fonttools was being cluster-fuzzed before you filed this issue..

There are many ways reading a TTFont from a .otf/.ttf, or importing one from XML, can fail. Not all of them may be wrapped with a TTLibError, some may be specific to the module or sub-package of fonttools where it is being thrown, some might not even be documented at all...

Fonts are complicated data structures and can be broken in so many little ways. Does the fuzzer literally generates a random string? That probably won't even ever pass the very early loading of the sfnt font header..

So, to answer your question directly: no, fontTools does not currently guarantee what exceptions can be thrown in the event of completely abritrary input.

I suppose this fuzzer of yours could help us uncover some of the ways fonttools can fail in an unexpected/undocumented ways.

**Comment by anthrotype** [comment]
> the very early loading of the sfnt font header

which is exactly what is failing here with the `struct.error` while trying to unpack an sfnt directory entry but not having enough bytes -- we use the stdlib module `struct` to go to/from bytes and python objects. That particular error would only occur with a really pathological input, and it doesn't really occur with real world font files, so we haven't found a need to provide caller with a nicer custom exception, e.g. TTLibError.

Are you suggesting that we wrap struct.errors like this in a TTLibError?

**Comment by behdad** [comment]
> Does the fuzzer literally generates a random string? That probably won't even ever pass the very early loading of the sfnt font header..

The fuzzer is smart... You'd be surprised where it gets.

**Comment by DavidKorczynski** [comment]
> thank you for this. TBH I wasn't even aware that fonttools was being cluster-fuzzed before you filed this issue..
> 

My pleasure, I'd be happy to work with this to come up with something meaningful for fonttools. OSS-Fuzz is putting in efforts to have more Python projects fuzzed but coming up with good targets is a bit more tricky, since there is no "default threat model" in Python as there is in memory unsafe languages (i.e. memory corruption is a general issue). 

> 
>  Does the fuzzer literally generates a random string? That probably won't even ever pass the very early loading of the sfnt font header..
> 
Yes, the fuzzer will generate arbitrary input. 

> So, to answer your question directly: no, fontTools does not currently guarantee what exceptions can be thrown in the event of completely abritrary input.
> 

Got it! How about something like the following, would that make sense from a perspective that `saveXML` should not fail?

```python
TestOneInput(data):
  ....
  try:
    otf = TTFont(file_with_random_data)
  except:
    # Catch all issues
    return
    
   # The following should not fail
   otf.saveXML('random_file')
```

> I suppose this fuzzer of yours could help us uncover some of the ways fonttools can fail in an unexpected/undocumented ways.

It would be great to have maintainer emails in `project.yaml` : https://github.com/google/oss-fuzz/blob/master/projects/fonttools/project.yaml Then you can get access to all instances of uncaught exceptions found by the fuzzers (3 -- here: https://github.com/google/oss-fuzz/tree/master/projects/fonttools )

If you let me know a set of emails then I'll get them in!

If you are curious about how far the fuzzer gets, then OSS-Fuzz uses Fuzz Introspector to get insights about fuzzing, and publishes reports here: https://oss-fuzz-introspector.storage.googleapis.com/index.html

The fonttools report is here: https://storage.googleapis.com/oss-fuzz-introspector/fonttools/inspector-report/20221231/fuzz_report.html and has links to code coverage reports. Unfortunately the fuzz introspector report is outdated a bit, but a recent code coverage report is here: https://storage.googleapis.com/oss-fuzz-coverage/fonttools/reports/20230314/linux/index.html -- here you can see how much code it explores.

**Comment by anthrotype** [comment]
thanks for the clarification.

> If you let me know a set of emails then I'll get them in!

sure, can you please add mine? My Github profile shows that https://github.com/anthrotype

Regarding your suggestion for a catch-all except, I honestly don't know what's best from a fuzzer perspective. In theory loading and then dumping to XML a valid (not overly broken) font should not throw an exception, yes.

**Comment by DavidKorczynski** [comment]
@behdad would you like me to add yours too? e.g. https://github.com/google/oss-fuzz/blob/39eebf89b2bd2522935724d43e4e245a8b59aae9/projects/harfbuzz/project.yaml#L5 ?

**Comment by behdad** [comment]
> @behdad would you like me to add yours too? e.g. https://github.com/google/oss-fuzz/blob/39eebf89b2bd2522935724d43e4e245a8b59aae9/projects/harfbuzz/project.yaml#L5 ?

I just submitted https://github.com/google/oss-fuzz/pull/9926
But yeah now I remembered why I used my gmail address before because that allows me to log into oss-fuzz. I close my PR. Please add my gmail address. Thanks.

**Comment by behdad** [comment]
TTFont in general does not guarantee loading broken fonts. One way I can think of as useful fuzzing it is cross-fuzzing with ots-sanitize. That is, first sanitize font with ots-sanitize and only if it passes, then pass it to TTFont (ideally in with an in-process Python instance). But that would require instrumenting ots-sanitize (which exists in oss-fuzz). But that would be a completely different project and not a Python fuzzing target.

**Comment by DavidKorczynski** [comment]
> In theory loading and then dumping to XML a valid (not overly broken) font should not throw an exception, yes.

Okay -- I can try and put a fuzzer up with this and then we can see the results that come out. There may perhaps be more operations that should be valid in case of a loaded font?

If you would like, we can move the fuzzers upstream to the fonttools library -- this may make it easier for you to experiment with fuzzers?

> TTFont in general does not guarantee loading broken fonts. One way I can think of as useful fuzzing it is cross-fuzzing with ots-sanitize. That is, first sanitize font with ots-sanitize and only if it passes, then pass it to TTFont (ideally in with an in-process Python instance). But that would require instrumenting ots-sanitize (which exists in oss-fuzz). But that would be a completely different project and not a Python fuzzing target.

Hmm -- am not familiar with ots as such but my intuition is we should be able to create a bridge from the python fuzzer to the ots library such that the python fuzzer can call the ots library to verify a given input? Am not sure how much work this would require though.

**Comment by behdad** [comment]
> Am not sure how much work this would require though.

It would require building OTS with fuzzing instrumentation and driving the fuzzing with the C fuzzer infrastructure though, so I'm not sure if it can be driven from Python.

**Comment by anthrotype** [comment]
if you need to call OTS from python, there are a couple of options already: https://github.com/googlefonts/ots-python (calls ots-sanitize as a subprocess) or https://github.com/adobe-type-tools/pyots (links to libots from a python extension module)

**Comment by anthrotype** [comment]
> building OTS with fuzzing instrumentation

ah so it won't work right out of the box if installing the pre-compiled wheels for ots-python or pyots?

**Comment by DavidKorczynski** [comment]
> It would require building OTS with fuzzing instrumentation and driving the fuzzing with the C fuzzer infrastructure though, so I'm not sure if it can be driven from Python.

Atheris, the fuzzer used, is based on libFuzzer and we can instrument the ots library at build time (quite a number of oss-fuzz projects do this), see e.g.https://github.com/google/oss-fuzz/tree/master/projects/mrab-regex where the native parts of mrab-regex are build with sanitizer flags. See the a recent build log here: https://oss-fuzz-build-logs.storage.googleapis.com/log-ab956c74-0009-49d4-baaa-b976ef676203.txt where we have (notice `-fsanitize=fuzzer-no-link`):
```
Step #3 - "compile-libfuzzer-address-x86_64": creating build/temp.linux-x86_64-3.8/regex_3
Step #3 - "compile-libfuzzer-address-x86_64": clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -fno-sanitize=function,leak,vptr, -fPIC -I/usr/local/include/python3.8 -c regex_3/_regex.c -o build/temp.linux-x86_64-3.8/regex_3/_regex.o
Step #3 - "compile-libfuzzer-address-x86_64": clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -fno-sanitize=function,leak,vptr, -fPIC -I/usr/local/include/python3.8 -c regex_3/_regex_unicode.c -o build/temp.linux-x86_64-3.8/regex_3/_regex_unicode.o
Step #3 - "compile-libfuzzer-address-x86_64": clang -pthread -shared -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -fno-sanitize=function,leak,vptr, build/temp.linux-x86_64-3.8/regex_3/_regex.o build/temp.linux-x86_64-3.8/regex_3/_regex_unicode.o -L/usr/local/lib -o build/lib.linux-x86_64-3.8/regex/_regex.cpython-38-x86_64-linux-gnu.so
```
I think this should work the only caveat is whether the instrumentation coverage is picked up by libFuzzer from shared libraries (which I think it does, but am not 100% sure without digging a bit deeper). I.e., we can use e.g. https://github.com/adobe-type-tools/pyots and building `ots` from source, this make work.

**Comment by madig** [comment]
What would be nice is wrapping random exceptions from the deep in TTLibErrors, adding context along the way (which table is malformed?).

**Comment by anthrotype** [comment]
we kind of do that on an ad-hoc basis for the hand-written table modules, but yeah I agree with your error handling could be improved. In this particular case, the struct.error is arguably quite unlikely to blow up with real-world fonts so the incentive of producing a nicer error message is less stringent IMO

**Comment by jdegenstein** [comment]
Came across this issue, and we are seeing a struct.error unpack with a "real-world" font that causes my application to crash. 

Further details:
https://github.com/jdegenstein/jmwright-CQ-Editor/issues/11

Had to resort to using ProcMon64 to trace this to the individual font... not something an average user would be capable of.

**Comment by kenmcd** [comment]
The "real-world" test fonts mentioned above: [comickbook.zip](https://github.com/fonttools/fonttools/files/11764012/comickbook.zip)

The fonts appear to have an issue in the OS/2 table.
`ttx` dump says this:
```
<OS_2 ERROR="decompilation error" raw="True">
  <!-- An error occurred during the decompilation of this table -->
  <!-- Traceback (most recent call last):
         File "C:\Users\Ken\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\ttFont.py", line 470, in _readTable
           table.decompile(data, self)
         File "C:\Users\Ken\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\tables\O_S_2f_2.py", line 118, in decompile
           dummy, data = sstruct.unpack2(OS2_format_1_addition, data, self)
         File "C:\Users\Ken\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\misc\sstruct.py", line 106, in unpack2
           return unpack(fmt, data[:length], obj), data[length:]
         File "C:\Users\Ken\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\misc\sstruct.py", line 88, in unpack
           elements = struct.unpack(formatstring, data)
       struct.error: unpack requires a buffer of 8 bytes
        -->
  <hexdata>
    00010431 01900005 0000059a 05330000
    0125059a 05330000 03a00066 02120000
    02000400 00000000 00008000 00270000
    00000000 00000000 00004745 4d000000
    0020f002 064afda8 000008bf 0258
  </hexdata>
</OS_2>
```

Also a traceback is available in the link above. 
(which appears to reference the same `fonttools` files as the `ttx` dump above)
