### ISSUE TITLE
AttributeError Error with instantiateSTAT : 'tuple' object has no attribute 'minimum'

### ISSUE THREAD

**Issue by HugoJourdan** [fonttools/fonttools#3080]
I try to subset and instantiate STAT table with `instantiateSTAT` here is my code :

```python
# Partially instantiate the font by setting the axis range
instantiateVariableFont(font, {"wght":(500, 900), "ital":(0,16), "mono":(50,50)}, inplace=True)

# Update the STAT table to reflect the new axis range
instantiateSTAT(font, {"wght":(500, 900), "ital":(0,16), "mono":(50,50)})
```

and I got the error:

```python
  File "/Users/hugojourdan/XXXXX/XXXXXXXX/from fontTools.ttLib import TTFont", line 19, in <module>
    instantiateSTAT(font, {"wght":(68, 120), "ital":(5,16), "mono":(50,50)})
  File "/usr/local/lib/python3.11/site-packages/fontTools/varLib/instancer/__init__.py", line 1008, in instantiateSTAT
    newAxisValueTables = axisValuesFromAxisLimits(stat, axisLimits)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fontTools/varLib/instancer/__init__.py", line 1036, in axisValuesFromAxisLimits
    if isAxisValueOutsideLimits(axisTag, axisValue):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fontTools/varLib/instancer/__init__.py", line 1020, in isAxisValueOutsideLimits
    if axisValue < triple.minimum or axisValue > triple.maximum:
                   ^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'minimum'
```

**Comment by behdad** [comment]
Why do you need to instantiate `STAT` separately?

Try:
```
from fontTools.varLib.instancer import AxisRange
instantiateSTAT(font, {"wght":AxisRange(500, 900), "ital":AxisRange(0,16), "mono":AxisRange(50,50)})
```

**Comment by HugoJourdan** [comment]
```python
instantiateVariableFont(font, {"wght":(500, 900), "ital":(0,16), "mono":(50,50)}, inplace=True)
```

Don't remove certain instances from the fvar table. Instances out of new range are replaced by others.

![Screenshot 2023-04-14 at 20 09 47](https://user-images.githubusercontent.com/76793951/232124119-43bb1aec-adf5-42a3-afe1-3406ccf8f010.png)
(Here for example, It duplicate Semi Mono Thin, three extra times)

`DeprecationWarning: AxisRange is deprecated; use AxisTriple instead`

```python
instantiateSTAT(font, {"wght":AxisTriple(500,500, 900), "ital":AxisTriple(0,0,16), "mono":AxisTriple(50,50,50)})
```

Return me Key Error :

```python
File "/Users/hugojourdan/XXXX/XXXXXXXX/from fontTools.ttLib import TTFont", line 23, in <module>
    font.save(output_font_path)
  File "/usr/local/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 201, in save
    writer_reordersTables = self._save(tmp)
                            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 248, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/usr/local/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 700, in _writeTable
    tabledata = self.getTableData(tag)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 722, in getTableData
    return self.tables[tag].compile(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fontTools/ttLib/tables/_a_v_a_r.py", line 52, in compile
    axisTags = [axis.axisTag for axis in ttFont["fvar"].axes]
                                         ~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 442, in __getitem__
    table = self._readTable(tag)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 449, in _readTable
    data = self.reader[tag]
           ~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.11/site-packages/fontTools/ttLib/sfnt.py", line 108, in __getitem__
    entry = self.tables[Tag(tag)]
            ~~~~~~~~~~~^^^^^^^^^^
KeyError: 'fvar'
```

**Comment by qwazwsx** [comment]
Font noob here so I'm sure I won't be much help. But I run into a similar error when trying to export a static instance of a variable font. Font used is Roboto from Google Fonts.
```python
user@computer:/$ fonttools varLib.mutator Roboto-Regular.ttf
Location: {}
Loading variable font
Traceback (most recent call last):
  File "/home/tony/.local/bin/fonttools", line 8, in <module>
    sys.exit(main())
  File "/home/tony/.local/lib/python3.10/site-packages/fontTools/__main__.py", line 31, in main
    runpy.run_module(mod, run_name="__main__")
  File "/usr/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tony/.local/lib/python3.10/site-packages/fontTools/varLib/mutator.py", line 515, in <module>
    sys.exit(main())
  File "/home/tony/.local/lib/python3.10/site-packages/fontTools/varLib/mutator.py", line 505, in main
    instantiateVariableFont(varfont, loc, inplace=True, overlap=options.overlap)
  File "/home/tony/.local/lib/python3.10/site-packages/fontTools/varLib/mutator.py", line 185, in instantiateVariableFont
    fvar = varfont["fvar"]
  File "/home/tony/.local/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 461, in __getitem__
    table = self._readTable(tag)
  File "/home/tony/.local/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 468, in _readTable
    data = self.reader[tag]
  File "/home/tony/.local/lib/python3.10/site-packages/fontTools/ttLib/sfnt.py", line 109, in __getitem__
    entry = self.tables[Tag(tag)]
KeyError: 'fvar'

```

**Comment by anthrotype** [comment]
Roboto-Regular.ttf is not a variable font, fonttools varLib.instancer (or the old mutator) are for instancing variable fonts.

**Comment by khaledhosny** [comment]
I think we should still give a more sensible error, though.

**Comment by anthrotype** [comment]
> AttributeError: 'tuple' object has no attribute 'minimum'

instantiateSTAT is not meant to be a public method that one should call from outside fonttools, it doesn't automatically convert the input bare tuples to internal AxisRange objects.
It is called already by instantiateVariableFont internally, you don't need to call it afterwards yourself.
In fact, it may even fail when you try to do that, because the font you get from instantiateVariableFont is no longer variable (has no 'fvar').

**Comment by anthrotype** [comment]
I think Behdad's comment above https://github.com/fonttools/fonttools/issues/3080#issuecomment-1508951010 already answered the question from the OP so this can be closed
