### ISSUE TITLE
[merge] Crash when merging two CFF CID-keyed font

### ISSUE THREAD

**Issue by NightFurySL2001** [fonttools/fonttools#3175]
When inputting two CFF CID-keyed font, an error occured as below:

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\Scripts\pyftmerge.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\misc\loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\merge\__init__.py", line 205, in main
    font = merger.merge(fontfiles)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\merge\__init__.py", line 118, in merge
    table = clazz(tag).merge(self, tables)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\merge\tables.py", line 250, in merge
    private = newfont.Private
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\cffLib\__init__.py", line 2647, in __getattr__
    raise AttributeError(name)
AttributeError: Private
```

**Comment by behdad** [comment]
Are you able to provide fonts to reproduce the issue?
CFF is hard to debug for me, but I can give it a try.

**Comment by behdad** [comment]
According to comments in the merger, merging CID-keyed fonts is not supported. I'm not sure why you don't get the nice error message though.

**Comment by behdad** [comment]
Fixed the error message... I don't know when / if I can implement this.
