### ISSUE TITLE
pyftmerge error message

### ISSUE THREAD

**Issue by pathumego** [fonttools/fonttools#321]
When I try to merge a Sinhala font with a Latin I get this error. I don't have any features on the Sinhala.

```
Traceback (most recent call last):
  File "/usr/local/bin/pyftmerge", line 9, in <module>
    load_entry_point('fonttools==2.5', 'console_scripts', 'pyftmerge')()
  File "build/bdist.macosx-10.10-intel/egg/fontTools/merge.py", line 939, in main
  File "build/bdist.macosx-10.10-intel/egg/fontTools/merge.py", line 769, in merge
  File "build/bdist.macosx-10.10-intel/egg/fontTools/merge.py", line 466, in merge
AttributeError: 'NoneType' object has no attribute 'Lookup'
```

**Comment by weiweihuanghuang** [comment]
I get this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/pyftmerge", line 9, in <module>
    load_entry_point('fonttools==2.5', 'console_scripts', 'pyftmerge')()
  File "/Library/Python/2.7/site-packages/fonttools-2.5-py2.7.egg/fontTools/merge.py", line 940, in main
    font = merger.merge(args)
  File "/Library/Python/2.7/site-packages/fonttools-2.5-py2.7.egg/fontTools/merge.py", line 770, in merge
    table = clazz(tag).merge(self, tables)
  File "/Library/Python/2.7/site-packages/fonttools-2.5-py2.7.egg/fontTools/merge.py", line 374, in merge
    assert m.duplicateGlyphsPerFont[fontIdx].get(oldgid, gid) == gid
AssertionError
```
