### ISSUE TITLE
[T1Lib] T1Font.saveAs() broken?

### ISSUE THREAD

**Issue by sl2c** [fonttools/fonttools#3238]
After doing:

```
t1 = T1Font('font.pfb')
t1.parse()
t1.saveAs('font-out.pfb', 'PFB')
```

and trying to open the resulting pfb file in fontforge I get an error from fontforge:

> Didn't understand "/...  " in blended font defn

This happens for every .pfb font I've tried (the original files are opened in fontforge with no problems at all).

Using the latest pip3 install of fontTools

**Comment by sl2c** [comment]
[fonts.zip](https://github.com/fonttools/fonttools/files/12250893/fonts.zip)

**Comment by justvanrossum** [comment]
I've managed to fix the problems, but be aware that Type 1 is extremely Legacy, and `fontTools.t1Lib` is hardly maintained.

`fontTools.t1Lib` has had only limited use, and _mostly_ for reading. Writing has hardly been testing in the field.

So while #3240 seems to address the issues exposed by this font, I'm not guaranteeing much support for the future.

Please reconsider wether you really really _really_ need Type1 fonts in the first place.

**Comment by sl2c** [comment]
Thanks form the prompt fix!

I've run your commit and the result causes the fontforge to output the same error. Not sure, what the problem is. At one point I thought that it's because I'm running it in python3 (the T1Font page on python docs says something like "python 2 only"), so I tried running under Python 2 and I get this:

Python 2.7.16 (default, Mar 25 2021, 18:52:10) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from fontTools.t1Lib import T1Font
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/Code/Python/lib/fontTools/__init__.py", line 2, in <module>
    from fontTools.misc.loggingTools import configLogger
  File "/Users/user/Code/Python/lib/fontTools/misc/loggingTools.py", line 5, in <module>
    from collections.abc import Mapping, Callable
ImportError: No module named abc

Any ideas on how to troubleshoot this?

As for your:
> Please reconsider wether you really really really need Type1 fonts in the first place.
well, the Type1 fonts may be retired by Adobe, but these are almost exclusively the fonts used in TeX/LaTeX typesetting. In other words, pretty much every scientific paper published to date (I mean those that were electronically typeset, and I exclude the ugly MS Word-typeset ones) and pretty much every paper that will be publish in the next decade will be using Type1 fonts exclusively.

(The reason is that in TeX/LaTeX, there are gazillion lines of tex code written for packages that heavily rely on the fonts being in the TFM/PFB combo; It's hard to imagine how a transition may occur to anything other than that. There's, of course, XeTeX/XeLaTeX, which uses TTF fonts, but it's incompatible on the package level, and so despite some initial promise, its use by the scientific community is negligible)

So, I am sorry to say that as far as publishing science is concerned, Type1 fonts are to stay for at least another decade (subjectively).

And as for whether I personally really need these — yes, I'm myself a scientist and I'm writing a tool that will migrate pre-Type1 era scientific papers to the Type1 era, so to say, by replacing the Type3 fonts with Type1 — kinda like what the https://en.wikipedia.org/wiki/Pkfix and https://ctan.org/pkg/pkfix-helper?lang=en do, but for PDFs instead of Postscript files.

Why not move one step further: Type3 --> TTF. Well, because these old fonts are only available in Type1, and some of them — not even in Type1, but in the form of the METAFONT sources (https://en.wikipedia.org/wiki/Metafont). And for these I am using a tool called mftrace  (https://ctan.org/pkg/mftrace?lang=en) that vector-traces bitmaps with the help of potrace (https://potrace.sourceforge.net/) to produce, you guessed it, Type1 PFB files.

Now, if you know of a way to convert Type1 to TTF I would love to use it of course — that would add another step to all the processes I described above, and in the end my code would go for a direct replacement of Type3 --> TrueType inside PDFs. Otherwise, I guess I am stuck with Type1 and with asking you to fix more bugs.

An alternative would be for me to read the Adobe Type1 font spec, figure out what the current code in T1Lib does, and join the ranks of its developers. But frankly, I am already overstretched as it is, given the mess I mentioned above.

And this is why I am really really asking for help here. And I think the cause is worth the effort.

Btw, when in my first successful test a file is converted from using raster fonts at 300dpi to using vector Type1 fonts (with proper hinting) the results look just amazing. Let me know if you have time for watching a few beautiful glyphs in the formulas in scientific papers, I might upload a few. If not just take my word for it — this might give new life to tons of old papers, for which no TeX/LaTeX sources exist anymore. And which look uglier than they should.

**Comment by justvanrossum** [comment]
> I've run your commit and the result causes the fontforge to output the same error.

No idea — are you sure you are running the patched fonttools?

> so I tried running under Python 2

FontTools does not support Python 2.

**Comment by sl2c** [comment]
> > I've run your commit and the result causes the fontforge to output the same error.
> 
> No idea — are you sure you are running the patched fonttools?

I am: I cloned master, but it for some reason had the old version of the file (so I assumed the commit was to a branch other than master, but I couldn't figure out which), so what I did was: I opened the commit page:

https://github.com/fonttools/fonttools/commit/2808d995b2e66969d84470450b168d928c0336d7

then clicked browse files:

https://github.com/fonttools/fonttools/tree/2808d995b2e66969d84470450b168d928c0336d7

then clicked Code and chose to download ZIP.

After unpacking I made sure the new t1Lib/__init__.py reflected the changes you made (all this bc I have no idea how to use github properly, I suppose). But none of that helped.

> 
> > so I tried running under Python 2
> 
> FontTools does not support Python 2.

https://fonttools.readthedocs.io/en/latest/t1Lib.html — I meant the header here.

**Comment by justvanrossum** [comment]
> https://fonttools.readthedocs.io/en/latest/t1Lib.html — I meant the header here.

Ah, that's a stale comment. I've removed it in my PR.

What you can do to check whether you are actually running the patched module is to introduce an error, say add `raise AssertionError("test")` at some place in the patched code that you know must run. For example in the `T1Font.__init__()`.

**Comment by sl2c** [comment]
Did that, and it raises the error, as expected.

I've attached the before/after pfb files, as well as the __init__.py file I got.
[fonts.zip](https://github.com/fonttools/fonttools/files/12257446/fonts.zip)

**Comment by justvanrossum** [comment]
I don't have fontforge, but another tool opens the "-out" font just fine (which it didn't with your initial fonts.zip). There still may be something wrong with the font, but I'm out of capacity to debug this further. If you can find out specifically what makes fontforge choke on this font we can perhaps work out a further fix.

**Comment by sl2c** [comment]
I tried to use the resulting file with pdftex (it embeds pfb files into PDF, basically). The output:

!pdfTeX error: pdftex (file ./file-out.pfb): 138039 bytes more than expected
 ==> Fatal error occurred, no output PDF file produced!

**Comment by justvanrossum** [comment]
I merged #3240, but will reopen this as the issues aren't completely resolved.

**Comment by miguelsousa** [comment]
@sl2c with [this script](https://gist.github.com/miguelsousa/66ee9504039a8b64c605defa316516c1) you can convert a Type 1 font into an OpenType-CFF font.
If you need a TrueType font you can use [otf2ttf.py](https://github.com/fonttools/fonttools/blob/main/Snippets/otf2ttf.py) to convert the OTF font.

**Comment by miguelsousa** [comment]
@justvanrossum I used the AFDKO's `detype1` tool to convert the **font-out.pfb** file into a PFA and the charstrings are garbled. If I use **font.pfb** instead the charstrings look correct.

**Comment by justvanrossum** [comment]
Is the out font you’re looking at made with fonttools after my initial set of fixes? Because I did fix a lot, but apparently not enough. But I believe the charstrings survive now.

**Comment by miguelsousa** [comment]
> But I believe the charstrings survive now.

Confirmed. My feedback was based on a file that was posted at the start of the thread.
I've updated to 4.42.1, round-tripped the PFB font, and the output looks good. Sorry for the false alarm.

**Comment by ihsandeniz** [comment]
I went looking at this one on current `main` (4a4138d7), using the `sfrm1000.pfb` that was attached to this thread in 2023. Summary: the failure that was reported here is gone, but the round-trip still drops something, so the issue may want closing or re-scoping rather than fixing as filed.

### The original problem is fixed

| | bytes | identical to input |
| --- | --: | --- |
| input `sfrm1000.pfb` | 138258 | — |
| `T1Font(...)` → `saveAs(...)` (no `parse()`) | 138258 | **yes, byte for byte** |
| `T1Font(...)` → `parse()` → `saveAs(...)` | 139110 | no |
| the `-out` file attached here in 2023 | 124979 | no (**13 KB smaller**) |

Structurally the `parse()` round-trip is clean now: **585 glyphs in, 585 out**, same glyph names, **zero charstring programs changed**, no decompile errors, no top-level key differences. The 13 KB shortfall in the 2023 output was the real corruption, and it no longer reproduces — consistent with what @miguelsousa found on 4.42.1 ("the output looks good. Sorry for the false alarm").

So the specific complaint (`saveAs` producing an unusable font) does not reproduce on `main`.

### What the round-trip still drops

The `+852` bytes above are not a size problem; the interesting part is what disappears from the cleartext header. Diffing segment 0 (24 lines → 21):

```
- %!FontType1-1.0: SFRM1000 0.3
- %%CreationDate: Wed Sep 12 2001
- % Copyright (c) 2001 Vladimir Volovich <vvv@vsu.ru>.
- % See the file COPYING (GNU General Public License) for license conditions.
- % Converted from METAFONT EC/TC and LH fonts:
- %   ecrm1000, tcrm1000, larm1000, lbrm1000, lcrm1000, rxrm1000.
+ %!FontType1-1.1: SFRM1000
+ %t1Font: (4.65.1.dev0)
+ %%BeginResource: font SFRM1000
```

The copyright line and the GPL licence pointer are part of what the round-trip discards, along with `readonly` on two definitions (`end readonly def` → `end def`, `/FontBBox{...}readonly def` → `/FontBBox {...} def`). The PFB segment headers stay consistent (declared length matches actual length in all three segments), so the container itself is fine.

Whether that matters is a judgement call I can't make for you. For a GPL-licensed font it is at least awkward that a library round-trip removes the licence notice, but I don't know if `t1Lib` intends to preserve header comments at all — and given the "extremely Legacy, hardly maintained" framing in this thread, "it doesn't" is a perfectly reasonable answer.

### Suggestion

If you want this issue to reflect reality, I'd close it: the reported corruption is fixed, and the reporter's own workaround note ("if I remove the `t1.parse()` step it produces a correct file") is still accurate — without `parse()` the output is byte-identical to the input.

If the header loss is worth tracking, it is a different and much narrower thing than what this issue says, so a fresh issue would probably read better than reopening the scope here. I'm happy to file that one with the measurements above if you'd like, but I won't unless you say so — no point adding to the pile if `t1Lib` isn't taking changes.

Method: Python 3.14, `git archive origin/main` into a clean tree, structural comparison via `T1Font.parse()` (glyph set, decompiled charstring programs, Private dict, Subrs lengths) plus a PFB segment-header check.
