### ISSUE TITLE
CMAP decompile error

### ISSUE THREAD

**Issue by moi15moi** [fonttools/fonttools#3256]
When I am trying to get an font cmap, I get an exception
You can download the font here: [DFHSMincho-W9__DFPHSMincho-W9__DFGHSMincho-W9.zip](https://github.com/fonttools/fonttools/files/12339813/DFHSMincho-W9__DFPHSMincho-W9__DFGHSMincho-W9.zip)

Sample
```pyfrom fontTools.ttLib.ttFont import TTFont

ttFont = TTFont(r"C:\Users\Admin\Downloads\DFHSMincho-W9__DFPHSMincho-W9__DFGHSMincho-W9.TTC", fontNumber=0)
cmap_table = ttFont["cmap"].getcmap(3,1)

print(cmap_table.cmap)
```

Which raise this exception:
```py
Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\import ctypes.py", line 6, in <module>
    print(cmap_table.cmap)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\tables\_c_m_a_p.py", line 289, in __getattr__
    self.ensureDecompiled()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\tables\_c_m_a_p.py", line 278, in ensureDecompiled
    self.decompile(None, None)  # use saved data.
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\ttLib\tables\_c_m_a_p.py", line 918, in decompile
    assert index < lenGIArray, (
AssertionError: In format 4 cmap, range (165), the calculated index (22351) into the glyph index array is not less than the length of the array (22351) !
```

Why is it happening?
What can I do to avoid it.

**Comment by justvanrossum** [comment]
The font is invalid; ots also rejects it.

**Comment by moi15moi** [comment]
I tested with libass which use freetype and it can correctly decode the cmap.
Why fonttools should reject it?
