### ISSUE TITLE
`FontBuilder` can't  `setupVerticalHeader()`

### ISSUE THREAD

**Issue by TakWolf** [fonttools/fonttools#3289]
fonttools==4.43.0

```python
builder = FontBuilder(2048, isTTF=is_ttf)

# some setup

builder.setupVerticalHeader(
    ascent=ascent,
    descent=descent,
)

# other setup

builder.save(file_path)
```

Cause error:

```
DEBUG:fontTools.ttLib.ttFont:Compiling 'maxp' table
DEBUG:fontTools.ttLib.ttFont:Writing 'maxp' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'CFF ' table
DEBUG:fontTools.ttLib.ttFont:Writing 'CFF ' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'head' table
DEBUG:fontTools.ttLib.ttFont:Writing 'head' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'hmtx' table
DEBUG:fontTools.ttLib.ttFont:Writing 'hmtx' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'hhea' table
DEBUG:fontTools.ttLib.ttFont:Writing 'hhea' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'OS/2' table
DEBUG:fontTools.ttLib.ttFont:Writing 'OS/2' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'name' table
DEBUG:fontTools.ttLib.ttFont:Writing 'name' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'cmap' table
DEBUG:fontTools.ttLib.ttFont:Writing 'cmap' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'post' table
DEBUG:fontTools.ttLib.ttFont:Writing 'post' table to disk
DEBUG:fontTools.ttLib.ttFont:Compiling 'vhea' table
Traceback (most recent call last):
  File "E:\Projects\Python\pixel-font-builder\examples\demo.py", line 183, in <module>
    main()
  File "E:\Projects\Python\pixel-font-builder\examples\demo.py", line 168, in main
    builder.save_otf(os.path.join(build_dir, 'demo.otf'))
  File "E:\Projects\Python\pixel-font-builder\src\pixel_font_builder\font.py", line 68, in save_otf
    self.to_otf_builder(flavor).save(file_path)
  File "E:\Projects\Python\pixel-font-builder\venv\Lib\site-packages\fontTools\fontBuilder.py", line 356, in save
    self.font.save(file)
  File "E:\Projects\Python\pixel-font-builder\venv\Lib\site-packages\fontTools\ttLib\ttFont.py", line 212, in save
    writer_reordersTables = self._save(tmp)
                            ^^^^^^^^^^^^^^^
  File "E:\Projects\Python\pixel-font-builder\venv\Lib\site-packages\fontTools\ttLib\ttFont.py", line 259, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "E:\Projects\Python\pixel-font-builder\venv\Lib\site-packages\fontTools\ttLib\ttFont.py", line 710, in _writeTable
    tabledata = self.getTableData(tag)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\Python\pixel-font-builder\venv\Lib\site-packages\fontTools\ttLib\ttFont.py", line 732, in getTableData
    return self.tables[tag].compile(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\Python\pixel-font-builder\venv\Lib\site-packages\fontTools\ttLib\tables\_v_h_e_a.py", line 48, in compile
    self.recalc(ttFont)
  File "E:\Projects\Python\pixel-font-builder\venv\Lib\site-packages\fontTools\ttLib\tables\_v_h_e_a.py", line 88, in recalc
    advanceHeight, tsb = vmtxTable[name]
                         ^^^^^^^^^
UnboundLocalError: cannot access local variable 'vmtxTable' where it is not associated with a value
```

**Comment by anthrotype** [comment]
hm NameError is never nice and we shall fix it, but looks like your font has vhea without vmtx table, which is a little weird

**Comment by justvanrossum** [comment]
Yeah, agreed on the poor error, but you can't do `builder.setupVerticalHeader()` without doing `builder.setupVerticalMetrics()`.

**Comment by TakWolf** [comment]
I got it, let me check!
