### ISSUE TITLE
[varLib.instancer] Can’t slice/instance VF after adding new default location

### ISSUE THREAD

**Issue by arrowtype** [fonttools/fonttools#3291]
This is not an urgent issue for me, but just something I noticed was unexpected, and seems like a bug. I’m getting this result with fonttools `4.43.1`.

If I run the instancer on a TTF which has already been given a new default location (with the Instancer), I get this error:

```bash
▶ fonttools varLib.instancer fonts__trial/ArrowType-NameSans-v1-Trial/variable/AT-NameSansVariable.Trial.ttf wght=400:700 opsz=12:72 ital=0:1
Restricting axes: {'wght': (400, None, 700), 'opsz': (12, None, 72), 'ital': (0, None, 1)}
Loading variable font
Restricted limits: {'wght': (400, 400, 700), 'opsz': (12, 12, 72), 'ital': (0, 0, 1)}
Normalized limits: {'opsz': (0, 0, 1, 0, 60), 'wght': (0, 0, 0.508728, 399, 600), 'ital': (0, 0, 1, 0, 1)}
Instantiating glyf/gvar tables
Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/name-sans/venv/bin/fonttools", line 8, in <module>
    sys.exit(main())
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/fontTools/__main__.py", line 31, in main
    runpy.run_module(mod, run_name="__main__")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/fontTools/varLib/instancer/__main__.py", line 5, in <module>
    sys.exit(main())
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/fontTools/varLib/instancer/__init__.py", line 1487, in main
    instantiateVariableFont(
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/fontTools/varLib/instancer/__init__.py", line 1236, in instantiateVariableFont
    instantiateGvar(varfont, normalizedLimits, optimize=optimize)
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/fontTools/varLib/instancer/__init__.py", line 638, in instantiateGvar
    _instantiateGvarGlyph(
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/fontTools/varLib/instancer/__init__.py", line 559, in _instantiateGvarGlyph
    defaultDeltas = instantiateTupleVariationStore(
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/fontTools/varLib/instancer/__init__.py", line 480, in instantiateTupleVariationStore
    newVariations = changeTupleVariationsAxisLimits(variations, axisLimits)
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/fontTools/varLib/instancer/__init__.py", line 510, in changeTupleVariationsAxisLimits
    newVariations.extend(changeTupleVariationAxisLimit(var, axisTag, axisLimit))
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/fontTools/varLib/instancer/__init__.py", line 531, in changeTupleVariationAxisLimit
    solutions = solver.rebaseTent(tent, axisLimit)
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/fontTools/varLib/instancer/solver.py", line 296, in rebaseTent
    sols = _solve(tent, axisLimit)
  File "/Users/stephennixon/type-repos/name-sans/venv/lib/python3.10/site-packages/fontTools/varLib/instancer/solver.py", line 178, in _solve
    assert axisMax <= newUpper  # Because outGain >= gain
AssertionError
(venv) 
```

The default location was previously added in Python with this code ([here’s the full script](https://gist.github.com/arrowtype/9fefe9633cae500bbaf0000230f6a3ed)):

```py
# create a new font with a default of 400 for the wght axis
newFont = instancer.instantiateVariableFont(varfont, {"wght": (minWght, 400, maxWght)})
```

However, if I run it on a file that is identical aside from not having that new default location, it works smoothly as expected:

```bash
▶ fonttools varLib.instancer fonts__trial/ArrowType-NameSans-v1-Trial/variable/AT-NameSansVariable.Trial.ttf wght=400:700 opsz=12:72 ital=0:1
Restricting axes: {'wght': (400, None, 700), 'opsz': (12, None, 72), 'ital': (0, None, 1)}
Loading variable font
Restricted limits: {'wght': (400, 700, 700), 'opsz': (12, 12, 72), 'ital': (0, 0, 1)}
Normalized limits: {'opsz': (0, 0, 1, 0, 60), 'wght': (-0.444458, 0, 0, 699, 300), 'ital': (0, 0, 1, 0, 1)}
Instantiating glyf/gvar tables
Instantiating MVAR table
Instantiating HVAR table
Instantiating GDEF and GPOS tables
Instantiating FeatureVariations of GSUB table
Instantiating avar table
Instantiating STAT table
Instantiating fvar table
Pruning name table
Saving instance font fonts__trial/ArrowType-NameSans-v1-Trial/variable/AT-NameSansVariable.Trial-instance.ttf
```

The same issue occurs on my "non-trial" fonts, too, so the subsetting and name changes in the trial fonts isn’t causing the issue.

This zip contains a font with and without the default location. Please feel free to use it in debugging the issue, if you like. I am also happy to email other files, if helpful!

[ArrowType-NameSans-v1-Trial-for_FontTools_Issue_Report.zip](https://github.com/fonttools/fonttools/files/12830897/ArrowType-NameSans-v1-Trial-for_FontTools_Issue_Report.zip)

The workaround is simple for me so this isn’t something I’m particularly worried about, but I wanted to report it rather than ignore it.

As always, thanks for such amazing tools!

**Comment by behdad** [comment]
Can you try this patch (only the first part is important):
```diff
index c991fcdcf..f9f2e78c0 100644
--- a/Lib/fontTools/varLib/instancer/solver.py
+++ b/Lib/fontTools/varLib/instancer/solver.py
@@ -99,7 +99,7 @@ def _solve(tent, axisLimit, negative=False):
     #                axisDef    |  axisMax
     #                           |
     #                      crossing
-    if gain > outGain:
+    if gain >= outGain:
         # Crossing point on the axis.
         crossing = peak + (1 - gain) * (upper - peak)
 
@@ -175,7 +175,7 @@ def _solve(tent, axisLimit, negative=False):
         #              axisDef      axisMax
         #
         newUpper = peak + (1 - gain) * (upper - peak)
-        assert axisMax <= newUpper  # Because outGain >= gain
+        assert axisMax <= newUpper  # Because outGain > gain
         if newUpper <= axisDef + (axisMax - axisDef) * 2:
             upper = newUpper
             if not negative and axisDef + (axisMax - axisDef) * MAX_F2DOT14 < upper:
```

**Comment by behdad** [comment]
I need to study the code a bit more. But I think this is the correct change.

**Comment by arrowtype** [comment]
Yes, sorry for the delay! I'm launching a couple of things, so my mind is in a hundred places at once. I plan to test this later today or tomorrow.

**Comment by arrowtype** [comment]
Hey @behdad, amazing work! The patch appears to work perfectly on my example.

```bash
▶ fonttools varLib.instancer fonts__trial/ArrowType-NameSans-v1-Trial-for_FontTools_Issue_Report/AT-NameSansVariable-new_default_loc.Trial.ttf wght=400:700 opsz=12:72 ital=0:1
Restricting axes: {'wght': (400, None, 700), 'opsz': (12, None, 72), 'ital': (0, None, 1)}
Loading variable font
Restricted limits: {'wght': (400, 400, 700), 'opsz': (12, 12, 72), 'ital': (0, 0, 1)}
Normalized limits: {'opsz': (0, 0, 1, 0, 60), 'wght': (0, 0, 0.508728, 399, 600), 'ital': (0, 0, 1, 0, 1)}
Instantiating glyf/gvar tables
Instantiating MVAR table
Instantiating HVAR table
Instantiating GDEF and GPOS tables
Instantiating FeatureVariations of GSUB table
Instantiating avar table
Instantiating STAT table
Instantiating fvar table
Pruning name table
Saving instance font fonts__trial/ArrowType-NameSans-v1-Trial-for_FontTools_Issue_Report/AT-NameSansVariable-new_default_loc.Trial-instance.ttf
```

The input had a wght range of 1–1000, with a new default of 400 added in post-build. The output now has a wght range limited to 400–700:
[AT-NameSansVariable-new_default_loc.Trial-instance.ttf.zip](https://github.com/fonttools/fonttools/files/12862716/AT-NameSansVariable-new_default_loc.Trial-instance.ttf.zip)

I wasn’t sure if there was a branch, so I literally just copied your code edits directly into the solver.py of fonttools in my current virtual environment. But yeah, it seems to work great!

**Comment by behdad** [comment]
Thanks @arrowtype. I'll review the code some more and commit it.

**Comment by behdad** [comment]
Okay, the fix was slightly more involved. @arrowtype Can you test the PR?

**Comment by arrowtype** [comment]
Sorry I wasn’t able to test this sooner. Looks like the PR has been reviewed and merged already, so I assume things are working well? Thanks so much for your work on it, @behdad and @anthrotype!

**Comment by behdad** [comment]
Yeah I think this is good now.
