### ISSUE TITLE
[subset] Subsetting doesn't work for Tabler Icons

### ISSUE THREAD

**Issue by loqusion** [fonttools/fonttools#3372]
I'm trying to do font subsetting on [Tabler Icons](https://tabler-icons.io/). When I run the following:

```sh
pyftsubset tabler-icons.ttf --unicodes='U+eb30,U+f684'
```

It gives me this error:

```
WARNING: 'created' timestamp seems very low; regarding as unix timestamp
WARNING: 'modified' timestamp seems very low; regarding as unix timestamp
WARNING: Unknown Coverage format: 4707
Traceback (most recent call last):
  File "/usr/bin/pyftsubset", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fontTools/subset/__init__.py", line 3710, in main
    subsetter.subset(font)
  File "/usr/lib/python3.11/site-packages/fontTools/subset/__init__.py", line 3498, in subset
    self._closure_glyphs(font)
  File "/usr/lib/python3.11/site-packages/fontTools/subset/__init__.py", line 3306, in _closure_glyphs
    font["GSUB"].closure_glyphs(self)
  File "/usr/lib/python3.11/site-packages/fontTools/subset/__init__.py", line 1852, in closure_glyphs
    self.table.LookupList.Lookup[i].closure_glyphs(s)
  File "/usr/lib/python3.11/site-packages/fontTools/subset/__init__.py", line 1518, in closure_glyphs
    st.closure_glyphs(s, cur_glyphs)
  File "/usr/lib/python3.11/site-packages/fontTools/subset/__init__.py", line 598, in closure_glyphs
    for g, seqs in self.ligatures.items()
                   ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fontTools/ttLib/tables/otBase.py", line 894, in __getattr__
    self.decompile(reader, font)
  File "/usr/lib/python3.11/site-packages/fontTools/ttLib/tables/otBase.py", line 1004, in decompile
    self.postRead(table, font)
  File "/usr/lib/python3.11/site-packages/fontTools/ttLib/tables/otTables.py", line 1118, in postRead
    assert len(input) == len(ligSets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

### Versions

fontTools: `4.46.0`
Python: `3.11.6`
Tabler Icons: `2.36.0` or `2.42.0`

**Comment by anthrotype** [comment]
the warnings and the error seem to suggest the font is somehow broken/faulty.
Can you try to pass it throug the OTS (opentype sanitizer tool) and see if it passes validation?
I can't download the fonts (they seem behind a paywall)

```
$ pip3 install opentype-sanitizer
$ python3 -m ots tabler-icons.ttf
```

**Comment by loqusion** [comment]
Well, I've decided to use Phosphor icons since I'm able to subset with no problems. I guess I'll close the issue. Thanks for the help regardless!
