### ISSUE TITLE
Error when reading cmap of TTF

### ISSUE THREAD

**Issue by NightFurySL2001** [fonttools/fonttools#3394]
When trying to load the cmap of this font file, it raises this error:
```
Traceback (most recent call last):
  File "extractor\__init__.py", line 61, in extractUFO
  File "extractor\formats\opentype.py", line 52, in extractFontFromOpenType
  File "extractor\formats\opentype.py", line 529, in extractOpenTypeGlyphs
  File "fontTools\ttLib\ttFont.py", line 503, in get
  File "fontTools\ttLib\ttFont.py", line 452, in __getitem__
  File "fontTools\ttLib\ttFont.py", line 469, in _readTable
  File "fontTools\ttLib\tables\_h_m_t_x.py", line 52, in decompile
  File "fontTools\ttLib\ttFont.py", line 537, in getGlyphOrder
  File "fontTools\ttLib\ttFont.py", line 596, in _getGlyphNamesFromCmap
  File "fontTools\ttLib\ttFont.py", line 452, in __getitem__
  File "fontTools\ttLib\ttFont.py", line 469, in _readTable
  File "fontTools\ttLib\tables\_c_m_a_p.py", line 179, in decompile
  File "fontTools\ttLib\tables\_c_m_a_p.py", line 289, in __getattr__
  File "fontTools\ttLib\tables\_c_m_a_p.py", line 278, in ensureDecompiled
  File "fontTools\ttLib\tables\_c_m_a_p.py", line 905, in decompile
IndexError: array index out of range
```
[LXGWWenKai-Regular.zip](https://github.com/fonttools/fonttools/files/13673603/LXGWWenKai-Regular.zip)

**Comment by justvanrossum** [comment]
The cmap is corrupt:
```
$ python -m ots LXGWWenKai-Regular.ttf 
ERROR: cmap: Failed to read segment start range 441
ERROR: cmap: Failed to parse format 4 cmap subtable 0
ERROR: cmap: Failed to parse table
Failed to sanitize file!
```

**Comment by NightFurySL2001** [comment]
I see... It seems that the font file was created from https://github.com/nowar-fonts/Warcraft-Font-Merger, which uses otfcc to merge the fonts. I will try to investigate how this bug happened..
