### ISSUE TITLE
`IndexError: list index out of range` on Google Sans Flex

### ISSUE THREAD

**Issue by KTibow** [fonttools/fonttools#3411]
Whatever I try to do with Google Sans Flex, it errors. Here's one example:
```
> fonttools varLib.instancer google_sans_flex.ttf
Restricting axes: {}
Loading variable font
Restricted limits: {}
Normalized limits: {}
Instantiating glyf/gvar tables
Instantiating GDEF and GPOS tables
Traceback (most recent call last):
  File "/home/kendell/.local/bin/fonttools", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kendell/.local/lib/python3.11/site-packages/fontTools/__main__.py", line 31, in main
    runpy.run_module(mod, run_name="__main__")
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/home/kendell/.local/lib/python3.11/site-packages/fontTools/varLib/instancer/__main__.py", line 5, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kendell/.local/lib/python3.11/site-packages/fontTools/varLib/instancer/__init__.py", line 1544, in main
    instantiateVariableFont(
  File "/home/kendell/.local/lib/python3.11/site-packages/fontTools/varLib/instancer/__init__.py", line 1304, in instantiateVariableFont
    instantiateOTL(varfont, normalizedLimits)
  File "/home/kendell/.local/lib/python3.11/site-packages/fontTools/varLib/instancer/__init__.py", line 951, in instantiateOTL
    defaultDeltas = instantiateItemVariationStore(varStore, fvarAxes, axisLimits)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kendell/.local/lib/python3.11/site-packages/fontTools/varLib/instancer/__init__.py", line 914, in instantiateItemVariationStore
    tupleVarStore = _TupleVarStoreAdapter.fromItemVarStore(itemVarStore, fvarAxes)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kendell/.local/lib/python3.11/site-packages/fontTools/varLib/instancer/__init__.py", line 822, in fromItemVarStore
    for axes, coordinates in zip(varDataRegions, zip(*varData.Item)):
  File "/home/kendell/.local/lib/python3.11/site-packages/fontTools/varLib/instancer/__init__.py", line 821, in <genexpr>
    varDataRegions = (regions[i] for i in varData.VarRegionIndex)
                      ~~~~~~~^^^
IndexError: list index out of range
```

Here's the font, wrapped in a `.zip` (don't sue me google)
[google_sans_flex.zip](https://github.com/fonttools/fonttools/files/13868553/google_sans_flex.zip)

**Comment by justvanrossum** [comment]
The font is currupt. OTS says this:
```
ERROR: Variations: Bad region index
ERROR: Variations: Failed to parse variation data subtable
ERROR: GDEF: Invalid item variation store
ERROR: GDEF: Failed to parse table
```

**Comment by KTibow** [comment]
It opens with Fontdrop just fine - is there some way to only read the correct part or normalize it or something?

**Comment by davelab6** [comment]
This font isn't meant to be used outside Google, please delete it.
