### ISSUE TITLE
varLib.mutator Font instancing produces invalid font file for certain fonts

### ISSUE THREAD

**Issue by mitterdoo** [fonttools/fonttools#3478]
Hiya,

I'm trying to create static font files (TTF) for the font Bahnschrift (now included with Windows) since the variable font does not play nice with Autodesk Fusion. However, when I run this command:
```powershell
fonttools varLib.mutator .\bahnschrift.ttf wght=300 wdth=100
```
then I try to open the new font file, Windows gives me the following error:
![The requested file bahnschrift-instance.ttf is not a valid font file.](https://github.com/fonttools/fonttools/assets/4317493/dc56867e-36cf-4fa1-8995-389edcc36b9d)

I'm not sure what the cause is, and I tried several different weight/width values to no avail. Below is the output with the verbose flag enabled:
```
Location: {'wght': 300.0, 'wdth': 100.0}
Loading variable font
Reading 'fvar' table from disk
Decompiling 'fvar' table
Reading 'avar' table from disk
Decompiling 'avar' table
Normalized location: {'wght': -1.0, 'wdth': 0.0}
Mutating glyf/gvar tables
Reading 'gvar' table from disk
Decompiling 'gvar' table
Reading 'post' table from disk
Decompiling 'post' table
Reading 'maxp' table from disk
Decompiling 'maxp' table
Reading 'glyf' table from disk
Decompiling 'glyf' table
Reading 'loca' table from disk
Decompiling 'loca' table
Reading 'head' table from disk
Decompiling 'head' table
Reading 'hmtx' table from disk
Decompiling 'hmtx' table
Reading 'hhea' table from disk
Decompiling 'hhea' table
Reading 'vmtx' table from disk
Mutating MVAR table
Reading 'MVAR' table from disk
Decompiling 'MVAR' table
Reading 'OS/2' table from disk
Decompiling 'OS/2' table
Mutating FeatureVariations
Reading 'GSUB' table from disk
Decompiling 'GSUB' table
Reading 'GPOS' table from disk
Decompiling 'GPOS' table
Reading 'GDEF' table from disk
Decompiling 'GDEF' table
Mutating GDEF/GPOS/GSUB tables
Pruning name table
Reading 'name' table from disk
Decompiling 'name' table
Removing variable tables
Saving instance font .\bahnschrift-instance.ttf
Compiling 'glyf' table
Writing 'glyf' table to disk
Compiling 'maxp' table
Writing 'maxp' table to disk
Compiling 'loca' table
Writing 'loca' table to disk
Compiling 'head' table
Writing 'head' table to disk
Compiling 'hmtx' table
Writing 'hmtx' table to disk
Compiling 'hhea' table
Writing 'hhea' table to disk
Compiling 'OS/2' table
Reading 'cmap' table from disk
Decompiling 'cmap' table
Writing 'OS/2' table to disk
Compiling 'cmap' table
Writing 'cmap' table to disk
Reading 'fpgm' table from disk
Writing 'fpgm' table to disk
Reading 'prep' table from disk
Writing 'prep' table to disk
Reading 'cvt ' table from disk
Writing 'cvt ' table to disk
Compiling 'name' table
Writing 'name' table to disk
Compiling 'post' table
Writing 'post' table to disk
Reading 'gasp' table from disk
Writing 'gasp' table to disk
Compiling 'GDEF' table
Writing 'GDEF' table to disk
Compiling 'GPOS' table
uharfbuzz not found, compiling 'GPOS' with pure-python serializer
Writing 'GPOS' table to disk
Compiling 'GSUB' table
uharfbuzz not found, compiling 'GSUB' with pure-python serializer
Writing 'GSUB' table to disk
Reading 'meta' table from disk
Writing 'meta' table to disk
```

I tested this with another variable font I had, but the resulting instanced font worked fine. I could open it normally and install it. Maybe there's some proprietary data in Bahnschrift that doesn't work well with fonttools? I'm a bit out of my league diagnosing this--my knowledge of font files is pretty shallow.

My environment:

Fonttools version 4.51.0 (from pip)
Python 3.10.7
Windows 11 64-bit version 23H2 build 22631.3447

**Comment by kenmcd** [comment]
> It's possible that the font has a `DSIG` table?

Yes.

**Comment by behdad** [comment]
Would dropping that make it work? You can ttx the instanced font, remove the DSIG table, and ttx it back to ttf.

**Comment by ftCLI** [comment]
Using `varLib.instancer` works without removing the `DSIG` table, but the instancer cannot update the `name` table.

In line 225 of `varLib.instancer.names`, `None` is returned because `platformID` 1 is parsed before `platformID` 3. Probably `platformID` 3 should be preferred, or `axisValueNameIDs` should be retrieved from `platformID` 3 when they are not present in `platformID` 1



```
C:\Users\cg\Desktop\Banshrift>ftcli converter vf2i . -out static
[ INFO     ] Converting file: bahnschrift.ttf
[ INFO     ] Exporting instance 1 of 15
[ ERROR    ] 'NoneType' object has no attribute 'toUnicode'
Traceback (most recent call last):

  File "D:\PycharmProjects\FondryTools-CLI\foundryToolsCLI\CLI\ftcli_converter.py", line 227, in vf2i
    converter.run(variable_font=variable_font, instances=instances)
    │         │                 │                        └ [<fontTools.ttLib.tables._f_v_a_r.NamedInstance object at 0x000001DEC34E8F70>, <fontTools.ttLib.tables._f_v_a_r.NamedInstance...
    │         │                 └ <foundryToolsCLI.Lib.VFont.VariableFont object at 0x000001DEC3467940>
    │         └ <function VariableToStatic.run at 0x000001DEC3506710>
    └ <foundryToolsCLI.Lib.converters.variable_to_static.VariableToStatic object at 0x000001DEC3467850>

  File "D:\PycharmProjects\FondryTools-CLI\foundryToolsCLI\Lib\converters\variable_to_static.py", line 38, in run
    static_instance = instantiateVariableFont(
                      └ <function instantiateVariableFont at 0x000001DEC34EDF30>

  File "C:\Users\cg\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\varLib\instancer\__init__.py", line 1294, in instantiateVariableFont
    names.updateNameTable(varfont, axisLimits)
    │     │               │        └ AxisLimits({'wght': (300, 300, 300), 'wdth': (100, 100, 100)})
    │     │               └ <foundryToolsCLI.Lib.VFont.VariableFont object at 0x000001DEC3528100>
    │     └ <function updateNameTable at 0x000001DEC34A2440>
    └ <module 'fontTools.varLib.instancer.names' from 'C:\\Users\\cg\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packag...

  File "C:\Users\cg\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\varLib\instancer\names.py", line 131, in updateNameTable
    _updateNameRecords(varfont, axisValueTables)
    │                  │        └ [<fontTools.ttLib.tables.otTables.AxisValue object at 0x000001DEC3528760>]
    │                  └ <foundryToolsCLI.Lib.VFont.VariableFont object at 0x000001DEC3528100>
    └ <function _updateNameRecords at 0x000001DEC34A25F0>

  File "C:\Users\cg\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\varLib\instancer\names.py", line 224, in _updateNameRecords
    typoSubFamilyName = " ".join(

  File "C:\Users\cg\AppData\Local\Programs\Python\Python310\lib\site-packages\fontTools\varLib\instancer\names.py", line 225, in <genexpr>
    getName(n, *platform).toUnicode() for n in axisValueNameIDs
    │       │   │                         └ 258
    │       │   └ (1, 0, 0)
    │       └ 258
    └ <bound method table__n_a_m_e.getName of <'name' table at 1dec3529a20>>

AttributeError: 'NoneType' object has no attribute 'toUnicode'
[ INFO     ] Elapsed time: 0.0512 seconds
```

**Comment by anthrotype** [comment]
thanks @ftCLI - unhandled AttributeError is a bug, if getName can sometimes return None its caller must handle that (skip it). Could you PR that? Or I can do it later

**Comment by ftCLI** [comment]
I Have no idea of how to open a PR in a repository that is not mine (sorry, just a hobbist here). I tried to push a snippet few days ago but the push was rejected.

**Comment by anthrotype** [comment]
no worries. In case you're interested, see

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by justvanrossum** [comment]
> I Have no idea of how to open a PR in a repository that is not mine

You fork the project to your own account, make a branch there, commit and push. Use GH website to create PR from you own branch/fork.

**Comment by ftCLI** [comment]
Thanks both!

**Comment by ftCLI** [comment]
Quick and dirty: enclose the call to `instantiateVariableFont` in a try-except clause.

https://github.com/fonttools/fonttools/pull/3480

Maybe using `getDebugName` could be used instead of `getName`. This will compile the name table correctly in case the NameRecords are present only on one table (Mac or Win), but I don't know if this is wanted.
