### ISSUE TITLE
lineLineIntersections divide by zero

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#3515]
It's all a sea of horrible edge cases:

```
>>> from fontTools.misc.bezierTools import lineLineIntersections
>>> lineLineIntersections( (310,0), (310,10), (310,800), (310,810) )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/simon/others-repos/fonttools/Lib/fontTools/misc/bezierTools.py", line 1191, in lineLineIntersections
    slope34 = (e2y - s2y) / (e2x - s2x)
              ~~~~~~~~~~~~^~~~~~~~~~~~~
ZeroDivisionError: division by zero
```

**Comment by behdad** [comment]
Should we raise a "don't intersect" exception instead? Or ValueError?
