### ISSUE TITLE
`CFFToCFF2` (and possibly `CFF2ToCFF`) is very brittle

### ISSUE THREAD

**Issue by behdad** [fonttools/fonttools#3521]
Many fonts crash it currently. Keeping this issue to track my progress mostly.

**Comment by behdad** [comment]
Looks like now the main issue is broken files generated by `CFF2ToCFF`:

https://github.com/fonttools/fonttools/issues/3534#issuecomment-2134012246

**Comment by liZe** [comment]
I’ve tried many tools, including PDF readers (my use case is to include fonts in PDF files):
- Firefox’s PDF reader prints the "CFF : Failed to parse Top DICT Data"
- Other browsers I’ve tried are OK with the PDF
- No browser can use the font in a HTML/CSS document, with various useless error messages
- Evince prints "some font thing failed"
- Poppler prints "Couldn't create a font for 'GHXLSD+Cantarell-Light'" (that’s the internal name of the font in the PDF)
- Ghostscript and PDF validators I’ve tried are happy with the PDF
- Fontforge crashes when opening the font file
- Gnome Fonts prints "Could not display font"

Don’t hesitate to ping me if I can do anything to help.

**Comment by behdad** [comment]
Thanks. I'm debugging.

**Comment by behdad** [comment]
Working here now: https://github.com/fonttools/fonttools/pull/3536

Still no luck with CFF2ToCFF though.

**Comment by behdad** [comment]
@liZe please give https://github.com/fonttools/fonttools/pull/3536 a try. I think it should be good now.

**Comment by liZe** [comment]
> @liZe please give #3536 a try. I think it should be good now.

I get this stacktrace:
```
Traceback (most recent call last):
  File "/tmp/subset_font.py", line 7, in <module>
    output_font.save('output.otf')
  File "/home/lize/.local/share/venv/weasyprint/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 216, in save
    writer_reordersTables = self._save(tmp)
                            ^^^^^^^^^^^^^^^
  File "/home/lize/.local/share/venv/weasyprint/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 263, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/home/lize/.local/share/venv/weasyprint/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 713, in _writeTable
    tabledata = self.getTableData(tag)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lize/.local/share/venv/weasyprint/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 735, in getTableData
    return self.tables[tag].compile(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lize/.local/share/venv/weasyprint/lib/python3.12/site-packages/fontTools/ttLib/tables/_h_h_e_a.py", line 64, in compile
    self.recalc(ttFont)
  File "/home/lize/.local/share/venv/weasyprint/lib/python3.12/site-packages/fontTools/ttLib/tables/_h_h_e_a.py", line 94, in recalc
    cs = charStrings[name]
         ~~~~~~~~~~~^^^^^^
  File "/home/lize/.local/share/venv/weasyprint/lib/python3.12/site-packages/fontTools/cffLib/__init__.py", line 1040, in __getitem__
    charString = self.charStrings[name]
                 ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'A'
```

**Comment by behdad** [comment]
> I get this stacktrace:

Yes, unfortunately.

Can you try instancing without `--downgrade-cff2` and then invoke the `fonttools cffLib.CFF2ToCFF` module on the result? That one I expect to work.

**Comment by liZe** [comment]
> That one I expect to work.

Unfortunately, I get the same error. I’ve tried both:
```python
output_font = instantiateVariableFont(input_font, axis)
convertCFF2ToCFF(output_font)
output_font.save('output.otf')
```

and 

```python
output_font = instantiateVariableFont(input_font, axis)
output_font.save('output.otf')
output_font = TTFont('output.otf')
convertCFF2ToCFF(output_font)
output_font.save('output.otf')
```

**Comment by behdad** [comment]
> ```python
> output_font = instantiateVariableFont(input_font, axis)
> output_font.save('output.otf')
> output_font = TTFont('output.otf')

Try passing `recalcBounds=False` here.

> convertCFF2ToCFF(output_font)
> output_font.save('output.otf')
> ```

**Comment by liZe** [comment]
> Try passing `recalcBoxes=False` here.

It doesn’t crash anymore.

The font seems to work in some cases (in browsers for HTML documents) but is still broken and/or print warnings with others (in PDF in browsers, in Fontforge, with Poppler, and with Ghostscript where the broken font generated by the stable version was working).

Just in case it helps, Firefox prints a warning: `FormatError: Required "loca" table is not found`

**Comment by behdad** [comment]
> Just in case it helps, Firefox prints a warning: `FormatError: Required "loca" table is not found`

That's very weird.

**Comment by liZe** [comment]
> That's very weird.

I did something wrong with the PDF generation, my bad. Here’s what I get with my code fixed.

For the font generated by the Python script:
- Browsers work
- hb-view and hb-info work
- Fontforge crashes

Embedded in PDF:
- Evince and Poppler work
- Ghostscript works
- PDF validator works
- PDF viewers in browsers work, but Firefox prints error messages in console:

```
downloadable font: CFF : Failed to parse Top DICT Data (font-family: "g_d0_f1" style:normal weight:400 stretch:100 src index:0)
downloadable font: CFF : Failed to parse table (font-family: "g_d0_f1" style:normal weight:400 stretch:100 src index:0)
downloadable font: rejected by sanitizer (font-family: "g_d0_f1" style:normal weight:400 stretch:100 src index:0)
downloadable font: font load failed (font-family: "g_d0_f1" style:normal weight:400 stretch:100 src index:0)
```

The result is much better, thanks a lot!

**Comment by behdad** [comment]
Okay, good. Thank you. I'll keep digging.

**Comment by justvanrossum** [comment]
We are also running into this problem. I can create a TTFont instance from a resulting font, but its `cmap` is not correct: it maps code points to (seemingly) arbitrary glyphs.

**Comment by behdad** [comment]
> We are also running into this problem. I can create a TTFont instance from a resulting font, but its `cmap` is not correct: it maps code points to (seemingly) arbitrary glyphs.

Is it possible to send me a reproducer privately?

**Comment by justvanrossum** [comment]
> Is it possible to send me a reproducer privately?

Sent, thanks!

**Comment by behdad** [comment]
> We are also running into this problem. I can create a TTFont instance from a resulting font, but its `cmap` is not correct: it maps code points to (seemingly) arbitrary glyphs.

Looks like the glyphnames in the CFF are coming from the CFF standardStrings. Probably because I'm not setting a charset on the CFF.

I'm really at a loss. Will bang my head against it a bit.

**Comment by jenskutilek** [comment]
Should simply upconverting a static OTF’s CFF table to CFF2 work in theory?

Getting mixed results ... macOS lets me use the font normally, but InDesign behaves as if all glyph widths are 0, and Windows says that the font file is not valid ...

**Comment by behdad** [comment]
> Should simply upconverting a static OTF’s CFF table to CFF2 work in theory?

No, we have not figured out how to make these two tools work unfortunately. Wee need a CFF specialist to look into these, but I have not been able to nerd-snipe down any yet.

**Comment by behdad** [comment]
I pushed some fixes to CFF2ToCFF in: https://github.com/fonttools/fonttools/pull/3886

Note that you still need to instantiate font WITHOUT `--downgrade-cff2`, and then do a `fonttools cffLib.CFF2ToCFF` separately. But if you do that, I'm interested to know how good or bad the resulting CFF is. Thanks.

**Comment by behdad** [comment]
The `CFF2ToCFF` and `--downgrade-cff2` should be fixed now. I'm closing this. If anyone's facing any issues with either `CFF2ToCFF` or `CFFToCFF2` with latest fonttools, please open a new issue with details and I'll dig into it right away. Thanks.

**Comment by jenskutilek** [comment]
Works beautifully, thank you @behdad!
