### ISSUE TITLE
[interpolatable] ZeroDivisionError on "unusual" outline

### ISSUE THREAD

**Issue by justvanrossum** [fonttools/fonttools#3533]
Running `python -m fontTools.varLib.interpolatable jp-test.ttf` on the attached font crashes with a ZeroDivisionError. Found via [fontbakery](https://github.com/fonttools/fontbakery/issues/4742)

[jp-test.ttf.zip](https://github.com/fonttools/fonttools/files/15458007/jp-test.ttf.zip)

Error:
```
ERROR: ('float division by zero', 'jp-test.ttf')
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/just/code/git/fonttools/Lib/fontTools/varLib/interpolatable.py", line 1132, in <module>
    problems = main()
               ^^^^^^
  File "/Users/just/code/git/fonttools/Lib/fontTools/varLib/interpolatable.py", line 919, in main
    for glyphname, p in problems_gen:
  File "/Users/just/code/git/fonttools/Lib/fontTools/varLib/interpolatable.py", line 338, in test_gen
    this_tolerance, proposed_point, reverse = test_starting_point(
                                              ^^^^^^^^^^^^^^^^^^^^
  File "/Users/just/code/git/fonttools/Lib/fontTools/varLib/interpolatableTestStartingPoint.py", line 52, in test_starting_point
    correlation = vector[5] / abs(vector[0])
                  ~~~~~~~~~~^~~~~~~~~~~~~~~~
ZeroDivisionError: ('float division by zero', 'jp-test.ttf')
```

**Comment by behdad** [comment]
I'll take a look. Thanks.
