### ISSUE TITLE
removeOverlaps error

### ISSUE THREAD

**Issue by potatoShield** [fonttools/fonttools#3629]
im using ttLib.removeOverlaps to remove overlaps in a VF font
```
 fonttools ttLib.removeOverlaps --ignore-errors SourceHanSans-VF.ttf new.ttf
```
but it causes err:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/fonttools", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fontTools/__main__.py", line 31, in main
    runpy.run_module(mod, run_name="__main__")
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fontTools/ttLib/removeOverlaps.py", line 389, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fontTools/ttLib/removeOverlaps.py", line 385, in main
    font.save(args.output)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 216, in save
    writer_reordersTables = self._save(tmp)
                            ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 263, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 713, in _writeTable
    tabledata = self.getTableData(tag)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 735, in getTableData
    return self.tables[tag].compile(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fontTools/ttLib/tables/_g_v_a_r.py", line 54, in compile
    axisTags, itertools.chain(*self.variations.values())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 913, in __iter__
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fontTools/misc/lazyTools.py", line 14, in __getitem__
    v = v(k)
        ^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fontTools/ttLib/tables/_g_v_a_r.py", line 133, in read_item
    return decompileGlyph_(
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fontTools/ttLib/tables/_g_v_a_r.py", line 268, in decompileGlyph_
    return tv.decompileTupleVariationStore(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fontTools/ttLib/tables/TupleVariation.py", line 770, in decompileTupleVariationStore
    decompileTupleVariation_(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fontTools/ttLib/tables/TupleVariation.py", line 822, in decompileTupleVariation_
    deltas_x, pos = TupleVariation.decompileDeltas_(len(points), tupleData, pos)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fontTools/ttLib/tables/TupleVariation.py", line 525, in decompileDeltas_
    assert numDeltas is None or len(result) == numDeltas
AssertionError
```

**Comment by potatoShield** [comment]
> looks like the gvar table is corrupt. Where can I find the same font file you used as input "SourceHanSans-VF.ttf"?

you can get font file from this repository:
https://github.com/adobe-fonts/source-han-sans/blob/release/Variable/TTF/SourceHanSans-VF.ttf

**Comment by anthrotype** [comment]
oh sorry I just realised, this is a variable font (TrueType flavoured with a gvar table). You can't use removeOverlaps on it I'm afraid. VFs are supposed to contain overlaps, that's how their glyphs are usually designed to work for interpolation.
We should make it clearer from the module's docustring and --help that this is meant to work with static (non-variable) fonts, like the static instances that are cut from a VF (with varLib.instancer) for example.

**Comment by potatoShield** [comment]
> oh sorry I just realised, this is a variable font (TrueType flavoured with a gvar table). You can't use removeOverlaps on it I'm afraid. VFs are supposed to contain overlaps, that's how their glyphs are usually designed to work for interpolation. We should make it clearer from the module's docustring and --help that this is meant to work with static (non-variable) fonts, like the static instances that are cut from a VF (with varLib.instancer) for example.

thanks for your answer! i'll close this issue :)

**Comment by anthrotype** [comment]
if you really want to remove the overlaps you should reduce the VF to one of its static instance fonts (but you lose its variability of course, you'll have to decide a particular location in its variation space, or make as many instances as you need) with varLib.instancer. The latter has an option to --remove-overlaps which calls the same module
