### ISSUE TITLE
Failure to re-compile font with `cmap` Mac Korean format 2 subtable record

### ISSUE THREAD

**Issue by miguelsousa** [fonttools/fonttools#3663]
The error below happens when I try to roundtrip a font that contains a `cmap` **Mac Korean format 2** subtable record.
Cannot include the font because it's not publicly available, but please reach out if you need a test case.

```
> ttx 2002236759.ttx
Compiling "2002236759.ttx" to "2002236759#1.otf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'name' table...
Parsing 'cmap' table...
Parsing 'post' table...
Parsing 'CFF ' table...
Parsing 'GSUB' table...
Parsing 'hmtx' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/lib/python3.11/site-packages/fontTools/ttx.py", line 452, in main
    process(jobs, options)
  File "/lib/python3.11/site-packages/fontTools/ttx.py", line 434, in process
    action(input, output, options)
  File "/lib/python3.11/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttx.py", line 334, in ttCompile
    ttf.save(output)
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 222, in save
    writer_reordersTables = self._save(tmp)
                            ^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 269, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 719, in _writeTable
    tabledata = self.getTableData(tag)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 741, in getTableData
    return self.tables[tag].compile(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 207, in compile
    chunk = table.compile(ttFont)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 629, in compile
    charCode = charCodes[0]
               ~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by behdad** [comment]
I can try take a look. CMAP subtable format 2 is a rarity AFAIK, so I might not be able to make sense of it. There's also some scary comments around that code.

**Comment by miguelsousa** [comment]
Thanks Behdad. It's definitely a legacy format that may not be worth the trouble, but wanted to make a record of it in case other people run int the same thing.
