### ISSUE TITLE
Error fonttools/lib/python3.12/site-packages/fontTools/subset/__init__.py", line 3478, in _closure_glyphs

### ISSUE THREAD

**Issue by PavelFil** [fonttools/fonttools#3664]
For file [test.zip](https://github.com/user-attachments/files/17452027/test.zip) This command:
```
pyftsubset 'test.ttf' --output-file='new-test.ttf' --unicodes='U+21-23' --layout-features="" --drop-tables+=GSUB --no-notdef-glyph
```
throw the error
```
Traceback (most recent call last):
  File "/home/webuser/.local/bin/pyftsubset", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/webuser/.local/share/pipx/venvs/fonttools/lib/python3.12/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/webuser/.local/share/pipx/venvs/fonttools/lib/python3.12/site-packages/fontTools/subset/__init__.py", line 3808, in main
    subsetter.subset(font)
  File "/home/webuser/.local/share/pipx/venvs/fonttools/lib/python3.12/site-packages/fontTools/subset/__init__.py", line 3596, in subset
    self._closure_glyphs(font)
  File "/home/webuser/.local/share/pipx/venvs/fonttools/lib/python3.12/site-packages/fontTools/subset/__init__.py", line 3478, in _closure_glyphs
    self.last_retained_order = max(self.reverseOrigGlyphMap.values())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty
```
But it works fine if we remove `--no-notdef-glyph` flag.

**Comment by behdad** [comment]
Can you confirm that you are subsetting to an empty font? Ie. the font has none of the requested Unicodes?

**Comment by PavelFil** [comment]
> Can you confirm that you are subsetting to an empty font? Ie. the font has none of the requested Unicodes?

Yes. The font file doesn't have requested unicodes.
