### ISSUE TITLE
No Brotli?

### ISSUE THREAD

**Issue by clauseggers** [fonttools/fonttools#3684]
When trying to decompile a WOFF2 I get the following error message.
```
Dumping "playfairdisplay-regular-webfont.woff2" to "playfairdisplay-regular-webfont#2.ttx"...
ERROR: The WOFF2 decoder requires the Brotli Python extension, available at: https://github.com/google/brotli
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/Users/claus/.local/pipx/venvs/fonttools/lib/python3.12/site-packages/fontTools/ttx.py", line 452, in main
    process(jobs, options)
  File "/Users/claus/.local/pipx/venvs/fonttools/lib/python3.12/site-packages/fontTools/ttx.py", line 434, in process
    action(input, output, options)
  File "/Users/claus/.local/pipx/venvs/fonttools/lib/python3.12/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/claus/.local/pipx/venvs/fonttools/lib/python3.12/site-packages/fontTools/ttx.py", line 289, in ttDump
    ttf = TTFont(
          ^^^^^^^
  File "/Users/claus/.local/pipx/venvs/fonttools/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 185, in __init__
    self.reader = SFNTReader(file, checkChecksums, fontNumber=fontNumber)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/claus/.local/pipx/venvs/fonttools/lib/python3.12/site-packages/fontTools/ttLib/woff2.py", line 53, in __init__
    raise ImportError("No module named brotli")
ImportError: No module named brotli
```
Activating the Virtual Environment it is installed in, then running `pip list` I can see that Brotli is installed.

I’m on MacOS Sequoia and have Python installed with Homebrew. Fonttools is installed with `pipx`

**Comment by justvanrossum** [comment]
You'll have to install fonttools with the opt-in woff dependencies. With regular pip this would go like this

    pip install "fonttools[woff]"

I assume it will be similar for pipx.
