### ISSUE TITLE
subset is broken in v4.55.0

### ISSUE THREAD

**Issue by TakWolf** [fonttools/fonttools#3695]
The same code can pass in v4.54.1, but error in v4.55.0

Example project: 

https://github.com/TakWolf/source-han-vf-sliced/blob/master/tools/build.py#L89

Reappear:

run `build.py` or execute

```shell
pyftsubset ./assets/fonts/sans/SourceHanSansSC-VF.otf.woff2 --text=─━│┃┄┅┆┇┈┉┊┋┌┍┎┏┐┑┒┓└┕┖┗┘┙┚┛├┝┞┟┠┡┢┣┤┥┦┧┨┩┪┫┬┭┮┯┰┱┲┳┴┵┶┷┸┹┺┻┼┽┾┿╀╁╂╃╄╅╆╇╈╉╊╋╌╍╎╏═║╒╓╔╕╖╗╘╙╚╛╜╝╞╟╠╡╢╣╤╥╦╧╨╩╪╫╬╭╮╯╰╱╲╳╴╵╶╷╸╹╺╻╼╽╾╿ --layout-features='*' --output-file=./SourceHanSans-CN-VF-Box-Drawing-0.otf.woff2
```

Full outputs:

```shell
Traceback (most recent call last):
  File "/Users/takwolf/Develop/FontDev/source-han-vf-sliced/.venv/bin/pyftsubset", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/takwolf/Develop/FontDev/source-han-vf-sliced/.venv/lib/python3.13/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/Users/takwolf/Develop/FontDev/source-han-vf-sliced/.venv/lib/python3.13/site-packages/fontTools/subset/__init__.py", line 3813, in main
    subsetter.subset(font)
    ~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/takwolf/Develop/FontDev/source-han-vf-sliced/.venv/lib/python3.13/site-packages/fontTools/subset/__init__.py", line 3601, in subset
    self._prune_post_subset(font)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/takwolf/Develop/FontDev/source-han-vf-sliced/.venv/lib/python3.13/site-packages/fontTools/subset/__init__.py", line 3584, in _prune_post_subset
    retain = table.prune_post_subset(font, self.options)
  File "/Users/takwolf/Develop/FontDev/source-han-vf-sliced/.venv/lib/python3.13/site-packages/fontTools/subset/cff.py", line 159, in prune_post_subset
    self.remove_unused_subroutines()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/takwolf/Develop/FontDev/source-han-vf-sliced/.venv/lib/python3.13/site-packages/fontTools/subset/cff.py", line 184, in remove_unused_subroutines
    self.cff.remove_unused_subroutines()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/takwolf/Develop/FontDev/source-han-vf-sliced/.venv/lib/python3.13/site-packages/fontTools/cffLib/__init__.py", line 324, in remove_unused_subroutines
    remove_unused_subroutines(self)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/takwolf/Develop/FontDev/source-han-vf-sliced/.venv/lib/python3.13/site-packages/fontTools/cffLib/transforms.py", line 461, in remove_unused_subroutines
    local_subrs = font.FDArray[0].Private.Subrs
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/takwolf/Develop/FontDev/source-han-vf-sliced/.venv/lib/python3.13/site-packages/fontTools/cffLib/__init__.py", line 2472, in __getattr__
    raise AttributeError(name)
AttributeError: Subrs
```

For font https://github.com/adobe-fonts/source-han-sans/releases/tag/2.004R,

Unicode block `Box-Drawing` seems something wrong.

**Comment by TakWolf** [comment]
Maybe related to https://github.com/fonttools/fonttools/pull/3672
