### ISSUE TITLE
Merging fonts using pyftmerge fails.

### ISSUE THREAD

**Issue by AmyAki** [fonttools/fonttools#3698]
Fonts: [IBMPlexSansJP-Regular.ttf](https://github.com/IBM/plex/blob/master/packages/plex-sans-jp/fonts/complete/ttf/hinted/IBMPlexSansJP-Regular.ttf), [IBMPlexSansTC-Regular.ttf](https://github.com/IBM/plex/blob/master/packages/plex-sans-tc/fonts/complete/ttf/hinted/IBMPlexSansTC-Regular.ttf)

fontTools Version: 4.55.0

Command: `pyftmerge IBMPlexSansJP-Regular.ttf IBMPlexSansTC-Regular.ttf --output-file=out.ttf`

Info:
```
WARNING: Dropped cmap subtable from font '1':	format  6, platformID  1, platEncID  2
WARNING: Dropped mapping from codepoint 0X02CB to glyphId 'uni02CB'
WARNING: Dropped mapping from codepoint 0X223C to glyphId 'similar'
Traceback (most recent call last):
  File "/home/user/.local/bin/pyftmerge", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/merge/__init__.py", line 244, in main
    font.save(options.output_file)
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 222, in save
    writer_reordersTables = self._save(tmp)
                            ^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 269, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 719, in _writeTable
    tabledata = self.getTableData(tag)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 741, in getTableData
    return self.tables[tag].compile(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 207, in compile
    chunk = table.compile(ttFont)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 1029, in compile
    header = struct.pack(
             ^^^^^^^^^^^^
struct.error: 'H' format requires 0 <= number <= 65535

```

**Comment by behdad** [comment]
The resulting font has more than the allowed 65,534 glyphs per font.

**Comment by AmyAki** [comment]
> The resulting font has more than the allowed 65,534 glyphs per font.

The The total number of glyphs is 9526 + 19217 < 65535.

**Comment by behdad** [comment]
Humm. Then something is going on.

**Comment by behdad** [comment]
I will debug. Be careful though, you can only merge OpenType fonts of the same flavor (TrueType vs Postscript), and only when they have the same UnitsPerEM.

**Comment by AmyAki** [comment]
Thank you very much.

**Comment by behdad** [comment]
The following patch makes it merge for me. I haven't inspected the result. I'm surprised we didn't have such a change before, as it is, I think, well-known that such fonts exist in the wild.
```patch
diff --git a/Lib/fontTools/ttLib/tables/_c_m_a_p.py b/Lib/fontTools/ttLib/tables/_c_m_a_p.py
index 484c331cb..a0306cde6 100644
--- a/Lib/fontTools/ttLib/tables/_c_m_a_p.py
+++ b/Lib/fontTools/ttLib/tables/_c_m_a_p.py
@@ -1025,7 +1025,7 @@ class cmap_format_4(CmapSubtable):
             restArray.byteswap()
         data = charCodeArray.tobytes() + idDeltaArray.tobytes() + restArray.tobytes()
 
-        length = struct.calcsize(cmap_format_4_format) + len(data)
+        length = min(struct.calcsize(cmap_format_4_format) + len(data), 0xFFFF)
         header = struct.pack(
             cmap_format_4_format,
             self.format,
```

**Comment by AmyAki** [comment]
The result can't be decompiled by ttx.

Command: `ttx out.ttf`
Info:
```
Dumping "out.ttf" to "out.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttx.py", line 452, in main
    process(jobs, options)
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttx.py", line 434, in process
    action(input, output, options)
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttx.py", line 295, in ttDump
    ttf.saveXML(
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 285, in saveXML
    self._saveXML(writer, **kwargs)
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 350, in _saveXML
    self._tableToXML(tableWriter, tag, splitGlyphs=splitGlyphs)
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 382, in _tableToXML
    table.toXML(writer, self)
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 221, in toXML
    table.toXML(writer, ttFont)
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 317, in toXML
    codes = sorted(self.cmap.items())
                   ^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 289, in __getattr__
    self.ensureDecompiled()
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 278, in ensureDecompiled
    self.decompile(None, None)  # use saved data.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 883, in decompile
    allCodes.frombytes(data)
ValueError: bytes length not a multiple of item size
```
