### ISSUE TITLE
lxml: OSError: Error reading file 'x.designspace': failed to load external entity "x.designspace"

### ISSUE THREAD

**Issue by yanone** [fonttools/fonttools#3702]
I’m getting an error when trying to generate this [Science Gothic .designspace file](https://github.com/googlefonts/science-gothic/blob/main/sources/UFO/ScienceGothic%5BYOPQ%2Cwdth%2Cwght%2Cslnt%5D.designspace).

```python
(venv) yanone@macbookair science-gothic % ./venv/bin/gftools builder sources/config.yaml
Traceback (most recent call last):
  File "/Users/yanone/Fonts/Github/science-gothic/./venv/bin/gftools", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/yanone/Fonts/Github/science-gothic/venv/lib/python3.11/site-packages/gftools/scripts/__init__.py", line 98, in main
    mod.main(args[2:])
  File "/Users/yanone/Fonts/Github/science-gothic/venv/lib/python3.11/site-packages/gftools/builder/__init__.py", line 437, in main
    pd = GFBuilder(config, fontc_args=fontc_args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanone/Fonts/Github/science-gothic/venv/lib/python3.11/site-packages/gftools/builder/__init__.py", line 78, in __init__
    automatic_recipe = self.call_recipe_provider()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanone/Fonts/Github/science-gothic/venv/lib/python3.11/site-packages/gftools/builder/__init__.py", line 109, in call_recipe_provider
    return provider(self.config, self).write_recipe()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanone/Fonts/Github/science-gothic/venv/lib/python3.11/site-packages/gftools/builder/recipeproviders/googlefonts.py", line 103, in write_recipe
    self.build_all_variables()
  File "/Users/yanone/Fonts/Github/science-gothic/venv/lib/python3.11/site-packages/gftools/builder/recipeproviders/googlefonts.py", line 230, in build_all_variables
    if not source.is_variable:
           ^^^^^^^^^^^^^^^^^^
  File "/Users/yanone/.pyenv/versions/3.11.1/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/yanone/Fonts/Github/science-gothic/venv/lib/python3.11/site-packages/gftools/builder/file.py", line 53, in is_variable
    self.is_designspace and len(self.designspace.sources) > 1
                                ^^^^^^^^^^^^^^^^
  File "/Users/yanone/.pyenv/versions/3.11.1/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/yanone/Fonts/Github/science-gothic/venv/lib/python3.11/site-packages/gftools/builder/file.py", line 69, in designspace
    return DesignSpaceDocument.fromfile(self.path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanone/Fonts/Github/science-gothic/venv/lib/python3.11/site-packages/fontTools/designspaceLib/__init__.py", line 2755, in fromfile
    self.read(path)
  File "/Users/yanone/Fonts/Github/science-gothic/venv/lib/python3.11/site-packages/fontTools/designspaceLib/__init__.py", line 2790, in read
    reader = self.readerClass(path, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanone/Fonts/Github/science-gothic/venv/lib/python3.11/site-packages/fontTools/designspaceLib/__init__.py", line 1977, in __init__
    tree = ET.parse(self.path)
           ^^^^^^^^^^^^^^^^^^^
  File "src/lxml/etree.pyx", line 3589, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1958, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1984, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1887, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1200, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 633, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 743, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 670, in lxml.etree._raiseParseError
OSError: Error reading file 'ScienceGothic[YOPQ,wdth,wght,slnt].designspace': failed to load external entity "ScienceGothic[YOPQ,wdth,wght,slnt].designspace"
```

It comes via `lxml`. However, when I use `lxml` directly, such as below, the `.designspace` file loads fine.

```python
from lxml.etree import *
tree = etree.parse("sources/UFO/ScienceGothic[YOPQ,wdth,wght,slnt].designspace")
```

What am I doing wrong?

**Comment by yanone** [comment]
For added fun, I tried replacing the whole `try/except` in `fonttools/misc/etree.py` with a plain `from lxml.etree import *` to make sure the `lxml` import works there, and it leads to the same unchanged error.

**Comment by justvanrossum** [comment]
FWIW, I can't reproduce with fonttools directly:

```python
from fontTools.designspaceLib import DesignSpaceDocument
p = "path/to/ScienceGothic[YOPQ,wdth,wght,slnt].designspace"
doc = DesignSpaceDocument.fromfile(p)
print(doc.sources)
```

Is GF tools modifying the file, and if so, can we see what it did?

**Comment by yanone** [comment]
Your code snippet works for me, too, without error.

I’ll investigate about possible changes to the file, although it’s weird, because none are written do disk for sure or else they would show up as `git` changes.

I’ll get back to you, I’ll see what else I can find.

**Comment by yanone** [comment]
Definitely no changes to the file, and the code reads straight from disk instead of an in-memory object. Also, `gftools` is not messing with the `lxml` installation somehow; doesn't even use it at all. I thought maybe it imports and overwrites something, but it doesn't.

Completely lost here. I made sure to set up a proper venv to rule out package issues in my default environment, which the traceback at the top reflects.

**Comment by yanone** [comment]
The UFO was in a subfolder of the path I specified for gftools, which I had overlooked, and thus couldn't be found. It’s entirely a user error. My apologies for the noise.
