### ISSUE TITLE
making <GlyphOrder> optional

### ISSUE THREAD

**Issue by Pomax** [fonttools/fonttools#386]
Right now if you take a TTX file without a glyph order section, the TTX conversion to font crashes with the message:

```
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'hmtx' table...
Parsing 'cmap' table...
Parsing 'loca' table...
Parsing 'glyf' table...
Traceback (most recent call last):
  File "C:\Program Files (x86)\TTX\ttx.py", line 303, in main
    process(jobs, options)
  File "C:\Program Files (x86)\TTX\ttx.py", line 288, in process
    action(input, output, options)
  File "C:\Program Files (x86)\TTX\ttx.py", line 189, in ttCompile
    ttf.importXML(input)
  File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\ttLib\__init__.py", line 336, in importXML
    reader.read()
  File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\misc\xmlReader.py", line 30, in read
    self._parseFile(file)
  File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\misc\xmlReader.py", line 49, in _parseFile
    parser.Parse(chunk, 0)
  File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\misc\xmlReader.py", line 115, in _endElementHandler
    self.currentTable.fromXML(name, attrs, content, self.ttFont)
  File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\ttLib\tables\_g_l_y_f.py", line 120, in fromXML
    self.glyphOrder = ttFont.getGlyphOrder()
  File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\ttLib\__init__.py", line 448, in getGlyphOrder
    self._getGlyphNamesFromCmap()
  File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\ttLib\__init__.py", line 488, in _getGlyphNamesFromCmap
    tempcmap = self['cmap'].getcmap(3, 1)
  File "c:\Program Files (x86)\Python 2.7\lib\site-packages\FontTools\fontTools\ttLib\__init__.py", line 405, in __getitem__
    raise KeyError("'%s' table not found" % tag)
KeyError: "'cmap' table not found"
(Hit any key to exit)
```

The error concludes that it can't find the `cmap` table, when really it has full access to that, but is missing an explicit glyph ordering. However, if the cmap ordering is "good enough", then there shouldn't be a need to manually specify glyph ordering.

It would be great if TTX simply checked the XML for a `<GlyphOrder>` element, and if not found, simply "make one" for use during the conversion run based on the data found in the `cmap` element.

**Comment by behdad** [comment]
Making an arbitrary glyph order wouldn't work right now.  Except that, you are right, we just need to know number of glyphs, which comes from maxp.  This definitely can be improved..

**Comment by Pomax** [comment]
I might try to take a stab at this (it's been a long time since I wrote any python though!), what's a good place to start looking?

**Comment by anthrotype** [comment]
I'd start from here:
https://github.com/behdad/fonttools/blob/master/Lib/fontTools/ttLib/__init__.py#L478
