### ISSUE TITLE
[feaLib] backslash-prefixed glyph names not supported

### ISSUE THREAD

**Issue by adrientetar** [fonttools/fonttools#457]
Given the following feature file:

```
@group = [\f \i];

feature liga {
    sub @group by f_i;
} liga;
```

Traceback:

```
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\scriptingWindow.py", line 40, in runScript
    exec(code, global_vars)
  File "<string>", line 8, in <module>
  File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 337, in getRepresentation
    representation = factory["factory"](self, **kwargs)
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\representationFactories\openTypeFactory.py", line 5, in TTFontFactory
    otf = compileOTF(font)
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\__init__.py", line 29, in compileOTF
    featureCompilerClass, kernWriter, markWriter)
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\__init__.py", line 18, in _compile
    featureCompiler.compile()
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\makeotfParts.py", line 26, in compile
    self.setupFile_features()
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\makeotfParts.py", line 59, in setupFile_features
    autoFeatures["kern"] = self.writeFeatures_kern()
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\makeotfParts.py", line 82, in writeFeatures_kern
    writer = self.kernWriter(self.font)
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\kernFeatureWriter.py", line 30, in __init__
    parser.parseFeatures(self, font.features.text)
  File "C:\Python34\lib\site-packages\feaTools\parser.py", line 645, in parseFeatures
    _parseUnknown(writer, text)
  File "C:\Python34\lib\site-packages\feaTools\parser.py", line 300, in _parseUnknown
    _parseUnknown(writer, precedingText)
  File "C:\Python34\lib\site-packages\feaTools\parser.py", line 408, in _parseUnknown
    text = _executeSimpleSlice(None, text, terminatorRE, writer)
  File "C:\Python34\lib\site-packages\feaTools\parser.py", line 420, in _executeSimpleSlice
    _parseUnknown(writer, precedingText)
  File "C:\Python34\lib\site-packages\feaTools\parser.py", line 412, in _parseUnknown
    raise FeaToolsParserSyntaxError("Invalid Syntax: %s" % text)
feaTools.parser.FeaToolsParserSyntaxError: 'Invalid Syntax: @group = [\\f \\i]'
```

Backslash-prefixed glyph name statements aren't supported (they are in place to distinguish glyph names from identically-named keywords).

**Comment by anthrotype** [comment]
this is a low hanging :cherries:
any takers?

**Comment by brawer** [comment]
Actually it seems to work fine, but let me add a test case to prevent regressions.

**Comment by anthrotype** [comment]
Oh sorry I didn't bother to check :)

**Comment by anthrotype** [comment]
thanks!

**Comment by moyogo** [comment]
@brawer The [spec](https://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#2.d) says
>  \    backslash       Identifies CIDs. Distinguishes glyph names from an identical keyword

`\glyphNameWithBackslash1` should be the same as `glyphNameWithBackslash1` in the test case. The main use of backslash is for glyph names like `\by`, `\sub`, `\lookup`, etc.

**Comment by miguelsousa** [comment]
Below is a CID example of `liga` from [Source Han Sans](https://github.com/adobe-fonts/source-han-sans/blob/master/Normal/features.JP#L360)

```
feature liga {
  substitute \71 \71 \74 by \58922;
  substitute \71 \71 \77 by \58923;
  substitute \71 \71 by \58919;
  substitute \71 \74 by \58920;
  substitute \71 \77 by \58921;
} liga;
```

**Comment by twardoch** [comment]
Note: DTL OTMaster, which has a really good OTL-to-FEA decompiler, always prefixes glyph names with backslashes, even those that don't conflict with reserved keywords.

**Comment by anthrotype** [comment]
something like this should work:

```diff
diff --git a/Lib/fontTools/feaLib/lexer.py b/Lib/fontTools/feaLib/lexer.py
index f11c933..0b6d950 100644
--- a/Lib/fontTools/feaLib/lexer.py
+++ b/Lib/fontTools/feaLib/lexer.py
@@ -118,6 +118,8 @@ class Lexer(object):
         if cur_char in Lexer.CHAR_NAME_START_:
             self.pos_ += 1
             self.scan_over_(Lexer.CHAR_NAME_CONTINUATION_)
+            if cur_char == "\\":
+                start += 1
             token = text[start:self.pos_]
             if token == "include":
                 self.mode_ = Lexer.MODE_FILENAME_
```

**Comment by anthrotype** [comment]
Actually, maybe the stripping of the initial backslash in glyph names should be done in the parser rather than in the lexer:

```diff
diff --git a/Lib/fontTools/feaLib/parser.py b/Lib/fontTools/feaLib/parser.py
index 56ff744..95d29c6 100644
--- a/Lib/fontTools/feaLib/parser.py
+++ b/Lib/fontTools/feaLib/parser.py
@@ -1184,6 +1184,8 @@ class Parser(object):
     def expect_glyph_(self):
         self.advance_lexer_()
         if self.cur_token_type_ is Lexer.NAME:
+            if self.cur_token_.startswith("\\"):
+                self.cur_token_ = self.cur_token_[1:]
             if len(self.cur_token_) > 63:
                 raise FeatureLibError(
                     "Glyph names must not be longer than 63 characters",
```

I'll add some tests tomorrow.

**Comment by anthrotype** [comment]
@miguelsousa btw, backslash-escaped CIDs (e.g. `\12345`) are already supported by feaLib parser.

**Comment by adrientetar** [comment]
> Actually, maybe the stripping of the initial backslash in glyph names should be done in the parser rather than in the lexer:

Are you saying that there's no ambiguity? i.e. sub sub by lookup; isn't ambiguous because of placement but feature file requires a backslash anyway? Would FDK reject this statement then, i.e. does it reject glyph names if they are identical to keywords?

**Comment by brawer** [comment]
No, makeotf rejects `sub sub by lookup;` unless the glyph names are prefixed by a backslash. (Just checked).
