### ISSUE TITLE
Boom decompiling GPOS table with Linux Libertine

### ISSUE THREAD

**Issue by simoncozens** [fonttools/fonttools#694]
```
$ ttx -o - -t GPOS ~/Library/Fonts/LinLibertine_RBI.otf
Dumping "/Users/simon/Library/Fonts/LinLibertine_RBI.otf" to "-"...
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="OTTO" ttLibVersion="3.1">

ERROR: An exception occurred during the decompilation of the 'GPOS' table
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/fonttools-3.1.3.dev95_ngb5d7eb8-py2.7.egg/fontTools/ttLib/__init__.py", line 418, in __getitem__
    table.decompile(data, self)
  File "/Library/Python/2.7/site-packages/fonttools-3.1.3.dev95_ngb5d7eb8-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 49, in decompile
    self.table.decompile(reader, font)
  File "/Library/Python/2.7/site-packages/fonttools-3.1.3.dev95_ngb5d7eb8-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 613, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/Library/Python/2.7/site-packages/fonttools-3.1.3.dev95_ngb5d7eb8-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 375, in read
    table.decompile(reader, font)
  File "/Library/Python/2.7/site-packages/fonttools-3.1.3.dev95_ngb5d7eb8-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 609, in decompile
    table[conv.name] = conv.readArray(reader, font, table, countValue)
  File "/Library/Python/2.7/site-packages/fonttools-3.1.3.dev95_ngb5d7eb8-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 108, in readArray
    l.append(self.read(reader, font, tableDict))
  File "/Library/Python/2.7/site-packages/fonttools-3.1.3.dev95_ngb5d7eb8-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 375, in read
    table.decompile(reader, font)
  File "/Library/Python/2.7/site-packages/fonttools-3.1.3.dev95_ngb5d7eb8-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 609, in decompile
    table[conv.name] = conv.readArray(reader, font, table, countValue)
  File "/Library/Python/2.7/site-packages/fonttools-3.1.3.dev95_ngb5d7eb8-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 108, in readArray
    l.append(self.read(reader, font, tableDict))
  File "/Library/Python/2.7/site-packages/fonttools-3.1.3.dev95_ngb5d7eb8-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 375, in read
    table.decompile(reader, font)
  File "/Library/Python/2.7/site-packages/fonttools-3.1.3.dev95_ngb5d7eb8-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 613, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/Library/Python/2.7/site-packages/fonttools-3.1.3.dev95_ngb5d7eb8-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 375, in read
    table.decompile(reader, font)
  File "/Library/Python/2.7/site-packages/fonttools-3.1.3.dev95_ngb5d7eb8-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 617, in decompile
    self.postRead(table, font)
  File "/Library/Python/2.7/site-packages/fonttools-3.1.3.dev95_ngb5d7eb8-py2.7.egg/fontTools/ttLib/tables/otTables.py", line 58, in postRead
    (r.StartCoverageIndex, len(glyphs))
AssertionError: (28, 25)
```

This is FontForge 2.0 : Linux Libertine O Bold Italic : 2-7-2012 Version 5.1.8.

**Comment by anthrotype** [comment]
The latest version of [Linux Libertine 5.3.0](https://sourceforge.net/projects/linuxlibertine/files/linuxlibertine/5.3.0/) decompiles just fine, so I'm inclined to think this might be a font bug... 😁

**Comment by anthrotype** [comment]
Yeah, I'm quite sure it's a font bug.

From the Coverate Format 2 specs, at https://www.microsoft.com/typography/otspec/chapter2.htm:

> The Coverage Indexes for the first range begin with zero (0), and the Start Coverage Indexes for each succeeding range are determined by adding the length of the preceding range (End GlyphID - Start GlyphID + 1) to the array Index.

FontTools is doing the math right, FontForge wasn't.

**Comment by anthrotype** [comment]
You know you can disable assertion by running the Python interpreter with `-O` (optimize) flags? I won't recommend it, but if you do that, they you can decompile the font with ttx:

`python -Om fontTools.ttx -t GPOS LinLibertine_RBI.otf`

However, when you attempt to merge the GPOS table back into the font (i.e., you compile it), another warning is issued `"GSUB/GPOS Coverage is not sorted by glyph ids."`, which again confirms there is something wrong with the way that font was originally compiled.

To be precise, the offending `MarkCoverage Format=2` table with wrong `StartCoverageIndex` values is the one in the `MarkBasePos index="2"`, in the `Lookup index="2"`.
