### ISSUE TITLE
assert (index < lenGIArray), "In format 4 cmap

### ISSUE THREAD

**Issue by HinTak** [fonttools/fonttools#723]
These are two old CJK fonts, shipped by a well-known font vendor.

```
Dumping 'GlyphOrder' table...
Traceback (most recent call last):
  File "/usr/bin/ttx", line 9, in <module>
    load_entry_point('fonttools==3.0', 'console_scripts', 'ttx')()
  File "/usr/lib/python3.5/site-packages/FontTools/fontTools/ttx.py", line 350, in main
    process(jobs, options)
  File "/usr/lib/python3.5/site-packages/FontTools/fontTools/ttx.py", line 333, in process
    action(input, output, options)
  File "/usr/lib/python3.5/site-packages/FontTools/fontTools/ttx.py", line 231, in ttDump
    bitmapGlyphDataFormat=options.bitmapGlyphDataFormat)
  File "/usr/lib/python3.5/site-packages/FontTools/fontTools/ttLib/__init__.py", line 304, in saveXML
    self._tableToXML(tableWriter, tag, progress, quiet)
  File "/usr/lib/python3.5/site-packages/FontTools/fontTools/ttLib/__init__.py", line 344, in _tableToXML
    table.toXML(writer, self)
  File "/usr/lib/python3.5/site-packages/FontTools/fontTools/ttLib/__init__.py", line 769, in toXML
    glyphOrder = ttFont.getGlyphOrder()
  File "/usr/lib/python3.5/site-packages/FontTools/fontTools/ttLib/__init__.py", line 471, in getGlyphOrder
    self._getGlyphNamesFromCmap()
  File "/usr/lib/python3.5/site-packages/FontTools/fontTools/ttLib/__init__.py", line 522, in _getGlyphNamesFromCmap
    cmap = tempcmap.cmap
  File "/usr/lib/python3.5/site-packages/FontTools/fontTools/ttLib/tables/_c_m_a_p.py", line 122, in __getattr__
    self.decompile(None, None) # use saved data.
  File "/usr/lib/python3.5/site-packages/FontTools/fontTools/ttLib/tables/_c_m_a_p.py", line 696, in decompile
    assert (index < lenGIArray), "In format 4 cmap, range (%d), the calculated index (%d) into the glyph index array  is not less than the length of the array (%d) !" % (i, index, lenGIArray)
AssertionError: In format 4 cmap, range (97), the calculated index (20498) into the glyph index array  is not less than the length of the array (20498) !
```

The md5sum's are:
```
bce90bc6d3615b8220479e52817efea4  jdftekai.ttf
1042ae54d7fcc54a0c937a082740225b  jdfxinch.ttf
```

Apologies this is fedora's `fonttools-3.0-4.fc24.noarch`.

**Comment by zhouhuacong** [comment]
I fond the same issue, when I try to detect weather an UNICODE char in the font. I use the Chinese fonts , Is there a solution ?

**Comment by anthrotype** [comment]
it looks to me like the font has a broken cmap. Not much we can do

**Comment by behdad** [comment]
Looks like one of those errors that might be common because of some buggy font compiler. Probably worth investigating.

**Comment by jdhao** [comment]
I have also met this issue today. Any solutions or hints?

**Comment by anthrotype** [comment]
@jdhao which font were you trying to decompile?

**Comment by jdhao** [comment]
Just a custom font I have collect from somewhere. If you need, I will post the font file here.

**Comment by anthrotype** [comment]
> I will post the font file here

double check the license first

**Comment by HinTak** [comment]
In general, you are not supposed to post publicly font files you have, unless the license gives you re-distribution rights. All libre fonts, do, but those two I listed above are fonts that "I collected somewhere", hence I only posted the md5 check sum.

**Comment by jdhao** [comment]
Thanks for pointing out.
