### ISSUE TITLE
ヒラギノ角ゴシック W4.ttc (Hiragino Sans W4) decompilation fails

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#740]
I tried to convert "ヒラギノ角ゴシック W4.ttc" version 11.0d7e4 (macOS Sierra system font), with this error:

```bash
$ ttx -y 0 hiragino.ttc 
Dumping "hiragino.ttc" to "hiragino.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'name' table...
Dumping 'cmap' table...
Dumping 'post' table...
Dumping 'CFF ' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/ttx.py", line 398, in main
    process(jobs, options)
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/ttx.py", line 372, in process
    action(input, output, options)
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/ttx.py", line 272, in ttDump
    newlinestr=options.newlinestr)
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/ttLib/__init__.py", line 308, in saveXML
    self._tableToXML(tableWriter, tag, progress)
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/ttLib/__init__.py", line 344, in _tableToXML
    table.toXML(writer, self, progress)
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/ttLib/tables/C_F_F_.py", line 42, in toXML
    self.cff.toXML(writer, progress)
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/cffLib.py", line 90, in toXML
    font.toXML(xmlWriter, progress)
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/cffLib.py", line 1609, in toXML
    self.decompileAllCharStrings(progress)
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/cffLib.py", line 1622, in decompileAllCharStrings
    for charString in self.CharStrings.values():
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/cffLib.py", line 364, in __getitem__
    item = self.produceItem(index, data, file, offset, size)
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/cffLib.py", line 395, in produceItem
    private = self.fdArray[self.fdSelect[index]].Private
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/cffLib.py", line 364, in __getitem__
    item = self.produceItem(index, data, file, offset, size)
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/cffLib.py", line 456, in produceItem
    fontDict.decompile(data)
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/cffLib.py", line 1547, in decompile
    dec.decompile(data)
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/misc/psCharStrings.py", line 1127, in decompile
    value, index = handler(self, b0, data, index)
  File "/Library/Python/2.7/site-packages/fonttools-3.2.0+2.gdf967e7-py2.7.egg/fontTools/misc/psCharStrings.py", line 21, in read_operator
    operator = self.operators[op]
KeyError: (12, 5)
```

Not sure if it’s a bug in the font or in FontTools ...

**Comment by justvanrossum** [comment]
I'm reproducing this with a font called "ヒラギノ角ゴ Pro W6.otf", and that certainly worked before, so this is a regression.

**Comment by justvanrossum** [comment]
If crashing on a `PaintStyle` entry inside the `FontDict` entry inside the `FDArray` element:

```xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<ttFont sfntVersion="OTTO" ttLibVersion="2.1+">

  <CFF>

    <CFFFont name="HiraKakuPro-W6">
      <ROS Registry="Adobe" Order="Japan1" Supplement="5"/>
      <Notice value="Copyright (c) 1993-2002 Dainippon Screen Mfg. Co., Ltd. All Rights Reserved.Hiragino is a trademark of Dainippon Screen Mfg. Co., Ltd. registered in Japan."/>
      <FullName value="HiraKakuPro-W6"/>
      <isFixedPitch value="0"/>
      <ItalicAngle value="0"/>
      <UnderlineThickness value="50"/>
      <PaintType value="0"/>
      <CharstringType value="2"/>
      <FontMatrix value="0.001 0 0 0.001 0 0"/>
      <FontBBox value="-401 -447 1327 1281"/>
      <StrokeWidth value="0"/>
      <XUID value="205 711003 8560901"/>
      <CIDFontVersion value="7.11"/>
      <CIDFontRevision value="0"/>
      <CIDFontType value="0"/>
      <CIDCount value="20317"/>
      <!-- charset is dumped separately as the 'GlyphOrder' element -->
      <UIDBase value="8560901"/>
      <FDSelect format="3"/>
      <FDArray>
        <FontDict index="0">
          <FontName value="HiraKakuPro-W6-AlphaNum"/>
          <isFixedPitch value="0"/>
          <ItalicAngle value="0"/>
          <UnderlineThickness value="50"/>
          <PaintType value="0"/>
          <CharstringType value="2"/>
          <FontMatrix value="0.001 0 0 0.001 0 0"/>
          <FontBBox value="0 0 0 0"/>
          <StrokeWidth value="0"/>
          <Encoding name="StandardEncoding"/>
          <Private>
            <BlueValues value="-250 -250 1100 1100"/>
            <BlueScale value="0.049999"/>
            <BlueShift value="7"/>
            <BlueFuzz value="1"/>
            <StdHW value="117"/>
            <StdVW value="129"/>
            <StemSnapH value="117"/>
            <StemSnapV value="129"/>
            <ForceBold value="0"/>
            <LanguageGroup value="1"/>
            <ExpansionFactor value="0.06"/>
            <initialRandomSeed value="0"/>
            <defaultWidthX value="1000"/>
            <nominalWidthX value="0"/>
            <Subrs>
```

**Comment by justvanrossum** [comment]
`FontDict` used to be a subclass of `TopDict`, but now it's a subclass of `BaseDict` and has its own very limited set of operators. I'm fairly sure it's caused by this change: https://github.com/fonttools/fonttools/commit/3063def35b7ad733bf584b45452f9ef8f6efbab4
@readroberts, can you tell whether the font is buggy or that there's a problem with cffLib.py?

**Comment by justvanrossum** [comment]
Finding this comment in cffLib.py:

> """Since fonttools used to pass a lot of fields that are not relevant in the FDArray FontDict, there are 'ttx' files in the wild that contain all these. These got in the ttx files because fonttools writes explicit values for all the TopDict default values. These are not actually illegal in the context of an FDArray FontDict - you can legally, per spec, put any arbitrary key/value pair in a FontDict - but are useless since current major company CFF interpreters ignore anything but the set listed in this file. So, we just silently skip them. An exception is Weight: this is not used by any interepreter, but some foundries have asked that this be supported in FDArray FontDicts just to preserve information about the design when the font is being inspected."""


Well, the situation is obviously worse: there are OTFs out there that contain these values... I suppose the decompiler could *also* just silently ignore KeyErrors there?

**Comment by justvanrossum** [comment]
I think I have an elegant solution. I'll clean it up for a PR tomorrow.

**Comment by mashabow** [comment]
@justvanrossum

> `FontDict` used to be a subclass of `TopDict`, but now it's a subclass of `BaseDict` and has its own very limited set of operators. I'm fairly sure it's caused by this change: 3063def

FYI, commits 3063def and 5b47971 are related to https://github.com/fonttools/fonttools/issues/601. See also https://github.com/adobe-type-tools/afdko/issues/137.

**Comment by justvanrossum** [comment]
Ah, thank you, @mashabow, that is important to reference here. I deferred all that from @readroberts comment in the code... Do you agree with my fix? The only thing that would be nice to add is to emit warnings if "useless" key/value pairs are found. But that seems fairly hard without messing a lot with this already fairly intricate code base.

**Comment by mashabow** [comment]
@justvanrossum LGTM👍
