### ISSUE TITLE
Trying pyftmerge against 2 Google Noto fonts - fails - different error message when doing same run multiple times - non deterministic?

### ISSUE THREAD

**Issue by capiman** [fonttools/fonttools#743]
I am executing the following command multiple times:

```
fonttools> pyftmerge NotoSansUI-Regular.ttf NotoSansCJKsc-Regular.otf
```

The input font are downloaded from

https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-hinted.zip

and

https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKsc-hinted.zip

(1)
```
fonttools> pyftmerge NotoSansUI-Regular.ttf NotoSansCJKsc-Regular.otf
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 858, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 48, in equal
    assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 48, in <genexpr>
    assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
  File "/usr/lib/python3.4/site-packages/fontTools/misc/py23.py", line 159, in __eq__
    return str.__eq__(self, self.transcode(other))
  File "/usr/lib/python3.4/site-packages/fontTools/misc/py23.py", line 151, in transcode
    blob = blob.decode('latin-1')
AttributeError: 'NotImplementedType' object has no attribute 'decode'
```
(2)
```
fonttools> pyftmerge NotoSansUI-Regular.ttf NotoSansCJKsc-Regular.otf
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 858, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 48, in equal
    assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
AssertionError: Expected all items to be equal: [2048, 1000]
```
(3)
```
fonttools> pyftmerge NotoSansUI-Regular.ttf NotoSansCJKsc-Regular.otf
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 858, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 91, in sumDicts
    d.update(item)
TypeError: 'NotImplementedType' object is not iterable
```
(4)
```
fonttools> pyftmerge NotoSansUI-Regular.ttf NotoSansCJKsc-Regular.otf
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 344, in merge
    for g in table.glyphs.values():
AttributeError: 'NotImplementedType' object has no attribute 'glyphs'
```
(5)
```
fonttools> pyftmerge NotoSansUI-Regular.ttf NotoSansCJKsc-Regular.otf
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 858, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 48, in equal
    assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
AssertionError: Expected all items to be equal: [2048, 1000]
```
(6)
```
fonttools> pyftmerge NotoSansUI-Regular.ttf NotoSansCJKsc-Regular.otf
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 858, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 48, in equal
    assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 48, in <genexpr>
    assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
  File "/usr/lib/python3.4/site-packages/fontTools/misc/py23.py", line 159, in __eq__
    return str.__eq__(self, self.transcode(other))
  File "/usr/lib/python3.4/site-packages/fontTools/misc/py23.py", line 151, in transcode
    blob = blob.decode('latin-1')
AttributeError: 'NotImplementedType' object has no attribute 'decode'
```
(7)
```
fonttools> pyftmerge NotoSansUI-Regular.ttf NotoSansCJKsc-Regular.otf
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 858, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
TypeError: unorderable types: NotImplementedType() > int()
```
(8)
```
fonttools> pyftmerge NotoSansUI-Regular.ttf NotoSansCJKsc-Regular.otf
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 858, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 48, in equal
    assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 48, in <genexpr>
    assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
  File "/usr/lib/python3.4/site-packages/fontTools/misc/py23.py", line 159, in __eq__
    return str.__eq__(self, self.transcode(other))
  File "/usr/lib/python3.4/site-packages/fontTools/misc/py23.py", line 151, in transcode
    blob = blob.decode('latin-1')
AttributeError: 'NotImplementedType' object has no attribute 'decode'
```
(9)
```
fonttools> pyftmerge NotoSansUI-Regular.ttf NotoSansCJKsc-Regular.otf
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 858, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 91, in sumDicts
    d.update(item)
TypeError: 'NotImplementedType' object is not iterable
```
The execution seems to be non-deterministic. The local files have old timestamp
so I think they were not changed. I am doing this with python 3.4.1 on a Suse 13.2
in latest VirtualBox VM.

fonttools was just installed (as root, but executed as normal user) a few minutes ago.

linux-wkdi:/home/fonttools # pip install fonttools
Downloading/unpacking fonttools
  Downloading fonttools-3.2.1-py2.py3-none-any.whl (665kB): 665kB downloaded
Installing collected packages: fonttools
Successfully installed fonttools
Cleaning up...

**Comment by capiman** [comment]
It could be the size of the font or huge amount of character of the font? 
Just tried 2 smaller Noto fonts and they are working.

```
fonttools> pyftmerge NotoSans-BoldItalic.ttf NotoSans-Bold.ttf
```

When trying to bigger chinese Noto font, I even just got a new error message:

(10)
```
fonttools> pyftmerge NotoSansMonoCJKsc-Bold.otf NotoSansMonoCJKsc-Regular.otf
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 946, in main
    font.save(outfile)
  File "/usr/lib/python3.4/site-packages/fontTools/ttLib/__init__.py", line 216, in save
    self._writeTable(tag, writer, done)
  File "/usr/lib/python3.4/site-packages/fontTools/ttLib/__init__.py", line 651, in _writeTable
    self._writeTable(masterTable, writer, done)
  File "/usr/lib/python3.4/site-packages/fontTools/ttLib/__init__.py", line 654, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/lib/python3.4/site-packages/fontTools/ttLib/__init__.py", line 665, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/lib/python3.4/site-packages/fontTools/ttLib/tables/_m_a_x_p.py", line 51, in compile
    data = sstruct.pack(maxpFormat_0_5, self)
  File "/usr/lib/python3.4/site-packages/fontTools/misc/sstruct.py", line 75, in pack
    data = struct.pack(*(formatstring,) + tuple(elements))
struct.error: 'H' format requires 0 <= number <= 65535
```

**Comment by capiman** [comment]
Perhaps this is helpful:
-ttx is running on both of them, no crashes
-but they have different headers (second one has CFF and VORG, which the first one does not have)
-ok, non-chinese ttx file is 9 MBytes, whereas chinese ttx file is 118 Mbytes

```
fonttools> ttx NotoSansUI-Regular.ttf
Dumping "NotoSansUI-Regular.ttf" to "NotoSansUI-Regular.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'fpgm' table...
Dumping 'prep' table...
Dumping 'cvt ' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'gasp' table...
Dumping 'GDEF' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
```
```
fonttools> ttx NotoSansCJKsc-Regular.otf
Dumping "NotoSansCJKsc-Regular.otf" to "NotoSansCJKsc-Regular.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'name' table...
Dumping 'cmap' table...
Dumping 'post' table...
Dumping 'CFF ' table...
Dumping 'BASE' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'VORG' table...
Dumping 'hmtx' table...
Dumping 'vhea' table...
Dumping 'vmtx' table...
Dumping 'DSIG' table...
```
I also tried and create small subset of both fonts, each only a few KBytes big,
from the example to extract only a few characters. When i try to merge them,
I also get error (same errors?):

(11)
```
fonttools> pyftmerge NotoSans-Bold.ttf.subset NotoSansMonoCJKsc-Regular.otf.subset
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 344, in merge
    for g in table.glyphs.values():
AttributeError: 'NotImplementedType' object has no attribute 'glyphs'
```
(12)
```
fonttools> pyftmerge NotoSans-Bold.ttf.subset NotoSansMonoCJKsc-Regular.otf.subset
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 858, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
TypeError: unorderable types: NotImplementedType() > int()
```
(13)
```
fonttools> pyftmerge NotoSans-Bold.ttf.subset NotoSansMonoCJKsc-Regular.otf.subset
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 858, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 48, in equal
    assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
AssertionError: Expected all items to be equal: [2048, 1000]
```
(14)
```
fonttools> pyftmerge NotoSans-Bold.ttf.subset NotoSansMonoCJKsc-Regular.otf.subset
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 858, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 48, in equal
    assert all(item == first for item in t), "Expected all items to be equal: %s" % lst
AssertionError: Expected all items to be equal: [2048, 1000]
```
(14) -> Fonts other way round!
```
fonttools> pyftmerge NotoSansMonoCJKsc-Regular.otf.subset NotoSans-Bold.ttf.subset
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 516, in merge
    feature = [featureMap[v] for v in langsys.FeatureIndex if featureMap[v].FeatureTag == 'locl']
AttributeError: 'NoneType' object has no attribute 'FeatureIndex'
```
(15)
```
fonttools> pyftmerge NotoSansMonoCJKsc-Regular.otf.subset NotoSans-Bold.ttf.subset
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 516, in merge
    feature = [featureMap[v] for v in langsys.FeatureIndex if featureMap[v].FeatureTag == 'locl']
AttributeError: 'NoneType' object has no attribute 'FeatureIndex'
```
(15)
```
fonttools> pyftmerge NotoSansMonoCJKsc-Regular.otf.subset NotoSans-Bold.ttf.subset
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 516, in merge
    feature = [featureMap[v] for v in langsys.FeatureIndex if featureMap[v].FeatureTag == 'locl']
AttributeError: 'NoneType' object has no attribute 'FeatureIndex'
```
(16)
```
fonttools> pyftmerge NotoSansMonoCJKsc-Regular.otf.subset NotoSans-Bold.ttf.subset
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 516, in merge
    feature = [featureMap[v] for v in langsys.FeatureIndex if featureMap[v].FeatureTag == 'locl']
AttributeError: 'NoneType' object has no attribute 'FeatureIndex'
```
(17)
```
fonttools> pyftmerge NotoSansMonoCJKsc-Regular.otf.subset NotoSans-Bold.ttf.subset
Traceback (most recent call last):
  File "/usr/bin/pyftmerge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 943, in main
    font = merger.merge(args)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 813, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/lib/python3.4/site-packages/fontTools/merge.py", line 516, in merge
    feature = [featureMap[v] for v in langsys.FeatureIndex if featureMap[v].FeatureTag == 'locl']
AttributeError: 'NoneType' object has no attribute 'FeatureIndex'
```
At least in cases (14) to (17) the error message stays the same.

**Comment by moyogo** [comment]
There are several issues with what you’re actually trying to merge:
-  (1-9 and 11-15) you cannot merge a TTF with an OTF. Both store the glyphs in different formats, you would have to convert one of the two to the format of the other before merging.
- (10) As you’ve noticed the Noto CJK fonts have close the the maximum number of glyphs, so merging any font that would make it exceed that number is not going to work. That’s why you get the errer `struct.error: 'H' format requires 0 <= number <= 65535` why it’s trying to write the number of glyphs in the maxp table.

**Comment by capiman** [comment]
Many thanks for your helpful analysis. 
I have overseen that the input font a most of the time different formats.
But even then, in case of an error, shall the error be deterministic? 
Is there some kind of variable not initialized/floating?
