### ISSUE TITLE
3-byte glyph codepoint CMAP table generation

### ISSUE THREAD

**Issue by RimeOCRLIB** [fonttools/fonttools#762]
Many Asian fonts use GB18030 and another encodings with 3-byte Unicode value.
How we can add this encodings to FontTool?

CMAP  compilation with this 3-byte Unicode fail with this message:
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 87, in compile
    offset = seen[id(table.cmap)]
KeyError: 4386115912

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fontTools/ttx.py", line 398, in main
    process(jobs, options)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fontTools/ttx.py", line 372, in process
    action(input, output, options)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fontTools/ttx.py", line 293, in ttCompile
    ttf.save(output)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fontTools/ttLib/__init__.py", line 216, in save
    self._writeTable(tag, writer, done)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fontTools/ttLib/__init__.py", line 654, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fontTools/ttLib/__init__.py", line 665, in getTableData
    return self.tables[tag].compile(self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 89, in compile
    chunk = table.compile(ttFont)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fontTools/ttLib/tables/_c_m_a_p.py", line 819, in compile
    charCodeArray = array.array("H", endCode + [0] + startCode)
OverflowError: unsigned short is greater than maximum

**Comment by anthrotype** [comment]
character codes in format 4 cmap subtable must be USHORT (unsigned short integers), i.e. 0 <= n <= 0xFFFF)
https://www.microsoft.com/typography/otspec/cmap.htm
