### ISSUE TITLE
Need help with compiling ttx.exe on Windows 7..

### ISSUE THREAD

**Issue by augustus673** [fonttools/fonttools#809]
Hi, I'd like to make ttx.exe as a _standalone_ program using py2exe/PyInstaller? like i want an all-in-one exe file that can run the _latest_ ttx (3.5 atm). i already have an old version 2.4 which is about 3MB and works great without any extra strings (files) attached ie. python etc. (dependencies), but i would like the newest version 3.5 in this format.

if an AIO file isnt possible then i would just like to have ttx in exe format and have it run on any system independent of python,etc. thats my #1 priority. it needs to be "distributable"

this is what i tried so far:
i installed fonttools 3.5 via pip on my Windows 7 x64 machine using Python 2.7.12 and this cmd:
pip install --upgrade git+https://github.com/behdad/fonttools.git#egg=fonttools

then i installed py2exe, and made my setup.py like this:

```
from distutils.core import setup
import py2exe

setup(console=['ttx.py'])
```

as per instructions from here: http://www.py2exe.org/index.cgi/Tutorial

i also followed this guide but again its old, works only for ttx 2.4: http://www.typophile.com/node/67406

py2exe created a ttx.exe but it doesnt work:

```
C:\Python27\Lib\site-packages\fontTools\dist>ttx
Traceback (most recent call last):
  File "ttx.py", line 85, in <module>
  File "fontTools\__init__.pyc", line 2, in <module>
  File "fontTools\misc\__init__.pyc", line 4, in <module>
  File "fontTools\misc\py23.pyc", line 305, in <module>
  File "decimal.pyc", line 5953, in <module>
  File "locale.pyc", line 13, in <module>
  File "encodings\__init__.pyc", line 4, in <module>
AttributeError: 'module' object has no attribute 'round'
```

im guessing my py2exe setup.py is wrong and needs more info to be added..?
can someone please help me with this? 
thanks in advance!

ps. i need this so i can be able to move the exe from machine to machine without having to rely on python or other such dependencies.

**Comment by anthrotype** [comment]
Have you tried pyinstaller?
http://www.pyinstaller.org

**Comment by augustus673** [comment]
i tried that too but running the compiled ttx.exe gives this error msg:

```
C:\Python27\Lib\site-packages\fontTools\dist>ttx
Traceback (most recent call last):
  File "Lib\site-packages\fontTools\ttx.py", line 89, in <module>
  File "c:\python27\lib\site-packages\PyInstaller-3.2.1-py2.7.egg\PyInstaller\lo
ader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\fontTools\misc\timeTools.py", line 7, in <module>
  File "c:\python27\lib\site-packages\PyInstaller-3.2.1-py2.7.egg\PyInstaller\lo
ader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "calendar.py", line 10, in <module>
  File "c:\python27\lib\site-packages\PyInstaller-3.2.1-py2.7.egg\PyInstaller\lo
ader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "locale.py", line 14, in <module>
ImportError: No module named aliases
Failed to execute script ttx
```

and this in warnttx.txt:

```
missing module named resource - imported by posix, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named posix - imported by os, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named os2 - imported by os, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named _emx_link - imported by os, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named ce - imported by os, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named riscos - imported by os, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named riscospath - imported by os, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named riscosenviron - imported by os, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named org - imported by pickle, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named logging.PercentStyle - imported by logging, fontTools.misc.loggingTools, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named zopfli - imported by fontTools.ttLib.sfnt, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named _xmlplus - imported by xml, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named _scproxy - imported by urllib
missing module named EasyDialogs - imported by getpass
missing module named termios - imported by getpass
missing module named SOCKS - imported by ftplib
missing module named rourl2path - imported by urllib
missing module named java - imported by xml.sax._exceptions
missing module named ElementC14N - imported by xml.etree.ElementTree, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named unicodedata2 - imported by fontTools.unicode, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named 'collections.abc' - imported by fontTools.ttLib.tables._h_d_m_x, fontTools.ttLib.tables._t_r_a_k, fontTools.misc.macRes, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named gi - imported by inspect, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named gtk - imported by inspect, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named 'encodings.aliases' - imported by locale, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named 'org.python' - imported by copy, C:\Python27\Lib\site-packages\fontTools\ttx.py, xml.sax
missing module named pwd - imported by posixpath, C:\Python27\Lib\site-packages\fontTools\ttx.py, getpass
missing module named readline - imported by cmd, pdb, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named fcntl - imported by tempfile, subprocess, C:\Python27\Lib\site-packages\fontTools\ttx.py
missing module named MacOS - imported by fontTools.misc.macCreatorType
missing module named macresource - imported by MacOS
missing module named xattr - imported by fontTools.misc.macCreatorType

```

i built using this cmd: pyinstaller.exe --onefile ttx.py
also tried with the option --debug and --onedir but no luck either

any ideas?

**Comment by anthrotype** [comment]
I'll give it a try once I find some spare time. Are you using the current pyinstaller 3.2.1?

**Comment by anthrotype** [comment]
I just tried with pyinstaller 3.2.1, python 2.7.12 running on Windows 10.

I checked out fonttools at 3.5.0 tag, then run this command from the root of the fonttools repo:
```
pyinstaller --onefile Lib/fontTools/ttx.py
```

It didn't throw any errors on me.
Here is what I got:
[ttx-fonttools-3.5.0-py27-win32.zip](https://github.com/fonttools/fonttools/files/709169/ttx-fonttools-3.5.0-py27-win32.zip)

It seems to be working fine.
Can you try using this or try to build again with the latest pyinstaller?

**Comment by augustus673** [comment]
wow thanks alot man! :)
but i would like to still see if i can do this myself so for future versions i dont need to ask anybody.

im running **Win7 x64, pyinstaller 3.2.1, python 2.7.12**

i open cmd anywhere (say Desktop) and typed: 
```
pip install fonttools
pip install brotli
pip install pyinstaller
```
i then enter **C:\Python27\Lib\site-packages\fontTools**
open cmd there and typed
`pyinstaller.exe --onefile ttx.py`

exe gets created but i get those errors thrown.

is this the same procedure u took?
if so then i might have to create like a new Win7 OS in VMware and start it all from scratch, i mean i dont know what else to do? or just uninstall/delete my C:\Python27 and repeat.
could my windows PATH env var be of any issue here?

thanks for ur input/feedback. i really appreciate u building this for me btw :)

PS.
python info: i think its x86 not x64 version, does this matter?

```
C:\Python27>python.exe
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (
Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
which python version is best to use _performance_ wise if that matters?
btw what do u mean by: I checked out fonttools at 3.5.0 tag?
as in u just typed pip install fonttools? or..?

**Comment by augustus673** [comment]
hey i got it to work!
instead of using pyinstaller on the pip'ed fonttools (in C:\Python27\Lib\site-packages\fontTools), i downloaded the fonttools from this site (so https://github.com/fonttools/fonttools.git). i unzipped the fonttools-master dir in Downloads folder or anywhere, opened cmd prompt in that folder, and ran the same code as u 
 `pyinstaller --onefile Lib/fontTools/ttx.py`
and it worked! 
mine is a bigger filesize, and its cuz i have brotli pip-ed i think. i tested it. woff2 will dump tables with mine, with urs it wont

here is the stdout from pyinstalling: its using Python 3.5.2 cuz i installed that too today thinking it might work better.

```
C:\Users\admin\Downloads\fonttools-master>pyinstaller --onefile Lib/fontTools/
ttx.py
85 INFO: PyInstaller: 3.2.1
86 INFO: Python: 3.5.2
86 INFO: Platform: Windows-7-6.1.7601-SP1
87 INFO: wrote C:\Users\admin\Downloads\fonttools-master\ttx.spec
88 INFO: UPX is not available.
90 INFO: Extending PYTHONPATH with paths
['C:\\Users\\admin\\Downloads\\fonttools-master\\Lib',
 'C:\\Users\\admin\\Downloads\\fonttools-master']
91 INFO: checking Analysis
91 INFO: Building Analysis because out00-Analysis.toc is non existent
91 INFO: Initializing module dependency graph...
93 INFO: Initializing module graph hooks...
94 INFO: Analyzing base_library.zip ...
2151 INFO: running Analysis out00-Analysis.toc
2559 INFO: Caching module hooks...
2564 INFO: Analyzing C:\Users\admin\Downloads\fonttools-master\Lib\fontTools\t
tx.py
3369 INFO: Loading module hooks...
3369 INFO: Loading module hook "hook-encodings.py"...
3450 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
3451 INFO: Loading module hook "hook-xml.py"...
3611 INFO: Loading module hook "hook-pydoc.py"...
3632 INFO: Looking for ctypes DLLs
3641 INFO: Analyzing run-time hooks ...
3650 INFO: Looking for dynamic libraries
3790 INFO: Looking for eggs
3790 INFO: Using Python library c:\python35\python35.dll
3791 INFO: Found binding redirects:
[]
3795 INFO: Warnings written to C:\Users\admin\Downloads\fonttools-master\build
\ttx\warnttx.txt
3808 INFO: checking PYZ
3808 INFO: Building PYZ because out00-PYZ.toc is non existent
3808 INFO: Building PYZ (ZlibArchive) C:\Users\admin\Downloads\fonttools-maste
r\build\ttx\out00-PYZ.pyz
4540 INFO: Building PYZ (ZlibArchive) C:\Users\admin\Downloads\fonttools-maste
r\build\ttx\out00-PYZ.pyz completed successfully.
4551 INFO: checking PKG
4552 INFO: Building PKG because out00-PKG.toc is non existent
4552 INFO: Building PKG (CArchive) out00-PKG.pkg
6279 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
6283 INFO: Bootloader c:\python35\lib\site-packages\PyInstaller\bootloader\Windo
ws-64bit\run.exe
6283 INFO: checking EXE
6284 INFO: Building EXE because out00-EXE.toc is non existent
6284 INFO: Building EXE from out00-EXE.toc
6284 INFO: Appending archive to EXE C:\Users\admin\Downloads\fonttools-master\
dist\ttx.exe
6293 INFO: Building EXE from out00-EXE.toc completed successfully.

C:\Users\admin\Downloads\fonttools-master>
```

i still got a warnttx.txt file tho with claims its missing 26 modules, similar list as before pretty much. i dont know if that will/could cause issues down the line.?


```
missing module named resource - imported by posix, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py
missing module named posix - imported by os, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py
missing module named _posixsubprocess - imported by subprocess, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py
missing module named 'org.python' - imported by pickle, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py, xml.sax
missing module named readline - imported by cmd, code, pdb, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py
excluded module named _frozen_importlib - imported by importlib, importlib.abc, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py
missing module named _frozen_importlib_external - imported by importlib._bootstrap, importlib, importlib.abc, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py
missing module named _winreg - imported by platform, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py
missing module named _scproxy - imported by urllib.request
missing module named java - imported by platform, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py
missing module named 'java.lang' - imported by platform, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py, xml.sax._exceptions
missing module named vms_lib - imported by platform, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py
missing module named termios - imported by tty, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py, getpass
missing module named grp - imported by tarfile, shutil, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py
missing module named pwd - imported by posixpath, tarfile, shutil, http.server, webbrowser, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py, netrc, getpass
missing module named ce - imported by os, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py
missing module named _dummy_threading - imported by dummy_threading, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py
missing module named org - imported by copy, C:\Users\nycionx\Downloads\fonttools-master\Lib\fontTools\ttx.py
missing module named zopfli - imported by fontTools.ttLib.sfnt
missing module named UserDict - imported by fontTools.ttLib.tables._h_d_m_x, fontTools.ttLib.tables._t_r_a_k, fontTools.misc.macRes
missing module named UserList - imported by fontTools.ttLib.tables.otConverters
missing module named unicodedata2 - imported by fontTools.unicode
missing module named MacOS - imported by fontTools.misc.macCreatorType
missing module named macresource - imported by MacOS
missing module named xattr - imported by fontTools.misc.macCreatorType
missing module named StringIO - imported by fontTools.misc.py23
```

**Comment by anthrotype** [comment]
I'm glad you made it work.
By "checking out the 3.5.0 tag" I meant doing `git checkout 3.5.0` from my local copy of fonttools git repository.
You have downloaded the git archive from Github, which also works.
However when you are re-packaging fonttools with pyinstaller I think you may want to use the latest final release, e.g. 3.5.0, instead of an in-development copy of the source code (i.e. whatever the master branch HEAD commit happens to be).
You can get the source distribution "fonttools-3.5.0.zip" from https://github.com/fonttools/fonttools/releases or from https://pypi.python.org/pypi/FontTools.
I'm going to close this now. Please reopen if you encounter any issues.
