### ISSUE TITLE
[varLib] KeyError: 'wght'

### ISSUE THREAD

**Issue by RoelN** [fonttools/fonttools#828]
I might be misunderstanding, so apologies for adding noise. Reporting anyway in case this really is a bug.

I'm building font with [i-can-variable-font](https://github.com/scribbletone/i-can-variable-font/) using this [designspace](https://github.com/scribbletone/i-can-variable-font/blob/master/example/varibox.designspace). The weight axis is called `weight` here, and this works nicely.

When using a similar designspace used in RoboFont, the weight axis is called `wght`, which seems to work there, but has fonttools spit out an error:

```
➤ fonttools varLib varibox.designspace
Index of base master: 0
Building variable font
Loading TTF masters
Axes:
{'wght': (100.0, 100.0, 900.0)}
Master locations:
[{'wght': 100.0}, {'wght': 900.0}]
Traceback (most recent call last):
  File "/usr/local/bin/fonttools", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/fontTools/__main__.py", line 29, in main
    runpy.run_module(mod, run_name='__main__')
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/__main__.py", line 7, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 366, in main
    gx, model, master_ttfs = build(designspace_filename, finder)
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 323, in build
    fvar = _add_fvar(gx, axes, instances, axis_map)
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 62, in _add_fvar
    for iden in sorted(axes.keys(), key=lambda k: axis_map[k][0]):
  File "/usr/local/lib/python2.7/site-packages/fontTools/varLib/__init__.py", line 62, in <lambda>
    for iden in sorted(axes.keys(), key=lambda k: axis_map[k][0]):
KeyError: 'wght'
```

**Comment by RoelN** [comment]
Ok, sent by mail!

**Comment by anthrotype** [comment]
thanks.
It seems like `fontTools.varLib.designspace` currently ignores the `axes` element, and only  reads `sources` and `instances` elements.

The `varLib.build` function has an `axisMap` argument which could be used to pass a custom mapping between axis tags and names, but when it is called from the command line it always defaults to this `standard_axis_map`:

```python
        standard_axis_map = {
		'weight':  ('wght', 'Weight'),
		'width':   ('wdth', 'Width'),
		'slant':   ('slnt', 'Slant'),
		'optical': ('opsz', 'Optical Size'),
		'custom':  ('xxxx', 'Custom'),
	}
```

So yes, I think we should look into adding support for reading this from the designspace file, if present, and have fontmake export it while creating the designspace.

This discussion might also be relevant: https://github.com/fonttools/fonttools/pull/763#discussion_r91488869

**Comment by behdad** [comment]
We now try to read axes from designspace file, so this should be fixed if the designspace has <axes> element. Can you confirm?
