### ISSUE TITLE
[subset] Subr subsetting fails on some CID-keyed CFF

### ISSUE THREAD

**Issue by mashabow** [fonttools/fonttools#856]
Recentry an issue with `--no-hinting` was fixed in #709, but I'm getting another error when subsetting a CID-keyed CFF:

```
$ pyftsubset OurAwesomeUnreleasedFont.otf --no-hinting --text="情"
Traceback (most recent call last):
  File "/Users/mnakamura/.pyenv/versions/fonttools-2.7.13/bin/pyftsubset", line 11, in <module>
    load_entry_point('fonttools', 'console_scripts', 'pyftsubset')()
  File "/Users/mnakamura/.ghq/github.com/mashabow/fonttools/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/mnakamura/.ghq/github.com/mashabow/fonttools/Lib/fontTools/subset/__init__.py", line 2975, in main
    subsetter.subset(font)
  File "/Users/mnakamura/.ghq/github.com/mashabow/fonttools/Lib/fontTools/subset/__init__.py", line 2789, in subset
    self._prune_post_subset(font)
  File "/Users/mnakamura/.ghq/github.com/mashabow/fonttools/Lib/fontTools/subset/__init__.py", line 2772, in _prune_post_subset
    retain = table.prune_post_subset(self.options)
  File "/Users/mnakamura/.ghq/github.com/mashabow/fonttools/Lib/fontTools/subset/__init__.py", line 2281, in prune_post_subset
    subr.subset_subroutines (local_subrs, font.GlobalSubrs)
  File "/Users/mnakamura/.ghq/github.com/mashabow/fonttools/Lib/fontTools/subset/__init__.py", line 1917, in subset_subroutines
    p[i-1] = subrs._used.index(p[i-1] + subrs._old_bias) - subrs._new_bias
AttributeError: 'list' object has no attribute '_used'
```

According to [Lib/fontTools/subset/\_\_init\_\_.py#L2266-L2281](https://github.com/fonttools/fonttools/blob/87527d726110b5fb0ec36c95a5ca5801e3c1f82a/Lib/fontTools/subset/__init__.py#L2266-L2281), when processing the GlobalSubrs, the value of `local_subrs` is always `[]` even if there are actually some local subrs. This seems to cause the error in `subr.subset_subroutines()`.

Note that this font hasn't been released yet, so unfortunately we cannot provide samples for now.

**Comment by anthrotype** [comment]
If you could also provide a small test font that reproduces the issue, it would be great.
But thanks anyway for the bug report.

**Comment by mashabow** [comment]
> If you could also provide a small test font that reproduces the issue, it would be great.

Yes, of course, I'll try it later.

**Comment by miguelsousa** [comment]
[TestGSUBR-Medium.otf.zip](https://github.com/fonttools/fonttools/files/811933/TestGSUBR-Medium.otf.zip)
Here's a test font that has three glyphs encoded as あ, ぃ, and い. The font contains global subroutines and is hinted. I've installed fontTools v3.7.2 in a virtual environment and ran `pyftsubset TestGSUBR-Medium.otf --no-hinting --text=` on each character. I got no errors and AFAIKT the subsetting results were correct. Perhaps I don't understand the problem and I'm using the wrong test input.

**Comment by mashabow** [comment]
@miguelsousa Thank you for providing the test! To reproduce the issue, I think, there have to be some global subroutines which include `callsubr`.

**Comment by mashabow** [comment]
[SubrTestCID-Regular.otf.zip](https://github.com/fonttools/fonttools/files/812951/SubrTestCID-Regular.otf.zip)

Here is another test font which has two glyphs, `.notdef` and `cid04817` (怕). In this font, there is a global subroutine including a `callsubr` operator:

```xml
    <GlobalSubrs>
      <!-- The 'index' attribute is only for humans; it is ignored when parsed. -->
      <CharString index="0">
        -848 -101 callsubr
        return
      </CharString>
```

And this is the actual result:

```
$ pyftsubset SubrTestCID-Regular.otf --text="怕"
Traceback (most recent call last):
  File "/Users/mnakamura/.pyenv/versions/fonttools-2.7.13/bin/pyftsubset", line 11, in <module>
    load_entry_point('fonttools', 'console_scripts', 'pyftsubset')()
  File "/Users/mnakamura/.ghq/github.com/mashabow/fonttools/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/mnakamura/.ghq/github.com/mashabow/fonttools/Lib/fontTools/subset/__init__.py", line 2975, in main
    subsetter.subset(font)
  File "/Users/mnakamura/.ghq/github.com/mashabow/fonttools/Lib/fontTools/subset/__init__.py", line 2789, in subset
    self._prune_post_subset(font)
  File "/Users/mnakamura/.ghq/github.com/mashabow/fonttools/Lib/fontTools/subset/__init__.py", line 2772, in _prune_post_subset
    retain = table.prune_post_subset(self.options)
  File "/Users/mnakamura/.ghq/github.com/mashabow/fonttools/Lib/fontTools/subset/__init__.py", line 2281, in prune_post_subset
    subr.subset_subroutines (local_subrs, font.GlobalSubrs)
  File "/Users/mnakamura/.ghq/github.com/mashabow/fonttools/Lib/fontTools/subset/__init__.py", line 1917, in subset_subroutines
    p[i-1] = subrs._used.index(p[i-1] + subrs._old_bias) - subrs._new_bias
AttributeError: 'list' object has no attribute '_used'
```

BTW, `OurAwesomeUnreleasedFont.otf` is now released as [AXIS Round 100](http://typeproject.com/en/fonts/axisround), yay!

**Comment by anthrotype** [comment]
Thanks Miguel and Masaya for providing test fonts.

So the issue seems to be when we the subsetter is renumbering the subroutines, and we have CID-keyed CFF which contains some `GlobalSubrs`.
In this case, the variable `local_subrs` is assigned an empty list object:

https://github.com/fonttools/fonttools/blob/46d487c/Lib/fontTools/subset/__init__.py#L2270

But if any of the global subroutines in turn contains a `callsubr` command, the call to `subr.subset_subroutines` method fails because it expects that these local_surbs have `_used` attribute, which of course they can't have.

The thing I don't quite understand is.. how can a global subroutines call a local one in CID-keyed CFF? How do you know which of the FontDict's `Private.Subrs` it is referring to?

And what would you set the value of `local_subrs` in the line above to work around this?

**Comment by miguelsousa** [comment]
I asked my colleagues and confirmed that it's invalid to use `callsubr` in global subroutines.

**Comment by behdad** [comment]
> I asked my colleagues and confirmed that it's invalid to use the callsubr operator in global subroutines.

It's nice of them to say so :).

Technically it's possible to call subr from gsubr; when processing the gsubr, the subrs from current font dict are used. Which, indeed, is a problem in subsetting.

**Comment by behdad** [comment]
> But if any of the global subroutines in turn contains a callsubr command, the call to subr.subset_subroutines method fails because it expects that these local_surbs have _used attribute, which of course they can't have.

Ah, you just successfully debugged https://github.com/fonttools/fonttools/issues/656 !  Thank you!!!!!!! Let me think about this a bit.

**Comment by miguelsousa** [comment]
Team work \o/

**Comment by mashabow** [comment]
@miguelsousa

> I asked my colleagues and confirmed that it's invalid to use the callsubr operator in global subroutines.

Oh, that's important. Thank you. Is there any document referring to this restriction?

**Comment by miguelsousa** [comment]
@mashabow I looked thru a few tech notes but didn't find it mentioned anywhere.

**Comment by behdad** [comment]
We fixed compreffor to not use this... Let's clean this part of subsetter later.  I think we should use the one subroutine vector if there's only FontDict at least.

**Comment by behdad** [comment]
Doesn't look like there's anything to be done here anymore.
