### ISSUE TITLE
[feaLib] report position in code for error

### ISSUE THREAD

**Issue by schriftgestalt** [fonttools/fonttools#946]
When the few code contains a problem, feaLib should give an error message with line number where to find the offending code. Now it only gives a backtrace.

**Comment by anthrotype** [comment]
well, the feaLib parser and builder do raise a custom `FeatureLibError` which should always carry with it the location (filename, line number, column) where it is raised.
If you are seeing a traceback without the location then it looks like a bug or an oversight.
What is the actual error, or the data that triggers it?

**Comment by schriftgestalt** [comment]
I got this:
'''
Traceback (most recent call last):
  File "/usr/local/bin/fonttools", line 9, in <module>
    load_entry_point('fonttools==3.9.2.dev0', 'console_scripts', 'fonttools')()
  File "/Users/georg/Programmierung/Stuff/fonttools-Main/Lib/fontTools/__main__.py", line 29, in main
    runpy.run_module(mod, run_name='__main__')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/georg/Programmierung/Stuff/fonttools-Main/Lib/fontTools/feaLib/__main__.py", line 42, in <module>
    sys.exit(main())
  File "/Users/georg/Programmierung/Stuff/fonttools-Main/Lib/fontTools/feaLib/__main__.py", line 37, in main
    addOpenTypeFeatures(font, options.input_fea)
  File "/Users/georg/Programmierung/Stuff/fonttools-Main/Lib/fontTools/feaLib/builder.py", line 16, in addOpenTypeFeatures
    builder.build()
  File "/Users/georg/Programmierung/Stuff/fonttools-Main/Lib/fontTools/feaLib/builder.py", line 80, in build
    self.build_feature_aalt_()
  File "/Users/georg/Programmierung/Stuff/fonttools-Main/Lib/fontTools/feaLib/builder.py", line 165, in build_feature_aalt_
    for glyph, repl in alternates.items()
  File "/Users/georg/Programmierung/Stuff/fonttools-Main/Lib/fontTools/feaLib/builder.py", line 166, in <dictcomp>
    if len(repl) > 1}
  File "/Users/georg/Programmierung/Stuff/fonttools-Main/Lib/fontTools/ttLib/__init__.py", line 628, in getGlyphID
    glyphID = d[glyphName]
KeyError: u'foursuperior'

'''

**Comment by anthrotype** [comment]
I see. In this case the `aalt` feature is being generated based on substitutions defined in other lookups, so it's not already in the features.fea and as such there's no line number to reference (yet).
I agree that the error message could be improved. Here we could intercept the KeyError and reraise a FeatureLibError saying that aalt feature failed to be generated because the font is missing u'foursuperior, or something like that.

**Comment by schriftgestalt** [comment]
Or generate the aalt feature at the end and hope that the other lookups raise the proper error?

**Comment by khaledhosny** [comment]
I can’t reproduce this. If aalt (or a feature it refrences) uses a non-existing glyph name, I get a nice error with location:
```
ERROR: The following glyph names are referenced but are missing from the glyph set:
 foo (first found at a.fea:6:14)
```
