### ISSUE TITLE
[varLib] Deltas with just one coordinate?

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#981]
I’m not sure if I understand this correctly.

Shouldn’t it be allowed for a gvar point delta to specify only one coordinate, so that the other coordinate will be interpolated from the surrounding point deltas for the same direction?

It seems impossible right now to express this in a ttx file. Compilation will fail if there are not both x and y coordinates present, like in the delta for pt 9 below.

````xml
    <glyphVariations glyph="a">
      <tuple>
        <coord axis="wdth" value="-1.0"/>
        <delta pt="0" x="-60" y="0"/>
        <delta pt="1" x="-60" y="0"/>
        <delta pt="2" x="-40" y="0"/>
        <delta pt="3" x="-20" y="0"/>
        <delta pt="4" x="0" y="0"/>
        <delta pt="5" x="0" y="0"/>
        <delta pt="6" x="-20" y="0"/>
        <delta pt="7" x="-40" y="0"/>
        <delta pt="8" x="-60" y="0"/>
        <delta pt="9" y="100"/>
        <delta pt="14" x="-60" y="0"/>
        <delta pt="20" x="0" y="0"/>
        <delta pt="21" x="-60" y="0"/>
        <delta pt="22" x="0" y="0"/>
        <delta pt="23" x="0" y="0"/>
      </tuple>
    </glyphVariations>
````

````bash
Parsing 'gvar' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/ttx.py", line 387, in main
    process(jobs, options)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/ttx.py", line 361, in process
    action(input, output, options)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/ttx.py", line 272, in ttCompile
    ttf.importXML(input)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/ttLib/__init__.py", line 372, in importXML
    reader.read()
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/misc/xmlReader.py", line 48, in read
    self._parseFile(self.file)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/misc/xmlReader.py", line 73, in _parseFile
    parser.Parse(chunk, 0)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/misc/xmlReader.py", line 141, in _endElementHandler
    self.currentTable.fromXML(name, attrs, content, self.ttFont)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/ttLib/tables/_g_v_a_r.py", line 197, in fromXML
    gvar.fromXML(tupleName, tupleAttrs, tupleContent)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/fontTools/ttLib/tables/TupleVariation.py", line 109, in fromXML
    x = safeEval(attrs["x"])
KeyError: 'x'
````

There is an example ttx file attached.

[VarFontB-VF.ttx.zip](https://github.com/fonttools/fonttools/files/1054712/VarFontB-VF.ttx.zip)

**Comment by behdad** [comment]
The font format does not allow that.

**Comment by behdad** [comment]
I have full optimizing IUP implemented BTW. Will push out soon.

**Comment by jenskutilek** [comment]
Thanks, looks like I imagined things ;)
