### ISSUE TITLE
TypeError: Struct() argument 1 must be string, not unicode

### ISSUE THREAD

**Issue by banxian** [fonttools/fonttools#993]
I have ttx via pip install fonttools, and use it to convert SourceHanSans.
but it give me an exception like this:

Dumping "SourceHanSansCN-Normal.otf" to "SourceHanSansCN-Normal.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "f:\python27\lib\site-packages\fontTools\ttx.py", line 387, in main
    process(jobs, options)
  File "f:\python27\lib\site-packages\fontTools\ttx.py", line 361, in process
    action(input, output, options)
  File "f:\python27\lib\site-packages\fontTools\misc\loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "f:\python27\lib\site-packages\fontTools\ttx.py", line 258, in ttDump
    newlinestr=options.newlinestr)
  File "f:\python27\lib\site-packages\fontTools\ttLib\__init__.py", line 311, in saveXML
    self._tableToXML(tableWriter, tag, progress)
  File "f:\python27\lib\site-packages\fontTools\ttLib\__init__.py", line 329, in _tableToXML
    table = self[tag]
  File "f:\python27\lib\site-packages\fontTools\ttLib\__init__.py", line 419, in __getitem__
    tableClass = getTableClass(tag)
  File "f:\python27\lib\site-packages\fontTools\ttLib\__init__.py", line 825, in getTableClass
    module = getTableModule(tag)
  File "f:\python27\lib\site-packages\fontTools\ttLib\__init__.py", line 807, in getTableModule
    __import__("fontTools.ttLib.tables." + pyTag)
  File "f:\python27\lib\site-packages\fontTools\ttLib\tables\_n_a_m_e.py", line 26, in <module>
    nameRecordSize = sstruct.calcsize(nameRecordFormat)
  File "f:\python27\lib\site-packages\fontTools\misc\sstruct.py", line 108, in calcsize
    return struct.calcsize(formatstring)
TypeError: Struct() argument 1 must be string, not unicode
(Hit any key to exit)

python version is 2.7.3, os is windows 7 x64 sp1.

**Comment by behdad** [comment]
Humm.  I suspect e8530360b, but why does it not fail in our continuous testing?

**Comment by banxian** [comment]
maybe my font (SourceHanSansCN-Normal.otf) have some magic triggered this exception.
it's 1.004 version which got from Adobe's source han project.

**Comment by anthrotype** [comment]
Before python 2.7.7 the struct module didn't support unicode strings, but required a nativ str (bytes).
https://bugs.python.org/issue19099

We don't run tests on such old pythons on our CI.
I'd suggest a wontfix and "please update your python, or better use python3".

**Comment by behdad** [comment]
sgtm

**Comment by vane** [comment]
Hi,
I have same problem unfortunately I cannot update python so easily. It doesn't depend on me.
I created pull request that fix this issue.
https://github.com/fonttools/fonttools/compare/master...vane:master  
I tested it with python 2.7.5

**Comment by anthrotype** [comment]
It turns out some fonttools users are still stuck with pythons older than 2.7.7.

I wouldn't like to add another Travis build to check for such old python, it's slow enough already.
Let's content ourselves of occasionally fixing things based on users' report.. Until the https://pythonclock.org/ finally reaches its end.

**Comment by anthrotype** [comment]
for this specific issue with the py27 struct module, fonttools devs should remember to use explicitly use bytes for the struct.pack and unpack format string (using the ``b""` notation) whenever the module in which the call to struct appears also imports `unicode_literals`.
The `unicode_literals` module is known to have some issue with some stdlib modules, but sometimes the convenience of not prefixing everything with `u""` outweighs its downsides.
Let's stick to using it like we currently do, i.e. only when a module manipulates potentially non-ASCII text strings.
